### PR TITLE
FIX: TH were used instead of TD in table fields

### PR DESCRIPTION
**Pull request by MrElectroNick**
This break custom styles for TH as header cell and TD as data cell
And finally it's just inconsistent

Before submitting pull request, please check that every commit:

- [X] Has proper Signed-Off-By
- [X] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
What is wrong on using `<th>` for field names? IMHO the CSS should rather look for `<thead>`...

**Comment by MrElectroNick** [comment]
All is good with TH but it should be inside <thead> and not <tbody>

As you can see all columns are TD and only field name is TH which is not correct

**Comment by nijel** [comment]
I don't see anything like that in the [HTML specification](https://www.w3.org/TR/html5/tabular-data.html#the-th-element). Actually their example uses `<th>` in same way as we do - as heading for the row.

**Comment by MrElectroNick** [comment]
Ok

**Pull request closed without merging**
