### PR TITLE
Fix #14447 - Error while copying database (pma__column_info)

### LINKED ISSUE #14447: Error while copying database (pma__column_info)
I heavy use the phpmyadmin "Internal relation" function.

While copying (structure and data) a hole database, it's gives

`1136 - Column count doesn't match value count at row 1`

error about the sql-query:

`REPLACE INTO phpmyadmin.pma__column_info (db_name, table_name, column_name, comment, mimetype, transformation, transformation_options)  VALUES('newdatabase','newtable','fieldabc','ListeA','','','','')`

I see 7 fields and 8 values in this query.

Affected versions i tried: phpMyAdmin-4.7.9 and phpMyAdmin-4.8.2
And not affected version for me is: phpMyAdmin-4.6.6

My "phpmyadmin" database is actual.

Apache/2.4.18
Database-Client Version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP-Extension: mysqli curl mbstring
PHP-Version: 7.0.30-0ubuntu0.16.04.1
Server-Type: MariaDB
Server-Version: 10.0.34-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
Protocol-Version: 10

### PR DESCRIPTION
**Pull request by yeezy69**
As described in issue #14447 the sql-query is incorrect. There are 7 fields and 8 values in this query.

Fixes #14447

### CODE REVIEW

**Comment by yeezy69** [comment]
Signed-off-by: Daniel yeezy69@babau.mywire.org

**Comment by williamdes** [comment]
`git commit --amend --signoff`
`git push --force`

**Comment by yeezy69** [comment]
@williamdes i don't use git. I edited the file in my fork on github web. i never used git/github before. i only want to change one line ;-) must i recreate this pull request with Signed-off-by line in the comment?

**Comment by williamdes** [comment]
@yeezy69 Your last name ?

**Comment by yeezy69** [comment]
Thank you :)

**Comment by williamdes** [comment]
@yeezy69 please remove me from the repo :)

**Comment by yeezy69** [comment]
@williamdes why this is not working? :(

**Comment by williamdes** [comment]
@yeezy69 Close and re-open the PR to trigger tests

**Comment by yeezy69** [comment]
to trigger tests

**Comment by yeezy69** [comment]
to trigger tests

**Comment by yeezy69** [comment]
next try close+open to trigger tests

**Comment by yeezy69** [comment]
reopen to trigger tests

**Comment by yeezy69** [comment]
@williamdes :(

**Comment by williamdes** [comment]
@yeezy69 Grant me access, I will rebase and force push.
I am 100% sure the tests will run afterwards...

**Comment by williamdes** [comment]
@yeezy69 Tests seem to have run successfully :)

**Comment by yeezy69** [comment]
Thank you @williamdes :) should i close this now?

**Comment by williamdes** [comment]
@yeezy69 You can remove access from your repo and wait that a maintainer merges this PR.
Maybe delete some messages in this PR to clean it :)

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
