### PR TITLE
profiling output when the result has no rows

### LINKED ISSUE #15465: No profiling output when the result has no rows
When the result has zero rows, the profiling data is not displayed.

More specificaly only the https://github.com/phpmyadmin/phpmyadmin/issues/15209 MySQL deprecation warning is displayed

### PR DESCRIPTION
**Pull request by ShailuJain**
Signed-off-by: Shailesh Jain <jainshailesh91@gmail.com>

### Description

Profiling output even when there are 0 rows in the result

Fixes #15465 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Merged :tada: 

Thank you for the contribution @ShailuJain !

I added 52c17a34d2af4f743b34c8472f092004c9623517 to display the chart

**Comment by williamdes** [comment]
Merged as f070efe37c457cb71d2ded50b6dcd83afe523be4 and bee6f1c476fc0a926caac5c25ab1e6e6401a7056

**Comment by ShailuJain** [comment]
Thank you. Can i join the slack channel of phpmyadmin @williamdes . I would like to contribute more.

**Comment by williamdes** [comment]
@ShailuJain Yes, absolutely 
https://join.slack.com/t/phpmyadmin/shared_invite/enQtNTQ3ODU0NzExNTExLTVjYTNhOGVjMDdlMzFiZTRkMjBjYjViY2YxNTlkZDE3OTNlNmViMjE2YTg3MTQ2MzQwNTk2ZjI3MzhkNzIzMDY

**Pull request merged**
