### PR TITLE
Remove tcpdf from composer suggest

### PR DESCRIPTION
**Pull request by gulaandrij**
tecnickcom/tcpdf present in require section and dont need to suggest it

### CODE REVIEW

**Comment by ibennetch** [comment]
Good catch. I rather think we should remove it from the required section and keep it as a suggestion. phpMyAdmin handles a missing tcpdf rather gracefully.

**Comment by gulaandrij** [comment]
did it

**Comment by nijel** [comment]
Indeed it should be just optional, however we still need at least 6.2, so appropriate conflict with older versions should be added as well.

Also it should be either added to require-dev or explicitly installed in Travis so that we test with it.

**Comment by nijel** [comment]
Fixed in git by a7950fa.

**Pull request closed without merging**
