### PR TITLE
type correction err resolved in tbl_change.js

### LINKED ISSUE #14982: setting "null" keep an "enum" value
In my database (mariadb) I have a enum field with "yes" or "not" ("si" o "no").  
If I do un insert new record, there is no problem, not setting that filed (remain NULL);  
but **if I copy from an existing record**, I cannot set to NULL that field: if it is yes is remain yes, even I check the NULL checkpox.

phpmyadmin enum bug

I tried with Falkon, Firefox and Chrome: always the same.
I think this is a bug: isn't it?
Thank you

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

### Description

As the type of operands is different, using `===` doesn't work as seen in #14982 . Thus `==` is needed.

Fixes #14982 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
I think the will not pass linting on master branch, can you add cast to Integer ?

Thank you for finding the fix :)

**Review by williamdes — APPROVED** [review]
LGTM :)

**Comment by bahl24** [comment]
I checked but in my system it is working fine, @williamdes do you have any clue why is this happening, kindly test it

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by bahl24** [comment]
> verificationsAfterFieldChange is not defined

I haven't modified the function or the parameters at all, no idea why you are getting this error

**Comment by DoctorSubtilis** [comment]
> > verificationsAfterFieldChange is not defined
> 
> I haven't modified the function or the parameters at all, no idea why you are getting this error

I think that the problem is something in browser javascript (error is in Falokn and in Firefox, **not** in Chrome)

**Comment by bahl24** [comment]
@DoctorSubtilis Were you getting the error before my patch also, or after the patch.
I had checked in Chrome, let me check in Firefox

**Comment by bahl24** [comment]
@DoctorSubtilis Found no error in firefox or chrome, kindly recheck. I haven't modified the function thus, it should not give any error.
Kindly check after pulling recent changes from github.

**Comment by DoctorSubtilis** [comment]
> @DoctorSubtilis @williamdes Found no error in firefox or chrome, kindly recheck. I haven't modified the function thus, it should not give any error.
> Kindly check after pulling recent changes from github.

In effect, it seems that **after clearing the cache** the problem has been **solved**. Thank you

**Comment by bahl24** [comment]
@williamdes the problem has been solved. Kindly test it.

**Comment by bahl24** [comment]
@williamdes @mauriciofauth @ibennetch Kindly test this PR

**Review by williamdes — CHANGES_REQUESTED** [review]
Did not fix the issue..

**Comment by bahl24** [comment]
> Did not fix the issue..

Hi @williamdes , did you try clearing the browser cache

**Review by williamdes — APPROVED** [review]

**Review by williamdes — APPROVED** [review]
Merged, thanks @bahl24 for your contribution !

**Pull request merged**
