### PR TITLE
Add grid-edit update query only to last query result box

### LINKED ISSUE #11702: Extraneous message after edit + grid-edit
Seen in 4.5.2. Browse a table, then click Edit for a row, make some change and click on Go. Then double-click on some data and change it. You see the messages for the two UPDATE statements.

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Fix #11702.

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Should we also remove the original update query when a new grid update query comes?

**Comment by lem9** [comment]
@nisargjhaveri Yes, it's confusing to see more than the last one.

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
