### PR TITLE
this is for bug #4744. 

### PR DESCRIPTION
**Pull request by tapanhalani**
I couldn't target this push myself to QA_4_3. But I have squashed all my commits here. Please evaluate and merge this.

### CODE REVIEW

**Comment by zixtor** [comment]
It still contains three commits.

**Comment by tapanhalani** [comment]
well how do I squash pushed commits?

**Comment by tapanhalani** [comment]
well I checked, The last commit i.e. test#4744 is the final commit, containing all the changes. But I could not remove or squash all the commits here.

**Comment by tapanhalani** [comment]
Hello,

I have closed the previous pull request and issued a new one #1490 and
commit with following id :56bcecc , link:
https://github.com/phpmyadmin/phpmyadmin/commit/56bcecccb7684a89b3114019bc08ffa4441a7ec6)
by the name of test#4744  is the final commit containing all the changes.
I could not remove all other and couldn't squash them. Maybe some mistake
with my concepts. Please pick my above mentioned commit and merge it.

Sorry for the inconvenience.

Thank you.

**Comment by zixtor** [comment]
Still, the commit you mention only removes some new lines and does not contain all changes. If you want I can commit with you as author (means commit will be credited to you). Moreover the message of the commit "test#4744" is not informing enough and is misleading towards some kind of test.

**Comment by zixtor** [comment]
About you git problem, we have a thorough documentation at https://wiki.phpmyadmin.net/pma/Git but for your particular problem I have written down some commands which, if assumptions are correct, should help you.

Assuming you only have these three new commits on your feaQA_4_3 branch and no other changes staged for commit, do following:-

git checkout feaQA_4_3
git reset --soft HEAD~3
git commit -sm "Fix bug#4744-Opening console scrolls down the page"
 // will give some sha id like [feaQA_4_3 some_id], note this some_id

git remote -v
// Check if your origin points to your own github
// and your upstream points to phpmyadmin's github

git push -f origin feaQA_4_3
// it should push a single properly named commit to your github feaQA_4_3

Now, optionally, to set up you QA_4_3 branch:-

git remote add upstream https://github.com/phpmyadmin/phpmyadmin.git
git fetch upstream
git branch -D QA_4_3
git branch --track QA_4_3 remotes/upstream/QA_4_3
git checkout QA_4_3
git cherry-pick above_noted_some_id
// if it applies without conflicts
git push -f origin QA_4_3

At this point you should be able to open a pull request targeting phpmyadmin's QA_4_3 from your github QA_4_3.

**Comment by tapanhalani** [comment]
Hello Atul,

A lot of thanks and appreciations to you for making out time to give such a
helpful and detailed guide. It helped my through. I pushed my changes to
feaQA_4_3 branch. The pull request id is #1493 and the commit id is
c21552d( link
https://github.com/phpmyadmin/phpmyadmin/commit/c21552d1bc9a4e1df9d357e11bc16fccc903700a
).

I am sure this would solve all the previous problems. Again , lot of thanks
for helping me through. Just out of curiosity, would this bug-fix be
authored by me or not? I mean will I get credits for this? It is important
for me as I am preparing for GSOC-2015. Any suggestions regarding Gsoc are
also welcome.

Thank you.

**Pull request closed without merging**
