### PR TITLE
Issue #14833 -- fixed (Sort by Time not working in Processlist)

### LINKED ISSUE #14833: Sort by Time not working in Processlist
### Describe the bug

Under Status -> Processes, clicking on Time to sort, will make applied filters (e.g. Show only active) disappear. Also, it doesn't actually sort, and clicking 2 times doesn't change the order (DESC or ASC).

Version 4.8.4

### To Reproduce

1. Go to Status -> Processlist
2. Click on 'Show only active'
3. Click on the column title 'Time'

### Expected behavior

This should maintain the previous selection and sort by time. Instead, it removes the current filter and doesn't actually sort the processes by time. 

### Screenshots

[Screencast of the problem](https://youtu.be/FsNVSDQ_wYI)

### Server configuration

- Operating system: Amazon Linux AMI release 2018.03 and Mac under Homebrew 
- Web server: nginx/1.12.1
- Database version: 5.7.23 and 8.0.12 
- PHP version: 7.0.31 and  7.3.0
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Chrome 71.0.3578.98 
- Operating system: Mac OS 10.14.2

### PR DESCRIPTION
**Pull request by saurass**
Signed-off-by: saurass <saurabhsrivastava312@gmail.com>

### Description

Fixes #14833

- In \libraries\classes\Server\Status\Processes.php -- getHtmlForServerProcesslist(), getHtmlForServerProcessItem()
It handled only POST requests.
- Where in the case above ajax call was made using GET
- So fixed points to handle both types of request.

### CODE REVIEW

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Hi, @saurass. Thanks for your contribution.

Please do not use the `$_REQUEST` superglobal. This needs to be fixed in a different way.

**Comment by saurass** [comment]
Yeah that is really a very bad method

I just figured that issue
#14800 and #14833 are closely related.

Both using GET for ajax whereas the code In Response.php is compatible only with POST request.

Working on that  :)

**Comment by saurass** [comment]
@mauriciofauth should I make changes to server_status_processes.js - to make the AJAX call via POST method or we gotta make changes to backend code (Processes.php) ??

Please lemme know which one should I work on ?

**Comment by mauriciofauth** [comment]
@saurass Yes, the request should use POST method.

**Comment by saurass** [comment]
Thanks @mauriciofauth , I will try to fix the js file.

**Pull request closed without merging**
