### PR TITLE
Message in Message class is self

### PR DESCRIPTION
**Pull request by Tithugues**
### Description

In `Message` class, I think this is clearer to use `self` instead of `Message` to target current class.

### CODE REVIEW

**Review by MauricioFauth — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Review by ibennetch — APPROVED** [review]

**Comment by Tithugues** [comment]
Hi,
I didn't expect to have any error on this MR… Do you see anything that could lead to this error please?
Thank you.

**Comment by mauriciofauth** [comment]
Apparently it was an error in Browserstack not related to this PR.

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Comment by ibennetch** [comment]
A quick look at the Travis build log doesn't show me anything that looks related to your pull request. I think you're not the responsible party here :)

**Comment by Tithugues** [comment]
Thanks to both of you for your confirmation.

**Pull request merged**
