### PR TITLE
fix - #15001 - Login cookie validity in settings->features

### LINKED ISSUE #15001: Login Cookie Validity
This might be a useful feature until I upgrade my wamp to 3.1.7 which has `phpmyadmin v4.8.4`. How can I set this now?

Screenshot:

### PR DESCRIPTION
**Pull request by saurass**
Signed-off-by: Saurabh Srivastava <saurabhsrivastava312@gmail.com>

# Description
Fixes #15001 - Login  cookie validity in settings->features.

## Changes Done
* In `libraries/classes/Config/Forms/User/FeaturesForm.php` , just added `LoginCookieValidity` in `$result` associative array in `getForms()` function.
* Rest other implementation are already present in the current codebase. 

# Contribution Checklist
- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by saurass** [comment]
@williamdes please have a look, Hope it's useful. : )

**Review by williamdes — APPROVED** [review]
tested: ok
ready to merge :)

**Comment by saurass** [comment]
great !!

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Review by jrchamp — CHANGES_REQUESTED** [review]
LoginCookieValidity was removed on purpose by @nijel in https://github.com/phpmyadmin/phpmyadmin/commit/1fb2887a2ad11ab4b030bc6cf427a75fa0384d0e

The reasoning was "there are more cookie related settings and all should be handled [consistently]". If I'm reading this correctly, then by adding just this one cookie-related setting, this change creates an inconsistency.

**Comment by williamdes** [comment]
@ibennetch do we need this change ?

**Review by williamdes — APPROVED** [review]
Tested a last time, it works.
Thank you for your contribution !
It was decided on https://github.com/phpmyadmin/phpmyadmin/issues/15001#issuecomment-721450919 to merge your work.

**Pull request merged**
