### PR TITLE
Alternative implementation for rfe #1602

### PR DESCRIPTION
**Pull request by madhuracj**
An alternative implementation is due to the problems described at https://github.com/phpmyadmin/phpmyadmin/pull/1498#issuecomment-76158097

### CODE REVIEW

**Comment by lem9** [comment]
@madhuracj I agree that the other implementation has problems. However, as a user I'm trying to figure out what the "Auto-saved" button means. I mean, if something is automatic, why would I have to click a button for it?  I think that this button should be named "Get auto-saved query"; merging now and I'll change the button. Feel free to react to my change later.

**Comment by madhuracj** [comment]
@lem9 "Get auto-saved query" sounds better. My only worry was whether it was too long for a button.

**Comment by lem9** [comment]
@madhuracj Yes is a bit long but IMO it needed a clarification.

**Comment by ibennetch** [comment]
I agree that "Get auto-saved query" is acceptable here.

**Pull request merged**
