### PR TITLE
Fixes #11497.

### LINKED ISSUE #11497: Incorrect indexes when exporting
Table indexes are broken when exporting. Example SQL to create the table:

    DROP TABLE IF EXISTS `jos_core_acl_aro`;
    CREATE TABLE IF NOT EXISTS `jos_core_acl_aro` (
      `id` int(11) NOT NULL,
      `section_value` varchar(240) NOT NULL DEFAULT '0',
      `value` varchar(240) NOT NULL DEFAULT '',
      `order_value` int(11) NOT NULL DEFAULT '0',
      `name` varchar(255) NOT NULL DEFAULT '',
      `hidden` int(11) NOT NULL DEFAULT '0'
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

    INSERT INTO `jos_core_acl_aro` (`id`, `section_value`, `value`, `order_value`, `name`, `hidden`) VALUES
    (10, 'users', '62', 0, 'Administrator', 0),
    (23, 'users', '75', 0, 'Test', 0),
    (24, 'users', '76', 0, 'Test 2', 0),
    (25, 'users', '77', 0, 'Test 3', 0),
    (26, 'users', '78', 0, 'Test 4', 0);

    ALTER TABLE `jos_core_acl_aro`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `jos_section_value_value_aro` (`section_value`(100),`value`(100)) USING BTREE,
      ADD KEY `jos_gacl_hidden_aro` (`hidden`);

Now export that table in PMA 4.5.0.1. The index section comes out like this:

    ALTER TABLE `jos_core_acl_aro`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `jos_section_value_value_aro` (`section_value`);

Works fine on PMA 4.4.9.

### PR DESCRIPTION
**Pull request by udan11**
Fixes #11497.
Cherry-picked udan11/sql-parser@1415469.

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
PHP Fatal error:  require_once(): Failed opening required 'common.php'

**Comment by lem9** [comment]
Is this big patch only to fix #11497 ?

**Comment by udan11** [comment]
No. This pull request includes multiple patches, one of them being the fix to this issue. The bug fix for this is in `Components/Key.php`.

**Comment by lem9** [comment]
Thanks but what about the test failure in PMA_ExportSql_Test::testReplaceWithAlias ?

**Comment by lem9** [comment]
Dan, could you produce a minimal patch for this problem? We want to target a quick 4.5.0.2 with just this fix, and the bigger patch (this PR) would be for 4.5.1 in one month.

**Comment by udan11** [comment]
Done.

**Comment by lem9** [comment]
Thanks; I cherry-picked this to MAINT_4_5_0.  Feel free to send a pull request of the big patch for QA_4_5.

**Pull request closed without merging**
