### PR TITLE
Fix #4957 "With selected" links doesn't work in table browse

### PR DESCRIPTION
**Pull request by Tithugues**
Because of a new level in DOM, the JS doesn't work anymore.

### CODE REVIEW

**Comment by Tithugues** [comment]
I just updated my fix. I didn't like the way it was writen.

**Comment by ibennetch** [comment]
Could you squash your commits?

**Comment by Tithugues** [comment]
Done.

**Comment by devenbansod** [comment]
Thanks a lot @Tithugues for the fix.

**Comment by ibennetch** [comment]
Looks good, nice fix.

**Pull request merged**
