### PR TITLE
Fix bug#4948

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by lem9** [comment]
Nisarg,
this does not fix the bug for me. To reproduce, open a database, click on SQL and type "EXPLAIN SELECT * FROM tablename" (of course, using a real table name)

**Comment by nisargjhaveri** [comment]
Umm, it looks like it is working for me! Can you please check again?

**Comment by lem9** [comment]
You see the results of the EXPLAIN statement? For me, it only shows "# Rows: 1".

**Comment by nisargjhaveri** [comment]
Yes, I can see the result of EXPLAIN statement.
On previous commit a069ab2, it shows "# Rows: 1" as you said.

**Comment by lem9** [comment]
When testing 7c5fb73 I don't see the result of EXPLAIN statement. Are you sure that you are *typing* the statement in the SQL query box?

**Comment by nisargjhaveri** [comment]
Yes, login -> select DB from navi panel -> Click on SQL from tabs -> type EXPLAIN statement -> click on go.

Git revision: 7c5fb73 from issue_4948 branch
PHP version: 5.5.9-1ubuntu4.9

**Comment by nisargjhaveri** [comment]
Okay, seems like it fails when Foreign key checks is unchecked. Looking into it. Is that the case with you too?

**Comment by nisargjhaveri** [comment]
Doesn't work :/
Closing.

**Pull request closed without merging**
