### PR TITLE
Remove underscore prefix from method names

### LINKED ISSUE #16149: Remove underscore prefix from method names
From [PSR-12](https://www.php-fig.org/psr/psr-12/#44-methods-and-functions):
> Method names MUST NOT be prefixed with a single underscore to indicate protected or private visibility.

To know what methods have an underscore, first remove this line from `phpcs.xml.dist` file:
```diff
- <exclude name="PSR2.Methods.MethodDeclaration.Underscore"/>
```

And then run PHPCS:
```
vendor/bin/phpcs
```

You can follow this commit as an example: https://github.com/phpmyadmin/phpmyadmin/commit/2937e9796db184082c1e0d99e244216d447dc396

### PR DESCRIPTION
**Pull request by charliewindred**
### Description

Removed underscore prefix from method names for PSR-12 compliance.

### Fixes 
Methods and method calls had underscore prefix removed.

Fixes: #16149 

The following methods were left unchanged because removing underscore created error “Cannot make public method private”:

classes/DatabaseInterface _FetchValue()
classes/Plugins/Export/ExportXml _exportRoutines()
libraries/classes/Plugins/Export/ExportSql _exportMetadata()

Additionally, method _putpages() of class "libraries/classes/Pdf" overrides method _putpages() in parent class TCPDF, so _putpages() remains with underscore.

### CODE REVIEW

**Comment by williamdes** [comment]
Hello @charliewindred 

Thank you for this PR !
Could you run `composer run update:baselines` and push the diff ?

Maybe also have a look to https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/693912185#L474

**Review by williamdes — APPROVED** [review]
The code looks all good

Only the baselines to be updated and see if the tests pass and I will merge your work

**Comment by williamdes** [comment]
I force pushed your last commit because it was not right for some reason

Please run `./vendor/bin/phpunit --no-coverage` and you will see that some tests are failing.

I am fixing the psalm issue introduced this morning so you can rebase your work

You will need to change all the method names in tests.
Using any good IDE  you can search for `'_` to fix things more quickly in the tests

**Comment by charliewindred** [comment]
Made the changes to method names and having no problems passing the tests now

**Comment by williamdes** [comment]
Thank you
My merging the remote branch you did add back the buggy baseline, I reverted this mistake and added your work on top

To that I added 707d2635318de1719c4ffe3c9ba03be4254f0b8d for 2 missed instances and 3f0b7390e2aaa82d63b3318aa14ff44fdf27c5f5 for the documentation.

If the tests pass, merging will follow

**Review by williamdes — APPROVED** [review]
Thank you @charliewindred for your contribution !

**Pull request merged**
