### PR TITLE
Added "Build Query" button to Visual Query Builder phpmyadmin#16485

### LINKED ISSUE #16485: Visual query builder missing "Build Query" button
The Visual Query Builder is missing the "Build Query" button.

I have tested 5.0.2 and 4.9.7, but haven't yet gone down any further to find the commit that causes this.

### 5.0.2
image

### 4.9.7
image

### To reproduce

1. click on the Query tab for a database
2. Click the "Query by example" second-level tab
3. Follow the link to "Switch to visual builder"

The pop out menu should have a "Build Query" button, but doesn't.

First reported here: https://stackoverflow.com/questions/64813163/how-to-use-the-query-visual-builder-in-phpmyadmin

### PR DESCRIPTION
**Pull request by Pauldro**
There was a ```if not visual_builder ``` that kept it from displaying. I did a search to see if that value is supplied and what it would mean.

Signed-off-by: Paul Gomez <pauldro952@hotmail.com>

### Description

Please describe your pull request.

Fixes #16485

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Hi,
I just want to let you know that closing PRs is not the best option ;)
You can do whan ever you want with the git history and then `git push --force` :100: 

Could you amend you commit with a fixed version of the file please ?
```
# edit the file
git add -A
git commit --amend
git push --force
```

**Comment by Pauldro** [comment]
> git push --force



> 
> 
> Hi,
> I just want to let you know that closing PRs is not the best option ;)
> You can do whan ever you want with the git history and then `git push --force` 💯
> 
> Could you amend you commit with a fixed version of the file please ?
> 
> ```
> # edit the file
> git add -A
> git commit --amend
> git push --force
> ```

Thank you for your help!

**Comment by williamdes** [comment]
By the way I think the for push was not done because as you can see you did what most users do, a sort of pull merge push
image
But do not worry I fixed it

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
I will test your changes and merge your work into next 5.1 and 5.2.0-dev ;)

**Comment by williamdes** [comment]
I improved the fix as 23e23e3b3bb51b83efa5ccc96bf789aaed3560f7

Happy new year !

**Pull request merged**
