### PR TITLE
Issue #15077 fixed

### PR DESCRIPTION
**Pull request by amokrousov12345678**
Fixed bug with incorrect page numeration when databases list is limited by 1 database per page.
Signed-off-by: Anton Mokrousov <settingx@mail.ru>

### CODE REVIEW

**Comment by williamdes** [comment]
#15077

**Review by williamdes — COMMENTED** [review]
LGTM

**Comment by BauyrzhanMaksot** [comment]
I found another error

**Comment by BauyrzhanMaksot** [comment]
Do I need to create another issue? the problem is similar

**Comment by williamdes** [comment]
@BauyrzhanMaksot Yes, please

**Pull request closed without merging**
