### PR TITLE
Fixed Error 14402 Javascript Error-adding index to a new column

### LINKED ISSUE #14402: Fatal javascript error while adding index to a new column
### Steps to reproduce
1. Create a new column in an existing table.
2. Select PRIMARY in the drop down to add index, deselect primary from the drop down.
3. PRIMARY still appears in the link below this dropdown, click the link.

### Expected behaviour
Should show the dialog to select index.

### Actual behaviour
Fatal javascript error, cannot read property undefined of null

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache 2.4.29

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
5.0.0-dev & 4.8.4

### Client configuration
**Browser:**
chrome 66.0.3359.117

### PR DESCRIPTION
**Pull request by kartik1000**
Signed-off-by: kathuriakartik0@gmail.com <Viratkohli218>

### Description
Please describe your pull request.
Fixed Javascript issue #14402. After this commit we can we deselect the index and the link will work as expected. Only needed small changes in javascript file.
Fixes #14402 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by kartik1000** [comment]
@williamdes or @ibennetch please, review the PR :)

**Comment by kartik1000** [comment]
@sudo-bot Deploy PR

**Comment by kartik1000** [comment]
@sudo-bot Deploy

**Review by williamdes — APPROVED** [review]
Works as expected, thank you @kartik1000 !

**Comment by williamdes** [comment]
Closed by 7ddb6be9e2bd054f901b63b43f2996a734063bfd
Merged :tada:

**Pull request closed without merging**
