### PR TITLE
Avoid check permissions on windows

### PR DESCRIPTION
**Pull request by Gemorroj**
Signed-off-by: Gemorroj wapinet@mail.ru

Avoid check permissions on windows

### CODE REVIEW

**Comment by williamdes** [comment]
Thank you for the fix, I will surely point it to QA_5_0 after validation :)

**Comment by williamdes** [comment]
@Gemorroj reading https://github.com/phpmyadmin/phpmyadmin/commit/ffc9a28eaf90312a79b91149786519b14db9f481 do you think your change is still right ?

**Comment by Gemorroj** [comment]
@williamdes 
see https://github.com/phpmyadmin/phpmyadmin/commit/0138cb471fe6497712e264ad96458f99f4f4b9cf#diff-f1bcf66fa65cf33b5a0cbe886dc736cfL753

I think this change still right

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you @Gemorroj for noticing and fixing this issue !

**Pull request merged**
