### PR TITLE
Fix numeric errors in PHP7.1 

### PR DESCRIPTION
**Pull request by devenbansod**
Fix numeric errors in PHP 7.1.

Before submitting pull request, please check that every commit:
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
I believe the Uptime issues were caused by wrong value used in tests, I've fixed this in 38b3fdf.

**Comment by nijel** [comment]
Same for '#', fixed in eb233da

**Comment by nijel** [comment]
I've cherry picked what was left in your PR as b1d0589b51595bdd940d5dff5766c0331e59f0de.

**Comment by devenbansod** [comment]
Thanks! :-)

**Comment by nijel** [comment]
Actually there was one more wrong data in the tests: 92cb95c

**Pull request closed without merging**
