### PR TITLE
Translated using Weblate (Filipino)

### PR DESCRIPTION
**Pull request by codygee237**
This is a continuation to the Filipino Language Translation (fil.po)
Currently translated at more than 1300 words out of 21,349 words and more than 250 strings translated out of 3208 strings

Signed-off-by: codygee237 <35871138+codygee237@users.noreply.github.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by codygee237** [comment]
Hi Good Day Sir! I am still waiting for the approval. I'm hoping for your positive feedback Sir. Thank you

**Comment by nijel** [comment]
Merged, thanks for your contribution!

Any reason for not making changes in Weblate directly?

**Comment by nijel** [comment]
Also you've made several mistakes in the po file, what would not happen when editing in Weblate, see bacdc21dc1

**Comment by codygee237** [comment]
Thank you Sir! I'm really sorry I was so busy for the past weeks. I hope you'd understand. Cheers!

**Pull request merged**
