### PR TITLE
Fix #15717 - remove spinner when the message is not a loading message

### LINKED ISSUE #15717: Warning popup not Dissapearing
### Describe the bug

In structure of any table when performing any multiple column action it pops a loader with error message: "No Column selected" and loader never dissapear 

### To Reproduce

1. Select any Database->Table
2. Click on 'Structure' tab
3. Click on any action of Mulitple columns (dont select any column)

### Expected behavior

The popup should dissapear after few seconds and there should not be any loading animation 

### Screenshots
issue

### Server configuration

- Operating system: Windows
- Web server: Apache
- Database version: 10.1.35-MariaDB
- PHP version: 7.2.9
- phpMyAdmin version:  5.1.0-dev

### Client configuration

- Browser: Chrome
- Operating system: Windows

### PR DESCRIPTION
**Pull request by victorphoenix3**
Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>
fixes #15717 .

After fixing:
notify

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by victorphoenix3** [comment]
@williamdes do review.

**Comment by victorphoenix3** [comment]
@williamdes  the PR keeps the same template as before but removes the spinner for notifications other than "loading...."

**Comment by williamdes** [comment]
Okay, thank you
Could you find the change that was made between 4.9 and 5.0 in order to fix that rather than adding a hack on the js file?

**Comment by victorphoenix3** [comment]
@williamdes  The bug is also present in 4.9 but only for the "original theme".

we use the .ajax_notification class for the these notification popups. 
In 4.9 the .ajax_notification has been defined twice in the css file for "pmahamme" theme.  "background" property is overriding the 'background-image' due to which the spinner is not visible for any popups.

In 5.0 we have no "background" property. Thus background-image is rendered and is present in every popup. If we remove it , we wont have the spinner for the "loading...." message.

should i define a seperate class for this specific popup to remove the spinner?

**Comment by williamdes** [comment]
@mauriciofauth what do you think about this solution ?

NB: do not merge the target must be QA_5_0

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you for your work @victorphoenix3 !

**Pull request merged**
