### PR TITLE
Abhishek kanojia

### PR DESCRIPTION
**Pull request by abhishekkanojia**
Warning "php 5.5+ is required " changed with one showing the current version of the PHP installed in the user's system.

### CODE REVIEW

**Comment by lem9** [comment]
Hello,
please squash your commits (see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). Also you did not follow my instructions given in your previous pull request about the Signed-Off-By line and about your author name, so it would be better to redo your commit. I could do it in your name but if your goal is to integrate our community, it's better you do it yourself. Reactions?

**Comment by dujam2014** [comment]
Thank you for your feedback . I am having a hard time understanding the git and its features , i am trying hard to understand it to every possible extent . I really want to contribute my ideas to the project . From now onwards , i'll make sure to do it in the appropriate manner .

**Comment by abhishekkanojia** [comment]
Thank you for your feedback . I am having a hard time understanding the git and its features , i am trying hard to understand it to every possible extent . I really want to contribute my ideas to the project . From now onwards , i'll make sure to do it in the appropriate manner.

**Comment by lem9** [comment]
Do you want me to do the commit in your name?

**Comment by ibennetch** [comment]
If you're having problems or questions, you can ask for help here, check our wiki page for git usage information, or there are several really good Git introductions online (I found the official book quite helpful).

**Comment by abhishekkanojia** [comment]
@lem9  Yes Please ,Not an issue :) . 
github                                                                                                        
Please have a look a the attached image and let me know whether it is a right way to commit the changes thereafter pushing it to remote and  creating a pull request from github?

**Comment by udan11** [comment]
@abhishekkanojia Instead of adding that `Signed-off` line by yourself simply add `--signoff` to the `git commit` command.

**Comment by abhishekkanojia** [comment]
@udan11  Thank you :) .I have already defined the my git identity using "git config --global user.name " and verified the same. Do I need to explicitly mention the author name during commit or it will automatically take my git identity as author ??

**Comment by udan11** [comment]
It will automatically use your name as author. After creating a commit, you can type `git log` and you'll see all commits. The first one from the list will be the last one (the one that you just created). It should mention the name of the author (yours).

**Comment by abhishekkanojia** [comment]
Thank you once again @udan11

**Comment by lem9** [comment]
Commit done in master: https://github.com/phpmyadmin/phpmyadmin/commit/1fa2fbdd0918b1848f4cd89f6f37e612de2e5d2d

**Comment by abhishekkanojia** [comment]
Q.1 Is there any specific function defined for redirection of link using ajax ? Just working on a new feature stuck at point where redirection is to be made .I would like to know the name of  function and its usage already defined for ajax redirection from one link to another. 

Q.2   For redirecting from one page to another say (from index.php to db_sql.php) , the parameters passed in url are "db","table", "server" and "token". I am able to access token parameter from session. how to access other parameters ? 
parameters


Q.3 How to display dismissible alert  (the one that is used to display a change in row) ? 
alert

Q.4 In which javascript file I should place my code so that it get included in each and every page ? I am using common.js file for this purpose .

**Comment by zixtor** [comment]
@abhishekkanojia If it is not related to this issue, please subscribe and post questions to developers@phpmyadmin.net list. See https://lists.phpmyadmin.net/mailman/listinfo/developers

**Comment by abhishekkanojia** [comment]
@zixtor Thanks ..... Subscribed to developer's mailing list . Should a write an email describing the same to developers@phpmyadmin.net for discussion ?

**Comment by zixtor** [comment]
@abhishekkanojia yes, for all questions or discussion related to PMA development.

**Pull request closed without merging**
