### PR TITLE
Modified CSS value font-size to revert instead of 1em.

### LINKED ISSUE #16252: Font size too small when editing rows
The font size is too small when editing rows in Chrome and the new Edge browser.

I don't remember the font ever being that small - it used to be the same size as the normal row text.

I'm using:
phpMyAdmin v4.9.5
Chrome v83.0.4103.116
Edge Chrome Browser v83.0.478.61

small-font-size

### PR DESCRIPTION
**Pull request by rajat315315**
Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Please describe your pull request.
I have modified the property `font-size` for `textarea` to value `revert` instead of `1em` in ALL themes.

Fixes #16252 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
Could you try another approach ?
Because https://caniuse.com/css-revert-value has poor support.

**Comment by rajat315315** [comment]
Changed from `revert` to `initial`.

**Comment by williamdes** [comment]
> initial

We still need to support IE .. (https://github.com/phpmyadmin/phpmyadmin/blob/master/.browserslistrc#L9)
https://caniuse.com/css-initial-value

**Comment by rajat315315** [comment]
ok

**Comment by qcybb** [comment]
Any ETA on when this fix will go live? 

It's very difficult to work with phpMyAdmin when the row's font size is so small.

**Comment by rajat315315** [comment]
Fixed.

**Comment by qcybb** [comment]
I'm not sure you want to adjust input and select - only textarea. Adjusting the other 2 makes them look too big.

Setting only textarea to "font-size:1.3em" looks good over here.

github

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
> I'm not sure you want to adjust input and select - only textarea. Adjusting the other 2 makes them look too big.

I agree

I rebased the changes and applied the new font width only for textareas.
Tested the fix and it makes sense, I will be merging this fix soon if anyone does comment against.

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
