### PR TITLE
Feature Request #1625 Autocomplete Sql

### PR DESCRIPTION
**Pull request by pratik**
Gives an option to user to toggle autocomplete of table and column
names in config settings

Signed-off-by: Pratik Sethia pratiksethia1@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Pratik,
tested with IE 11 and Firefox 36. In both cases, when the feature is deactivated via Settings, whenever I start to type in a SQL box, I get a Javascript error.

**Comment by pratiksethia1** [comment]
Thanks Marc, I'll try to fix it

**Comment by pratiksethia1** [comment]
After multiple tries, in addition to IE and Firefox, the error is even generating in chrome(39/MacOS).
In past also, some people reported same problems but the issue seemed to be resolved by clearing cache/cookies or by reinstalling. But these workarounds are not working in these case.

**Comment by lem9** [comment]
Pratik,
with f7c0896 the bug is gone for me, but it does not seem a good idea to send one POST per character typed.

**Comment by pratiksethia1** [comment]
May be i'm not right but It's still sending the whole table with the response.

**Comment by lem9** [comment]
Pratik,
is your comment related to my remark about the one POST per character?

**Comment by pratiksethia1** [comment]
Yes Marc.

**Comment by lem9** [comment]
Well I don't understand it. In the current master, without your patch, a POST request is not sent for each character typed in the SQL box. With your patch, there is one POST request per character typed, do you find this normal?

**Comment by pratiksethia1** [comment]
I agree it isn't normal. I'll try to figure something out.

**Comment by nisargjhaveri** [comment]
@lem9, this is probably because the autocomplete function in JavaScript [(here)](https://github.com/phpmyadmin/phpmyadmin/blob/master/js/functions.js#L1730) keeps trying until it gets the table list on each character typed. The PR just prevents tables/columns list from server. So, on next character entry, it tries again.

@pratiksethia1, The correct way would be to not send a request to server at all if this is disabled.

**Comment by pratiksethia1** [comment]
Yea i'll add a die function and submit patch. Thanks

**Comment by lem9** [comment]
@nisargjhaveri Good point.

**Comment by pratiksethia1** [comment]
Marc,
would it be okay if I store the value of $GLOBALS['cfg']['EnableAutocompleteForTablesAndColumns'] in a variable by including a script in the php file and then accessing the value in function.js , so that it becomes one time thing as suggested be @nisargjhaveri

**Comment by lem9** [comment]
If you need to access at the js level something that comes from the PHP level, see https://wiki.phpmyadmin.net/pma/Page_loader#Accessing_common_parameters_via_JS

**Comment by pratiksethia1** [comment]
Thanks, I went through it already.
But I implemented the issue with https://github.com/pratiksethia1/phpmyadmin/commit/c3e0a58ec16655513dd43bf525b7bb296997280f

**Comment by pratiksethia1** [comment]
Its tested in all the browsers and environments.

**Comment by lem9** [comment]
Thanks.

**Comment by pratiksethia1** [comment]
Took a little time to find the best solution!
Thanks for guiding.

**Pull request merged**
