### PR TITLE
Inject dependencies

### PR DESCRIPTION
**Pull request by Tithugues**
### Description

Provide more and more services...

Related to #15266

### CODE REVIEW

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
There are some PHPStan errors.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/536940586#L441

You can run PHPStan with:
```
vendor/bin/phpstan analyze
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
There was 1 PHPUnit error:
```
1) PhpMyAdmin\Tests\Controllers\Table\StructureControllerTest::testPMAGetDataForSubmitMult
TypeError: Argument 4 passed to PhpMyAdmin\Controllers\Table\StructureController::getDataForSubmitMult() must be an instance of Symfony\Component\DependencyInjection\ContainerBuilder, array given

/home/travis/build/phpmyadmin/phpmyadmin/libraries/classes/Controllers/Table/StructureController.php:1539
/home/travis/build/phpmyadmin/phpmyadmin/test/classes/Controllers/Table/StructureControllerTest.php:289
```
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/537521864#L433

**Comment by Tithugues** [comment]
> There was 1 PHPUnit error:
> 
> ```
> 1) PhpMyAdmin\Tests\Controllers\Table\StructureControllerTest::testPMAGetDataForSubmitMult
> TypeError: Argument 4 passed to PhpMyAdmin\Controllers\Table\StructureController::getDataForSubmitMult() must be an instance of Symfony\Component\DependencyInjection\ContainerBuilder, array given
> 
> /home/travis/build/phpmyadmin/phpmyadmin/libraries/classes/Controllers/Table/StructureController.php:1539
> /home/travis/build/phpmyadmin/phpmyadmin/test/classes/Controllers/Table/StructureControllerTest.php:289
> ```
> 
> https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/537521864#L433

Thank you. I didn't yet find time to fix this one.
I believe there still are selenium errors, so I'll wait for the new report.

**Comment by Tithugues** [comment]
It seems that there are no more errors (even in Selenium tests!), so unless you find other things to fix / change, and if the global idea of this PR is OK, I can squash the commits if you prefer.

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged. Thank you for your contribution.

**Pull request merged**
