### PR TITLE
Fixes error in foreign key sql generation + drop foreign key contraint

### PR DESCRIPTION
**Pull request by aroralakshya**
Changed:
	templates/table/relation/foreign_key_row.twig
The destination_column_names were getting passed as a 1d array, the names when extracted gave a string. Passing it as a 2d array (see templates/table/relation/foreign_key_row.twig lines 123,133) fixes the issue.

Signed-Off-By: Lakshay arora (b16060@students.iitmandi.ac.in)

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by Gemorroj** [comment]
I think it is also necessary to correct the error display.
The response "success: true", which is wrong.

**Comment by nulll-pointer** [comment]
I thing making success:false also expects an error parameter in the json object returned, the error is generated during parsing so i'm still figuring out how to display the message.

**Comment by mauriciofauth** [comment]
Related to #13941

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
