### PR TITLE
Fix #17869 - Removing the stale table header cell.

### LINKED ISSUE #17869: Extra table header cell incorrectly added
### Describe the bug

View any database table in Browse mode. On the right of the header row there is an extra cell. It's only on the header, not the table body. Image:

Screenshot 2022-11-04 at 13 45 38

In the HTML it's an extra td element like this:

    <td class="d-print-none"><span></span></td>

It doesn't happen on the demo server, but the theming is slightly different on there (in 5.2 it's paler).

### Server configuration

- Operating system: Ubuntu
- Web server: nginx
- Database version: 8.0.29-0ubuntu0.20.04.3
- PHP version: 7.4.3
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Chrome/Firefox
- Operating system: macOS

### PR DESCRIPTION
**Pull request by vimalMK**
Signed-off-by: Vimal K <vimalinfo10@gmail.com>

### Description

Removing the stale table header cell.

image

Fixes #17869 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Review by williamdes — CHANGES_REQUESTED** [review]
I am looking into this but I feel there was a reason. So for now I am blocking this until I figure out

Sources:
https://github.com/phpmyadmin/phpmyadmin/commit/76409e259d061ba65458516ca16c8f99588f6630#diff-401fa9ac455f80ecd82d75155b189c586eadf55f976b2050915d031eaf79a39dR2050-R2065
https://github.com/phpmyadmin/phpmyadmin/commit/37d50c1822c9b3b8d8bd1f5cb5c8a5e74ee1d268#diff-98f45ff6ce5760b40756ed7ce67dc0b880e8ba55f1298d7c79bd7bb8b49a3d60R671-R685

It goes back 20 years ago ...
What was the reason 🤔

**Comment by williamdes** [comment]
Seems like it goes back 21 years ago from 16843c684b5d5229343595c68e4331bbc8dc0c3e

**Review by williamdes — CHANGES_REQUESTED** [review]
This fix needs to also delete the line in 

https://github.com/phpmyadmin/phpmyadmin/blob/e97af7568e47ce6c58decd63fd38c5a6595dbeb8/libraries/classes/Display/Results.php#L1315

You need to go to information_schema DB and OPTIMIZER_TRACE view
See: https://github.com/phpmyadmin/phpmyadmin/issues/17869#issuecomment-1313619549

**Comment by vimalMK** [comment]
> This fix needs to also delete the line in
> 
> https://github.com/phpmyadmin/phpmyadmin/blob/e97af7568e47ce6c58decd63fd38c5a6595dbeb8/libraries/classes/Display/Results.php#L1315
> 
> You need to go to information_schema DB and OPTIMIZER_TRACE view See: [#17869 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/17869#issuecomment-1313619549)

shall I go ahead and remove it now or wait for the update regarding the purpose?

**Comment by williamdes** [comment]
> > This fix needs to also delete the line in
> > https://github.com/phpmyadmin/phpmyadmin/blob/e97af7568e47ce6c58decd63fd38c5a6595dbeb8/libraries/classes/Display/Results.php#L1315
> > 
> > You need to go to information_schema DB and OPTIMIZER_TRACE view See: [#17869 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/17869#issuecomment-1313619549)
> 
> shall I go ahead and remove it now or wait for the update regarding the purpose?

I think you can go ahead, please be sure to check as much as possible that it is not breaking something and remove the method param if it is not used anymore

**Comment by vimalMK** [comment]
> > > This fix needs to also delete the line in
> > > https://github.com/phpmyadmin/phpmyadmin/blob/e97af7568e47ce6c58decd63fd38c5a6595dbeb8/libraries/classes/Display/Results.php#L1315
> > > 
> > > You need to go to information_schema DB and OPTIMIZER_TRACE view See: [#17869 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/17869#issuecomment-1313619549)
> > 
> > 
> > shall I go ahead and remove it now or wait for the update regarding the purpose?
> 
> I think you can go ahead, please be sure to check as much as possible that it is not breaking something and remove the method param if it is not used anymore

Sounds good.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
I don't think such change should go to a QA branch.

**Comment by williamdes** [comment]
> I don't think such change should go to a QA branch.

Yeah, it's a bit too risky. Let's merge into master branch

**Comment by williamdes** [comment]
This has to be re-done, the code has changed too much for me to be able to merge this

**Pull request closed without merging**
