### PR TITLE
fixed html element typo in indexes.js

### PR DESCRIPTION
**Pull request by t-howell**
### Description

I was looking for issues with inline styles as described in this thread: https://github.com/phpmyadmin/phpmyadmin/issues/12262 when I found a misspelled element. I'm just getting to know this project, so let me know if there are any issues, or if this is too small to merge! 

I realize I forgot to signoff in my commit message, and will do so going forward.

Fixes #

Fixed misspelling of "label" on line 293 ('</lablel>')

### CODE REVIEW

**Comment by t-howell** [comment]
I'm not really sure what to do about the signoff now.. the git rebase patch failed. Can we count the correct signoffs? Sorry for all the commits!

**Comment by williamdes** [comment]
@t-howell thank you for the contribution, I will fix the git history before merging :)

**Comment by t-howell** [comment]
Thank you so much @williamdes !!

**Comment by williamdes** [comment]
@t-howell Can you review the diff and tell me if I missed some changes ?

**Comment by t-howell** [comment]
@williamdes I think that might have been the CSS changes. I moved the inline css out of a js file and only updated the original theme css. I have added the same lines to pmahomme now.

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@t-howell Thank you for your patience, I rebased your work and It looks good

but:
> Fixed misspelling of "label" on line 293 ('')

I could not find that change in the diff

can you please use :
```
git checkout master
git pull
git reset --hard origin/master
```
before adding any more commits, or I will have to do the fixing work again..

**Comment by williamdes** [comment]
Hi @t-howell 
I merged your work, I apologize for taking so long to merge a very simple PR
Your contributions are very welcome and thank your for this one !

**Pull request merged**
