### PR TITLE
Use Bootstrap buttons component 

### PR DESCRIPTION
**Pull request by MauricioFauth**
Uses [Bootstrap buttons component](https://getbootstrap.com/docs/4.1/components/buttons/) for buttons style.

### CODE REVIEW

**Comment by maandeep98** [comment]
Hi There,
I am Maandeep Singh and I want to work in Convert the UI to Bootstrap 4 this year for gsoc 2019. I had spent some good time with front-end web programming and want you to mentor me for gsoc. Please help me regarding this.

**Comment by Sid2217** [comment]
Hi ,
I am Siddhesh Ladkat and I am interested in this project of converting UI to Bootstrap 4 .
I have spent some time in Bootstrap and will share a link to my projects  that i have previously worked on . 
And i intend to apply for this year's gsoc 2019 .

**Comment by Manda7rsnt** [comment]
Hi there @mauriciofauth ,

I am Prashant Manda and I wish to work in **Convert the UI to Bootstrap 4** this year for **GSOC 2019**. I have prior exposure to frameworks for developing websites and web apps with HTML/CSS and JS. I would really appreciate your mentoring regarding the same. 

Regards
Prashant Manda

**Comment by Nayananga** [comment]
Hi,

I'm Nayananga Muhandiram, a second year undergraduate in Computer science at the University of Jaffna, Srilanka. I would like to do this project for GSoC 2019. Please help me get started.

**Comment by mauriciofauth** [comment]
Hi, thank you all for the interesting.

Our main entry point for new GSoC hopefuls is the wiki page [GSoC_home](https://github.com/phpmyadmin/phpmyadmin/wiki/GSoC_home). We also have some discussion occurring in our [Gitter room](https://gitter.im/phpmyadmin/GSoC) or on the [developers](https://lists.phpmyadmin.net/mailman/listinfo/developers) mailing list.

**Pull request merged**
