### PR TITLE
Add number formatting to Total on Browse

### LINKED ISSUE #18666: add `number_format` function to rows count
please apply `number_format` function to count of query result for more readability:

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Closes #18666

Should it be done in QA too?

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thanks!
No need for QA as it's a good change but clearly will maybe confuse users as they do not expect such changes

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
> Should it be done in QA too?

I think this could count as an accessibility issue, instead of an enhancement, so it can go to QA as well.

**Comment by MauricioFauth** [comment]
Let's keep it for 6.0.

**Comment by liviuconcioiu** [comment]
Dumb question: shouldn't the formatting be added to between rows too?

Untitled

**Comment by kamil-tekiela** [comment]
It should and I thought I did.

**Comment by williamdes** [comment]
> Dumb question: shouldn't the formatting be added to in between rows too?
> 
> Untitled

I would not format this one, as other values can be there, it could also be strings or hex

**Pull request merged**
