### PR TITLE
Refactoring designer

### PR DESCRIPTION
**Pull request by Bournvita1998**
### Description

Removed vanilla js and added jQuery at several places
Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Can you squash your commits and rebase with the latest changes in [gsoc-db-designer](https://github.com/phpmyadmin/phpmyadmin/tree/gsoc-db-designer) branch?

**Comment by Bournvita1998** [comment]
@mauriciofauth Okay I will do that.

**Comment by shucon** [comment]
Travis build failed. Refer https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/543239134

**Comment by Bournvita1998** [comment]
@mauriciofauth @shucon  I have created a new PR for refactoring designer. It's because when I was trying to squash with 9 commit messages, I don't know how but it was showing 784 commits in the next window which we get after entering the command on terminal.

You can have a look at that [here](https://github.com/phpmyadmin/phpmyadmin/pull/15318).

**Comment by Bournvita1998** [comment]
[here](url)

**Pull request closed without merging**
