### PR TITLE
Fix #16222 Secure parameters before giving them to DI

### LINKED ISSUE #16222: Can't use search page when table have a special characters
### Describe the bug

I got error when I try to search in some table that contains special characters in the table name.

### To Reproduce

1. Create some table with a special character as "ç", "ã", "õ" and others.
2. Select the created table.
2. Click in the search button.

### Expected behavior

The search page with the selected table columns as options to search/select.

### Screenshots

error

### Server configuration

- Operating system: Windows Server 2016
- Web server: Microsoft-IIS/10.0
- Database version: MySQL 8.0.19
- PHP version: 7.4.1
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome Version 83.0.4103.116
- Operating system: Windows 10

### Additional context

In the screenshot I've reproduced the same problem in my own desktop using xampp 7.2.31

### PR DESCRIPTION
**Pull request by Tithugues**
### Description

Parameters sent to DI may sometimes have content that look like DI parameters. The intent of this PR is to secure the `url_query` parameter used in many pages.

Fixes #16222

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
:clap: Thank you for the work and tests :100: 

I will try it and merge if everything is okay
For now I am wondering if I call my table `%response%_%table%` will it break ?

**Comment by Tithugues** [comment]
Ahah, you're looking for problems!

I didn't check this one... Maybe it will break...

**Comment by Tithugues** [comment]
Please don't validate this one for now. There might be a cleaner way to secure the parameters, with less impact.

**Comment by Tithugues** [comment]
This PR is replaced by https://github.com/phpmyadmin/phpmyadmin/pull/16240

This one will also manage the tables named %table%.

**Pull request closed without merging**
