### PR TITLE
Fixes #14658 - Regression on multi table query

### LINKED ISSUE #14658: Regression on multi table query functionality (foreign keys)
### Describe the bug
Since 4.8.0 foreign keys are not part of the generated query.

#### Test data
```sql
CREATE TABLE `table1` (
  `idtable1` int(11) NOT NULL COMMENT 'id table 1',
  `valuetable1` varchar(255) NOT NULL COMMENT 'value table 1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='table 1';
ALTER TABLE `table1`
  ADD PRIMARY KEY (`idtable1`);
ALTER TABLE `table1`
  MODIFY `idtable1` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id table 1';
CREATE TABLE `table2` (
  `idtable2` int(11) NOT NULL COMMENT 'id table 2',
  `valuetable2` varchar(255) NOT NULL COMMENT 'value table 2'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='table 2';
ALTER TABLE `table2`
  ADD PRIMARY KEY (`idtable2`);
ALTER TABLE `table2`
  MODIFY `idtable2` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id table 2';
ALTER TABLE `table2` ADD CONSTRAINT `fk_id_tables` FOREIGN KEY (`idtable2`) REFERENCES `table1`(`idtable1`) ON DELETE RESTRICT ON UPDATE RESTRICT;


```

Use screenshots.
1. Use test data above
2. Select `table1.*` and `table2.*` like in screenshot
3. Update query
4. See that foreign keys are not part of the request using phpMyAdmin version >`4.7.9`

### Expected behavior

I expect that foreign keys are part of the generated query like `4.7.9` did.

#### Generated query
```sql
SELECT `table1`.*, `table2`.*
FROM `table1`
    LEFT JOIN `table2` ON `table2`.`idtable2` = `table1`.`idtable1`
```
#### Generated query
```sql
SELECT `table1`.*, `table2`.*
FROM `table1`, `table2`;
```
#### Screenshot
5.0.0-dev

### Server configuration
- phpMyAdmin version: 4.8.3, 4.7.9, 5.0.0-dev

### Additional context

Using multi table query

### PR DESCRIPTION
**Pull request by ales-bulko**
### Description

Added functionality to generate SELECT query with JOINs of requested tables. It was mentioned that it's just a bug and it was working in previous versions, but I did not see any code fragments that would make it possible. Please, feel free to suggest any better solution if you don't like that one.

Fixes #14658

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

Signed-off-by: Aleš Buľko ales.bulko@student.tuke.sk

### CODE REVIEW

**Comment by williamdes** [comment]
@ales-bulko Your work looks great, I will test on my local setup when I have time and approve this PR :)
If you need help for DCO feel free to ask

**Comment by ales-bulko** [comment]
Thanks, I will wait for response. I already fixed signoff. I just wrote my name without diacritics. :)

**Comment by williamdes** [comment]
@ales-bulko Let me know when you are finished working on this PR :)

**Comment by williamdes** [comment]
@ales-bulko Can you fix this error ?

`Uncaught TypeError: Cannot read property 'length' of undefined`

  | tryJoinTable | @ | db_query_generator.js?v=5.0.0-dev:94
-- | -- | -- | --
  | appendTable | @ | db_query_generator.js?v=5.0.0-dev:104
  | generateFromBlock | @ | db_query_generator.js?v=5.0.0-dev:122
  | (anonymous) | @ | db_multi_table_query.js?v=5.0.0-dev:106
  | new_func | @ | error_report.js?v=5.0.0-dev:252
  | dispatch | @ | jquery.min.js?v=5.0.0-dev:2
  | $event.dispatch | @ | jquery.event.drag-2.2.js?v=5.0.0-dev:374
  | y.handle | @ | jquery.min.js?v=5.0.0-dev:2

### Debug

Failed: `db_multi_table_query.php?db=accountmanager&tables%5B%5D=auths&tables%5B%5D=auths__websites&ajax_request=1&token=3%7C%23%2FGa%24r%23%3ES.%7F%5C%7Df&_nocache=1541407626533361984&token=3%7C%23%2FGa%24r%23%3ES.%7F%5C%7Df`

Response: `{"redirect_flag":"1","success":false,"error":""}`

**Comment by williamdes** [comment]
@ales-bulko If you need my database to reproduce this ask me :)

**Comment by williamdes** [comment]
@ales-bulko I can not reproduce this issue on my production server.
This pull-request works well on my production server.
I will investigate for you on my local setup ;)

**Comment by ales-bulko** [comment]
@williamdes I have applied your script and I was able to create SELECT query with JOIN. It is just guess but is it possible that when you encountered error, your session just expired? There is just one place in code where I found that redirect_flag is set to 1 and it's when you are redirected to login page.

Generated query:
```
SELECT `fks`.*, `users`.*
FROM `fks` 
	LEFT JOIN `users` ON `fks`.`idUser` = `users`.`id`;
```

**Comment by williamdes** [comment]
@ales-bulko The issue is that you need to pass `server={theserverid}` as parameter in the query that fetchs foreign keys.
Use a multi server setup to reproduce this issue :)

**Comment by ales-bulko** [comment]
@williamdes I didn't even know that I can define more than one database connections. I applied your fix and tried it with two connections. It works well :)

**Comment by ales-bulko** [comment]
Hello @williamdes, is there still some problem with that merge that I can fix? :)

**Review by williamdes — APPROVED** [review]
Looks good to me !
Thank you !
@ales-bulko I had forgot to add my review ^^

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Hi. Thank you for your contribution.

There are some coding style issues with _db_query_generator.js_. See:
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/452847937#L645

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
