### PR TITLE
Added: Integer Validations on Search page

### LINKED ISSUE #13326: No quotes when field type is int
https://demo.phpmyadmin.net/QA_4_9/tbl_select.php?db=sakila&table=actor

    SELECT * FROM `actor` WHERE `actor_id` = test LIMIT 0, 25 :(

I think it should put quotes around test..

### PR DESCRIPTION
**Pull request by thesmallstar**
Signed-off-by: Manthan Surkar <manthan.surkar@gmail.com>

### Description
**The only thing I am worried about is the way the validation appears(table expands) I will fix that once these changes are approved.** 

#15794 refer discussion on this PR for details, used a different branch to save the work that was done on this PR.

Fixes - Does not fix any particular issue, added as a suggestion. 

image

 Fixes #13326 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by thesmallstar** [comment]
Since these are validations( Rather a feature and not bug) I made a PR on master Branch, should I change it?

**Review by williamdes — APPROVED** [review]
The code looks good and clean, testing it now

**Comment by williamdes** [comment]
> I don't think it is an error though since the function is called through and event

Can you find out where there is a line to ignore this error for the original function below ?
One found, add yours to the ignore list

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
Search:
image
Insert:
image

I am not sure that you can do something about it, if you can not solve it I will merge it and try to fix it :+1: 

Maybe an unsigned/not unsigned issue

**Comment by williamdes** [comment]
I tested it and it works great !
:tada: :1st_place_medal:

**Comment by williamdes** [comment]
@thesmallstar can you use QA_5_0 as base and force-push ?

**Comment by thesmallstar** [comment]
@williamdes I have spent quite a time trying to find a way to solve that, I could not find a way without an easy way for it. You can merge this PR I will still try to find if I can do something about it and will let you know accordingly :)

**Comment by thesmallstar** [comment]
> @thesmallstar can you use QA_5_0 as base and force-push ?

Yes

**Comment by thesmallstar** [comment]
image
Will this work? haven't done this before

**Comment by williamdes** [comment]
@thesmallstar I will do it for you, thank you for your great work !

https://github.com/phpmyadmin/phpmyadmin/pull/15819#issuecomment-576010209 is a priority soon to help you do such operations :)

**Comment by williamdes** [comment]
> Will this work? haven't done this before
yes, you can

I checked and you are using QA_5_0 as base
image

**Comment by thesmallstar** [comment]
Oh sorry, my bad!

**Comment by williamdes** [comment]
Merged :tada:

**Pull request merged**
