### PR TITLE
Add iconv to composer.json as requirement

### LINKED ISSUE #14642: Missing dependency on PHP iconv extension?
Functions supplied by the PHP iconv extension are used (e.g. in vendor/symfony/polyfill-mbstring/Mbstring.php) but the iconv extension is not listed in composer.json.

Should iconv be added to the "require" list in composer.json?

### PR DESCRIPTION
**Pull request by davidporos92**
### Description

Added iconv PHP extension as a requirement to composer.json.

Fixes #14642

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Can you please rebase and use signoff like in your commit : https://github.com/phpmyadmin/phpmyadmin/pull/14645/commits/001f1ce09c371ca09b04b90eb0f862b849eb820c ?

**Comment by davidporos92** [comment]
Sure, but can you please give me some hint how to do it properly, because I did not use rebase much :\

**Comment by williamdes** [comment]
Yes
`git rebase origin/master --exec 'git commit --amend --no-edit --signoff'`
Will rebase and signoff the commit.
Add `--interactive` to enable interactive mode and remove commits if needed.

**Comment by davidporos92** [comment]
It says "error: unknown option `amend'"

**Comment by williamdes** [comment]
Just tried on my local repo and it works perfectly.
Can you send a screenshot of the command line ?

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
