### PR TITLE
Fix bug#4897

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by lem9** [comment]
@nisargjhaveri Please rebase because of a recent fix in QA_4_4

**Comment by nisargjhaveri** [comment]
This seems merge-able. What do I need to do?

**Comment by lem9** [comment]
Try this, assuming that "origin" is from where you forked:
````
git rebase -i origin/QA_4_4
````

**Comment by nisargjhaveri** [comment]
I did that and updated the PR.

But still, not quite clear about why it was needed? Can you please explain?

**Comment by lem9** [comment]
There was a problem in QA_4_4 that produced a fatal error when Travis ran the test suite under PHP < 5.5. I fixed this bug in 4c5592e6325e76d37b698d6138ace270f4ec5583, so by rebasing,  you incorporated this fix in your branch. Then it is expected that Travis will complete the test suite in your pull request. Seeing that the test suite runs correctly in many PHP versions, as tested by Travis, is encouraging for the student and the mentor.

**Comment by nisargjhaveri** [comment]
Got it. Thanks :)

**Comment by lem9** [comment]
Also, when GSoC starts and you have a feature branch (based on master), it will be interesting to rebase it from time to time.

**Comment by nisargjhaveri** [comment]
Umm. It still fails. Probably on the same test. Any idea?

**Comment by lem9** [comment]
It failed on another test that I just fixed (4db6481ea347d9409fa9d52f1bebe4b96ee377f6) , please rebase again.

**Comment by lem9** [comment]
Once again please ...

**Comment by nisargjhaveri** [comment]
Done.

**Comment by lem9** [comment]
Not only does it fix the bug, but it clarifies the logic.

**Pull request merged**
