### PR TITLE
Fixed most of deprecated Jquery calls

### PR DESCRIPTION
**Pull request by williamdes**
```regex
\.(blur|focus|focusin|focusout|resize|scroll|click|dblclick|mousedown|mouseup|mousemove|mouseover|mouseout|mouseenter|mouseleave|change|select|submit|keydown|keypress|keyup|contextmenu)\(\)
```

Ref:  #13173

### CODE REVIEW

**Review by MauricioFauth — APPROVED** [review]

**Comment by arcanisgk** [comment]
versión: 4.9.0.1 (updated).
Google Chrome Versión 75.0.3770.142.

image

**Comment by williamdes** [comment]
@arcanisgk As you can see above the warnings will be removed in 5.0.0

**Comment by yashrajbothra** [comment]
Hey @williamdes did you change all calls manually?

**Comment by williamdes** [comment]
Hey @yashrajbothra 
I am using Microsoft Visual Studio Code and it has an awesome regex search and replace
So I used the regex https://github.com/phpmyadmin/phpmyadmin/pull/15355#issue-291273760 and did automatic replacements and some manual ones

**Comment by arcanisgk** [comment]
Warning with Jquery Version 5.1.0-dev: 
https://demo.phpmyadmin.net/master-config/

image

image

image

**Comment by arcanisgk** [comment]
@williamdes when they migrate to BS and remove the jquery dependency completely we could close this post...

**Pull request merged**
