### PR TITLE
Fix tests for regression #14422

### LINKED ISSUE #14422: Table comment not showing since 4.8.1
Introduced by https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a6
### Steps to reproduce
1. Install phpMyAdmin 4.8.1
2. Execute :
```sql
CREATE TABLE `test` (
  `test` int(11) NOT NULL,
  `testvirt` varchar(11) GENERATED ALWAYS AS (`test`) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='test comment';
```
3. Browse to table

### Expected behaviour
Show table comment in header
OK

### Actual behaviour
No comment in header
bug

### Why

https://github.com/phpmyadmin/phpmyadmin/blob/31e9a31695dd62cebe1d6e21f20da72195f7d1de/libraries/classes/DatabaseInterface.php#L730-L731

https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a#diff-7e4ecd960e6109e08a7b4f472e0101edR344

https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a#diff-28fc97db3ff33e2fab815cbbb01790ccL69

### PR DESCRIPTION
**Pull request by williamdes**
Fixes the unit tests of issue #14422

### CODE REVIEW

**Comment by lem9** [comment]
It's better to target the QA_4_8 branch for this kind of regression fix.

**Comment by williamdes** [comment]
@lem9 Yes, I can not change the target
I recreate the PR ?

**Comment by lem9** [comment]
Please do.

**Comment by williamdes** [comment]
@lem9 Done, I think #14550 should be merged on `QA_4_8` only.
#14423 Has the unit tests fixed and should be merged on `master`.

**Comment by williamdes** [comment]
@mauriciofauth This PR contains a fix for unit tests.
Can you please merge this one ?, the unit tests fail for some reason
They pass on my local setup.

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
