### PR TITLE
Fixes button issues

### LINKED ISSUE #15190: plugin buttons not responsive
### Describe the bug

plugin buttons not responsive (breaking/splitting)

### To Reproduce

1. Go to 'Plugin'.
2. Try to resize browser window.
3. You will notice something like I've captured in the screen shot below.

btn_issue1

This is really horrible how the buttons are splitting into 2 parts , and appearing in different lines.
a small part of butons 'INFORMATION SCHEMA' and 'VALIDATE PASSWORD' is appearing on differnt line .

### PR DESCRIPTION
**Pull request by murex971**
Signed-off-by: Nupur Agrawal <nupur202000@gmail.com>

Fixes https://github.com/phpmyadmin/phpmyadmin/issues/15190

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Hi @murex971. Thanks for your contribution.

This pull request works, but I think a better solution is to use the Bootstrap button classes, like `class="btn btn-primary"`.

**Comment by murex971** [comment]
hi @mauriciofauth 
I first thought of applying bootstrap button only but in this process, whole of the appearance of button and its text will be changed since they are defined in <a> tags whereas btn-primary has its own predefined properties.
Also if we remove the <a> tag completely then we have to join an 'on click' event to the button.
So AFAIK the changes I've made serves the purpose also and do not affect the present code much also.
Even then you want any changes, please let me know, I'll try to do the necissities.

**Comment by mauriciofauth** [comment]
@murex971 I was thinking in adding the Bootstrap classes to the `a` tag so is not necessary to add a `button` tag. And then remove the custom style at: https://github.com/phpmyadmin/phpmyadmin/blob/ecfeeb9bf2cbca9df550ebf4932ed713d2272c5c/themes/pmahomme/scss/_common.scss#L1823

And also apply the changes to Metro and Original themes.

**Comment by murex971** [comment]
OK, I'm working on it.

**Comment by murex971** [comment]
The other two themes already have btn btn-primary class mentioned inside <a> tag.

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
