### PR TITLE
Issue#14965

### PR DESCRIPTION
**Pull request by Gaurav-Punjabi**
Signed-off-by: Gaurav Punjabi gaurav.punjabi6@icloud.com

### Description
This is in reference to solve issue #14965. Removed the default server collation from the footer of databases table in the database page. Solved by simply removing the collation label in the footer.

##### Before
screen shot 2018-11-01 at 12 41 07 am

##### After
screen shot 2018-11-01 at 12 41 19 am

Fixes #14706 

Before submitting pull request, please review the following checklist:

  Make sure you have read our CONTRIBUTING.md document.
  Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the master branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
  Every commit has proper Signed-off-by line as described in our DCO. This ensures that the work you're submitting is your own creation.
  Every commit has a descriptive commit message.
  Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
  Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Fixes: #14695

**Comment by ibennetch** [comment]
I believe the bot doesn't like the hyphen in your first signed-off-by line (Gaurav-Punjabi compared to Gaurav Punjabi). I wouldn't worry about it though in this case since clearly you intended to agree with the DCO, and got the next two correct.

**Comment by williamdes** [comment]
@ibennetch @Gaurav-Punjabi I manually set DCO to pass because it is correct :)

**Comment by williamdes** [comment]
Merged into `master`, Thank you for your contribution @Gaurav-Punjabi !

**Pull request merged**
