### PR TITLE
Fix alignment of action #12167

### PR DESCRIPTION
**Pull request by ankitjain28may**
Signed-off-by: Ankit Jain ankitjain28may77@gmail.com

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ankitjain28may** [comment]
@mauriciofauth pls review the PR.

**Comment by mauriciofauth** [comment]
Some of the Selenium tests failed. See https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/278652033#L856

**Comment by ankitjain28may** [comment]
ok, I will fix them.

**Comment by mauriciofauth** [comment]
Please, use your real name in the Signed-Off-By line. See [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO)

**Comment by ankitjain28may** [comment]
@mauriciofauth Does it look good to you ?

**Comment by ankitjain28may** [comment]
@mauriciofauth pls review the PR

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
