### PR TITLE
problem regarding weblate-fix for saving attribute in central column

### PR DESCRIPTION
**Pull request by rakeshkumar4294**
In the new table create page in PMA , Pick from central column does not show attribute at its right place and does not update attribute column. I think it was left accidentally and forgot to split the extra column value to array as done in the PHP code. This is fix for it.
Signed-off-by: Rakesh Kumar rakeshkumar4294@gmail.com

### CODE REVIEW

**Comment by smita786** [comment]
Rakesh,
I am able to reproduce the issue. While create table, pick from central column is not updating attribute field right? Can you please mention here the commit you are talking about which introduced the issue ?

**Comment by rakeshkaundilya** [comment]
Yes ,
First it was initiated by me this pull request[pull request]( https://github.com/phpmyadmin/phpmyadmin/pull/1528) .
Then modified by weblate [pull request](https://github.com/phpmyadmin/phpmyadmin/commit/9c6da42e648cebbda9467a4f07ec7b1c142e92a7)

**Comment by smita786** [comment]
Hi @madhuracj 
I guess this is related to your this commit https://github.com/phpmyadmin/phpmyadmin/commit/4b057ae45f8bccb96fb074721e34ee2cb044c9bf . You might want to have a look. :-)
Thanks.

**Comment by nijel** [comment]
Just to clarify - Weblate does not change the code at all, the 9c6da42e648cebbda9467a4f07ec7b1c142e92a7 is merge commit, not sure why GitHub shows it as changing some code. @smita786 already mentioned the actual commit doing code changes (which was then merged by Weblate).

**Comment by madhuracj** [comment]
@rakeshkaundilya 
I think it's best to handle this at PHP level, so that JS code does not have to worry about the complications. 
Should be fixed with https://github.com/phpmyadmin/phpmyadmin/commit/3821b724cc5d105b06bbdb5f34705d2407dd2d8a Can you confirm?
I've moved the code to a single function that handle splitting.

**Comment by rakeshkaundilya** [comment]
Hi @madhuracj ,
There is just one little bug: we are not able to view the central columns list for a database,it can be fixed by modifying the line no 93 of central_columns.lib.php.
Everything else seems to be working fine.
Thanks.

**Comment by madhuracj** [comment]
Thanks @rakeshkaundilya. I made the commit under your name. https://github.com/phpmyadmin/phpmyadmin/commit/92d276b3aceda6514ab9dfb4e4d36571f3a58dfc

**Pull request closed without merging**
