### PR TITLE
Refactored Tracker to use SqlParser, Issue #11966

### PR DESCRIPTION
**Pull request by 007durgesh219**
Before submitting pull request, please check that every commit:
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them

Signed-off-by: Durgesh 007durgesh219@gmail.com

### CODE REVIEW

**Comment by 007durgesh219** [comment]
This is just for review not complete.  A parser bug needs to be fixed to complete it.  @nijel Kindly let me know if I am going in right direction

**Comment by 007durgesh219** [comment]
@nijel any updates on this??

**Comment by nijel** [comment]
Not yet, it was weekend and I tend to be offline during weekends ;-).

**Comment by nijel** [comment]
I think it looks good, but maybe @udan11 can comment on the parser usage here...

**Comment by 007durgesh219** [comment]
OK. Also there was bug in parser so I created PR waiting to be merged.

**Comment by 007durgesh219** [comment]
@udan11 any updates on this??

**Comment by nijel** [comment]
Thanks, I've merged this for 4.7.0.

**Pull request merged**
