### PR TITLE
Translated using Weblate (Filipino)

### PR DESCRIPTION
**Pull request by codygee237**
Hi this is my first pull request for this project and I am a beginner. Please review my pull request and correct me if I have made any mistakes. Thank you!

Currently translated at 6% out of 21,349 words (1290 words out of 21,349 words) and 6.5% out of 3208 strings (211 strings out of 3208 strings).

Signed-off-by: codygee237 <35871138+codygee237@users.noreply.github.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
Thanks, I've merged this through Weblate in 1d0c800eb2a4c7f6f783687f3bd2f258c2cfd120. 

Generally it is recommended to edit translations in Weblate as that way they will correctly get into all maintained branches, see https://hosted.weblate.org/projects/phpmyadmin/4-7/fil/

**Comment by codygee237** [comment]
Hello Sir, why is it not being merged?

**Comment by nijel** [comment]
I've merged the changes manually because you've added the file instead of changing existing one (po/fil.po).

**Comment by codygee237** [comment]
Alright Sir, is it okay that I won’t use webplate for my next translation on fil.po sir? So that I will just translate on the existing file in the repo.

**Comment by codygee237** [comment]
Can't you merge this commit yet? I can't be rewarded if I don't get ur approval for my translation for fil.po. Hehe. God bless @nijel  :)

**Comment by nijel** [comment]
No I can't merge it as the file is wrongly placed, sorry.

**Comment by codygee237** [comment]
Okay Sir, I will still continue my translation on this file but how can I correctly place it? Do I need to submit a PR after my translation or will the Weblate just directly pull request my translation? I'm still confused

**Comment by nijel** [comment]
Changes done directly in Weblate should go automatically to all maintained branches.

**Pull request closed without merging**
