### PR TITLE
removed blank space

### PR DESCRIPTION
**Pull request by Bharath-Shet1999**

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
Why ?
cc @ibennetch

**Comment by Bharath768** [comment]
iam new to github i was trying pull request..

my bad

**Comment by williamdes** [comment]
@Bharath768 You are welcome to create a pull-request if you want to fix a bug ;)
If you need help feel free to ask

**Comment by ibennetch** [comment]
This pull request only adds a space in the README file. If you're trying to do a test to see if you've gotten it right, then you have indeed successfully submitted a pull request, congratulations! If you have a bigger fix that didn't get included, mention that here and we can help you through adding more files to your commit.

One thing to note is that we do require contributions to use the git "signed off by" feature to indicate that you agree to our [DCO document](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) which basically states that any work you contribute is your own. Your commit did not include that, but next time you can add it when committing on your local machine with `git commit -s`.

Thanks for your interest in phpMyAdmin.

**Pull request closed without merging**
