### PR TITLE
Designer saves page successfully even if dB name has period.

### LINKED ISSUE #14945: Designer page save fails if dB name contains period.
Ver 4.8.5, repeatable
Open database with a period in the name
Ex beta.testdb

When saving page from designer, an error box opens  "insert into phpmyadmin.pma__table_coords..." 

Viewing the pma_table_coords, phpmyadmin saved the part of the database name before the period, in the case above "beta" into the db_name column, which I believe should be the full database name, and the part after the period, "testdb" as the table name.

### PR DESCRIPTION
**Pull request by Bournvita1998**
Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

### Description

Designer pages will now be successfully saved even if it has period.

Fixes #14945 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
@sudo-bot Deploy PR

**Comment by shucon** [comment]
Please fix Travis-CI errors. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/573213868

**Comment by williamdes** [comment]
@Bournvita1998 thanks for trying to help, I fixed the issue with a23f2ba51a93af0c5eedf91646aa9e04b9bc3a12

**Comment by Ahmedmostafaelhlethy** [comment]
> يرجى إصلاح أخطاء Travis-CI. راجع: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/573213868

**Pull request closed without merging**
