### PR TITLE
Create the `Identifiers\Identifier` interface

### PR DESCRIPTION
**Pull request by MauricioFauth**
Changes `Dbal\DatabaseName`, `Dbal\TableName` and `Triggers\TriggerName` to implements the new `Identifiers\Identifier` interface.
Moves `Dbal\DatabaseName`, `Dbal\TableName` and `Triggers\TriggerName` to the
`Identifiers` namespace.
Renames the `tryFromValue()` and `fromValue()` methods to just `tryFrom()` and `from()` respectively.

### CODE REVIEW

**Comment by MauricioFauth** [comment]
cc @kamil-tekiela

**Review by kamil-tekiela — APPROVED** [review]
Looks good. I only have one question. Does it have to be in Dbal namespace? Maybe a dedicated namespace would be better?

**Comment by MauricioFauth** [comment]
> Looks good. I only have one question. Does it have to be in Dbal namespace? Maybe a dedicated namespace would be better?

What namespace you suggest?

**Comment by MauricioFauth** [comment]
> Maybe `Identifiers`? For me, this interface doesn't have anything to do with Dbal logic.

It really makes more sense than Dbal. I also rename IdentifierName to just Identifier, as it seemed redundant.

**Review by kamil-tekiela — APPROVED** [review]
This looks sensible.

**Pull request merged**
