### PR TITLE
Add Charset and Collation value objects

### PR DESCRIPTION
**Pull request by MauricioFauth**
### Description

Introduces Charset and Collation value objects. This way we can have a well defined structure instead of an array of strings, witch is prone to errors.

### CODE REVIEW

**Comment by mauriciofauth** [comment]
@williamdes Why my commit has an invalid Signed-Off-By line?

See: https://github.com/phpmyadmin/phpmyadmin/pull/15348#commitcomment-34042130

**Comment by williamdes** [comment]
@mauriciofauth I think this is because https://github.com/phpmyadmin/scripts/blob/23993f4de420b741668672f1f49807b5eeb4a90f/hooks/commits.php#L121 uses a line break in the pattern

Try to push a commit that has a line break before the signoff

**Comment by mauriciofauth** [comment]
> Try to push a commit that has a line break before the signoff

My commit message has a line break. See:

Screenshot from 2019-06-22 23-45-50

**Comment by williamdes** [comment]
@mauriciofauth I found out why, the regex was missing the unicode modifier.
Fixed by https://github.com/phpmyadmin/scripts/commit/153613e5362f301c07c206744d560977daf50e1c

**Pull request merged**
