### PR TITLE
Fix Designer JavaScript error relating to token

### LINKED ISSUE #12804: Designer is broken
### Steps to reproduce
1. Open Designer tab

### Expected behaviour
Designer should appear without errors.

### Actual behaviour
Designer opens, but there are errors hidden behind the window.

95064ed9fbf77e4f43ac438591d03998c6bb38c6 seems to be the first bad commit.

### PR DESCRIPTION
**Pull request by ibennetch**
Fixes #12804

Signed-off-by: Isaac Bennetch <bennetch@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ibennetch** [comment]
This works for me and looks correct, but I'd like confirmation that this is the correct solution.

**Comment by nijel** [comment]
I've rather migrated the code to use same logic as we use elsewhere in bca2e1c588626298c69a2b795cec84c223fce593.

**Comment by nijel** [comment]
But thanks for pointing out where the problem is!

**Comment by ibennetch** [comment]
That's a much better solution, thanks.

**Pull request closed without merging**
