### PR TITLE
Disable unnecessary tables actions when empty

### PR DESCRIPTION
**Pull request by faissaloux**
Hello 👋🏻 

In this PR I have disabled `Search` and `Empty` actions on empty tables since they have no use in this case.

## Before
You can click on `Search` and `Empty` actions on all tables.

image

## After
You can't click on `Search` and `Empty` actions on empty tables.

image

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @faissaloux 
I can not accept this request because it goes against #15582 and it's PR #15585

**Comment by kamil-tekiela** [comment]
On top of this, I would like to add that having disabled UI buttons is not user-friendly. A button should either return an unsuccessful response or be idempotent.

**Comment by faissaloux** [comment]
@williamdes on https://github.com/phpmyadmin/phpmyadmin/issues/15582 I think the problem was unable to click `empty` after clicking it in this PR I don't allow to `empty` empty tables from the start! Or should it be enabled anyway?

What about the `search`?

**Comment by kamil-tekiela** [comment]
I would leave it enabled. PMA doesn't necessarily represent the current state. It can only know the state at the time the page was opened. If the data changes in the meantime, the user is left with the only option of refreshing the page. That is quite annoying. Let the buttons be always active.

**Comment by williamdes** [comment]
> I would leave it enabled. PMA doesn't necessarily represent the current state. It can only know the state at the time the page was opened. If the data changes in the meantime, the user is left with the only option of refreshing the page. That is quite annoying. Let the buttons be always active.

That's exactly the reason

**Comment by williamdes** [comment]
> What about the search?

You can transform this PR to make search always clickable if it's not already like that. Basically all of the buttons should be available. 

> It can only know the state at the time the page was opened. If the data changes in the meantime, the user is left with the only option of refreshing the page. That is quite annoying.

Because of this reason

**Comment by faissaloux** [comment]
Ow yeah you are right @kamil-tekiela  👌🏻 Good point

@williamdes Yeah, it makes sense, thank you.

**Pull request closed without merging**
