### PR TITLE
Adding Filter Process List | Feature #1606 

### PR DESCRIPTION
**Pull request by devenbansod**
I am a novice in PMA Development. Tried this first patch. Please suggest changes.

Changes made:
1. Added filter for 'Show only Active'.
2. Changed the Conditions and the SQL generated accordingly in the library file.

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by devenbansod** [comment]
Hi Marc,

[This link ] (http://dev.mysql.com/doc/refman/5.5/en/general-thread-states.html) mentions and explains the various thread states.

It was a mistake on my part that I didn't think it through. But I now think it's a valid point to be discussed that which specific thread states should the filter hide and which should it show. Or should we provide a text box filter instead ? 

I will post a query to the request owner and revert back once it gets confirmed, and will then make the changes to the patch accordingly.

Any suggestion/ guidance is welcome. :+1:

**Comment by lem9** [comment]
Hi Deven,
According to the link, maybe you should check for "executing" ?

About offering to filter by state, the UI must remain simple; we should avoid cluttering it with too many details. Also, it will help when I regain access to SourceForge's tracker, to read the feature description.

**Comment by devenbansod** [comment]
Hi Marc,
Even I think it should be 'executing' and I am sorry but even I am unable to recall why did I choose 'init'. I think I was testing if it was working and as the init was regularly coming so I was continuously checking for that only and it remained in the final pull request commit. Will take care such a thing does not happen from now.

Anyways, I will change it to 'executing'. Do you have any other suggestions ? 

Also, I am unable to understand why the patch is failing the tests. Any help/link to documentation would be appreciated.

**Comment by lem9** [comment]
If you follow the Details link for Travis, you'll reach a list of jobs. Picking one of them (in red) shows me https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/51247569 which contains a message with the fatal error you introduced with this patch.

**Comment by devenbansod** [comment]
Hi Marc,
I have removed the fatal error as reported by Travis which was being caused by conflicting function names, but I am still unable to understand and correct the error with **Scrutinizer** . 

Any suggestion/help ?

**Comment by lem9** [comment]
Scrutinizer could not complete its inspection, so there is nothing to do about this. Later if your code is merged, you can have a look at a further inspection to see if you introduced problems in the code.

**Comment by lem9** [comment]
Deven,
when I select "Show only active" and click on Refresh, I get a lot of notices. The first one is 
````
Notice in ./libraries/server_status_processes.lib.php#292
Undefined index: Id
````

**Comment by devenbansod** [comment]
Sorry Marc, but I am testing on my local machine with specifications : Ubuntu Linux x64, Apache2 and MySQL 5.5 with E_ALL and display_errors = on and I am still unable to reproduce the notices you are pointing to. 

Also, the line number you mentioned in the notice i.e. #292 is unchanged from before the patch. So I am unable to comprehend where the patch must have gone wrong ? The 'Id' index mentioned in the notice is the id of the process for which the function PMA_getHtmlForServerProcessItem is called while generating the server process list. 

Can you please post a screenshot of the other notices may be, so that I may try to remove the errors more effectively ?

Thanks

**Comment by lem9** [comment]
````
Notice in ./libraries/server_status_processes.lib.php#292
Undefined index: Id

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()

Notice in ./libraries/server_status_processes.lib.php#300
Undefined index: Id

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()

Notice in ./libraries/server_status_processes.lib.php#301
Undefined index: User

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()

Notice in ./libraries/server_status_processes.lib.php#302
Undefined index: Host

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()

Notice in ./libraries/server_status_processes.lib.php#307
Undefined index: Command

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()

Notice in ./libraries/server_status_processes.lib.php#308
Undefined index: Time

Backtrace

./libraries/server_status_processes.lib.php#223: PMA_getHtmlForServerProcessItem(
array,
boolean true,
boolean false,
)
./libraries/server_status_processes.lib.php#40: PMA_getHtmlForServerProcesslist()
./server_status_processes.php#59: PMA_getHtmlForServerProcesses()
````

**Comment by devenbansod** [comment]
Hi Marc,

I don't know why I am not able to reproduce the notices but I am looking into it. 

Anyways, I think I could figure out the problem, and I have tried to remove it with the new commit. Hope this would fix this notices. 

Please let me know if still it doesn't.

**Comment by lem9** [comment]
Hi Deven,
yes, the notices are gone. I found a problem: when activating auto-refresh, sleeping threads are shown in spite of "Show only active" being selected.

**Comment by devenbansod** [comment]
Hi Marc,
Thanks for pointing that error out. I should be more careful now that, at first, none of this error was visible to me.

Anyways, I have tried and committed  a few changes that may help to remove the error that you pointed out.

I am searching too but please let me know if there are any other errors that are coming or if the error that you pointed out did not get fixed.

Thanks.

**Comment by lem9** [comment]
Hi Deven,
I confirm the fix. Now, could you rebase your commits into just one? It would help reviewing the patch. See
https://wiki.phpmyadmin.net/pma/Git#Changing_history

**Comment by devenbansod** [comment]
Squashed into a single commit!

Thanks Marc for all your inputs, suggestions and bearing me through the patch. :)

Hope the patch is okay now.

**Comment by devenbansod** [comment]
Hi Marc,

Refactored the code by getting the url params from a function defined as getUrlParams. The function returns the params based on whether the show Only active filter is checked or not.

Please let me know if you suggest something different.

**Comment by D-storm** [comment]
@lem9 Scrutinizer will keep failing even after merging as well. It seems they are using new PHPCS version (2.x) which is no longer compatible with our PHPCS PMAStandard.

**Comment by lem9** [comment]
@D-storm You're right, I updated phpcs on my machine and now get an error. Do you want me to work on this or are you?

**Comment by D-storm** [comment]
@lem9 As Scrutinizer does seem to have any configuration  parameter to by which we can specify which version of PHPCS to use, we will have to rewrite our PMAStandard. I'm already looking on how to rewrite it from here: https://www.squizlabs.com/php-codesniffer/2.0.0a1-released

**Comment by devenbansod** [comment]
Hi Marc,

I tried re-factoring the if-else repetitive code. Also, have merged the changes into one commit.

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
