### PR TITLE
Feature Request:#1608 Central columns allowing setting SIGNED UNSIGNED attribute to integer

### PR DESCRIPTION
**Pull request by rakeshkumar4294**
An extra column col_attribute is added to pma_central_column table and accordingly all the pages  are modified.

Signed-off-by: RAKESH KUMAR rakeshkumar4294@gmail.com

### CODE REVIEW

**Comment by smita786** [comment]
Hey,
I think you need to update the sql/create_tables.sql as well, as you are adding a new column to pma_central_columns table. Please do update that accordingly.

**Comment by madhuracj** [comment]
Changing the pma table structures should be the last resort IMO. Can't we use `col_extra` to store extra information as comma separated values and store SIGNED, UNSIGNED attribute in there?

**Comment by rakeshkaundilya** [comment]
Hi Madhura,
I think it would be more simple to add an extra column as it would be little confusing to put attribute in extra.But I will do as you suggest ,if to put it in 'col_extra'.
Thanks.

**Comment by madhuracj** [comment]
Adding an extra column is easy for the developer, but upgrading will not be easy for the user. We have to advertise that there is change to the pma table structures and even the code will have to handle situations where the user has installed the new version but has not upgraded the table structures. I suggest you start a discussion on this on the developer mailing list.

**Pull request closed without merging**
