### PR TITLE
Fix: Auto Increment reset issue

### LINKED ISSUE #15410: Table options & Auto increment
1. Open Table Operations - Table options in two tabs
2. Update the Auto increment value in the first tab to simulate some inserts.
3. Update the Table comment in the second tab
4. Note the Auto increment value has been reset to the original value.

I'm not sure about the consequences but I don't think the reset is desirable.

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

added new hidden input tag for auto increment value

Fixes #15410

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
@gurrrung can you please review this PR?

**Review by rahgurung — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
Thank you @yashrajbothra !

**Pull request merged**
