### PR TITLE
Fix broken foreign key links

### PR DESCRIPTION
**Pull request by williamdes**
### Description

Fixes: #14270 - Middle-click on foreign key link broken
Fixes: #14363 - Broken relational links in tables

Fixes the broken foreign key links

### CODE REVIEW

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Comment by williamdes** [comment]
@ftrotter @Drakar2007 @OlafvdSpek @Jay04653 @fliespl

**Comment by Jay04653** [comment]
Hi,

Tested here: https://phpmyadmin-pr-15325.wdes.eu.org/db_structure.php?db=public&server=10
Tables: t1 and t2

Seems all working fine

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
This pull request fixes the issue but it is not safe because the token is session based and not request based, so it is possible to forge the query signature using a token from a previous request.

**Comment by williamdes** [comment]
> This pull request fixes the issue but it is not safe because the token is session based and not request based, so it is possible to forge the query signature using a token from a previous request.

Nope, I think that you got confused between the the phpmyadmin session and how I use it

Currently, you can not change the contents or it will void the signature

The signature is query and session based

I will added a Unit test that proves my point of view

**Comment by williamdes** [comment]
@mauriciofauth I think I understand your comment, maybe I can store a random secret that is never sent to the user into the session ?

**Comment by OlafvdSpek** [comment]
> This pull request fixes the issue but it is not safe because the token is session based and not request based, so it is possible to forge the query signature using a token from a previous request.

If one has the token it's game over already isn't it?

**Comment by williamdes** [comment]
> If one has the token it's game over already isn't it?

Yes absolutely, if the phpmyadmin session token is stolen then game over.

**Comment by williamdes** [comment]
@sudo-bot /deploy

**Comment by williamdes** [comment]
@mauriciofauth I made the secret a secret for the user (80a7f0a75c72ec2b92216647ac66890ff58002f8)
Can you please re-review ?

**Review by MauricioFauth — APPROVED** [review]

**Review by devenbansod — APPROVED** [review]
💯

**Comment by williamdes** [comment]
@ibennetch @madhuracj I would like to have some feedback ;)

@madhuracj Do you have some security advice ?

I will merge soon :)

**Pull request merged**
