### PR TITLE
Feature #15555 ip2long transformation

### LINKED ISSUE #15555: Add Ip2Long transformation. For Input. You already have Long2Ip transformation.
### Is your feature request related to a problem? Please describe.

I want to store ipv4 addresses efficiently. But manual input in phpmyadmin is a little annoying to find and select INET_ATON again and again.

### Describe the solution you'd like

An input transformation which converts ip addresses to BigInt / Long like INET_ATON. To be compatible with the existing Long2Ip transformation.

### Describe alternatives you've considered

Selecting INET_ATON again and again for manual input

### Additional context

- phpMyAdmin version: 4.9.1

### PR DESCRIPTION
**Pull request by Tithugues**
Fixes: #15555

### CODE REVIEW

**Comment by Tithugues** [comment]
Related to ticket #15555 .

**Comment by Tithugues** [comment]
Based on https://github.com/phpmyadmin/phpmyadmin/pull/15556

**Review by williamdes — APPROVED** [review]
Code looks good to me
@ibennetch should we merge this in QA 4.9 ?

**Comment by williamdes** [comment]
Thank you @Tithugues for this feature !

**Pull request merged**
