### PR TITLE
Feature Request: Lock page navigation when entering data

### PR DESCRIPTION
**Pull request by djprawns**
Added lock page on table relation view, database search/query/operation tabs.

Signed-off-by: Pranav Sharma vanarpsharma@gmail.com

### CODE REVIEW

**Comment by vanarpsharma** [comment]
Working on Select Boxes and Checkboxes for lock pages.

**Comment by D-storm** [comment]
Hi @vanarpsharma,
I am not sure whether we need lock page feature on table relation view but on database search/query/operations tabs we definitely don't require lock page. This feature was added to save users from accidentally navigating away from certain pages such as insert page so that they don't have to redo lot of work. On database search/query/operations page there is nothing much to do, just table/database name is to be entered and adding this feature to them might annoy most of the users more than it help. You might also want to have a look at this: b7108e9e70ae8b6f82061864e8a82ed74575b663. Maybe we can get other developers opinion on it.

**Comment by vanarpsharma** [comment]
Then can it be clarified exactly where all you need this mechanism.
Also, i am working on a solution for dropdowns and checkboxes. If we select checkboxes and dropdowns then the lock page mechanism shall be activated.

**Comment by zixtor** [comment]
I also think we do not need lock-page feature on database search/query/operations tabs.
Also, extending lock-page to checkboxes and select boxes sounds unnecessary, as the utility of lock-page is to prevent the loss of some sizeable typed input, but there is not much to a checkbox or selectbox to worry about locking the page.

**Comment by vanarpsharma** [comment]
Okay so should we finalize this? Only for textboxes and textareas. I personally feel it should be extended to atleast dropdowns since dropdowns encapsulate sizable input if not typed.

**Comment by vanarpsharma** [comment]
Hey @zixtor @D-storm , I know this is off topic but i had a general query. If i feel that i can execute some specific gsoc idea presently, can i start working on it right away and start making pushes? Or are the gsoc ideas strictly meant to be worked on after the student is accepted. I feel that i can work on some gsoc ideas, so was curious.

**Comment by D-storm** [comment]
Hi,

GSoC ideas are meant to be worked on after the student gets accepted. So,
try to work on bugs/features apart from it.

**Comment by vanarpsharma** [comment]
Okay, it seems that people are already working on some gsoc ideas and submitting their codes. For instance https://github.com/phpmyadmin/phpmyadmin/pull/1549. My only query is should i change my proposal which includes this idea and its implementation to be consistent with the code before gsoc. Or should i stick to what I have written and my approach.

**Comment by D-storm** [comment]
Well, I am not in favor of extending this to dropdowns.

**Comment by lem9** [comment]
https://github.com/phpmyadmin/phpmyadmin/pull/1549 has been closed.
Indeed, it's premature to work on a project that is scheduled for GSoC.

**Comment by vanarpsharma** [comment]
Hey Mark, should we extend this to dropdowns?

**Comment by lem9** [comment]
@vanarpsharma On which page do you propose to "protect" dropdowns?

**Comment by vanarpsharma** [comment]
I feel we should protect them on the table edit page. It is a page where some heavy editing could take place.

**Comment by lem9** [comment]
You mean table Structure?

**Comment by lem9** [comment]
Added discussion about lock page on table structure dropdown changes for tomorrow's team meeting:
https://wiki.phpmyadmin.net/pma/2015-03_Meeting#Feature_requests_discussion

**Comment by vanarpsharma** [comment]
Yes Marc, I meant the table structure page. Thanks.

**Comment by lem9** [comment]
Closing this, as it does not pass the test suite.

**Pull request closed without merging**
