### PR TITLE
Issue #14581: Escaped HTML in 'Add a new server' setup

### PR DESCRIPTION
**Pull request by VictorAlagwu**
Signed-off-by: VictorAlagwu <victoralagwu@gmail.com>
Fix for Issue #14581 
Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
@VictorAlagwu I think you forgot to put a space in your name on the Signed-off-by line. Is that correct?

**Comment by VictorAlagwu** [comment]
It is correct as VictorAlagwu, it was added by GitHub using the --signoff command

**Comment by mauriciofauth** [comment]
In your profile you use _Victor Alagwu_, with a space between the names. I'm just asking this, because our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) requires it to be the full real name.
Could you confirm how you want your commit to be signed-off-by?
```
Signed-off-by: Victor Alagwu <victoralagwu@gmail.com>
```
or
```
Signed-off-by: VictorAlagwu <victoralagwu@gmail.com>
```

**Comment by VictorAlagwu** [comment]
Ok, I go with the former
``Signed-off-by: Victor Alagwu <victoralagwu@gmail.com>``

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
