### PR TITLE
[Work in progress] Page related settings

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Major changes
- Updated `page_settings.lib.php` and how page related settings work
- Fixed some JS
- Added page settings in some more pages to have clearer idea

### CODE REVIEW

**Comment by lem9** [comment]
Nisarg,
what's your plan with this part of the RFE: "There are also other ways to set options. In Browse, we have Options, and other remembered settings like column visibility, column sorting and order of display. I am not sure if these mechanisms should be integrated or not to the new way."

**Comment by nisargjhaveri** [comment]
Marc,
I've been thinking about this part of the RFE. After some thought, I am really confused even about the usefulness of this. And also, implementation. I was just planning to mail `-devel` asking for opinions. Expect an email in few hours.

**Comment by nisargjhaveri** [comment]
I've pushed a couple of commits. Please check.

**Comment by lem9** [comment]
Looks fine, please have a look at the merge conflicts.

**Comment by nisargjhaveri** [comment]
Please check this now. If you think it is fine, I'll squash the commits. Anything else can you remember that is still left?

**Comment by lem9** [comment]
Merging works now. The hint on the top icon is missing the hyphen. Also what about the settings related to the navigation panel?

**Comment by nisargjhaveri** [comment]
I'll fix the hyphen. 

For settings related to navigation panel, should we have separate settings icon along with the five buttons at the top of the panel?

**Comment by lem9** [comment]
Yes it looks like the best place to put this icon.

**Comment by nisargjhaveri** [comment]
So, should I do that with this or later in different commit? Because it'll be a different, special case of page-related settings.

**Comment by lem9** [comment]
You can squash now, I'll do a final review, merge and you can work for the navi panel afterwards.

**Comment by nisargjhaveri** [comment]
I'll squash it on a different branch and open a PR.

**Pull request closed without merging**
