### PR TITLE
Fix #17793 - insert record - fix null not selected if nullable UUID & insert error

### LINKED ISSUE #17793: Inserting a row with UUID should insert the user value when not empty
By default, when inserting a row, the uuid type column has UUID as function set by default. I think it should be empty, because when the column is set to NULL, it still inserts a uuid, instead of NULL.

The same case applies when a user enters his own UUID, it will still insert the one generated by MariaDB and not what user has entered.

What can be done, is to have UUID (uuid() function) added to the Default select (if MariaDB and column is uuid), like it is with CURRENT_TIMESTAMP.

https://user-images.githubusercontent.com/25424343/195730197-5f711440-2ed0-4e2a-af7d-a0a16531db80.mp4

### PR DESCRIPTION
**Pull request by sureemo**
### Description

- Fix issue - null is not selected for uuid field with nullable setting
- Fix issue - default select option not select `UUID` when alter column 

Related PR: https://github.com/phpmyadmin/phpmyadmin/pull/17797
Reference issue: https://github.com/phpmyadmin/phpmyadmin/issues/17793

Signed-off-by: Mo Sureerat <sureemo@gmail.com>

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Awesome!
Let me know when it's ready

**Comment by sureemo** [comment]
> Awesome! Let me know when it's ready

Thank you .. difficult to fix code coverage and static analysis check failed. Will update you if ready.

**Comment by sureemo** [comment]
@williamdes hello william, now one build check is failed. anyway i think it's ready for review. thank you ^_^

**Comment by williamdes** [comment]
> > Awesome! Let me know when it's ready
> 
> Thank you .. difficult to fix code coverage and static analysis check failed. Will update you if ready.

Okay let me know, but if possible when something is green I prefer to merge it and you can open a new one for improvements?

**Comment by williamdes** [comment]
Thank you so much for your great hard work onto this subject @sureemo !

**Pull request merged**
