### PR TITLE
Fix label alignment on login page

### LINKED ISSUE #15177: label not aligned with baseline
### Describe the bug

label text aligned at the top.

### Expected behavior

label text should be properly aligned to baseline.

### Screenshots

baseline

### PR DESCRIPTION
**Pull request by murex971**
Signed-off-by: Nupur Agrawal <nupur202000@gmail.com>

Fixes https://github.com/phpmyadmin/phpmyadmin/issues/15177

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
Multiple failed tests.
1. Please sign-off commit using `git commit --sign-off`
2. Refer https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/519256558 for linting issues

**Comment by AghaSaad04** [comment]
Hey @murex971 I think, ```text-align: center;``` is not the right solution for this. If we have Email instead of Username It'll look something like this, which doesn't seem good.

image

A better solution for this will be:
```
form.login label {
    width: 8em;
    margin-left: 3em;
}
```

image

**Comment by murex971** [comment]
@AghaSaad04 Thanks for the input.
I agree it's looking better the way you suggested.
Working on it :)

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
