### PR TITLE
Strict check for create_addfield.lib.php

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: ZhiFeng Hu hufeng1987@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
@netroby Which problem are you trying to fix?

**Comment by netroby** [comment]
WIPE, strict compare and check.

**Comment by lem9** [comment]
I don't see a risk with the current code.

**Comment by netroby** [comment]
I am using tools like PHP code sniffer and php mess detector to find out code bad mess. 
Clean code and strict check may improve code quality. I would like to contribute my time on works like this.

**Comment by lem9** [comment]
Thanks.

**Comment by netroby** [comment]
I will using these tools to dig and improve phpmyadmin code quality. thanks for your time. PHP 7 will ship to us these year. we have much more works to do to add compatible with it

**Pull request merged**
