### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by peteos123**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by ibennetch** [comment]
I'm not sure that I see how this pull request relates to phpMyAdmin itself, though?

**Comment by ibennetch** [comment]
Does Gitpod package phpMyAdmin?

**Comment by williamdes** [comment]
> Does Gitpod package phpMyAdmin?

Seems like not, but this implementation is missing composer

**Comment by mauriciofauth** [comment]
Looks like spam: https://github.com/search?q=Fully+automate+dev+setup+with+Gitpod&type=issues

**Pull request closed without merging**
