### PR TITLE
Fix #11752

### LINKED ISSUE #11752: 4.5.2 breaks MySQL Master Master Cluster
I have updated phpmyadmin from 4.2.12 to 4.5.2.

I have configured a MySQL Master Master Replication and I can login on both nodes from phpmyadmin, here is the phpmyadmin config:
/* Servers configuration */
$i = 0;

/* Server: hostname1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname1';
$cfg['Servers'][$i]['host'] = '1.1.1.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* Server: hostname2 [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname2';
$cfg['Servers'][$i]['host'] = '2.2.2.2';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'somelongstring';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['VersionCheck'] = '0';
$cfg['DisplayServersList'] = 'true';
$cfg['VersionCheckProxyUrl'] = 'http://proxy.domain:8080'

After the update, my SLAVE on hostname2 breaks with the following errors:

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`db`(`host`, `Db`, `User`) VALUES("pma_test_host", "mysql", "pma_test_user")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`columns_priv`(`host`, `Db`, `User`, `Table_name`, `Column_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user-' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`tables_priv`(`host`, `Db`, `User`, `Table_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--PROCEDURE' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`procs_priv`(`host`, `Db`, `User`, `Routine_name`, `Routine_type`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "PROCEDURE")'

The "mysql" database is not replicated over the cluster. 
replicate-ignore-db = mysql 
replicate-ignore-db = information_schema
replicate-ignore-db = performance_schema

I dont have configured the pma control user as I dont use the pma configuration storage.

It seems like pma is doing some permissions checks after I log in with my account which seems to break my master master replication.

### PR DESCRIPTION
**Pull request by devenbansod**
Unset foreign_key_checks while testing 'insert privileges' and reset it back.

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
@devenbansod Please assign yourself to the pull requests that you intend to merge.

**Comment by lem9** [comment]
Also please assign yourself to the issues on which you are working.

**Comment by lem9** [comment]
@devenbansod If this is intended for 4.5.3 and ready, please merge because tomorrow, 4.5.3 will be frozen and in test mode.

**Comment by devenbansod** [comment]
Sorry, I was waiting for more feedback for the issue opener. But since I am not getting it, I will go on and merge this.

**Pull request merged**
