### PR TITLE
Add a JavaScript package manager

### LINKED ISSUE #12677: Consider using package manager for javascript libraries
We already use [Composer](https://getcomposer.org/) for managing PHP dependencies. Having something like this for javascript would be useful as well to avoid need for manual library updates, however such approach first need to be investigated and checked for feasibility.

Things to check:

* Can we cover all javascript libraries we use?
   * if we can't find most of the libs packaged, it's probably not worth of the effort
* What package manager to use? Some choices (
   * [Bower](https://bower.io/) - Node based package manager
   * [BowerPHP](https://bowerphp.org/) - Composer ready reimplementation of above
   * use javascript packages from components project (eg. [jQuery](https://packagist.org/packages/components/jquery) or [jQuery-cookie](https://packagist.org/packages/components/jquery-cookie))

### PR DESCRIPTION
**Pull request by MauricioFauth**
I created a `package.json` file using the [Yarn](https://yarnpkg.com/) package manager.

I chose Yarn because it's [compatible](https://yarnpkg.com/en/docs/migrating-from-npm) with [npm](https://www.npmjs.com/), which is the most popular package manager, and also because it's the manager [recommended by the Bower team](https://bower.io/blog/2016/using-bower-with-yarn/). In other words, you can use npm to install the dependencies if you want.

I don't know if the way I copied the files after they were installed is the most appropriate one. I chose this way because I thought it would be easier to later remove the `node_modules` directory when creating a release.

I doesn't included all the scripts, as most of them are scripts that seem abandoned by their maintainers and some are not in the package manager registries.

Fix #12677 

Signed-off-by: Maurício Meneghini Fauth <mauriciofauth@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Related to #13173.

**Comment by mauriciofauth** [comment]
I think that in the future we should use a tool like [Browserify](http://browserify.org/) or [webpack](https://webpack.js.org/).

**Comment by nijel** [comment]
Not that I'd be experienced in this area, but I have some generic questions:

* Couldn't it be done without postinstall? If not, will it work on Windows?
* Should be yarn.lock part of the repository?
* Does it make sense to use yarn now and switch to Browserify or webpack later?
* What about OpenLayers, those doesn't seem to be handled here?

**Comment by mauriciofauth** [comment]
Thanks for the feedback, @nijel 

> Couldn't it be done without postinstall? If not, will it work on Windows?

Maybe there are other ways, I'm not the most experienced at it either.
npm's postinstall is common and probably works on Windows. But the shell script I don't know if works, because I don't have a Windows system to test on. Maybe it's a good time to start using a CI tool for Windows, like the [AppVeyor](https://www.appveyor.com/).

> Should be yarn.lock part of the repository?

According to the [Yarn documentation](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control), the lock file should be included in version control.

> Does it make sense to use yarn now and switch to Browserify or webpack later?

Yes, because they are not the same thing. Webpack and Browserify are module loaders/bundlers and not package managers. They serve to concatenate js files in a smart way to use them in browsers. This helps to modularize the scripts.

> What about OpenLayers, those doesn't seem to be handled here?

We use OpenLayers 2.13.1 and this version is not present in the registry, only 3.0+, which causes some conflicts. So I decided to do the pull request without OpenLayers to save the work of updating the library, because I think we can do this gradually. Just like the other scripts that are missing.

**Comment by nijel** [comment]
Thanks for clarifications! AppVeyor will certainly not answer this question as their environment has quite a lot of tools installed which are not there on normal Windows systems. Thinking about that it's probably not that big problem as Git does include shell anyway and most people wanting to run this will get phpMyAdmin from Git anyway...

**Comment by mauriciofauth** [comment]
An alternative would be to include the files directly from `node_modules`, but I don't think that's a good idea.

I thought about using webpack this way:
We could require dependencies directly from `node_modules` and then bundle them with webpack.
That's a lot of work, but the result would be great. I think this would involve reviewing all js files and where they are used, since the files that would be included in the HTML would be those bundled.

**Comment by mauriciofauth** [comment]
I think for now it would be better just to add the package manager and update all the libraries, what do you think?

**Comment by nijel** [comment]
How about having the package manager to update the libraries, but store the in git (to include js/vendor in your patch)?

This way we would not enforce having yarn for anybody who downloads git (I'm quite worried about portability of the postinst script), but still would have automated way to update (most of) javascript libraries?

**Comment by mauriciofauth** [comment]
This is a good idea, @nijel. So we can test the package manager without causing so much trouble.
I'll do it as soon as I have some free time.

**Comment by mauriciofauth** [comment]
I had to revert jqPlot and jquery.event.drag because they were giving errors related to module.
In other words, for these cases, it will be necessary to use the webpack, which is something that I need to study a little more.

**Comment by nijel** [comment]
I just realized there is additional topic to address - distributing source code. We currently do that in js/jquery/src/, but that's just for jQuery (which you can remove in the PR as it no longer matches shipped jQuery anyway). The good thing is that the yarn packages include source code, but the legal question is whether including link to download source code is good enough :-). I will raise this to Software Freedom Conservancy...

**Comment by mauriciofauth** [comment]
I just removed the `js/jquery/src` directory, @nijel.

**Comment by mauriciofauth** [comment]
I started to think that this isn't a good patch to merge, because this script isn't a good way to copy the files. I'm studying how to use webpack and it seems promising.

**Comment by mauriciofauth** [comment]
I will close this PR without merging it, because I think it is better to use the webpack directly, and in the meantime I will prepare the code base with updates and necessary changes.

**Comment by nijel** [comment]
Okay, thanks for investigating this!

**Pull request closed without merging**
