### PR TITLE
partial fix issue #12262

### PR DESCRIPTION
**Pull request by codehimanshu**
Signed-off-by: codehimanshu <himanshuagrawal1998@gmail.com>

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Comment by mauriciofauth** [comment]
In your next contribution, it's a good idea to use a branch other than master, then open the PR from this new branch.
See https://github.com/phpmyadmin/phpmyadmin/wiki/Git#working-on-new-features

**Comment by lem9** [comment]
@mauriciofauth Hi Mauricio, I suggest that in the future you ask the contributor to squash their commits into one because the "remove trailing whitespaces" commit does not make sense by itself.

**Comment by codehimanshu** [comment]
@mauriciofauth Thanks for merge and suggestion. Will work in other branch and create PR from that.
@lem9 Sure, will squash the commits before PR from now on.

**Comment by mauriciofauth** [comment]
Thank you, @lem9.
I'll remember that next time.

**Pull request merged**
