### PR TITLE
Fix #16604 - Table width 100%

### LINKED ISSUE #16604: Table action links takes all the place on a big screen
5.1.0-rc1

This doesn't look right.

image

### LINKED ISSUE #16684: Table row links take all place on a big screen on version 5.1.0
### Describe

On a big screen the "row links" take too much space, I tried to search on report already open but I didn't find something about it.
Is there something we can make with a maximum or fixed size?

### Screenshots
I took a screenshot on the demo.phpmyadmin.net with the last version:
image

### Server configuration

nginx/1.14.2
Database client version: libmysql - mysqlnd 7.4.14
PHP extension: mysqli curl mbstring 
PHP version: 7.4.14

### Client configuration

- Browser: Chrome last version
- Operating system: Windows 10

### LINKED ISSUE #16733: Table columns are permanently stretched proportional to page width
### Describe the bug

Table column widths are disproportionately stretched and ignore column width preferences.
This UX change makes it hard to read, edit, or click buttons on the tables.

### To Reproduce

1. Make sure browser is full screened (preferably on a large resolution widescreen monitor for emphasis)
2. Go to any table with only a few columns

### Expected behavior

Tables should not have columns stretched beyond their regular widths.

### Screenshots

Prior to updating (4.9.7):

phpMyAdmin 4 9 7

After updating (5.1.0):

phpMyAdmin 5 1 0

### Server configuration

- Operating system: Ubuntu 18.04 LTS
- Web server: Linux Apache
- Database version: MySQL 5.7.32
- PHP version: 8.0.2
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome and Firefox
- Operating system: WIndows 10

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes: #16604
Fixes: #16684
Fixes: #16733 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by linaspasv** [comment]
There is a small glitch for "columns toggle" button when w-auto class is applied on a ``browse table``:

before w-auto class
image

after w-auto class
image

**Comment by shucon** [comment]
> There is a small glitch for "columns toggle" button when w-auto class is applied on a `browse table`:
> 
> before w-auto class
> image
> 
> after w-auto class
> image

Can you please try hard refreshing the page? I can't reproduce your screenshot.

**Comment by linaspasv** [comment]
> Can you please try hard refreshing the page? I can't reproduce your screenshot.
Oh, maybe it's auto generated by JavaScript. I have tried to apply the class on a loaded table.

**Comment by williamdes** [comment]
> Can you please try hard refreshing the page? I can't reproduce your screenshot.

This is fixed by #16687 you can not reproduce it anymore now :)

**Pull request merged**
