### PR TITLE
Fix #14916 Missing autofill of SQL query when creating a new view

### LINKED ISSUE #14916: Creating a view using a query does not pre-fill the query
### Describe the bug

Creating a view using a query does not pre-fill the query

### To Reproduce

1. Select from a table
2. Click on 'Create a view'

### Expected behavior

Pre-fill the query into the modal

### Actual behavior

Empty query

### Additional bug

**Submit empty modal shows waiting forever !**

### PR DESCRIPTION
**Pull request by bahl24**
### Description

Added provision for auto fill of SQL query, when create view is clicked. Fixed bug that makes the create view form unresponsive indefinitely when fields are empty.

Fixes #14916 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

Thank you @bahl24 !

**Comment by ibennetch** [comment]
When I click the bottom "Go" button (the one next to Cancel), I now get a JavaScript error. I'm not certain whether this is related to your code changes, but suspect not because with QA_4_8 I get a yellow "Loading..." bar forever. 

```
{
    "pma_version": "4.8.6-dev",
    "browser_name": "FIREFOX",
    "browser_version": "64.0",
    "user_os": "Mac",
    "server_software": "Apache/2.4.25 (Debian)",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "7.3.0-2+0~20181217092659.24+stretch~1.gbp54e52f",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "codemirror_editor is null",
        "stack": [
            {
                "func": "PMA_createViewDialog/

        
        
            Automatically send report next time        

```

**Review by williamdes — CHANGES_REQUESTED** [review]
Can you explain the changes on the twig template ?
For me you can remove them

**Comment by bahl24** [comment]
@williamdes That's because we can't add placeholder/prefill query in sql box
Existing data can only be filled in text input.
Also see, https://github.com/phpmyadmin/phpmyadmin/pull/14941

**Comment by williamdes** [comment]
> @williamdes That's because we can't add placeholder/prefill query in sql box
Existing data can only be filled in text input.

Can you test another time locally because this is not true for me :confused: 

Have a look at (applied the removed line patch from this PR)
- https://phpmyadmin-pr-7.wdes.eu.org/ (public, public)
- https://phpmyadmin-pr-6.wdes.eu.org/ (public, public)

**Comment by mauriciofauth** [comment]
Closed in #15058.

Thank you for your contribution.

**Pull request closed without merging**
