### PR TITLE
WIP: Refining Table & TableSearch class

### PR DESCRIPTION
**Pull request by gzzhanghao**
The purpose of this PR is refining the Table class and TableSearch class.

Currently there are some functions in Table class are static, we should make it member functions.
For some unrelated functions like `getUiProp`, we should put it in a more appropriate place.
Some setter functions like `setName` is removed since it makes no sense in current context.
Also, a controller will be created for the TableSearch class.

### CODE REVIEW

**Comment by zixtor** [comment]
I find these improvements good, looking forward to more, also, I propose to refine TableSearch to be a controller on the lines of relation, indexes, gis etc.

**Comment by zixtor** [comment]
@gzzhanghao I see the TableSearchController.class.php and other improvements but the previous TableSearch.class.php has not been deleted yet. There are conflicts when merging, please resolve and rebase your work.

**Comment by gzzhanghao** [comment]
@zixtor Hello, I deleted TableSearch class in my latest commit and didn't push to GitHub yet. It should be available soon after I analysed the test failures in the CI, and test manually to ensure there's no flaws in it.

**Comment by gzzhanghao** [comment]
@zixtor Hi, I fixed conflicts but I found there are some significant bugs, So don't merge at this moment until we fix it.
First, the page should originally loaded by AJAX method is not converted into JSON string correctly. After analysing network traffics, I found it returned a mixture of JSON string and HTML. Could you help me out locating the bug?
Second, failures in tests is confusing. It said "Expectation failed for method name is equal to <string:query> when invoked at sequence index 5. Mocked method does not exist." I think it's caused by my works on Table cache in the DBI. I will post on the dev mailing-list for this problem.

Further, I analysed the structure.lib.php. There are some functions start with `PMA_getHtml` which means we can first make it templates. So I will start my initial work on structure.lib.php soon.

**Comment by zixtor** [comment]
@gzzhanghao The conflicts are not fixed yet! Further, apart from testGetTableDefWithoutDrizzle, there are some more test failures, please fix all of them.

**Comment by gzzhanghao** [comment]
@zixtor I removed the references to TableSearch.class.php, and tests for TableSearchController will be created in the future when I start working on tests on all controllers.

**Comment by gzzhanghao** [comment]
@zixtor Hi, test failures should be fixed, you can merge this PR now.

**Comment by zixtor** [comment]
Looks good! Thanks!

**Pull request merged**
