### PR TITLE
gitgnore ".github" folder

### PR DESCRIPTION
**Pull request by solracsf**

### CODE REVIEW

**Comment by nijel** [comment]
We use the `.github` folder, so it certainly should not be ignored: https://github.com/phpmyadmin/phpmyadmin/tree/master/.github

**Comment by acs-ferreira** [comment]
What's the local use of that folder? Shouldn't it remain in github only?

**Comment by nijel** [comment]
The local use is to be able to edit those files - it's configuration for GitHub issue tracking.

**Comment by acs-ferreira** [comment]
OK, so no local (production) use.
No problem, as many other projects just `.gitignore` it, i've submitted this PR, but if it is non-sense, just keep it closed :)

**Comment by nijel** [comment]
Well the files in git serve development purposes as well :-). The releases do not contain those. I've added .gitattributes to avoid shipping them using composer in f407601d5988f97b47ff53e5bace9e17463b8f50.

**Pull request closed without merging**
