### PR TITLE
Solved the UI issues in Navigation Setting / Server #15873

### LINKED ISSUE #15873: Unexpected UI in Navigation Setting / Server
### To Reproduce

1. Go to 'Navigation Panel'
2. Click on 'Setting (⚙️) icon '
3. Go to 'Server' tab

### Expected behavior

image

### Screenshots

image

### Additional context

Only in Master-branch

### PR DESCRIPTION
**Pull request by OfficialOzioma**
Signed Off By-Ozioma Dike <dikep15@gmail.com>

### Description

Solved the UI issues in sittings/navigation panel>server server, Setting/Main Panel 

git
Fixes #15873

### CODE REVIEW

**Comment by OfficialOzioma** [comment]
@williamdes  i have resolved the conflicts issues, can it be merged now

**Comment by williamdes** [comment]
@OfficialOzioma unfortunately no
Please have a look to https://github.com/phpmyadmin/phpmyadmin/pull/15907/files

I would suggest that you install GitKraken to have a visual representation of what is going on

**Comment by OfficialOzioma** [comment]
@williamdes  what do i need to do here  https://github.com/phpmyadmin/phpmyadmin/pull/15907/files

and how can GitKraken can help

**Comment by williamdes** [comment]
@OfficialOzioma so GitKraken will help you fo the following steps
Right click on the base commit (first one before yours) and reset > soft to this commit.
Then you can right click on any change in the working area and revert/discard it
When you removed all the unrelated changes you can commit and push
Accept to force push

Is that okay?

**Pull request closed without merging**
