### PR TITLE
Change referrer policy to same-origin

### PR DESCRIPTION
**Pull request by abij**
The `no-referrer` setting is blocked by Azure http_auth integration used in AppService and ContainerApps, resulting in a 403 and not reaching phpmyadmin.

I think `same-origin` is a good fit when I compare the types: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

Related issues: [#17240](https://github.com/phpmyadmin/phpmyadmin/issues/17240) and [phpmyadmin/docker#420](https://github.com/phpmyadmin/docker/issues/420)

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you
@MauricioFauth good for QA?

**Comment by abij** [comment]
Ill fix the testater tonight.

**Comment by abij** [comment]
I cannot trigger a new workflow run, myself.

**Comment by abij** [comment]
I'll squash the commits into a single commit, hold-on.

**Comment by abij** [comment]
Question, should this change be made against QA-branch?
- Only branch `QA_5_2` is mergeable with the test file change.
- `QA_5_1` and ``QA_5_0` can both benefit from the changed template file.

**Comment by williamdes** [comment]
Only QA_5_2 should be used. The when we merge the PR QA_5_2 will be merged into master.

**Comment by abij** [comment]
Oke, I changed the destination branch to `QA_5_2`, and just included my commit.

**Review by williamdes — APPROVED** [review]
Perfect, congratulations for this rebase to QA_5_2

**Comment by abij** [comment]
I don't know why the tests fail. Maybe you can give me a hint tomorrow.

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
