### PR TITLE
Use namespaces and autoloading.

### PR DESCRIPTION
**Pull request by Tithugues**
Use namespaces to start PSR-2 validation.
This is just the beginning to see which modifications are needed to use namespaces. If you have any feedback to these first modifications, I listen to you.

(Sorry, there are also some coding style modifications.)

Tasks to do:
- [x] Use namespace in all PMA classes 
- [x] Add "use" everywhere it's needed
- [x] Rename all PMA classes by removing "PMA_" prefix
- [x] Add autoloader
- [x] Rename all classes file by removing ".class"
- [x] Remove unneeded require for classes files

### CODE REVIEW

**Comment by Tithugues** [comment]
It's not over, but I squashed the commits. (Or at least tried… because I did "merge" and "rebase", and I don't know how it deals when there are both…)

Nevertheless it's moving on. I still have some work like fixing unit tests, renaming files, removing useless include, etc.
I just looked at autoloading and nothing else related to PSR and I think this is huge enough…

Before going further, can someone confirm that it's feasible to merge in master this PR please? I mean… There is a lot of work here (and still a lot) and I wouldn't like to hear at the end that is to huge to be controlled.
Thanks.

**Comment by lem9** [comment]
Hugues,
does it have to be done in one giant commit?

**Comment by Tithugues** [comment]
No,  I don't think so. Is it a problem to have only one commit?

**Comment by lem9** [comment]
There can be merge conflicts, especially if there is a long time span before it's ready.

**Comment by Tithugues** [comment]
Even if I rebase my branch with master?

Le sam. 29 août 2015 à 1:15, Marc Delisle <notifications@github.com> a
écrit :

**Comment by lem9** [comment]
Indeed with frequent rebases and looking at the outcome, you will be able to catch conflicting situations.

**Comment by Tithugues** [comment]
Unbelievable! The unit tests are OK!

**Comment by Tithugues** [comment]
Please, does anyone have an idea about the errors that I get here? I can't fix it and can't even explain why I get it. The error is linked to mock objects, but I don't know how to solve it.
I can't reproduce it locally.
Thanks.

**Comment by Tithugues** [comment]
See last travis error: https://travis-ci.org/Tithugues/phpmyadmin/jobs/78940192

**Comment by lem9** [comment]
With 3539b01 you went from 46 to 14 errors in my local tests, keep up fixin' :)

**Comment by Tithugues** [comment]
Thanks, I hid 3 errors related to mock objects, but I achieved to fix more others.

**Comment by lem9** [comment]
Not sure if you still want my results: now down to 10.

**Comment by Tithugues** [comment]
Thanks for your feedback Marc. It seems that it's movig on!
I was a little bit afraid about @madhuracj 's work on Drizzle, but I could merge it in less than 1 hour.
I still have some work, I'll probably ask a little bit of help later to check that all pages are still OK.

**Comment by Tithugues** [comment]
It seems that almost everything has been migrated.
I'm currently testing the interface to be sure that nothing (not sure I'll be able to test everything…) is broken.
For now, I saw that export seems to have an issue. If someone see anythink else, please report it here.
Thanks.

**Comment by lem9** [comment]
In Server > SQL > I type "use monty" with monty being an existing db, and get
````
Invalid class name "Node", using default of "Node"
````

**Comment by lem9** [comment]
With the employees sample database, Database > Query > Use tables > select departments and dept_emp, then "Update query":
````
Warning in ./libraries/DbQbe.php#1571
array_map() expects parameter 1 to be a valid callback, class 'Util' not found

Backtrace

./libraries/DbQbe.php#1571: array_map(
string 'Util::backquote',
array,
)
./libraries/DbQbe.php#1795: PMA\libraries\DbQbe->_getFromClause()
./libraries/DbQbe.php#1859: PMA\libraries\DbQbe->_getSQLQuery()
./db_qbe.php#155: PMA\libraries\DbQbe->getSelectionForm()
````

````
Warning in ./libraries/DbQbe.php#1572
implode(): Invalid arguments passed

Backtrace

./libraries/DbQbe.php#1572: implode(
string ', ',
NULL,
)
./libraries/DbQbe.php#1795: PMA\libraries\DbQbe->_getFromClause()
./libraries/DbQbe.php#1859: PMA\libraries\DbQbe->_getSQLQuery()
./db_qbe.php#155: PMA\libraries\DbQbe->getSelectionForm()
````

**Comment by lem9** [comment]
In Database > Operations > Create table > enter a table name, then Go: error 500; error log says:
````
PHP Fatal error:  Class 'PMA\\output\\Application_Octetstream_Download' not found in libraries/transformations.lib.php on line 175
````

**Comment by Tithugues** [comment]
@lem9 , thanks a lot for your tests. I'll have a look as soon as possible.

**Comment by Tithugues** [comment]
Related to `Invalid class name "Node", using default of "Node"`, I don't have the error.
I know that when I switch from master to the branch, I should remove my cookies and reconnect. Without this, I've some errors. Could you please try this?
Did anyone else try this branch and get this error?

**Comment by Tithugues** [comment]
With "Query" page, I didn't get any error. But you're right that something is wrong here. So I did a fix. Is it better for you?

**Comment by Tithugues** [comment]
And related the last one (`create table`), I didn't get any error too…
Do you have something specific in your config.inc.php please?

**Comment by ibennetch** [comment]
With PHP 7.0.0-rc1, I get this when first loading the page (before the login page is shown):
> Fatal error: Cannot use PMA\libraries\String as String because 'String' is a special class name in /var/www/pma-dev/fork/index.php on line 8

**Comment by ibennetch** [comment]
With PHP 5.6.12-0+deb8u1, I see the Node error shown three times at the bottom of the main page (after successfully logging in via cookie auth_type):
>  Invalid class name "Node", using default of "Node"
repeated three times.

**Comment by Tithugues** [comment]
I reverted PMA_String rename. That's the only solution I see now.
For the second issue about the node, I'll try again to reproduce it. Here is my PHP: `PHP 5.6.4-4ubuntu6.2`

**Comment by ibennetch** [comment]
My PHP7 system now shows this:
> 
Fatal error: main(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;PMA_Theme_Manager&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/pma-dev/fork/libraries/common.inc.php on line 662

**Comment by Tithugues** [comment]
@ibennetch , I've this error each time I've cookies and switch to branch. You need to remove your cookies and reconnect.

**Comment by Tithugues** [comment]
What kind on navigation tree do you have please?
Do you have groups?

**Comment by Tithugues** [comment]
@lem9 @ibennetch 
Can you please give your config.inc.php?

**Comment by Tithugues** [comment]
@lem9 : do you still have your create table error with transformation plugin please?

**Comment by ibennetch** [comment]
>> Fatal error: Cannot use PMA\libraries\String as String because 'String' is a special class name in /var/www/pma-dev/fork/index.php on line 8

> You need to remove your cookies and reconnect.

This does appear to be a browser issue; I've been clearing my cache between each run and logging out, I also tried with clearing cookies and the error continues. However, I tried a new browser and the error did not occur. I'm not sure what else to clear in the first browser as I've reloaded, cleared cache and cookies, but I'll figure it out -- clearly this particular problem isn't related to your code and is some problem with my browser, so carry on.

**Comment by ibennetch** [comment]
<pre>
$cfg['blowfish_secret'] = 'abba';

$cfg['Error_Handler']['display']=true;

$i = 0;
$i++;

$cfg['Servers'][$i]['host']          = 'localhost'; 
$cfg['Servers'][$i]['socket']        = '/var/run/mysqld/mysqld.sock';  
$cfg['Servers'][$i]['connect_type']  = 'socket';  
$cfg['Servers'][$i]['extension']     = 'mysqli'; 
$cfg['Servers'][$i]['auth_type']     = 'cookie'; 
$cfg['Servers'][$i]['AllowNoPassword'] = true;
</pre>

No change if I use the `mysql` extension, by the way.

**Comment by ibennetch** [comment]
My navigation tree has 24 databases, of which three are grouped together. If I change $cfg['NavigationTreeDbSeparator'] = '_'; to a different character so that there are no database groups, the Node error goes away. It seems rather clearly related to having database groups.

**Comment by ibennetch** [comment]
If I'm in the navigation tree, without any grouped databases, and expand a database, then click the New link to create a new table, I get a popup saying 
<pre>
Error in processing request
Error code: 200
Error text: OK
</pre>

There is nothing in the Apache error log.

**Comment by ibennetch** [comment]
I also get the error 200 when I go to the database's structure page and try to add a new table there; the error occurs when pressing Go.

**Comment by ibennetch** [comment]
I get a different error when going to the User accounts tab and clicking Edit privileges for any user:
<pre>
Fatal error: Uncaught Error: Class 'PMA\Template' not found in /var/www/pma-dev/fork/libraries/server_privileges.lib.php:3336 Stack trace: #0 /var/www/pma-dev/fork/libraries/server_privileges.lib.php(4702): PMA_getHtmlForAllTableSpecificRights('', '%', 'database') #1 /var/www/pma-dev/fork/server_privileges.php(435): PMA_getHtmlForUserProperties('', '', '', '%', '', '') #2 {main} thrown in /var/www/pma-dev/fork/libraries/server_privileges.lib.php on line 3336
</pre>

**Comment by lem9** [comment]
@Tithugues I could send you my exact config.inc.php if you were using GPG; here is a modified one:
````
$cfg['blowfish_secret'] = 'X';
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

$cfg['UploadDir'] = './upload';
$cfg['SaveDir'] = '';

$cfg['UserprefsDeveloperTab'] = true;
$cfg['ShowPhpInfo'] = true;
````

**Comment by lem9** [comment]
Testing 2e5bdf414cc83c29fe3ceff189f630115f4745e7.

Trying to create a table; on clicking Go:
````
PHP Fatal error:  Class 'PMA\\libraries\\plugins\\transformations\\.\\libraries\\plugins\\transformations\\output\\Application_Octetstream_Download' not found in libraries/transformations.lib.php on line 175
````

In Server > SQL > I type "use sakila" where sakila is an existing db containing tables and the navi panel is not expanded:
````
Invalid class name "Node", using default of "Node"
````
and nothing in the error log. But now the sakila db is expanded in the navi panel, and if I repeat the command, there is no error.

**Comment by Tithugues** [comment]
Thanks to your answers, I was able to reproduce the `Node` error.
To fix it, I updated the autoloader and the way the nodes are loaded.
Could you please try again?
Thanks!

**Comment by Tithugues** [comment]
Does anyone has a correct configuration to test transformations please?

**Comment by Tithugues** [comment]
All the unit tests of master are now OK on the branch! :)

**Comment by ibennetch** [comment]
I confirm the node error is fixed, nice work

Testing with 00e743eb3267145eb2ffdceb7fd2b6242c853f3e.

When I try to edit the structure of an existing row, the Input transformation and Input transformation options portions of the form are not correctly displayed.

From the table Structure tab, the "Add (1) column after (foo)" Go button gives an error:
<pre>
Error in processing request
Error code: 200
Error text: OK
</pre>

From the main page, clicking the "Plugins" link gives an error:
<pre>
Fatal error: Uncaught Error:
Class 'PMA_Response' not found in /var/www/pma-dev/fork/server_plugins.php:17
Stack trace: #0 {main} thrown in /var/www/pma-dev/fork/server_plugins.php on line 17
</pre>

**Comment by Tithugues** [comment]
The `PMA_Response` should be fixed. 

But I can't reproduce the one related to "Add column".
* Did you try to delete your cookies?
* Do you have more complete stack trace?
* Is it possible to get the content of the response of `tbl_addfield.php` ajax call please?

**Comment by lem9** [comment]
Testing 5f17b32689ebc8850d83bae299bcdb8957531495; trying to create a table with the default number of columns gives me this in the web server's log:
````
PHP Fatal error:  Class PMA\\libraries\\plugins\\transformations\\abs\\CodeMirrorEditorTransformationsPlugin' not found in libraries/plugins/transformations/input/Text_Plain_JsonEditor.php on line 24, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP Stack trace:, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   1. {main}() tbl_create.php:0, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   2. require() tbl_create.php:107, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   3. PMA\\libraries\\Template->render() libraries/tbl_columns_definition_form.inc.php:406, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   4. include() libraries/Template.php:75, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   5. PMA\\libraries\\Template->render() templates/columns_definitions/column_definitions_form.phtml:78, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   6. include() libraries/Template.php:75, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   7. PMA\\libraries\\Template->render() templates/columns_definitions/table_fields_definitions.phtml:129, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   8. include() libraries/Template.php:75, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP   9. PMA\\libraries\\Template->render() templates/columns_definitions/column_attributes.phtml:218, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP  10. include() libraries/Template.php:75, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP  11. PMA_getTransformationDescription() templates/columns_definitions/transformation.phtml:14, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31

PHP  12. include_once() libraries/transformations.lib.php:174, referer: http://localhost/phpmyadmin/db_structure.php?server=1&db=employees&token=3159721db625fab53dc1f0e367e28c31
````

**Comment by Tithugues** [comment]
@lem9 , do you have the error:
* after clicking on "Go" in "Create table" block of DB page?
* after filling the fields in "Create table" page and submitting form?
  * if this one, how did you fill the fields?

Could you please give me the steps to reproduce this error?

**Comment by Tithugues** [comment]
I achieved to enable transformations. I get the error now. I do my best to fix it.

**Comment by lem9** [comment]
@Tithugues It's after clicking on Go when trying to create a table.

**Comment by Tithugues** [comment]
@lem9 , it should be OK now. It was a typo in a class name…
Can you confirm it's OK for you too please?
Thanks.

**Comment by lem9** [comment]
@Tithugues I confirm that with 2960e6780a88c4e254dec362324bd9b01ccc502b  my creation table problem is fixed, good job! I'll retest all other problems I reported.

**Comment by lem9** [comment]
@Tithugues The previous problems I reported are fixed. I found a new one. In database Structure, click on the star to mark one table as favorite (that works) then click on another star: error 500. The log says
````
PHP Fatal error:  Call to a member function query() on null in libraries/mysql_charsets.inc.php on line 21, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP Stack trace:, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   1. {main}() db_structure.php:0, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   2. require_once() db_structure.php:15, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   3. require() libraries/common.inc.php:322, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   4. session_start() libraries/session.inc.php:101, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   5. spl_autoload_call() libraries/session.inc.php:101, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   6. PMA\\Psr4Autoloader->loadClass() libraries/session.inc.php:0, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   7. PMA\\Psr4Autoloader->loadMappedFile() libraries/Psr4Autoloader.php:98, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   8. PMA\\Psr4Autoloader->requireFile() libraries/Psr4Autoloader.php:137, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP   9. require() libraries/Psr4Autoloader.php:156, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
PHP  10. require_once() libraries/controllers/DatabaseStructureController.php:19, referer: http://localhost/phpmyadmin/db_structure.php?db=sakila&token=b2360fcffe497068942a4bf9b30163a9
````

**Comment by Tithugues** [comment]
@lem9 , I can't reproduce this error…
I see that you used sakila DB. Could you please tell me exactly which tables you starred firstly and secondly?

(Regarding your trace, it seems that session_start tries to load DatabaseStructureController. I don't really understand why…)

**Comment by lem9** [comment]
I can no longer reproduce it (testing bd0d2b7). Maybe it's because of my fix to https://github.com/phpmyadmin/phpmyadmin/issues/11524.

**Comment by Tithugues** [comment]
Perfect. :)
I found an error in setup and already fix it. (It seems that I didn't push it yesterday…)

**Pull request merged**
