### PR TITLE
Add composer.lock file

### PR DESCRIPTION
**Pull request by MauricioFauth**
Removes the `composer.lock` file from the ignored list and change the documentation and scripts to use `composer install` instead of `composer update`.

Related to #14338

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by ibennetch** [comment]
Also somewhat related to #15518

**Comment by williamdes** [comment]
Commits from https://github.com/williamdes/phpmyadmintest/commits/sami-4.9 will be needed

**Comment by williamdes** [comment]
I assigned you the issue so I can triage non-assigned PRs

**Comment by williamdes** [comment]
Closing for now

**Pull request closed without merging**
