### PR TITLE
Fixed the Undefined array key criteriaColumnOperators

### LINKED ISSUE #18611: ErrorException: Undefined array key "criteriaColumnOperators"
### Describe the bug

```
Internal error in .\libraries\classes\Table\Search.php#102
ErrorException: Undefined array key "criteriaColumnOperators"
```

### To Reproduce

1. Use `opengis.world_cities` table
2. Click on `Search`
3. Click on `Go`

### Expected behavior

No error should happen and the results should be shown.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/ecda6cbd-768b-43c2-bbc9-a9454231b578

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
### Description

Fixed the Undefined array key criteriaColumnOperators

Please describe your pull request.

Fixes #18611

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
@SachinBahukhandi can you fix it in QA_5_2?

**Review by MauricioFauth — APPROVED** [review]

**Comment by SachinBahukhandi** [comment]
@MauricioFauth why was this PR closed?

**Comment by williamdes** [comment]
It was not really closed, it was merged as https://github.com/phpmyadmin/phpmyadmin/commit/38968ef36c6972139b3c3aa9645ccd1ec2696c4c

But since you did not use QA_5_2 as a base a traditional merge could not be done :)
But everything is good and merged into QA and master

**Comment by SachinBahukhandi** [comment]
> It was not really closed, it was merged as [38968ef](https://github.com/phpmyadmin/phpmyadmin/commit/38968ef36c6972139b3c3aa9645ccd1ec2696c4c)
> 
> But since you did not use QA_5_2 as a base a traditional merge could not be done :) But everything is good and merged into QA and master

Thanks @williamdes @MauricioFauth, much appreciated!

**Pull request closed without merging**
