### PR TITLE
Fixes Table width

### LINKED ISSUE #15905: Bad UI: Empty space after charsets table
### Describe the bug

There is an empty space after the charsets table.

### To Reproduce

1. Go to 'top navigations'
2. Click on 'charset'
3. See empty space after the charset table 

### Screenshots
charset)

### Expected behavior

charset1

### Client configuration

- Browser: chrome and Microsoft edge
- Operating system: Windows 10

### Additional context

I will be working on this issue.

### PR DESCRIPTION
**Pull request by victorphoenix3**
Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>
Fixes #15905

### CODE REVIEW

**Comment by anirudhsingh20** [comment]
@victorphoenix3 I had already fixed this issue
.

**Comment by victorphoenix3** [comment]
@anirudhsingh20 Next time do link the issue in the description when you open a PR. I thought the issue was unattended.

**Comment by anirudhsingh20** [comment]
I mentioned the issue in the description as well @victorphoenix3

**Comment by mauriciofauth** [comment]
The issue was closed by #15906.

Thanks for your contribution.

**Pull request closed without merging**
