### PR TITLE
Bug fix: Fix triple HTML encoding

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Some values were double or even triple encoded in the HTML/JS. This resulted in garbled up text. This PR removed HTML escaping from places where it is not needed.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Does this affect 5.1 versions ?

**Comment by kamil-tekiela** [comment]
> Does this affect 5.1 versions ?

Yes, I can reproduce it on 5.1 too

**Review by williamdes — CHANGES_REQUESTED** [review]
Can you rebase this onto QA_5_1 please ?
Or create a new PR if the changes are very different on 5.1

**Comment by kamil-tekiela** [comment]
> Can you rebase this onto QA_5_1 please ? Or create a new PR if the changes are very different on 5.1

The changes are the same on 5.1 but I am just not savvy enough to be able to rebase it onto another branch without going through 1000 merge conflicts. I will cherry-pick it onto another branch and create a new PR.

**Comment by williamdes** [comment]
> > Can you rebase this onto QA_5_1 please ? Or create a new PR if the changes are very different on 5.1
> 
> The changes are the same on 5.1 but I am just not savvy enough to be able to rebase it onto another branch without going through 1000 merge conflicts. I will cherry-pick it onto another branch and create a new PR.

Perfect, thank you
By the way you may find useful informations here: https://github.com/phpmyadmin/phpmyadmin/wiki/GIT_MANUAL

**Comment by mauriciofauth** [comment]
Closing this in favor of #17247.

**Pull request closed without merging**
