### PR TITLE
Added filtering tables by name in export

### PR DESCRIPTION
**Pull request by jakubstanecki**
Signed-off-by: Jakub Stanecki <staneckijakub@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Apparently you're only hiding the tables without unchecking the hidden tables. All checked tables are being exported, even if they are hidden.

**Comment by mauriciofauth** [comment]
But I don't know if automatically unchecking the hidden tables would be a good idea.

**Comment by jakubstanecki** [comment]
@mauriciofauth I can add button "Uncheck hidden".

**Comment by mauriciofauth** [comment]
@jakubstanecki I think a button might be a good idea.

**Comment by nijel** [comment]
See also https://github.com/phpmyadmin/phpmyadmin/issues/13517 for discussion on this topic...

**Pull request closed without merging**
