### PR TITLE
Removed inline onmousedown javascript

### LINKED ISSUE #12261: Remove inline javascript
There are currently several places in our code which use inline javascript (mostly `onclick`, `onsubmit` and `onchange`). These should be removed and placed into javascript files.

After removal we can get rid of `'unsafe-inline'` for scripting in CSP.

### PR DESCRIPTION
**Pull request by manishbisht**
Fixes : #12261 

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by Fenn-CS** [comment]
@manishbisht great.. I thought or rather expected to see an additional js file containing the code removed from in-line or added to and existing js file. It looks like some functionality might be brick by simple removing the in-line js.

**Comment by nijel** [comment]
With your change moving objects in designer no longer works as before. Before it was possible to drag by whole table header, now it works only on the text.

**Comment by manishbisht** [comment]
Are you sure about this. Because I have cross checked the master branch and found that it only works when mouse was moved over the table text. Correct me if I am missing something.

**Comment by nijel** [comment]
You don't have the extra space where it doesn't work in your example :-). You need table with longer column definitions:

page-shot-2017-3-15 localhost localhost gammu phpmyadmin 4 8 0-dev

Here moving works fine on the text, but when I try to move using the big title area without text, it no longer works after your changes.

**Comment by manishbisht** [comment]
Thanks for the quick update. Just updated the PR according to it. :)

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
