### PR TITLE
Add a tool tip explaining the Lock symbol | Feat Req 1607

### PR DESCRIPTION
**Pull request by devenbansod**
Add a tool tip to explain the lock symbol appearing in the top right corner while you have made some un-saved changes to a page like inserting data or sql query.

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by ibennetch** [comment]
Looks great, thanks.

I won't be able to merge this until later today or tomorrow; in the mean time if some other team member wants to review and merge then please feel free.

**Comment by lem9** [comment]
Looks great only for English users ;) The message has to be made translatable. As an example, try
````
 git grep strSaveAndClose
````

**Comment by devenbansod** [comment]
Thanks Marc for pointing that out.

Anyways, added the string to ```js_messages``` array and printed from accessing that array.

Please suggest changes or I will then merge all commits into one commit.

**Comment by lem9** [comment]
Please squash.

**Comment by devenbansod** [comment]
Hi Marc,

I have squashed all into one commit!

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
