### PR TITLE
Alphabetic sorting of Export dropdown

### PR DESCRIPTION
**Pull request by Victor-Gomez**
Made the Export dropdown menu alphabetically sorted, related to this issue https://github.com/phpmyadmin/phpmyadmin/issues/13425
Signed-off-by: Victor Gomez <victor.gomez.spain@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by DrHouseDev** [comment]
This is my first commit with the DCO sign-off thing and I can't seem to get it right :/

**Comment by nijel** [comment]
Merged, thanks for your contribution!

PS: There should be at least one blank line before signed-off-by tag.

**Comment by OlafvdSpek** [comment]
Just wondering, wouldn't it make sense to do the sorting in the dropdown control related code, such that it can be shared by all other dropdowns (operating on a sorting flag of course).

**Comment by OlafvdSpek** [comment]
I think a case insensitive function should be used, but it's much better already, Thanks @DrHouseDev!

**Comment by nijel** [comment]
I've made it case insensitive in 33a545d4b40ff14b7f6ef69190bdcfeb22e39aa6.

**Comment by DrHouseDev** [comment]
Thanks for merging it!
Also thanks for the signed-off-by tip. :)

**Pull request merged**
