### PR TITLE
Fix #14130 - Created new messages for U2F errors 

### LINKED ISSUE #14130: [4.8 RC1] Wrong Error message for U2F Error code 4.
### Steps to reproduce
0. have 2 different U2F devices ready
1. set one of them as 2FA for the account.
2. try to log in
3. use THE OTHER U2F Device.

### Expected behaviour
Error Message 4 saying that the stick used is unknown to this account

### Actual behaviour
Error message 4 saying "Failed security key activation (4)."

### Reason
Error Message 4 works differently for Registration and Login as described here:
https://developers.yubico.com/U2F/Libraries/Client_error_codes.html

For Registration: the key is already used.
For Login: the key is unknown.

### Server configuration
**Operating system**: Win 8.1 Pro x64

**Web server:** Caddy 0.10.11

**Database:** MySQL 5.6.21

**PHP version:** 7.2.0

**phpMyAdmin version:** 4.8 RC1

### Client configuration
**Browser:** Opera 52

**Operating system:** Win 8.1 Pro x64

### PR DESCRIPTION
**Pull request by quinnzipse**
Signed-off-by: Quinn Zipse <qzipse@outlook.com>

### Description

This patch fixes the error codes displayed when you use the wrong key. It is now updated to have a new message for each error code in the Yubico specification [here](https://developers.yubico.com/U2F/Libraries/Client_error_codes.html).

Fixes #14130

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
This looks very nice !
Did you have a chance to test some of them ?
Do you have screenshots ?

**Comment by williamdes** [comment]
@My1 could you test this PR please ?

**Comment by quinnzipse** [comment]
I'm not sure how to get it to error to get all the messages. I will take screenshots of using the wrong key.

**Comment by williamdes** [comment]
> I'm not sure how to get it to error to get all the messages. I will take screenshots of using the wrong key.

Maybe you can locally change the error code to make them match a code you are able to have
Just to check all messages are working fine :)

**Comment by quinnzipse** [comment]
Here's what the new message looks like:

image

**Comment by quinnzipse** [comment]
> > I'm not sure how to get it to error to get all the messages. I will take screenshots of using the wrong key.
> 
> Maybe you can locally change the error code to make them match a code you are able to have
> Just to check all messages are working fine :)

I will do that!

**Comment by williamdes** [comment]
> Here's what the new message looks like:
> 
> image

Nice, could you disable the spinner or is it intended ?

**Comment by quinnzipse** [comment]
> > Here's what the new message looks like:
> > image
> 
> Nice, could you disable the spinner or is it intended ?

I'm not sure where the spinner comes from, it must be part of the function used to display the error. I kept it because that's how it was implemented before.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/c69ef03ddd191b6658934ab101f64abab4db6c4f/js/src/functions.js#L2196-L2234

I think you can find what you are searching for in the parameters, maybe using `'error'` would be better

Anyway, do what makes you confortable since the spinner was there before as you said ;)

**Comment by quinnzipse** [comment]
Here's what it looks like when I change it to use "error" like described above:
image

I think it makes more sense this way because the spinner indicates something is working in the background which is not the case.

**Review by williamdes — APPROVED** [review]
💯

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
