### PR TITLE
Fixes #16050: Added proper classes to html elements …

### LINKED ISSUE #16050: [5.1] French login form misaligned
image

NB: I use LastPass

And *Choix du serveur :* is not in bold

### PR DESCRIPTION
**Pull request by ankush-0x90**
Signed-off-by: Ankush Patil <aspraz2658@gmail.com>

### Description

Fixes #16050 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [ x Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by asprazz** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@asprazz is everything okay ?

**Comment by asprazz** [comment]
> @asprazz is everything okay ?

Sorry for this mess. But I think I have nearly fixed this issue by not messing up with css :)
But the problem is getting that labels in **bold** ..

**Comment by williamdes** [comment]
> But the problem is getting that labels in bold ..

Maybe we can remove the bold effect as it was not in a ChangeLog for me it is a bug

**Comment by asprazz** [comment]
> > But the problem is getting that labels in bold ..
> 
> Maybe we can remove the bold effect as it was not in a ChangeLog for me it is a bug

Oke. Well, for making that labels bold, if we need, we will have to change css little bit, i think.

**Comment by williamdes** [comment]
> > > But the problem is getting that labels in bold ..
> > 
> > 
> > Maybe we can remove the bold effect as it was not in a ChangeLog for me it is a bug
> 
> Oke. Well, for making that labels bold, if we need, we will have to change css little bit, i think.

Okay, I will test the behavior between themes and comparing 5.0 to see if it is similar enough

NB: my docker infrastructure is repair in progress ^^, the deployed PR will be available soon I hope

**Comment by williamdes** [comment]
@sudo-bot deploy PR

**Review by williamdes — APPROVED** [review]
It looks very nice on https://phpmyadmin-pr-16066.wdes.eu.org/index.php

**Review by williamdes — APPROVED** [review]
I have nothing more to say, perfect work :100: 
Works fine on all tested languages, and in mobile mode

**Pull request merged**
