### PR TITLE
Stay on table structure page.

### LINKED ISSUE #15663: Structure not shown after adding column
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=zzz

pma

### PR DESCRIPTION
**Pull request by victorphoenix3**
Fixes #15663

Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>

This is similar to #15662 .

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@mauriciofauth did you introduce a better way to build routes ?

**Review by MauricioFauth — APPROVED** [review]
Thanks for your contribution.

**Comment by mauriciofauth** [comment]
> @mauriciofauth did you introduce a better way to build routes ?

If I remember correctly, I did not. I think we should open an issue to add an URL function like the Twig one.

**Comment by williamdes** [comment]
Thank you for your contributions @victorphoenix3 !

**Comment by victorphoenix3** [comment]
@williamdes  am quite caught up with my University coursework and gsoc proposals at the moment. Will continue contributing to PMA in a short while. :)

**Comment by williamdes** [comment]
> @williamdes am quite caught up with my University coursework and gsoc proposals at the moment. Will continue contributing to PMA in a short while. :)

I understand, happy to know that you will be back 
We appreciate your contributions!

**Pull request merged**
