### PR TITLE
Remove redundant jQuery Event Drag plugin

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Awesome !

**Comment by williamdes** [comment]
@sudo-robot deploy

**Review by MauricioFauth — COMMENTED** [review]
Hi, please target the master branch.

Is this plugin not being used?

**Review by MauricioFauth — APPROVED** [review]

**Review by williamdes — APPROVED** [review]
Added 2 more fixes to make the non OSM drag work as we had found out it was not working on 4.9 
cc @shucon

**Pull request merged**
