### PR TITLE
Drop support for PHP 5.5

### PR DESCRIPTION
**Pull request by nijel**
This is mostly to continue discussion started in #13228. Please share your feedback!

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
You forgot to change the PHP requirement in `composer.json` from `"php": ">=5.5.0",` to `"php": "^5.6 || ^7.0",`.

**Comment by nijel** [comment]
Thanks! I've stayed with existing syntax and used `"php": ">=5.6.0"`.

**Comment by Dummann** [comment]
I ended up here searching why PHP 5.4 was no longer supported in recent builds, and now I'm reading that support for 5.5 is getting dropped.

Seems to me that you are forgetting that in a lot of serious hosting environments (with this I mean non-hobby) PHP 5.4x is still used. Hell, it's even the standard version for RedHat and Centos 7, and security fixes will get backported until 2024.

Simply throwing all those users an error like 'PHP 5.5+ is required' (while it runs fine on lower PHP version as well) seems lazy to me.

**Comment by mauriciofauth** [comment]
@Dummann You can still use phpMyAdmin 4.0.x if you use older versions of PHP.

The fact that CentOS 7 will receive support until 2024 doesn't mean that PHP 5.4 will receive support until 2024. It's not because CentOS ships with a 2013 version of PHP that has known bugs, that PMA also need to support this version.

As I said before, you can continue to use PMA 4.0.x if you use an older version of PHP, since this branch still receives security updates.

**Comment by mauriciofauth** [comment]
You can check more discussions on this subject in issue #13228.

**Comment by Dummann** [comment]
It does in fact mean that PHP 5.4 will receive security support for many, many years to come, you are underestimating this. This is the sole reason why most companies that need stability are going with either RedHat or Centos.

Even version 5.3 (from 2009?) is still being backported: https://access.redhat.com/security/updates/backporting

One could say that most RedHat/Centos users will prefer commandline over phpmyadmin, which is probably true, but still; I don't think certain distro users with default installations should be excluded from using the most recent version of phpmyadmin - especially when phpmyadmin doesn't rely on any new functionality introduced in those newer PHP versions.

Linux === freedom. The least you could do is make sure phpmyadmin works with all default installations on all popular distro's. I seriously don't get why you should drop support for PHP versions that are known to work perfectly fine with phpmyadmin. Not all phpmyadmin users are students/Ubuntu users.

**Comment by mauriciofauth** [comment]
It's strange that you want to have the latest version of a software while you want the maximum stability of other software to the point that you don't mind having old versions.
As I said before, and I don't mind repeating myself, if you want a stable version that supports your system, you can use PMA 4.0.x.

Please take into consideration that everything I said is just my opinion, I have no authority to speak on behalf of phpMyAdmin team.

**Comment by nijel** [comment]
Sorry, but we really can't keep compatibility with all PHP versions. It's evolving language and PHP 5.5 brought few important things, the most important for us is probably [finally block for exceptions](http://php.net/manual/en/migration55.new-features.php#migration55.new-features.finally), but there might be more things. See also https://github.com/phpmyadmin/phpmyadmin/issues/12790#issuecomment-265680575 for discussion on similar topic.

Note that we're not really exception in the PHP ecosystem, random examples I've found:

* [Drupal needs PHP greater or equal PHP Version 5.5.9](https://www.drupal.org/docs/8/system-requirements/web-server)
* [Joomla needs 5.6 + or 7 +](https://docs.joomla.org/J3.x:Installing_Joomla)
* [Moodle needs minimum PHP 5.6.5](https://docs.moodle.org/dev/Moodle_3.2_release_notes#Server_requirements)
* [MediaWiki needs PHP version 5.5.9 or later](https://www.mediawiki.org/wiki/Manual:Installation_requirements#PHP)

So I'd say we're quite on par with current requirement of 5.5.

Also if this pull request would be merged, it would change requirements to 5.6 for future 4.8.0 release, which will certainly not happen earlier than in Q4, but more likely early in 2018.

Until April we did also provide security support for 4.0 exactly to support older PHP versions. In case we will raise PHP requirements in 4.8, the 4.7 will also get extended period of security support.

**Comment by JorisDebonnet** [comment]
Perhaps this could be an opportunity to introduce [Semantic Versioning](http://semver.org/), which would mean dropping php 5.5 support should require pma's major version to bump to 5.

**Comment by Dummann** [comment]
I don't really get the comparison with Joomla and other projects. PhpMyAdmin is a database tool, which should be all about reliability - it's not some fancy platform that needs the latest functionalities to satisfy the masses.

Some sysadmins suggested to start a private fork, which seems the wrong direction to me. Come on, why would we drop support for PHP versions without proper reason? The newest version of phpMyAdmin also works on older PHP versions, so there is no reason to throw 'You need PHP 5.X or newer' right away. If you want me to test upcoming changes in older PHP versions - I'll do it - if that means older version will be supported and effort will be made to keep supporting them.

**Comment by nijel** [comment]
Okay, this is probably too early to do this.

@Dummann phpMyAdmin does not work properly with older PHP than 5.5, there are several places which depend on PHP 5.5 syntax, see https://github.com/phpmyadmin/phpmyadmin/pull/13363 (I've done it again as build logs for #12795 seem to be lost) where I've tried what is broken.

**Pull request closed without merging**
