### PR TITLE
default password 'cbb74bc' changed to 'change_password'

### LINKED ISSUE #16177: Change password cbb74bc to something like CHANGEME
The string `cbb74bc` is used as password in file `doc/setup.rst` at:
`$cfg['Servers'][$i]['password']      = 'cbb74bc'; // use here your password`
it's better to use string like 'changeme' or 'CHANGEME' or 'not-secure-need-to-be-changed' etc.. to imply that the string need to be changed (not use the declared password for anything)

### PR DESCRIPTION
**Pull request by olumide95**
Signed-off-by: Olumide Olugbemiro <olugbemiro.olumide@gmail.com>

### Description
default password 'cbb74bc' changed to 'change_password' to infer that the password should be changed.

closes #16177

### CODE REVIEW

**Comment by williamdes** [comment]
cc @ibennetch @emanuelb I would prefer something more explicit but I would agree to merge it, what do you think ?

**Comment by emanuelb** [comment]
I like the "ChangeMe" (variations of it) because it:
1.  is in widespread use, see by searching of `default password "changeme"` such as results from:
https://bizuns.com/default-passwords-list
https://cloudpathshala.com/2018/07/20/list-of-default-username-and-password-of-different-products/
2. explain that it need to be changed.

**Comment by ibennetch** [comment]
I agree with Emanuel on this, thanks.

By the way, Emanuel, thank you for all your recent suggestions. They are
much appreciated.

**Comment by olumide95** [comment]
thanks for your input @williamdes @emanuelb the commit has been updated to the agreed 'changeme' as default.

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
I am merging it :)

**Comment by williamdes** [comment]
Thank you @olumide95 for this documentation improvement !

**Comment by olumide95** [comment]
@williamdes I'm glad I could be of help, this is my first OS contribution. Looking to contribute more in the coming months 😊

**Comment by williamdes** [comment]
> @williamdes I'm glad I could be of help, this is my first OS contribution. Looking to contribute more in the coming months

We will be glad to welcome more contributions ;)

**Pull request merged**
