### PR TITLE
Fix phpstan `return type` errors

### PR DESCRIPTION
**Pull request by ghost**
Hello,

ich checked out the phpmyadmin baseline and fixed some return type errors, for example

```
			message: "#^Method PhpMyAdmin\\\\Config\\\\ServerConfigChecks\\:\\:performConfigChecksServersSetBlowfishSecret\\(\\) return type has no value type specified in iterable type array\\.$#"
			count: 1
			path: libraries/classes/Config/ServerConfigChecks.php
```

This is my first PR in the phpymadmin repo. Please feel free to comment, if i have to change things :)

Greetings

Daniel

#hacktoberfest

### CODE REVIEW

**Comment by standan-hulk** [comment]
closed due to dco issues

**Comment by williamdes** [comment]
> closed due to dco issues

Could you please explain?

**Review by williamdes — COMMENTED** [review]
The changes where cool!

**Comment by standan-hulk** [comment]
> > closed due to dco issues
> 
> Could you please explain?

sorry. i forgot to sign my commits.  This is my new pr: https://github.com/phpmyadmin/phpmyadmin/pull/17782

**Pull request closed without merging**
