### PR TITLE
removes some inconsistencies and unnecessary rules

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by williamdes** [comment]
With command line: `git commit --amend --signoff` & `git push -f`

**Comment by ibennetch** [comment]
Could you also please use your name in the sign off message? This can be automatically generated by Git if you configure your name and email address as in https://help.github.com/articles/setting-your-username-in-git/

**Comment by BO41** [comment]
yeah, sure ;)

**Comment by BO41** [comment]
now, finally!

please review my changes. These are my first PR's to this project. 

Please tell me if such changes are welcome. Or where I can find easy issues to solve :)

**Comment by williamdes** [comment]
@ibennetch
I think it would be cool to have a place (Slack or whatever) where contributors can meet and discuss, maybe also find easily issues to work on.
What do you think about that ?

cc @nulll-pointer

**Comment by BO41** [comment]
@ibennetch you already have the [newbie](https://github.com/phpmyadmin/phpmyadmin/labels/newbie) tag, but like on many projects, it is not that newbie friendly.

great idea. would be great to see something like this.
but please easy to join and not something like an irc channel

just my opinion :smile:

**Comment by williamdes** [comment]
@BO41 https://join.slack.com/t/phpmyadmingh/shared_invite/enQtNDAyODc0MzE2MzczLWY4ZDU0NmViYTdhN2UyZGM0Njc4YjRiYTRiYzI4YTQ0NWJhZjYyMDhlODI4M2JkYThlMzIzZTFiNzNjZWRhZjI

**Comment by BO41** [comment]
@ibennetch thank you this information. It might be good to have it on the [website/contribute](https://www.phpmyadmin.net/contribute/) and in the https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md and the https://github.com/phpmyadmin/phpmyadmin/blob/master/README.

At least for me, it is hard to find a issue that I can work on. Although it might be tagged _newbie_ or _good first issue_. Because I don't even know where to find the right file. And then it is even harder to understand the issue.
I think it would help to leave some hints, like "this needs to be changed in `/js/.../.../` so that new people know where to start looking and read into the code.

but maybe this is just me having problems

Thank you all for the help :-)

**Comment by BO41** [comment]
replaced with #14532

**Pull request closed without merging**
