### PR TITLE
Prevent multiple request for SQL autocomplete

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Fix Bug#4858

### CODE REVIEW

**Comment by lem9** [comment]
@nisargjhaveri Please rebase because of a recent fix in QA_4_4

**Comment by lem9** [comment]
The fix looks fine.

**Comment by nisargjhaveri** [comment]
You merged this, right?

**Comment by lem9** [comment]
Yes I did. Sorry, I thought I had confirmed the merge.

**Pull request closed without merging**
