### PR TITLE
Remove jquery.sortableTable.js from js/vendor dir

### PR DESCRIPTION
**Pull request by MauricioFauth**
It is not a vendor file, but an internal file.
Added by commit 1c6a388ca0b44ae5577d3a243639cefe61b43cf9.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Very good!

**Comment by williamdes** [comment]
No addScript calls to adjust?

**Comment by mauriciofauth** [comment]
> No addScript calls to adjust?

Only one, already fixed. :)

**Review by williamdes — APPROVED** [review]
Reviews on mobile ^^
Skipped a file on previous review

**Pull request merged**
