### PR TITLE
Fixed urls in navigation

### LINKED ISSUE #15626: vsprintf(): Too few arguments
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=z&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure&field=a&change_column=1

pma

### LINKED ISSUE #15893: Invalid Link of Column | Index in Nav Panel
### To Reproduce

1. Go to 'Navigation Panel'
2. Expand Database -> Table
3. See error (Invalid URL of link)

### Expected behavior

image

### Screenshots

image

### Additional context

Only in Master Branch

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

concatinated url string and removed from array

Fixes: #15893 
Fixes: #15626

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
I am not sure this fix it a good solution, can you try to fix the routing function or improve it?

**Comment by yashrajbothra** [comment]
Definately I will try to improve the function.

I pushed this fix becuz all other urls follow similar concatenation ⬇️
image

**Comment by yashrajbothra** [comment]
Hey I tried multiple possible solution but all had some consequenses so only this one fits the best.

Can you suggest anything @williamdes or should we call other members to review

**Comment by williamdes** [comment]
@yashrajbothra did you see 
https://github.com/phpmyadmin/phpmyadmin/blob/0032dff0d33b3f8d84ece0381e7bb437797ddf57/libraries/classes/Url.php#L288
calls

https://github.com/phpmyadmin/phpmyadmin/blob/0032dff0d33b3f8d84ece0381e7bb437797ddf57/libraries/classes/Url.php#L173-L175

maybe add a parameter so it calls https://github.com/phpmyadmin/phpmyadmin/blob/0032dff0d33b3f8d84ece0381e7bb437797ddf57/libraries/classes/Url.php#L208 directly

**Comment by yashrajbothra** [comment]
Yes I was debugging and saw all of those but the problem is when we call `getCommonRaw` it uses 
https://github.com/phpmyadmin/phpmyadmin/blob/0032dff0d33b3f8d84ece0381e7bb437797ddf57/libraries/classes/Url.php#L229
so the return value cannot have any `$` and this results to error when we use `vsprint` to generate link ahead

**Comment by williamdes** [comment]
> Yes I was debugging and saw all of those but the problem is when we call `getCommonRaw` it uses
> https://github.com/phpmyadmin/phpmyadmin/blob/0032dff0d33b3f8d84ece0381e7bb437797ddf57/libraries/classes/Url.php#L229
> 
> 
> so the return value cannot have any `$` and this results to error when we use `vsprint` to generate link ahead

htmlspecialchars seems to be what blocks the code

**Comment by yashrajbothra** [comment]
'vsprintf` contains false because link doesnt contain instructed format.
image

And here we can see that format is changed by this function 
image

As a result we cant see any link 😕

**Comment by williamdes** [comment]
> `vsprintf` contains false because link doesnt contain instructed format.
> image
> 
> And here we can see that format is changed by this function
> image
> 
> As a result we cant see any link

> htmlspecialchars seems to be what blocks the code

Did you remove the function htmlspecialchars to try ?
Did you try to change the https://www.php.net/manual/en/function.http-build-query.php enc_type param ?

**Comment by yashrajbothra** [comment]
> Did you remove the function htmlspecialchars to try ?

Yes, I did try but it didnt worked.

> Did you try to change the https://www.php.net/manual/en/function.http-build-query.php enc_type param ?

Yes, I tried both encoding types but i dindn't help 🤔

**Review by williamdes — APPROVED** [review]
Best solution for now, thank you

**Review by MauricioFauth — APPROVED** [review]
I'm fine with this change if it fixes the issue. However I think we should find another solution that doesn't require to build the query string manually.

**Comment by williamdes** [comment]
Thank you so much for the fix @yashrajbothra !

**Pull request merged**
