### PR TITLE
Handle large number of tables in database (based on QA_5_2)

### PR DESCRIPTION
**Pull request by PicoI2**
Hi, this is a patch to handle large number of table in a single database. I test it with more than 300 000 tables.
It works with or without DisableIS.
To be able to use phpMyAdmin with this amount of table, $cfg['EnableAutocompleteForTablesAndColumns'] must be set to false.
I hesitated to automatically disable EnableAutocompleteForTablesAndColumns when there was more than 10 000 tables, I can add it if you think it can be helpful.

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @PicoI2
T

**Comment by williamdes** [comment]
Hi @PicoI2
This one was good, just the PR target was wrong, there is an dit button for it:)

**Comment by PicoI2** [comment]
No, I made a mistake rebasing my branch, and I would like to do the fix in a single commit.
I force push on my branch and did open a 3rd PR.
I develop for more than 10 years but each times I want to contribute to a open source project I feel like I am the worst noob !

**Comment by williamdes** [comment]
> No, I made a mistake rebasing my branch, and I would like to do the fix in a single commit. I force push on my branch and did open a 3rd PR. I develop for more than 10 years but each times I want to contribute to a open source project I feel like I am the worst noob !

Don't feel like that, it takes some time to understand some small details about tools we use in open source

**Pull request closed without merging**
