### PR TITLE
change of typo

### PR DESCRIPTION
**Pull request by johnlow95**
change of typo in the intro.rest where logs in is change to login

Before submitting pull request, please check that every commit:

- [X] Has commit message which describes it

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This does not really sound right for me.
I don't think any change is needed

**Comment by johnlow95** [comment]
because im kinda confusing with this part since it sound more like the password and username will be pass directly to mySQL when a user login, or am i misunderstood it?

**Comment by lem9** [comment]
I confirm that the original sentence is fine, no change needed. Please close.

**Review by williamdes — CHANGES_REQUESTED** [review]
I think no change is needed.

**Comment by ibennetch** [comment]
Thanks for your submission. I agree with the others that this isn't a proper change. "Login" is a noun, which is why we use the verb "log in" or, in the context of this sentence, "logs in".

You're correct that phpMyAdmin passes the username and password directly to MySQL.

**Pull request closed without merging**
