### PR TITLE
FRE #1568: fold add column position radio into one 'add column after' 

### PR DESCRIPTION
**Pull request by smita786**
I have used 'After' and Begin as mysql uses 'AFTER' and 'FIRST' in queries not 'BEFORE'.

In the after dropdown, I have used 'At Begin' not sure if it looks fine. Please suggest if we can put it in better way.
Signed-off-by: Smita Kumari kumarismita62@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Looks good. I suggest to replace "At Begin" with "Beginning of table" because the full phrase "after at begin" looks weird. With your choice of not putting "After" in each choice (which I support for clarity), we have to do something about the "At Begin" choice.

**Comment by smita786** [comment]
Hi Marc,
Thanks. Yeah I changed it to "Beginning of table", it sounds better .

**Comment by lem9** [comment]
Great; please merge.

**Comment by smita786** [comment]
merged. Thanks :-)

**Pull request merged**
