### PR TITLE
Fix #15363 Remove unexpected quotes on text fields

### LINKED ISSUE #15363: Alter table with TEXT DEFAULT '' misbehaves
Changing the default value of a field with type TEXT to nothing (empty string), adds two quotes as a new default.

Given a table 'test' with a field 'content' as TEXT.

Reproduce v1: 
- open table structure view
- click on CHANGE for field 'content'
- change field settings to DEFAULT 'As defined' and leave default value blank.

Reproduce v2: 
- go to SQL and
- ```ALTER TABLE `test` CHANGE `content` `content` TEXT NOT NULL DEFAULT '';```

Expected:
- In the structure view, the default value should be empty and not show '' (compare to type varchar).
- INSERT form should not add '' to the text field but rather leave it empty.

Environment:
- Operating system: Win10
- Web server: Apache/2.4.39 (Win64) OpenSSL/1.1.1c
- Database version: 10.3.15-MariaDB
- PHP version: PHP/7.3.6
- phpMyAdmin version: 4.9.0.1
- Browser: Any
- Operating system: Any

Verified the problem with a completely different linux environment, but i don't have the specs right now.

### PR DESCRIPTION
**Pull request by Tithugues**
Fixes #15363

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
@Tithugues I made more changes, please test using my test table:
```sql

CREATE TABLE `issue-15363` (
  `id` int(11) DEFAULT NULL,
  `empty text` text DEFAULT '',
  `empty varchar` varchar(25) NOT NULL DEFAULT '',
  `really empty string` varchar(25) NOT NULL DEFAULT '''''',
  `really empty text` text NOT NULL DEFAULT '\'\'',
  `l'eau dans un varchar` varchar(25) NOT NULL DEFAULT 'l''eau ',
  `l'eau 2` text NOT NULL DEFAULT 'l\'eau',
  `l'eau dans un texte` text NOT NULL DEFAULT 'l\'eau',
  `l'eau` varchar(25) NOT NULL DEFAULT 'l''eau \\n \\n \\t l''eau',
  `l'eau 3` text NOT NULL DEFAULT 'l\'eau \\n \\n \\t l\'eau'
) ENGINE=InnoDB DEFAULT;
```

**Comment by williamdes** [comment]
@mauriciofauth can you please review ?

**Comment by williamdes** [comment]
NOTE for merging: cherry-pick c51d16391cec5b12942bf11559fa74db81ca4e95 and squash into merge of `QA_4_9` into `QA_5_0`

**Comment by williamdes** [comment]
There is still an issue when you edit a text column the preview sql is shown instead of "no changes" when you did not change anything. (I kinda introduced the issue)
image

**Review by MauricioFauth — APPROVED** [review]

**Comment by Tithugues** [comment]
> There is still an issue when you edit a text column the preview sql is shown instead of "no changes" when you did not change anything. (I kinda introduced the issue)
> image

@williamdes , I think that you didn't introduced this issue (at least, not with this MR). I have the same behavior on `master`. This happens on `nullable` fields. We can see in the form that the `field_null_orig[0]` (the fact that the field is `nullable` or not) contains `YES` when the field is nullable, whereas `field_null[0]` contains `"NULL"`.

**Comment by williamdes** [comment]
Thanks a lot @Tithugues for the investigation!
I will merge the PR soon :)

**Comment by williamdes** [comment]
Thanks for helping solve #15363 @Tithugues !

**Pull request merged**
