### PR TITLE
Fix GIS functions for mysql >= 5.6

### LINKED ISSUE #12865: Possible MySQL 8.0.0 issue with GIS display
I'll start off my saying that my client library doesn't match my MySQL version, so that definitely could be the cause of this, but I’m trying PMA master with MySQL 8.0.0 and GIS is broken. It would be great if someone with a better configuration could confirm or refute this.

1. Browse a table with GIS data
2. At the bottom of the results, click the "Visualize GIS data" link

MySQL: 8.0.0-dmr MySQL Community Server
Database client version: libmysql - 5.5.53
PHP extension: mysqli curl mbstring
PHP version: 5.6.29-0+deb8u1

This works okay with my MySQL 5.5 installation

```
Warning in ./libraries/dbi/DBIMysqli.php#257
mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given

Backtrace

./libraries/dbi/DBIMysqli.php#257: mysqli_fetch_array(
boolean false,
integer 1,
)
./libraries/DatabaseInterface.php#2425: PMA\libraries\dbi\DBIMysqli->fetchAssoc(boolean false)
./libraries/gis/GISVisualization.php#214: PMA\libraries\DatabaseInterface->fetchAssoc(boolean false)
./libraries/gis/GISVisualization.php#140: PMA\libraries\gis\GISVisualization->_fetchRawData()
./libraries/gis/GISVisualization.php#88: PMA\libraries\gis\GISVisualization->__construct(
string 'SELECT * FROM `capitals`',
array,
integer 25,
string '0',
)
./libraries/controllers/table/TableGisVisualizationController.php#152: PMA\libraries\gis\GISVisualization::get(
string 'SELECT * FROM `capitals`',
array,
integer 25,
string '0',
)
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#589
Undefined index: maxX

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#589
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#590
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#590
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#602
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#604
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#604
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#611
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#612
Undefined index: maxX

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#613
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#614
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#302: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/gis/GISVisualization.php#318: PMA\libraries\gis\GISVisualization->_svg()
./libraries/gis/GISVisualization.php#505: PMA\libraries\gis\GISVisualization->asSVG()
./libraries/controllers/table/TableGisVisualizationController.php#207: PMA\libraries\gis\GISVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#589
Undefined index: maxX

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#589
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#590
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#590
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#602
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#604
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#604
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#611
Undefined index: minX

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#612
Undefined index: maxX

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#613
Undefined index: minY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()
Notice in ./libraries/gis/GISVisualization.php#614
Undefined index: maxY

Backtrace

./libraries/gis/GISVisualization.php#421: PMA\libraries\gis\GISVisualization->_scaleDataSet(array)
./libraries/controllers/table/TableGisVisualizationController.php#208: PMA\libraries\gis\GISVisualization->asOl()
./tbl_gis_visualization.php#43: PMA\libraries\controllers\table\TableGisVisualizationController->indexAction()


```

### LINKED ISSUE #14383: Warning when browsing certain tables
On the demo server, I can reproduce this with the opengis database by trying to browse the "gis_all" table. I don't see anything obviously different about that table, though. The problem exists with both master and QA_4_8.

When browsing the table, I get a long line of warnings, starting with:
```
Warning in ./libraries/classes/Dbi/DbiMysqli.php#262
mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given

Backtrace

./libraries/classes/Dbi/DbiMysqli.php#262: mysqli_fetch_array(
boolean false,
integer 2,
)
./libraries/classes/DatabaseInterface.php#2554: PhpMyAdmin\Dbi\DbiMysqli->fetchRow(boolean false)
./libraries/classes/Util.php#2985: PhpMyAdmin\DatabaseInterface->fetchRow(
boolean false,
integer 0,
)
./libraries/classes/Display/Results.php#3703: PhpMyAdmin\Util::asWKT(string )
./libraries/classes/Display/Results.php#3050: PhpMyAdmin\Display\Results->_getDataCellForGeometryColumns(
string ,
string 'data not_null ',
,
array,
array,
boolean false,
array,
array,
array,
array,
)
./libraries/classes/Display/Results.php#2695: PhpMyAdmin\Display\Results->_getRowValues(
,
array,
integer 0,
boolean false,
array,
string '',
boolean false,
string 'SELECT * FROM `gis_all`',
array,
)
./libraries/classes/Display/Results.php#4289: PhpMyAdmin\Display\Results->_getTableBody(
,
array,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#1738: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#2031: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean false,
string '7',
integer 7,
NULL,
,
array,
)
./libraries/classes/Sql.php#2252: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'opengis',
string 'gis_all',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '7',
integer 7,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `gis_all`',
NULL,
)
./libraries/classes/Sql.php#2129: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'opengis',
string 'gis_all',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `gis_all`',
NULL,
NULL,
)
./sql.php#215: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'opengis',
string 'gis_all',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `gis_all`',
NULL,
NULL,
)
```

### PR DESCRIPTION
**Pull request by williamdes**
### Description

Fixes #14383
Fixes #12865

### CODE REVIEW

**Comment by williamdes** [comment]
@mauriciofauth and @ibennetch Can you please review this bug fix ?

**Review by MauricioFauth — APPROVED** [review]

**Comment by ibennetch** [comment]
This is a major improvement, however I still can get an error. When browsing the opengis database, gis_all table, I scroll to the bottom and click "Visualize GIS data."

This error is shown:
```
Warning in ./libraries/classes/Gis/GisGeometry.php#230
A non-numeric value encountered

Backtrace

./libraries/classes/Gis/GisMultiPoint.php#207: PhpMyAdmin\Gis\GisGeometry->extractPoints(
string '(125 50),(156 250),(178 143),(175 80)',
array,
)
./libraries/classes/Gis/GisVisualization.php#676: PhpMyAdmin\Gis\GisMultiPoint->prepareRowAsSvg(
string 'MULTIPOINT((125 50),(156 250),(178 143),(175 80))',
string '',
string '#E0D62E',
array,
)
./libraries/classes/Gis/GisVisualization.php#314: PhpMyAdmin\Gis\GisVisualization->_prepareDataSet(
array,
array,
string 'svg',
string '<path d=" M 206.25, 435 L 238.8, 225 L 261.9, 337.35 Z " name="" id="106450595" class="polygon vector" stroke="black" stroke-width="0.5" fill="#B02EE0" fill-rule="evenodd" fill-opacity="0.8"/><path d=" M 217.8, 393 L 229.35, 347.85 L 245.1, 356.25 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1238202467"/><path d=" M 185.25, 435 L 133.8, 225 L 156.9, 337.35 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1429915285"/>',
)
./libraries/classes/Gis/GisVisualization.php#329: PhpMyAdmin\Gis\GisVisualization->_svg()
./libraries/classes/Gis/GisVisualization.php#516: PhpMyAdmin\Gis\GisVisualization->asSVG()
./libraries/classes/Controllers/Table/TableGisVisualizationController.php#213: PhpMyAdmin\Gis\GisVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#42: PhpMyAdmin\Controllers\Table\TableGisVisualizationController->indexAction()
Notice in ./libraries/classes/Gis/GisGeometry.php#232
A non well formed numeric value encountered

Backtrace

./libraries/classes/Gis/GisMultiPoint.php#207: PhpMyAdmin\Gis\GisGeometry->extractPoints(
string '(125 50),(156 250),(178 143),(175 80)',
array,
)
./libraries/classes/Gis/GisVisualization.php#676: PhpMyAdmin\Gis\GisMultiPoint->prepareRowAsSvg(
string 'MULTIPOINT((125 50),(156 250),(178 143),(175 80))',
string '',
string '#E0D62E',
array,
)
./libraries/classes/Gis/GisVisualization.php#314: PhpMyAdmin\Gis\GisVisualization->_prepareDataSet(
array,
array,
string 'svg',
string '<path d=" M 206.25, 435 L 238.8, 225 L 261.9, 337.35 Z " name="" id="106450595" class="polygon vector" stroke="black" stroke-width="0.5" fill="#B02EE0" fill-rule="evenodd" fill-opacity="0.8"/><path d=" M 217.8, 393 L 229.35, 347.85 L 245.1, 356.25 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1238202467"/><path d=" M 185.25, 435 L 133.8, 225 L 156.9, 337.35 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1429915285"/>',
)
./libraries/classes/Gis/GisVisualization.php#329: PhpMyAdmin\Gis\GisVisualization->_svg()
./libraries/classes/Gis/GisVisualization.php#516: PhpMyAdmin\Gis\GisVisualization->asSVG()
./libraries/classes/Controllers/Table/TableGisVisualizationController.php#213: PhpMyAdmin\Gis\GisVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#42: PhpMyAdmin\Controllers\Table\TableGisVisualizationController->indexAction()


```

**Review by ibennetch — CHANGES_REQUESTED** [review]
This is a major improvement, however I still can get an error. When browsing the opengis database, gis_all table, I scroll to the bottom and click "Visualize GIS data."

This error is shown:
```
Warning in ./libraries/classes/Gis/GisGeometry.php#230
A non-numeric value encountered

Backtrace

./libraries/classes/Gis/GisMultiPoint.php#207: PhpMyAdmin\Gis\GisGeometry->extractPoints(
string '(125 50),(156 250),(178 143),(175 80)',
array,
)
./libraries/classes/Gis/GisVisualization.php#676: PhpMyAdmin\Gis\GisMultiPoint->prepareRowAsSvg(
string 'MULTIPOINT((125 50),(156 250),(178 143),(175 80))',
string '',
string '#E0D62E',
array,
)
./libraries/classes/Gis/GisVisualization.php#314: PhpMyAdmin\Gis\GisVisualization->_prepareDataSet(
array,
array,
string 'svg',
string '<path d=" M 206.25, 435 L 238.8, 225 L 261.9, 337.35 Z " name="" id="106450595" class="polygon vector" stroke="black" stroke-width="0.5" fill="#B02EE0" fill-rule="evenodd" fill-opacity="0.8"/><path d=" M 217.8, 393 L 229.35, 347.85 L 245.1, 356.25 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1238202467"/><path d=" M 185.25, 435 L 133.8, 225 L 156.9, 337.35 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1429915285"/>',
)
./libraries/classes/Gis/GisVisualization.php#329: PhpMyAdmin\Gis\GisVisualization->_svg()
./libraries/classes/Gis/GisVisualization.php#516: PhpMyAdmin\Gis\GisVisualization->asSVG()
./libraries/classes/Controllers/Table/TableGisVisualizationController.php#213: PhpMyAdmin\Gis\GisVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#42: PhpMyAdmin\Controllers\Table\TableGisVisualizationController->indexAction()
Notice in ./libraries/classes/Gis/GisGeometry.php#232
A non well formed numeric value encountered

Backtrace

./libraries/classes/Gis/GisMultiPoint.php#207: PhpMyAdmin\Gis\GisGeometry->extractPoints(
string '(125 50),(156 250),(178 143),(175 80)',
array,
)
./libraries/classes/Gis/GisVisualization.php#676: PhpMyAdmin\Gis\GisMultiPoint->prepareRowAsSvg(
string 'MULTIPOINT((125 50),(156 250),(178 143),(175 80))',
string '',
string '#E0D62E',
array,
)
./libraries/classes/Gis/GisVisualization.php#314: PhpMyAdmin\Gis\GisVisualization->_prepareDataSet(
array,
array,
string 'svg',
string '<path d=" M 206.25, 435 L 238.8, 225 L 261.9, 337.35 Z " name="" id="106450595" class="polygon vector" stroke="black" stroke-width="0.5" fill="#B02EE0" fill-rule="evenodd" fill-opacity="0.8"/><path d=" M 217.8, 393 L 229.35, 347.85 L 245.1, 356.25 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1238202467"/><path d=" M 185.25, 435 L 133.8, 225 L 156.9, 337.35 Z " name="" class="multipolygon vector" stroke="black" stroke-width="0.5" fill="#E0642E" fill-rule="evenodd" fill-opacity="0.8" id="1429915285"/>',
)
./libraries/classes/Gis/GisVisualization.php#329: PhpMyAdmin\Gis\GisVisualization->_svg()
./libraries/classes/Gis/GisVisualization.php#516: PhpMyAdmin\Gis\GisVisualization->asSVG()
./libraries/classes/Controllers/Table/TableGisVisualizationController.php#213: PhpMyAdmin\Gis\GisVisualization->toImage(string 'svg')
./tbl_gis_visualization.php#42: PhpMyAdmin\Controllers\Table\TableGisVisualizationController->indexAction()


```

**Comment by williamdes** [comment]
@ibennetch Can you please have a look ?
I have fixed the bug with https://github.com/phpmyadmin/phpmyadmin/pull/15149/commits/ccc82e82b5447f558c164552e91487b7b8d0ffbe

**Pull request merged**
