### PR TITLE
Basic functionality for varchar(10) without Faker added

### PR DESCRIPTION
**Pull request by Achilles-96**
Before submitting pull request, please check that every commit:
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on its own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

Signed-off-by: Achilles-96 raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by Achilles-96** [comment]
Not to merge. I made basic functionality for varchar(10). Please review interface. If it is fine, I'll integrate with Faker for all datatypes.

**Comment by nijel** [comment]
Seems this really slipped of our attention, sorry.

Few comments:

- Such feature and dependency should be IMHO optional.
- I'm not really sure if placing it on insert/edit page is good idea, certainly it makes no sense for edit one. Maybe it would be better to do this on the operations page?
- Please avoid adding more spaghetti code to top level files, rather implement the code in a separate class which can be properly tested.

**Comment by Achilles-96** [comment]
Thanks for the review. Am I encouraged to work on this now. [Here](https://github.com/phpmyadmin/phpmyadmin/wiki/GSoC_2017_applicant_guide#get-involved-with-phpmyadmin), it says otherwise.

**Comment by nijel** [comment]
I'm not sure - you've already spent quite some time on it, but having it implemented before summer would force us to add new tasks to the GSoC idea. What does @ibennetch think?

**Comment by ibennetch** [comment]
I think you can continue to work on this and we can find another project for the GSoC list (such as I've done at https://github.com/phpmyadmin/phpmyadmin/wiki/GSoC_2017_ideas_list/_compare/0d46ca50b68e2fcd360dbcf9d76085e786228cef...71ea3d2e0cde72cb70057f396afbbf17d30d8893)

**Comment by Achilles-96** [comment]
It is fine with me if you close this for now.

**Pull request closed without merging**
