### PR TITLE
Fix #17656 - Replace/Change/Set table prefix is not working

### LINKED ISSUE #17656: Replace table prefix not working for me
**Describe the bug**

If I try to replace table prefix(es) nothing happens.

**To Reproduce**

1. Select one or more tables
2. Select 'Prefix/Replace table prefix' in 'With selected' dropbox 
3. Fill **from** and **to** fields (example: aaa_, bbb_)
4. Press Continue

Nothing happens.

**Expected behavior**

All the selected tables prefixes' aaa_ shoud be replaced by bbb_

**Server configuration**

- Operating system: Windows 10 (xampp) or Linux (same behavior)
- Web server: Apache
- Database version: 10.4.24-MariaDB or 10.3.28-MariaDB
- PHP version: 7.4.30 or 8.1.5
- phpMyAdmin version: 5.2.0

**Client configuration**

- Browser: Any (tested on Firefox, Chrome, Opera and Edge)
- Operating system: Windows 10

**Additional context**

Used to work in all previous phpMyAdmin versions I've tested.

### PR DESCRIPTION
**Pull request by codegain**
### Description

The browser prevents the bulkActionModal loading other forms directly into its modal-body (f.e. the "Replace table prefix" action) because it itself is placed inside a `form` tag.

Fixes #17656

---

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
This looks good, thank you !
Will test it and then merge it

**Review by williamdes — APPROVED** [review]
This works but breaks the modal for adding to the central list

**Comment by williamdes** [comment]
It's maybe better to move out the modal (https://github.com/phpmyadmin/phpmyadmin/blob/220ed30ef8a2f7ee0dd985d921811e2912b98193/templates/database/structure/check_all_tables.twig#L41-L57) in a new twig file so the other one does not break

**Comment by codegain** [comment]
@williamdes I moved it into a new file `bulk_action_modal.twig` :+1:

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
> @williamdes I moved it into a new file `bulk_action_modal.twig` +1

Works perfectly
Thank you for contributing on this one !

**Pull request merged**
