### PR TITLE
Small fix Code style

### PR DESCRIPTION
**Pull request by rsgrinko**
### Description

Small codestyle fix in examples

### CODE REVIEW

**Comment by williamdes** [comment]
That was not bad, why was it closed ?
@mauriciofauth can we pick this ?

**Comment by mauriciofauth** [comment]
> That was not bad, why was it closed ?
> @mauriciofauth can we pick this ?

Looks like it was closed because the repository or branch was excluded.

**Comment by williamdes** [comment]
> > That was not bad, why was it closed ?
> > @mauriciofauth can we pick this ?
> 
> Looks like it was closed because the repository or branch was excluded.

Sure, but we still can merge and pick this
GitHub stores PRs in a funny way and so you still can merge deleted PRs
I can do it if this looks okay

**Comment by mauriciofauth** [comment]
> Sure, but we still can merge and pick this
> GitHub stores PRs in a funny way and so you still can merge deleted PRs
> I can do it if this looks okay

I approve. You can the [.patch](https://github.com/phpmyadmin/phpmyadmin/pull/17400.patch) or [.diff](https://github.com/phpmyadmin/phpmyadmin/pull/17400.diff) links to get the code.

**Pull request closed without merging**
