### PR TITLE
Fix for #13424 Importing a CSV created tables named Table ##"

### LINKED ISSUE #13424: Don't use spaces in table names in CSV import
Importing a CSV created tables named "Table ##" with ## being a number. Spaces in table names are annoying, could you drop the space or replace it by an underscore?

Even better, have a table name field in the form and default it to the base file name.

### PR DESCRIPTION
**Pull request by amarjitsingh52922**
Signed-off-by: Amarjit Singh <amarjitsingh52922@gmail.com>

### Description
I have added enhancement for Importing CSV to use table name as filename or filename_##  with ## being a number

Fixes #13424

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by OlafvdSpek — COMMENTED** [review]
> and trim to first 10 characters

Why?

**Comment by amarjitsingh52922** [comment]
Basically to avoid cluttering or UI not look bad  if filename length is
more longer.  10 I just choose may be seniors can comment better

**Comment by OlafvdSpek** [comment]
If it was a good name for a file it should be a good name for a table. ;)

**Comment by OlafvdSpek** [comment]
IMO the name should allow underscores (what else is valid / commonly used for names?). Dashes and spaces could be replaced by underscores instead of being stripped.

**Comment by amarjitsingh52922** [comment]
Ok i will make that changes

**Comment by amarjitsingh52922** [comment]
and made to use full name

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
@sudo-bot /deploy PR

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Comment by amarjitsingh52922** [comment]
> Merged, thanks for your contribution!

its my pleasure to work with coders like you

**Pull request merged**
