### PR TITLE
Fixes #11679

### LINKED ISSUE #11679: Cannot export results of some queries
Seen in 4.5.0 to 4.5.2. Test case:
````
CREATE TABLE `product` (
  `product_id` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `product` (`product_id`, `price`) VALUES
(1, 10),
(2, 20);

CREATE TABLE `product_special` (
  `product_id` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `product_special` (`product_id`, `price`) VALUES
(1, 10);

ALTER TABLE `product`
  ADD PRIMARY KEY (`product_id`);

ALTER TABLE `product_special`
  ADD PRIMARY KEY (`product_id`);
````

Run this query:
````
SELECT a.product_id, b.price
 FROM product a, product_special b
 WHERE a.product_id = b.product_id
 LIMIT 1
````

then Query results operations > Export. We don't reach the export dialog.

### PR DESCRIPTION
**Pull request by Achilles-96**
Modification for #11718

Signed-off-by: Raghuram Vadapalli raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by lem9** [comment]
Thanks. Did you read my objection to your other patch, 5 days ago? This patch produces the same error message.

**Comment by Achilles-96** [comment]
@lem9 
Yeah, I read the objection. I changed the patch. Now it doesn't produce same error for me. 
It exports properly. I assume this the command you are testing with:

SELECT a.product_id, b.price
 FROM product a, product_special b
 WHERE a.product_id = b.product_id
 LIMIT 1

**Comment by lem9** [comment]
@Achilles-96 I tested this PR (#11738) and I get the same error when I want to export in CSV. I am testing with the scenario explained in #11679.

**Comment by Achilles-96** [comment]
@lem9 
I followed the same scenario as in #11679. It is not rising any errors. Anyway, I'll confirm it once more.

**Comment by lem9** [comment]
@Achilles-96 I mean this: With your fix I can reach the export dialog but I still cannot export the results. Let's say I choose CSV:
````
MySQL said: #1052 - Column 'product_id' in field list is ambiguous
````

**Comment by Achilles-96** [comment]
@lem9 
I read that in my old PR. In my old PR, I changed only `libraries/tbl_common.inc.php` due to which we were able to go to export dialog. But the problem due to aliases is in `tbl_export.php`. I modified that file in this PR which resolved that MySQL error.

**Comment by lem9** [comment]
@Achilles-96 I told you that in this PR (#11738) I still have the problem (MySQL error).

**Comment by Achilles-96** [comment]
@lem9 I confirmed with one more person. This PR #11738 doesn't rise MySQL error for scenario in #11679 . Please recheck.

**Comment by devenbansod** [comment]
Hi Marc, I tried to test this PR as Raghuram told me to and I am not able to reproduce the MySql error you noted.
The export goes through as expected for me!

**Comment by lem9** [comment]
I rechecked and I can no longer reproduce the problem. It remains to be verified the full impact of the code removal in this PR.

**Comment by lem9** [comment]
By the way, if you remove the code section that populates $aliases, there is another code section below which uses $aliases, that should be removed too. I'm still unsure of the goal of aliases removal in the original code.

**Comment by Achilles-96** [comment]
Actually aliases are removed and are not replaced. The reason given in the comment is that alias will replaced. But ultimately they are not being replaced. So, I tried not removing them in first place and everything seemed to work fine. 
I didn't remove lower code section because I just wanted to make sure this didn't cause any malfunctioning and in that case I can update PR.

**Comment by lem9** [comment]
"Everything seemed to work fine" until we find a test case that does not work fine. I'll ask the author of this code about it.

**Comment by Achilles-96** [comment]
Actually there is no need to remove any code. I found bug in parser. I'll update PR.

**Comment by lem9** [comment]
Standing by. Please reply on my message on the developers mailing list.

**Comment by lem9** [comment]
Nice work, this looks fine.

**Pull request merged**
