### PR TITLE
Group/Ungroup queries in console SQL debug

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by lem9** [comment]
Nicely done! Very clear code.

**Comment by nisargjhaveri** [comment]
Thanks :)

Now I'll work on sorting queries according to time taken, order of execution, count, etc. Anything else?

**Comment by lem9** [comment]
Showing the percentage of time taken.

**Comment by nisargjhaveri** [comment]
Yes. About that, what should I show for grouped queries. For queries belonging to a group, the percentage should be shown with respect to total time or with respect to the group?

**Comment by lem9** [comment]
I believe that what most helps is the percentage of this group with respect to total time.

**Pull request merged**
