### PR TITLE
refactor: Security Key Example

### PR DESCRIPTION
**Pull request by LucaTanks**
### Description

I have added Yubikey's as an example for security key 2FA, as there are examples for App Authentication

### CODE REVIEW

**Comment by LucaTanks** [comment]
I'll sign off later on, sorry about that. Didn't realise I would have to for something as minor as that

**Review by williamdes — APPROVED** [review]

**Comment by mauriciofauth** [comment]
> I'll sign off later on, sorry about that. Didn't realise I would have to for something as minor as that

Adding a comment here with the sign-off-by line is enough.

**Review by MauricioFauth — APPROVED** [review]

**Comment by LucaTanks** [comment]
Signed-off by LucaTanks <luca@lucatanks.xyz>

**Comment by LucaTanks** [comment]
Hi, are you able to follow up and add the `hacktoberfest-accepted` label?

**Pull request merged**
