### PR TITLE
Fix issue #11500

### LINKED ISSUE #11500: Error when creating new user on MariaDB 10.0.21
Hello,

When trying to create a new user (User accounts -> Add user account) I get the following errors

```
#1065 - Query was empty
```

and then

```
The selected user was not found in the privilege table.
```

Running the following query generated my phpmyadmin

```
CREATE USER 'test_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '***';GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
```

gets the following error

```
Error
Static analysis:

1 errors were found during analysis.

Unrecognized statement type. (near "WITH" at position 47)
SQL query:

CREATE USER 'test_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '***'

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY '***'' at line 1
```

If I remove *WITH mysql_native_password* from the query, they query is executed fine.

Versions: CentOS release 6.7 (Final)
Apache: Apache/2.2.15
PHP: PHP 5.5.29
PHP extension: mysqli
Database: 10.0.21-MariaDB-log MariaDB Server
Database client version: libmysql

### PR DESCRIPTION
**Pull request by devenbansod**
Tries to fix #11500 

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Nice fix Deven.

**Comment by lem9** [comment]
See 62a4e61a65971ebc10ce4989cb54f5ce455f0878.

**Comment by propertunist** [comment]
how do i manually integrate this fix into my install here? thanks

**Comment by lem9** [comment]
@propertunist if you know how to use the patch utility, here is the patch: https://github.com/phpmyadmin/phpmyadmin/commit/9bf88cbd32f5f5b4a18bd7ec60e89c5b75bcf947.patch

**Comment by propertunist** [comment]
@lem9 thanks for the link. i'm having difficulty locating an explanation of the patch utility online. i have never used it before - is there a recommended link / guide for it?

**Comment by lem9** [comment]
https://en.wikipedia.org/wiki/Patch_(Unix)

**Comment by propertunist** [comment]
@lem9 oh ok, i thought you were referring to a phpmyadmin specific tool. i ran patch and got a message back in the terminal saying that the changed file could not be found. am i right in thinking that i need to download the whole package and compile it, then reinstall it (rather than just making a simple update to an existing file in my live installation)?

**Comment by lem9** [comment]
You can download the patch (see reference above), save it to a file (say, a.patch) then type
````
patch < a.patch
````

**Comment by propertunist** [comment]
@lem9 that is what i did, yes. i thought that the file to be changed was not in my local file structure.. but i just found it. i ran the patch and tested the change by adding a new user in phpmyadmin.. all went well - thanks :)

**Comment by nigelterry** [comment]
@lem9 Thanks!  Worked for me.

I thought I was going insane. Not the first time I created a user. :-)

**Pull request merged**
