### PR TITLE
Fixed: Change password is not showing password Strength difference at…

### PR DESCRIPTION
**Pull request by akkywadhwa**
… the second attempt. #14948

Signed-off-by: Hritik Wadhwa <akkywadhwa@gmail.com>

### Description

Please describe your pull request.

Fixes #14964 

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by akkywadhwa** [comment]
@williamdes waiting for you to see this :)

**Comment by williamdes** [comment]
@sudo-bot Deploy pr plz

**Comment by williamdes** [comment]
@akkywadhwa Can you fix the Javascript error that occurs when typing the password
Have a look to the deployed pull-request please :)

**Review by williamdes — APPROVED** [review]
Works as expected, thank you @akkywadhwa !

**Comment by williamdes** [comment]
Merged, thank you @akkywadhwa :)

**Pull request closed without merging**
