### PR TITLE
Fix #11752

### LINKED ISSUE #11752: 4.5.2 breaks MySQL Master Master Cluster
I have updated phpmyadmin from 4.2.12 to 4.5.2.

I have configured a MySQL Master Master Replication and I can login on both nodes from phpmyadmin, here is the phpmyadmin config:
/* Servers configuration */
$i = 0;

/* Server: hostname1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname1';
$cfg['Servers'][$i]['host'] = '1.1.1.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* Server: hostname2 [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname2';
$cfg['Servers'][$i]['host'] = '2.2.2.2';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'somelongstring';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['VersionCheck'] = '0';
$cfg['DisplayServersList'] = 'true';
$cfg['VersionCheckProxyUrl'] = 'http://proxy.domain:8080'

After the update, my SLAVE on hostname2 breaks with the following errors:

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`db`(`host`, `Db`, `User`) VALUES("pma_test_host", "mysql", "pma_test_user")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`columns_priv`(`host`, `Db`, `User`, `Table_name`, `Column_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user-' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`tables_priv`(`host`, `Db`, `User`, `Table_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--PROCEDURE' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`procs_priv`(`host`, `Db`, `User`, `Routine_name`, `Routine_type`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "PROCEDURE")'

The "mysql" database is not replicated over the cluster. 
replicate-ignore-db = mysql 
replicate-ignore-db = information_schema
replicate-ignore-db = performance_schema

I dont have configured the pma control user as I dont use the pma configuration storage.

It seems like pma is doing some permissions checks after I log in with my account which seems to break my master master replication.

### PR DESCRIPTION
**Pull request by devenbansod**
Move to analysing the grant strings to perform checks for privileges instead of running all the test queries on mysql db.

@nijel : could you please take a look/test this once if you get time ? I am not exactly sure if I have covered all the cases in checking for the user having required privileges.

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by nijel** [comment]
I'll look at it next week. However I'm not sure if this is good fit for QA_4_5 as the change is quite intrusive. Maybe @lem9 can comment on this as well...

**Comment by lem9** [comment]
It's a big patch but it contains mostly code removal, so I would be confident for QA_4_5.

**Comment by zaverichintan** [comment]
@devenbansod
 how much efficient is this change? 
Will it affect the security part of pma?

**Comment by devenbansod** [comment]
Hi @zaverichintan : this is slightly efficient as we are running only one query `SHOW GRANTS` now and actually a better way too, to check for the required privileges. 
Previously, we would run test queries once the user logged in, and if those queries were successful, we would assume that user has the required privileges. 
This patch would change that and we would now follow a procedure similar to `PMA_analyseShowGrant()` to determine the privileges.

Also, I don't see any changes to the security in phpMyAdmin due to this patch.
And no, this does not fix the issue #11834.

I hope I answered all your queries.

**Comment by zaverichintan** [comment]
@devenbansod  Thank you for your response. 
What if someone fixes issue #11834 and then this fix #11752 is merged, the issue will again rise. Try to some that if possible. 
Its very efficient way of checking.

**Comment by nijel** [comment]
@zaverichintan I don't think these are related. In #11834 it seems that the SQL we use for adjusting privileges is generated wrong, this code is about detecting whether we can adjust privileges (so in case it would be wrong, it would not work at all, not just in single case).

**Comment by nijel** [comment]
I did some testing and this seems to work fine. However with current complexity, I think the ``PMA_analyseShowGrant`` really deserves separate testcase whether it works as expected...

**Comment by devenbansod** [comment]
@nijel : I was also thinking on re-factoring some code of `PMA_analyseGrant()` and adding some tests.
But do you think the tests and the refactoring should be targetted to QA_4_5 or to master in a separate PR ?

**Comment by nijel** [comment]
Refactoring should definitely go to the master and it indeed makes sense to add tests with it. I'll merge this and let's target refactoring and tests to master...

**Pull request merged**
