### PR TITLE
Add list of supported browsers

### PR DESCRIPTION
**Pull request by MauricioFauth**
Uses [Browserslist](https://github.com/browserslist/browserslist) format.

Same list used by [Bootstrap v4.4](https://getbootstrap.com/docs/4.4/getting-started/browsers-devices/).

> Bootstrap supports the latest, stable releases of all major browsers and platforms. On Windows, we support Internet Explorer 10-11 / Microsoft Edge.

### CODE REVIEW

**Comment by williamdes** [comment]
Should we add a plugin like https://github.com/amilajack/eslint-plugin-compat to make sure the JS code respects this file ?

**Comment by williamdes** [comment]
A lot of plugins seem interesting on https://github.com/browserslist/browserslist#browserslist-

I am not sure how our scss compiler would adapt to add prefixes

**Review by williamdes — APPROVED** [review]
:100:

**Review by ibennetch — APPROVED** [review]

**Comment by williamdes** [comment]
https://docs.phpmyadmin.net/en/latest/faq.html#with-mozilla-0-9-to-1-0-and-netscape-7-0-pr1-i-can-t-type-a-whitespace-in-the-sql-query-edit-area-the-page-scrolls-down
https://docs.phpmyadmin.net/en/latest/faq.html#mac-os-x-safari-browser-changes-special-characters-to

@ibennetch Should we remove all the Netscape FAQs ?

**Pull request merged**
