### PR TITLE
Remove leading underscores on protected fields.

### PR DESCRIPTION
**Pull request by Tithugues**
Rename fields with pMA standards.

### CODE REVIEW

**Comment by D-storm** [comment]
I am not sure whether we should remove leading underscores from protected fields as they are good indicators that field is not public and a standard naming convention.

**Comment by Tithugues** [comment]
Le ven. 7 août 2015 à 19:28, Chirayu Chiripal <notifications@github.com> a
écrit :

I am not sure whether we should remove leading underscores from protected
fields as they are good indicators that field is not public and a standard
naming convention.

—
Reply to this email directly or view it on
<https://github.com/phpmyadmin/phpmyadmin/pull/11365#issuecomment-128772813>
GitHub
<https://github.com/phpmyadmin/phpmyadmin/pull/11365#issuecomment-128772813>.


Hi,

I agree with this and would like to talk about this. I didn't do it because
I agree with this, but because this is one of pMA standards.

For me too, everything not-public should be prefixed with an underscore.

Can we review our position regarding this standard?

H.

**Comment by Tithugues** [comment]
That's strange, I don't have this error running Travis on my repository: https://travis-ci.org/Tithugues/phpmyadmin/builds/74488023

**Comment by Tithugues** [comment]
This PR is closed. I'll see this modifications later when trying to use PSR rules.

**Pull request closed without merging**
