### PR TITLE
Fixed bug: - Redirect to table structure page on creation of new table

### PR DESCRIPTION
**Pull request by djprawns**
Signed-off-by: Pranav Sharma vanarpsharma@gmail.com

### CODE REVIEW

**Comment by ibennetch** [comment]
Could you add an entry to the file ChangeLog for this fix?

I haven't had a chance to review the rest of this.

**Comment by vanarpsharma** [comment]
how do i do that?

**Comment by ibennetch** [comment]
Actually, in this case it's better not to add a ChangeLog entry due to there being many pull requests that will cause merge conflicts. So just ignore what I said.

If you were to do so, however, you'd want to edit the file ChangeLog in the root of the phpMyAdmin folder and follow the same format used there. But don't do that now :)

**Comment by vanarpsharma** [comment]
ok cool :)

**Comment by lem9** [comment]
Nice work.

**Comment by vanarpsharma** [comment]
Thanks @lem9 !

**Pull request merged**
