### PR TITLE
New designer menu

### PR DESCRIPTION
**Pull request by gzzhanghao**
Moved from #1483

### CODE REVIEW

**Comment by lem9** [comment]
This is better, but did you test all of the Designer features? I tried deleting a relation by clicking on the ending part (round) of the arrow and nothing happens. The arrow is supposed to turn red and I should be seeing a "Delete relation" confirmation dialog. I am testing with the employees sample database.

**Comment by gzzhanghao** [comment]
@lem9 Yeah you are right, I didn't even know there are such a feature. I'll fix it and check if I'd missed anything else.

**Comment by lem9** [comment]
@gzzhanghao Your ignorance of such feature made me realize that we should probably advertise it via the menu.

**Comment by lem9** [comment]
@gzzhanghao I confirm your fix for the delete relation feature. Now could you take care of the trailing whitespace then rebase to produce just one commit? It would help us to review your patch.

**Comment by gzzhanghao** [comment]
@lem9 Alright, committed.

**Comment by gzzhanghao** [comment]
@lem9 I think it's better to check click on lines but not on the small circle. But it's likely to be much more difficult.

**Comment by lem9** [comment]
@gzzhanghao After getting a second opinion from a developer, here is more feedback. Unless the user has a huge screen, the new side-menu eats a lot of the available space. We find ourselves always in the need of toggling the text in to see the descriptions, then out to see the working space. A solution would be to auto-expand the menu on hover and shrink it otherwise. What are your thoughts about this?

**Comment by gzzhanghao** [comment]
@lem9 That's a good idea, but we can't follow the $cfg['TabsMode'] then.

**Comment by lem9** [comment]
Excellent! Could you produce just one commit that includes the whole patch, not forgetting to sign it, and I'll merge for the upcoming 4.4 release.

**Comment by gzzhanghao** [comment]
@lem9 Sure, nice to hear that :-)

**Comment by lem9** [comment]
Nice job.

**Pull request merged**
