### PR TITLE
Improve README.rst to make it easier for new contributors getting involved

### PR DESCRIPTION
**Pull request by anp-tech**
### Description

I improved the README.rst by adding more introductory information to make it easier for new contributors getting involved. I have modified and included additional links for list of requirements, installation instructions, support, contributions, code of conduct, and sponsor to the original version.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Good suggestion !
@anp-tech do you thing you could help me with #15942 ?

**Comment by ibennetch** [comment]
anp-tech and I were just emailing about this, so I'm glad to see the pull request.

I have a few suggestions about reordering some of the items and maybe changing some things, which I'll comment on or submit another commit, but I'm pleased with the effort and think this will be a helpful improvement.

**Comment by anp-tech** [comment]
@williamdes Thank you! I will help when time permits.

**Comment by anp-tech** [comment]
> 
> 
> anp-tech and I were just emailing about this, so I'm glad to see the pull request.
> 
> I have a few suggestions about reordering some of the items and maybe changing some things, which I'll comment on or submit another commit, but I'm pleased with the effort and think this will be a helpful improvement.

@ibennetch Thank you! Your comments and suggestions will be appreciated.

**Pull request closed without merging**
