### PR TITLE
Fix #11896 Remove hard dependency on phpseclib

### LINKED ISSUE #11896: Remove hard dependency on phpseclib
Please remove the hard dependency on phpseclib again. Before (4.0.10.13), 4.4.15.3 and 4.5.4 it was possible to use phpMyAdmin without phpseclib as long as php-openssl was available (since at least 4.3.0). This has been changed in order to fix some security flaws, however without making phpseclib conditionally, see also #11892 and #11891.

### PR DESCRIPTION
**Pull request by madhuracj**
Signed-off-by: Madhura Jayaratne madhura.cj@gmail.com

### CODE REVIEW

**Comment by madhuracj** [comment]
I skipped the version checks suggested in https://github.com/phpmyadmin/phpmyadmin/issues/11896#issuecomment-176244475 since PHP 5.3.7 is the minimum version for 4.4.x branch.

**Comment by ibennetch** [comment]
That makes sense

**Comment by nijel** [comment]
I think you should also pass true as second parameter to openssl_random_pseudo_bytes. Same for #11899.

**Comment by madhuracj** [comment]
Looks to me like it's a variable filled in by the function to specify whether the generated random value is cryptographically strong rather than to direct the function to generate a cryptographically strong one.

**Comment by madhuracj** [comment]
Yes, didn't see your edit in time.

**Pull request merged**
