### PR TITLE
Feature Request:#1608 Allowing signed/unsigned attribute central column

### PR DESCRIPTION
**Pull request by rakeshkumar4294**
The 'attribute' and 'extra' is stored in col_extra column in json_encoded form.During fetching of columns if col_extra is a json string then it is decoded and resulting array is stored in same variable as col_extra and col_attribute.Similarly it is done in javascript.
But If col_extra is not a json string (to make compatible with old column values) then simply col_attribute is assigned null string and remaining are done in similar way.
Signed-off-by: Rakesh Kumar rakeshkumar4294@gmail.com

### CODE REVIEW

**Comment by smita786** [comment]
Hey
It looks good. Working fine for me. Can you squash these three commits in one. Check this tutorial on squashing commits https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ .

**Comment by rakeshkaundilya** [comment]
Thanks.

**Comment by smita786** [comment]
Hey,
One last thing to do, can you try to fix the issues scrutinizer is complaing for coding standards. Here the list of coding standards violations introduced with your patch: https://scrutinizer-ci.com/g/phpmyadmin/phpmyadmin/inspections/27780b66-cb46-48b8-aa07-e22e3db5611e/issues/?status=new&selectedAuthors%5B0%5D=rakeshkumar4294%40gmail.com&orderField=path&order=asc .
Click on each of the file name and see the suggestions to fix them.
Thanks.

**Comment by rakeshkaundilya** [comment]
I am sorry. I messed up something

**Pull request closed without merging**
