### PR TITLE
Remove unnecessary comment

### LINKED ISSUE #15095: Wrong format of comments
### Describe the bug

There is the wrong format used to comment inside a PHP file.

### To Reproduce

1. Go to `phpmyadmin\libraries\error.inc.php`
2. Scroll down to `line 30` inside the CSS block

### Expected behavior

To comment down, should use `//` or `/* ... */`

### Server configuration

- Operating system: Windows 10(1809)
- Web server: WAMP 
- PHP version: 7.2.10
### Client configuration

- Browser: Chrome
- Operating system: Windows

### PR DESCRIPTION
**Pull request by AghaSaad04**
Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>

### Description
I have removed the wrong syntax of comment.

Fixes #15095 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.

### CODE REVIEW

**Comment by apoorvkhare07** [comment]
@williamdes we should be making Pull requests to QA_4_8 or master ?

**Comment by williamdes** [comment]
@apoorvkhare07 Bug fixes to QA_4_8 and non bug fixes or enhancements to master

**Comment by ibennetch** [comment]
Wow, this is some old code — it looks like the it was added with commit 77172fab57e in 2001 !

I wonder why this was commented in the first place and have the idea that perhaps it was to hide it from browsers that didn't deal with CSS. We do (or used to do, anyway) that with JavaScript, of course, but my memory of CSS from 17 years ago is fading. It occurs to me that perhaps the best fix may be to remove the comments entirely, rather than converting these to CSS comments. I can't think of why the intention would be to comment this out.

**Comment by AghaSaad04** [comment]
Okay, I am going to completely remove that part of the code @ibennetch.

**Comment by mauriciofauth** [comment]
Isaac is right, this comment lines are to hide the CSS from old browsers that didn't deal with CSS. The fix is to remove only these lines and not all the CSS.

**Comment by mauriciofauth** [comment]
@williamdes I think #15108 was the proper fix, because this PR removed the CSS.

Before:
Before

After:
After

**Comment by AghaSaad04** [comment]
Yeah Sir @mauriciofauth, I was thinking that too.

**Comment by williamdes** [comment]
@mauriciofauth @AghaSaad04 Fixed by 10cd180
Thank you for reporting this error :)

**Pull request merged**
