### PR TITLE
Update DatabaseInterface.php

### PR DESCRIPTION
**Pull request by jasgripen**
ignore errors if variable lc_messages is not supported by the server

Signed-off-by: Andreas Grip <andreas@wk.se>

### CODE REVIEW

**Comment by nijel** [comment]
Do you get error here in other case than when running on unsupported MySQL server? Current phpMyAdmin releases require MySQL 5.5 or newer....

**Comment by jasgripen** [comment]
I realize I run an unsupported version of MySQL, but so far this is the only thing I found that is not working.

And I must argue that not catching errors so the software crashes are always bad and since this is a non important function it's better to ignore any error and let the software continue. This function is not even run for all languages because MySQL do not support all languages that phpMyAdmin supports.

**Comment by nijel** [comment]
Sorry, but silently ignoring errors is usually not a good idea. You will never know that this code is broken once you start to ignore errors. I really prefer to let user know that something is wrong than ignoring failure silently.

**Comment by kvtb** [comment]
`lc_messages` is read-only in TiDB since recently (https://github.com/pingcap/tidb/pull/33708)
So it is the issue again

**Comment by ibennetch** [comment]
As presented, this pull request wasn't found to be a good solution, so it's better to open an issue than to try to get this old pull request merged (you could reference it for some developer to use as a starting point, though). 

However, TiDB claims to be MySQL compatible, so it seems like the problem is on their end, not ours. We don't claim to be compatible with TiDB since we don't have the resources to test against their systems, but the phpMyAdmin behavior with `lc_messages` is compatible with MySQL.

**Comment by kvtb** [comment]
Read only `lc_messages` is the only incompatibility

**Pull request closed without merging**
