### PR TITLE
QA Fix gis extent calculation

### PR DESCRIPTION
**Pull request by MoonE**
https://github.com/phpmyadmin/phpmyadmin/pull/18100#issuecomment-1449019663

### CODE REVIEW

**Comment by kamil-tekiela** [comment]
Wouldn't it be easier to just merge down my PR?

**Comment by williamdes** [comment]
> Wouldn't it be easier to just merge down my PR?

What is merging down?
I never heard of that

**Review by williamdes — APPROVED** [review]
Thank you!
Is there no way to have a more minimal diff?

**Comment by MoonE** [comment]
I'm looking into it. Though the diff would certainly be  the diff bigger.

**Comment by MoonE** [comment]
Now the diff is quite a bit smaller. If you are comfortable with it the `isset($min_max['min...'])` checks in Geometry::scaleRowData and GeometryCollection::scaleRowData can also be removed. (See the added lines in phpstan-baseline.neon):

https://github.com/phpmyadmin/phpmyadmin/pull/18179/files#diff-307e5a412ebf2cecc30f4381f50c21b22933a4f19de2dd00696cb3f8e5e26762R170-R183
https://github.com/phpmyadmin/phpmyadmin/pull/18179/files#diff-f3cf8327bebadf3c1ea977a4d68309b09085cc9436ba76b16d7dc9c03754eaffR82-R97

**Comment by williamdes** [comment]
> I mean merge my PR into 5.2 branch.

It's not possible since it's based onto master :/
I would have needed to be down based to QA_5_2 before merge

**Review by williamdes — APPROVED** [review]
Awesome 💯

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
