### PR TITLE
Improved localization.

### PR DESCRIPTION
**Pull request by udan11**
Improved localization.
Updated the sql-parser library to udan11/sql-parser@e5fc868.

I didn't get to test it. I will tomorrow.

I had to refactor the code a little bit to be able to use user's preferences (language selection).

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by udan11** [comment]
Tested. Works fine after `*.po` and `*.mo` files are updated.

**Comment by udan11** [comment]
It didn't find the messages because they weren't constants, but stored in variables. Now, I modified the library to use the `__` function. I tried to make the library independent from the `__` function, but it resulted a mess. The new approach is better.

**Comment by lem9** [comment]
Please squash so I can have a better look.

**Comment by lem9** [comment]
Dan,
when I merge your branch to the current master branch and I try it, I have a problem. Let's say I type
````
SLECT
````
in the SQL query form. The hint on the red X says
````
Unexpected beginning of statement. (near %s)
````
So parameter subtitution does not happen.

**Comment by lem9** [comment]
Nice job.

**Pull request merged**
