### PR TITLE
Feature Request: - Export Progress Bar

### PR DESCRIPTION
**Pull request by djprawns**
Made changes to progress_sess.php to have string keys instead of constant values.

Export progress is now a 10 part process if rows exceed by 20. Also the export progress process goes from the server level down to the row level.
Progress Bar is also animated.
Currently with these changes, my php error log shows no errors.

Signed-off-by: Pranav Sharma vanarpsharma@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Tested in Chrome 42 (Linux)
````
[Sun Apr 19 08:11:59 2015] [error] [client ::1] PHP Notice:  Undefined index: export_progress in progress_sess.php on line 5
[Sun Apr 19 08:11:59 2015] [error] [client ::1] PHP Notice:  Undefined index: percentage in progress_sess.php on line 6
````

**Comment by vanarpsharma** [comment]
Marc,
Could you replace lines 5 - 10 with this: - 
if(isset($_SESSION['export_progress']))
{
$result = $_SESSION['export_progress'];
}
else
{
$result = '';
}
if(isset($_SESSION['percentage']))
{
$percentage = $_SESSION['percentage'];
}
else
{
$percentage = '';
}
and comment if any error. 
Pardon any inconvenience, I dont see any other way to debug since I am not getting any errors on my system. Also my progress bar is working properly.

**Comment by vanarpsharma** [comment]
Also, maybe you could try adding session_write_close(); as the last statement in progress_sess.php to see any errors vanish.

**Comment by lem9** [comment]
I tested bce99300db5b34991e3e300bef5ac843a1fbb0a1 with Chrome 42 (Win 7). Things are better: the bar is progressing (but I'll have to retest on Linux). The only problem now can be seen in the error log, which shows notices (maybe your PHP is not set to show notices). When I export I get 16 lines of:
````
 PHP Notice:  A session had already been started - ignoring session_start() in progress_sess.php on line 4
````

**Comment by lem9** [comment]
Closed until further feedback.

**Comment by vanarpsharma** [comment]
I have set my error_reporting to On in php.ini.
Also turned on notices.
Still not getting anything. Very odd. Let me dig deeper.

**Comment by vanarpsharma** [comment]
Marc, how is it behaving on Linux?

**Comment by vanarpsharma** [comment]
Hey Marc, could you reopen this pull, I needed to make some changes.
Or you can make yourself by replacing lines 3-4 with: -
if(!isset($_SESSION))
{
session_id($_COOKIE['phpMyAdmin']);
session_start();
}
Maybe the errors go away.

**Comment by lem9** [comment]
Done.

**Comment by lem9** [comment]
I'll be able to retest on Linux in a few hours.

**Comment by vanarpsharma** [comment]
ok Marc, please test a65a9a6

**Comment by lem9** [comment]
The PHP notices about the session are fixed, thanks. Could you squash your commits?

**Comment by vanarpsharma** [comment]
Marc, could you guide me how I could do that. These commits I have made through this interface and not command line.

**Comment by lem9** [comment]
OK, I'll do the squash.

**Comment by lem9** [comment]
I am working on the unit tests failures but haven't found a solution yet.

**Comment by lem9** [comment]
By the way, I'm not sure that progress_sess.php is safe. Maybe it can be manipulated to generate XSS.

**Comment by vanarpsharma** [comment]
Okay, Marc In that case, I will have to research a little about XSS and add appropriate changes. Do we need the safeguards immediately? Or is this acceptable for merging?

**Comment by lem9** [comment]
We won't merge code that might be prone to an attack.

**Comment by vanarpsharma** [comment]
So I have done some initial search, will using echo htmlspecialchars(json_encode($arr), ENT_QUOTES, 'UTF-8');
stop the XSS attack?

**Comment by vanarpsharma** [comment]
I have just tested, I dont think that will work. I will have to research and then make appropriate changes. If you could give me a case how XSS could be done, I would get some direction.

**Comment by lem9** [comment]
Instead of looking how XSS could be done, can you use our usual token protection? This is done by including libraries/common.inc.php, which verifies that the valid token is part of the request. Then all calls to progress_sess.php would need the token as a parameter. With Firefox + Firebug, you can see the token that is passed, for example when entering export.php.

**Comment by vanarpsharma** [comment]
Hey Marc, I am able to pass the token as parameter to progress_sess.php. and have included libraries/common.inc.php in progress_sess.php. However it seems including it renders the response as entire html page response. I have looked at the documentation, and figured out that I can get the response using 
$response = PMA_Response::getInstance();
$response->addJSON('message', $message);
I use it but still get the same html page as response. What am i doing wrong?

**Comment by lem9** [comment]
Maybe this would help:
http://wiki.phpmyadmin.net/pma/Generating_pages_and_ajax_responses_in_pma4#Bypassing_the_framework

**Comment by vanarpsharma** [comment]
Hey @lem9 ,
Made appropriate changes. Token protection is being used as common.inc.php is included. Also standard pma response for ajax request is being used.
Wouldn't have been possible without your valuable guidance.
Thankyou :)

**Comment by lem9** [comment]
With 2352621c2826c048937315bbc62044c60efae40d the progress bar stops at about half the distance, while my export has completed normally. I got the same results twice when exporting a table that produces a 14 MB file.

**Comment by vanarpsharma** [comment]
@lem9 ,
On my system, the only time this happens is when cancel the file location system popup. Otherwise it works fine. I have also tested this multiple times using the employees db and its tables.
Maybe I could use some db or table you are using? and test on my system. I can put it in my system through the mysql terminal.

**Comment by lem9** [comment]
I am testing the employees MySQL sample database.

**Comment by vanarpsharma** [comment]
As in you are going to test, or the problem has occurred using the MySQL employees database?

**Comment by lem9** [comment]
The problem happens with employees.dept_emp.

**Comment by vanarpsharma** [comment]
Hey @lem9 ,
Hopefully all should go well now.

**Comment by lem9** [comment]
@vanarpsharma I tested c1f45705b2fe61290744b4ebe382349b71c72460. Now the progress bar reaches approximately half the distance, but I know that the export is almost complete. When the export has completed, the bar reaches the right end and the "Done" message is displayed, but the bar does not reflect the true progression. It's more evident when exporting employees.salaries.

**Comment by vanarpsharma** [comment]
Hey @lem9 ,
Give me some time, working on it.

**Comment by vanarpsharma** [comment]
@lem9 ,
The reason why we are not getting true progression is not because of exactly a bug but rather the fact that sometimes, the client misses getting one of the session values since the php script has already executed one of the previous sess_messages. So instead of 10 requests we get nine. and some of the percentage is lost. So one request fetches the 8th table request and the second fetches the 10th, missing the 10th.
So the strategy that I am now thinking for this problem is to append data to the session variable instead of overwriting it.
In the client, I could determine what I have already shown in the progress bar and only show the new stuff from the session variables. This shall fix the issue of the "true progression", since some data is being lost.
So I guess my question is, is what I have just discussed an acceptable solution. One of the features of this solution is that it does not have that much net overhead. I am trying to make minimum requests while trying to achieve a satisfactory level of progression. What the solution does guarantee is that the last messages will be pretty near the 100% mark, which I think is still in happening most of the cases. It is not precisely accurate right now, but almost. The modified solution discussed will take some time to implement; If you ok it, I shall proceed. Please let me know what other requirements you would like?

**Comment by lem9** [comment]
Pranav,
when you mention "it's not precisely accurate right now, but almost" does not correspond to what I see: a progression to about the center of the bar, then a last chunk that completes the bar.

**Comment by lem9** [comment]
Closing for now.

**Pull request closed without merging**
