### PR TITLE
Solution for ".noSelect is not a function #11864"

### PR DESCRIPTION
**Pull request by zenineasa**
I think I just came up with a solution for ".noSelect is not a function #11864". Just move the function named .noSelect from function.js to makegrid.js.

### CODE REVIEW

**Comment by lem9** [comment]
@zenineasa You did not come up with this solution, I was the one to suggest it in the issue's comments.

**Comment by zenineasa** [comment]
@lem9 Yes, I agree with you. I agree with your DCO too. Where and in what name should the file containing the certificate be added?

**Comment by lem9** [comment]
@zenineasa There is no file involved, you just have to follow the advice given above and use the Signed-Off-By tag when you do your commit. So please redo your commit (just one commit is needed) and sign it. See http://stackoverflow.com/questions/13457203/how-to-add-the-signed-off-by-field-in-the-git-patch for an example.

**Comment by zenineasa** [comment]
@lem9 Do I have to make a fresh fork and pull request in order to do this?

**Comment by lem9** [comment]
@zenineasa Make a new branch and pull request. Anyway it's better to name your branch according to the fix you are doing, see http://wiki.phpmyadmin.net/pma/Git#Working_on_new_features.

**Pull request closed without merging**
