### PR TITLE
Fix #17793 UUID - Fix insert error for 5.3

### LINKED ISSUE #17793: Inserting a row with UUID should insert the user value when not empty
By default, when inserting a row, the uuid type column has UUID as function set by default. I think it should be empty, because when the column is set to NULL, it still inserts a uuid, instead of NULL.

The same case applies when a user enters his own UUID, it will still insert the one generated by MariaDB and not what user has entered.

What can be done, is to have UUID (uuid() function) added to the Default select (if MariaDB and column is uuid), like it is with CURRENT_TIMESTAMP.

https://user-images.githubusercontent.com/25424343/195730197-5f711440-2ed0-4e2a-af7d-a0a16531db80.mp4

### PR DESCRIPTION
**Pull request by sureemo**
### Description

Same fix as commits based on `QA_5_2` branch
- Fix issue - null is not selected for uuid field with nullable setting
- Fix issue - default select option not select `UUID` when alter column 

But add new commit (required change on `master` because effected code not existed in `QA_5_2`)
- Fix issue - insert error

Related PR: https://github.com/phpmyadmin/phpmyadmin/pull/17860
Reference issue: https://github.com/phpmyadmin/phpmyadmin/issues/17793

Signed-off-by: Mo Sureerat <sureemo@gmail.com>

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you!

**Comment by liviuconcioiu** [comment]
Thank you @sureemo! Is perfect! @williamdes I've tested the code and it fixes all the issues.

**Comment by williamdes** [comment]
Then is #17860 ready for review and merge ?

**Comment by liviuconcioiu** [comment]
> Then is #17860 ready for review and merge ?

Yes. Tested that too and it works! Everything is fixed.

**Comment by sureemo** [comment]
> > Then is #17860 ready for review and merge ?
> 
> Yes. Tested that too and it works! Everything is fixed.

@liviuconcioiu Thank you for help verify and feedback.

**Comment by williamdes** [comment]
This is what got merged into 5.3 after 5.2 got merged into 5.3: c00a90482717764334bcccb47e91da3e85a463e3

**Comment by williamdes** [comment]
Seems like you have pushed a merge of master into your branch (I prefer a rebase ;))
And I was about to push the merge, so this pull-request will be marked as closed but is merged for sure ;)

**Pull request closed without merging**
