### PR TITLE
Fix #15905 : Removed empty space after charsets table 

### LINKED ISSUE #15905: Bad UI: Empty space after charsets table
### Describe the bug

There is an empty space after the charsets table.

### To Reproduce

1. Go to 'top navigations'
2. Click on 'charset'
3. See empty space after the charset table 

### Screenshots
charset)

### Expected behavior

charset1

### Client configuration

- Browser: chrome and Microsoft edge
- Operating system: Windows 10

### Additional context

I will be working on this issue.

### PR DESCRIPTION
**Pull request by anirudhsingh20**
### Description

There is empty space after the charsets table.

Fixes #15905

Removed empty space after charsets table 
charset1

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@anirudhsingh20 I would recommend you to install GitKraken so you can view the history
I am afraid you did have to do complicated manipulations between PRs
`git remote add phpmyadmin https://git@github.com/phpmyadmin/phpmyadmin.git` will be useful

**Comment by anirudhsingh20** [comment]
Installed, thanks

**Comment by williamdes** [comment]
@anirudhsingh20 can you rebase onto latest commit of phpmyadmin master branch and then squash all your commits using the reset soft feature?

**Comment by anirudhsingh20** [comment]
okay, sure. @williamdes can you please tell me how can I understand complete codebase? and any suggestions?

**Comment by williamdes** [comment]
> okay, sure. @williamdes can you please tell me how can I understand complete codebase? and any suggestions?

So I think it is not possible to now the full codebase, only time trying to debug and understand things can help you. 
I do not now a lot of the codebase.
My suggestion would be to try to fix issues to build the knowledge

**Comment by anirudhsingh20** [comment]
Okay ✌👍

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
