### PR TITLE
#1591 Shortcut link to search page

### PR DESCRIPTION
**Pull request by Tithugues**
I implemented a new configuration variable to define a new icon in navigation tree for tables.

### CODE REVIEW

**Comment by ibennetch** [comment]
@Tithugues I seem to be having trouble; after checking out your branch I get this notice:
<pre>
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#822: PMA_NavigationTree->_renderNode(
object,
boolean true,
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#822: PMA_NavigationTree->_renderNode(
object,
boolean true,
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#822: PMA_NavigationTree->_renderNode(
object,
boolean true,
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#822: PMA_NavigationTree->_renderNode(
object,
boolean true,
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#822: PMA_NavigationTree->_renderNode(
object,
boolean true,
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
Notice in ./libraries/navigation/NavigationTree.class.php#1064
Undefined offset: 1

Backtrace

./libraries/navigation/NavigationTree.class.php#824: PMA_NavigationTree->_renderNode(
object,
boolean true,
string 'last',
)
./libraries/navigation/Navigation.class.php#44: PMA_NavigationTree->renderPath()
./navigation.php#70: PMA_Navigation->getDisplay()
</pre>

**Comment by Tithugues** [comment]
@ibennetch thanks for the feedback!
I noticed this this morning. This should be fixed.

**Comment by lem9** [comment]
@Tithugues   Looks fine. At first I was concerned about the screen space taken but as this is deactivated by default, it's fine. 
One thing does not work for me: if the directive is activated only via Settings (user preferences), nothing happens.

**Comment by Tithugues** [comment]
Right, I did not checked that.
I did some modifications and now it works for me.

**Comment by Tithugues** [comment]
Sorry, here is the commit.

**Comment by lem9** [comment]
Settings: fix confirmed.

**Comment by Tithugues** [comment]
@ibennetch Is it ok for you too about the notices please?

Does any one else as something to say about this? Any other bug or improvement?
Thanks.

**Comment by ibennetch** [comment]
Looks good for me now. Thanks

**Comment by lem9** [comment]
@Tithugues Due to b44e9cb3 there is a merge conflict, can you look at it?

**Comment by Tithugues** [comment]
Done.
Thanks for your tests and feedbacks.

**Pull request merged**
