### PR TITLE
Fix #15970: Removed wrong html a tag

### LINKED ISSUE #15970: Status page wrong html tag
### Describe the bug

@williamdes
The replication status this title used anchor tag, But it didn't have href value,
So I think it would remove anchor tag, Am I right?

### To Reproduce

1. Go to the status page.
2. Click the Replication status title.
3. The browser will be redirected to the index page.

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.41 (Win64)
- Database version: mysqlnd 5.0.12-dev
- PHP version: PHP/7.3.10
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Chrome(79.0.3945.130), Firefox(72.0.2)
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Signed-off-by: Cliff Su <stu01509@yahoo.com.tw>

### Description

Fixes issue #15970
Removed wrong HTML a tag in status page.

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by MauricioFauth — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@stu01509 can you use #15942 and rebase onto QA_5_0?

**Comment by stu01509** [comment]
@williamdes 
Did you mean,  I follow these git commands and create a new pull request to QA_5_0 branch?

```shell
git fetch --all --prune
git checkout origin/QA_5_0
git reset --hard phpmyadmin/QA_5_0
git push --force
```

**Comment by williamdes** [comment]
> @williamdes
> Did you mean, I follow these git commands and create a new pull request to QA_5_0 branch?
> 
> ```shell
> git fetch --all --prune
> git checkout origin/QA_5_0
> git reset --hard phpmyadmin/QA_5_0
> git push --force
> ```

> create a new pull request to QA_5_0 branch?
no :)

I think you will be interested by https://github.com/phpmyadmin/phpmyadmin/pull/15942/files#diff-b74d2c6a6e35fef3746c7fe1ef55f386R133 "rebasing down"

**Comment by stu01509** [comment]
> > @williamdes
> > Did you mean, I follow these git commands and create a new pull request to QA_5_0 branch?
> > ```shell
> > git fetch --all --prune
> > git checkout origin/QA_5_0
> > git reset --hard phpmyadmin/QA_5_0
> > git push --force
> > ```
> 
> > create a new pull request to QA_5_0 branch?
> 
> no, just change the target after the operation :)
> 
> I think you will be interested by https://github.com/phpmyadmin/phpmyadmin/pull/15942/files#diff-b74d2c6a6e35fef3746c7fe1ef55f386R133 "rebasing down"

i've been changed base to QA_5_0 branch, Am I right ?

**Comment by williamdes** [comment]
> > > @williamdes
> > > Did you mean, I follow these git commands and create a new pull request to QA_5_0 branch?
> > > ```shell
> > > git fetch --all --prune
> > > git checkout origin/QA_5_0
> > > git reset --hard phpmyadmin/QA_5_0
> > > git push --force
> > > ```
> > 
> > 
> > > create a new pull request to QA_5_0 branch?
> > 
> > 
> > no, just change the target after the operation :)
> > I think you will be interested by https://github.com/phpmyadmin/phpmyadmin/pull/15942/files#diff-b74d2c6a6e35fef3746c7fe1ef55f386R133 "rebasing down"
> 
> i've been changed base to QA_5_0 branch, Am I right ?

Yes but you need to run the "rebasing" operation to change the base branch
```
git reset --hard phpmyadmin/QA_5_0
# The commit you made
git cherry-pick 8d605efa6ec4381cb3cdea2594ea0b000b26205b
git push --force
```
I hope this will work for you

**Comment by stu01509** [comment]
@williamdes 
I am follow your git commands, Is it correct?

**Review by williamdes — APPROVED** [review]
All correct, thank you

**Comment by williamdes** [comment]
Thank you @stu01509 for your contribution !

**Pull request merged**
