### PR TITLE
Automatically add index while editing an existing row and setting auto increment

### PR DESCRIPTION
**Pull request by aroralakshya**
This PR - 
1. Automates the addition of PRIMARY KEY index when user tries to edit an existing row and set AUTO INCREMENT.
2. Disables the popup on insert new column page when user sets AUTO INCREMENT and automatically sets the index to PRIMARY KEY.

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ibennetch** [comment]
This is odd to me, I fixed one error with Selenium tests for you but there are two that don't seem to me to be related. Do you have any thought about the errors shown around https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/398511173#L859 ?

**Comment by nulll-pointer** [comment]
isn't this related to https://github.com/phpmyadmin/phpmyadmin/issues/13621

**Comment by nulll-pointer** [comment]
I tried looking into the tests-
1. The first one tries to drop a table, and asserts if it is dropped, but the test shows -
>  Unable to locate element: {"method":"id","selector":"input_username"}
which is quite strange because #input_username textbox used to input username in login form. **So I feel this is unrelated to my changes.**
2. The second one tries to submit an empty sql query and asserts if it shows an error alert, the test shows-
> element not visible
Which is expected after [e5ff7f3](https://github.com/phpmyadmin/phpmyadmin/pull/14046/commits/e5ff7f34fe944975ce5c2d770d8a97b8d5534b7e), because after this commit, sql query field is never left blank, when the test tries to submit the query, it's never empty. **So I feel this on is also unrelated to my changes.**

**Comment by nulll-pointer** [comment]
@ibennetch I've fixed tests. Only lint tests failed, which can be fixed by --fix.

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
