### PR TITLE
Drop and Truncate display the database name

### PR DESCRIPTION
**Pull request by diegobanos**
Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by diegobanos** [comment]
How should I deal with the missing Signed-Off-By? Should I delete this one and create a new pull request?

**Comment by ibennetch** [comment]
You can sign off your existing commit (by amending it) and push the revision back to your fork (which requires using the --force option since you're technically changing history).

If that's too complex, you can close this one and create a new pull request, but it's slightly preferable to try to do it in this one. Let me know if you get stuck along the way and we'll try to help.

Thanks for asking.

**Comment by diegobanos** [comment]
Did I do it right @ibennetch?

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
