### PR TITLE
Included DROP statement with export of Routines

### LINKED ISSUE #16242: Routine export to include DROP
### Is your feature request related to a problem? Please describe.
When I export routines through the database export I get an option to include a DROP statement, but I have to export all routines, including all my utility routines that are never sent to production.

When I export selected routines from the Routines list, I don't get the chance to include a DROP statement. 

If I want to update my production site from my development site, I want to select just the required routines, but I need a DROP statement to merge them into the production system. 

### Describe the solution you'd like
Include a DROP statement with the selective Routine export from the Routines list.

### Describe alternatives you've considered
The alternative is a manual addition of DROP statements.

### Additional context

- phpMyAdmin version:
image

### PR DESCRIPTION
**Pull request by rajat315315**
Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Please describe your pull request.
It adds DROP PROCEDURE IF EXISTS statement before every Routine export

Fixes #16242

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
I think this change should be made in back-end :thinking: 
Anyway, you can rebase onto master and change the target to master because this is an enhancement :)

**Comment by rajat315315** [comment]
> I think this change should be made in back-end 

I also thought so but there's a hidden SQL statement behind the DROP button in UI itself. So, I thought to make use of it. It is used to DROP routine only.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
I think this should be done in backend as well.

**Comment by rajat315315** [comment]
ok, will do.

**Comment by williamdes** [comment]
:ping_pong:

**Comment by williamdes** [comment]
Closing it for now, you can re-open if you want to implement another solution :) 
Thank you for contributing !

**Pull request closed without merging**
