### PR TITLE
[WIP] Rewrote a part of the import mechanism.

### LINKED ISSUE #11340: Not all results are displayed
Hello,

I am not sure if this is intentional or not, but I see that the behavior of the following query changed:

    USE sakila;
    SELECT * FROM actor;
    SELECT * FROM address;

In [master](http://demo.phpmyadmin.net/master-config/), it looks like it displays results only for the third query and in [4.4](http://demo.phpmyadmin.net/QA_4_4/?pma_username=root) it looks like it displays results only for the first and the second query.

At first, I thought I broke something with the new parser, but I tested against 053f7fc, which is the last commit of the pull request that implemented the [new parser](https://github.com/phpmyadmin/phpmyadmin/pull/1728) and it worked fine.

### PR DESCRIPTION
**Pull request by udan11**
Rewrote a part of the import mechanism.
Updated sql-parser library to udan11/sql-parser@9130cca0d17169b4647d39b644cc6483b600623c

This is still work in progress. I didn't get to test very much. This should fix ~~#11340~~ 11339 too.

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Dan, could you add a comment containing checkboxes describing the remaining work?

**Comment by lem9** [comment]
@udan11 I get an error when trying to import actor.sql (from sakila).

**Comment by udan11** [comment]
In my opinion it is done, but I didn't get to test too much and that's why I said it is work in progress. I haev a feeling that the MySQL specific statements will be ignored (those between /*! */) and I'll have to test against that too.

**Comment by udan11** [comment]
For large dumps, lexing the entire dump, initializing tokens and parsing them to delimit queries is a lot slower than the parser the import mechanism already uses.

**Pull request closed without merging**
