### PR TITLE
Update JS dependencies

### PR DESCRIPTION
**Pull request by williamdes**
- I updated the JS dependencies we have.
- Checked all the files and improved my script

### CODE REVIEW

**Comment by williamdes** [comment]
https://github.com/gregwebs/jquery-uitablefilter/pull/13

**Comment by ibennetch** [comment]
LGTM! Nice work.

**Comment by williamdes** [comment]
Waiting for publishing: https://github.com/kayahr/jquery-fullscreen-plugin/pull/37

**Comment by williamdes** [comment]
Force published https://www.npmjs.com/package/jquery.plugin.debounce-throttle/v/1.0.6
https://github.com/dfilatov/jquery-plugins/pull/6

**Comment by williamdes** [comment]
@cleonello @harryzhux would it be possible to have a npm version with all bundles ?
See: https://github.com/phpmyadmin/phpmyadmin/pull/16071/files#diff-3d586001f3dea035474fcb3e7e0b081aR105

For now only 2 plugins can be copied from the npm version

```bash
echo 'Update jqplot'
#see: https://github.com/jqPlot/jqPlot/blob/master/src/jquery.jqplot.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.pieRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.barRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.pointLabels.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.enhancedLegendRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.dateAxisRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.categoryAxisRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.canvasTextRenderer.js
#see: https://github.com/jqPlot/jqPlot/blob/master/src/plugins/jqplot.canvasAxisLabelRenderer.js

cp ./node_modules/jqplot/jqplot.cursor.js ./js/vendor/jqplot/plugins/jqplot.cursor.js
cp ./node_modules/jqplot/jqplot.highlighter.js ./js/vendor/jqplot/plugins/jqplot.highlighter.js
```

**Comment by williamdes** [comment]
Ref: #13173
Closes: #12677

**Comment by AdrianoCahete** [comment]
And JFYI: https://www.npmjs.com/package/npm-check-updates

**Comment by williamdes** [comment]
> And JFYI: https://www.npmjs.com/package/npm-check-updates

best cli ever, I use it for a long time now !

**Pull request merged**
