### PR TITLE
Get default config values from `Config\Settings` classes

### PR DESCRIPTION
**Pull request by MauricioFauth**
~~Removes the `libraries/config.default.php` file.~~

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Hi, @ibennetch and @williamdes. I'm split about removing the `config.default.php` file. With this PR, it is not needed anymore by the code, however it is useful for copying config directives, but it is also redundant in its majority with the documentation. Should we removed it? Should we keep it for reference?

**Comment by williamdes** [comment]
> Hi, @ibennetch and @williamdes. I'm split about removing the `config.default.php` file. With this PR, it is not needed anymore by the code, however it is useful for copying config directives, but it is also redundant in its majority with the documentation. Should we removed it? Should we keep it for reference?

I would really like to keep it, maybe just built a test to check that the default config file matches the default values in the classes ?

Or maybe we still should load it 🤔 
Because not removing it, people maybe will edit it 🤔 ?

**Comment by ibennetch** [comment]
I agree with everything you've both said. Since it's redundant, it makes sense to remove it — but sometimes users edit the default file instead of creating their own `config.inc.php`.

I also refer to that file very regularly to see the definitive source of possible values. It's useful for users to see the exact syntax for a directive (whether it's a `$i` or a global directive, in particular).

I'm really uncertain about what is best with this.

**Comment by ibennetch** [comment]
I also don't want to end up with _two_ places to maintain default values.

**Comment by mauriciofauth** [comment]
I'm not going to remove the `libraries/config.default.php` file for now. We can figure out what to do later.

**Pull request merged**
