### PR TITLE
Issue 14965

### LINKED ISSUE #14695: Database tab Total collation
### Describe the bug

A collation type is shown for the Total number of databases

### Expected behavior

No collation type should be shown at all. As it is not related to any particular DB.

### Screenshots

image

### Server configuration

- Operating system: Windows 8.1 (Local machine)
- Web server: Apache 2.4.34
- Database version: MariaDB 10.1.36
- PHP version: 7.1.22 
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Firefox Dev version
- Operating system: Windows 8.1

### PR DESCRIPTION
**Pull request by Gaurav-Punjabi**
### Description

This pull request is in reference to solve Issue #14695.
The issue was that the server collation is being displayed on the database page.
Which should not happen as the server does not have any collation.

So this was simply solved by removing the footer collation section of databases table on the database page.

Fixes #14695 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by ibennetch** [comment]
Hi and thanks for your contribution.

It seems you did your work on the master branch and then when you made the pull request targeting the QA_4_8 branch, all the changes from master are also included. It also seems to me this change should not go to QA_4_8, but only in master (master is the development version that will become phpMyAdmin 5). This isn't really fixing a bug but is changing the UI so that's why I don't think it belongs in the 4.x branch, and @williamdes and I can discuss that.

Anyway, I do see that you haven't signed off your commit, which is an important part to ensure that the work you're contributing is your own and that you agree to the [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) document. You can amend your previous commit with `git commit --amend --signoff` then push (with the `--force` option) the changes back to your github repository.

**Comment by Gaurav-Punjabi** [comment]
> Hi and thanks for your contribution.
> 
> It seems you did your work on the master branch and then when you made the pull request targeting the QA_4_8 branch, all the changes from master are also included. It also seems to me this change should not go to QA_4_8, but only in master (master is the development version that will become phpMyAdmin 5). This isn't really fixing a bug but is changing the UI so that's why I don't think it belongs in the 4.x branch, and @williamdes and I can discuss that.
> 
> Anyway, I do see that you haven't signed off your commit, which is an important part to ensure that the work you're contributing is your own and that you agree to the [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) document. You can amend your previous commit with `git commit --amend --signoff` then push (with the `--force` option) the changes back to your github repository.

OKay wait I'll do that and make a request again.

**Comment by ibennetch** [comment]
If you give push back to the repository, it updates this pull request so you don’t even need to close this and make another one.

**Comment by Gaurav-Punjabi** [comment]
> If you give push back to the repository, it updates this pull request so you don’t even need to close this and make another one.

But as all the files have been added to the pull request i need to remove them

**Pull request closed without merging**
