### PR TITLE
Fix #16611 - Renaming exported databases/tables/columns checkbox not working twice

### LINKED ISSUE #16611: Unable to add tables to rename aliases twice on Export
### Describe the bug

The `rename exported...` checkbox on the export tab fails to do anything. 

### To Reproduce

1. Go to any table with rows e.g. `mysql`.`db`
2. Click on the `Export` tab
  Export Method: `Custom - display all possible options`
  Format: `SQL`
  Output: `Rename exported databases/tables/columns`
3. Enter anything into "Select database" and "Select Table"
4. Save And Close

`Rename exported databases/tables/columns` checkbox remains unticked (and is impossible to tick). While exported SQL file does not use the new table/database names.

### Expected behavior

`Rename exported databases/tables/columns` checkbox should be checked after saving and the output SQL file should have the given names for db and table.

### Screenshots

image
image

### Server configuration

- Operating system: 
- Web server: https://demo.phpmyadmin.net/QA_5_0/index.php
- Database version: 8.0.18 - MySQL Community Server
- PHP version:  7.4.11
- phpMyAdmin version: 5.0.5-dev

### Client configuration

- Browser: Chrome Latest
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #16611

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
`$('#alias_data tfoot tr')` seems to magically disappear after one use. This saves the row for any future use.

**Comment by williamdes** [comment]
It does not affect 5.1 ?

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by shucon** [comment]
> It does not affect 5.1 ?

It does, sorry for the confusion.

**Comment by williamdes** [comment]
Did you find what caused this bug between 4.9 and 5.0 ?

**Comment by shucon** [comment]
> Did you find what caused this bug between 4.9 and 5.0 ?

I tried, but couldn't as it was very difficult as the issue is not constantly reproducible.

**Comment by williamdes** [comment]
> > Did you find what caused this bug between 4.9 and 5.0 ?
> 
> I tried, but couldn't as it was very difficult as the issue is not constantly reproducible.

Thank you, I will test and merge your work :100:

**Review by williamdes — APPROVED** [review]
Fixes the scenario: https://github.com/phpmyadmin/phpmyadmin/issues/16611#issuecomment-772360284

**Pull request merged**
