### PR TITLE
Issue #15711: UI on wide screens

### LINKED ISSUE #15711: UI on wide screens
Some UI controls are aligned to the right corner of the window, so they are too far from the main UI elements on wide screens.

Please align them to the left corner of the window, or make alignment configurable in the settings.

The main easily fixable buttons are:

### Browse
"Bookmark this SQL query" button.
SQL query links (Profile, Edit inline, Edit, Explain SQL, etc.)

### Structure
**Table structure** -> "Partition table" button
**Relation view** -> "Preview SQL" and "Save" buttons

Screenshot_2

### PR DESCRIPTION
**Pull request by rabeehrz**
### Description

Fixes #15711 

Fixed:
"Bookmark this SQL query" button.
SQL query links (Profile, Edit inline, Edit, Explain SQL, etc.), in Browse Tab

Table structure -> "Partition table" button
Relation view -> "Preview SQL" and "Save" buttons, in Structure Tab

### CODE REVIEW

**Comment by williamdes** [comment]
@rabeehrz could you please remove the added package-lock file?

**Comment by rabeehrz** [comment]
@williamdes Should be done, please review.

**Comment by rabeehrz** [comment]
@williamdes Is there anything I should change in this?

**Comment by williamdes** [comment]
@rabeehrz can you try the right to left mode ?
Using arabic languages will help you trigger the rtl mode

**Comment by rabeehrz** [comment]
@williamdes I've changed it to left alight. Please review.

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@mauriciofauth and @ibennetch can you please review

**Comment by rabeehrz** [comment]
@williamdes Do I need to make any changes in this?

**Comment by williamdes** [comment]
@rabeehrz From my point of view the code is okay, I just need another review before merging :)

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
# Before
image

# After
image

**Comment by williamdes** [comment]
@rabeehrz I think we should add a media query so most of our users do not have this behavior.
(IMO only very lare screens should have the position switched)
I am not fan of this major change affecting most users that did not ask for it..
What do you think about it @mauriciofauth @ibennetch @kolya7k @lem9

**Comment by mauriciofauth** [comment]
I agree with you @williamdes.

**Comment by kolya7k** [comment]
I agree with @williamdes but i think that this should be the configuration option "Control elements/buttons alignment: Left/Right (+maybe Center)"

**Comment by rabeehrz** [comment]
> I think we should add a media query so most of our users do not have this behavior.

Yep, I think that can definitely be added. Is there any specific screen size that I should consider?

**Comment by williamdes** [comment]
> > I think we should add a media query so most of our users do not have this behavior.
> 
> Yep, I think that can definitely be added. Is there any specific screen size that I should consider?

https://getbootstrap.com/docs/4.1/layout/overview/

Maybe this one:
```css
// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

**Pull request closed without merging**
