### PR TITLE
Create .github/FUNDING.yml file

### PR DESCRIPTION
**Pull request by MauricioFauth**
Adds a FUNDING file to enable a sponsor button.

https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Comment by mauriciofauth** [comment]
Screenshot from 2019-05-23 10-51-25

Screenshot from 2019-05-23 10-52-57

**Comment by mauriciofauth** [comment]
@ibennetch If this pull request is approved, the sponsor button will have to be enabled in the repository settings.

**Comment by ibennetch** [comment]
At the least, we probably should also include a PayPal link so people can still donate even if they don't wish to become full sponsors through the sponsorship program. I don't have a link for that off hand, but we probably have that information around our site somewhere since we do get some donations through this method already.

**Comment by mauriciofauth** [comment]
> we probably have that information around our site somewhere

We have a PayPal button on our site in the Donate page.

**Comment by ibennetch** [comment]
Quite right, then — I was thinking about the sponsorship page, not the donate page. Thanks for the correction.

Looks good to me.

**Review by ibennetch — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Thanks @ibennetch.

I think it would interesting to enable this button on the other repositories as well.

**Comment by mauriciofauth** [comment]
@ibennetch You need to enable the Sponsor button on the repository settings.

**Comment by ibennetch** [comment]
Done, thank you.

**Comment by mauriciofauth** [comment]
Thank you, Isaac.

**Pull request merged**
