### PR TITLE
Feature #1558 Designer menu

### PR DESCRIPTION
**Pull request by gzzhanghao**
Redesigned the designer menu and add support for $cfg['TabsMode']
Works fine with chrome and firefox, needs help for test in IE

designer

### CODE REVIEW

**Comment by lem9** [comment]
I'm not so sure about your implementation. The feature request was asking for menu levels. Also, the menu takes much screen space. Waiting for comments from other developers.

By the way, the ticket is assigned to myself because it's intended for a GSoC 2015 summer task.

**Comment by gzzhanghao** [comment]
User can hide the text by clicking "Toggle text" button:
hidetext

And I'm interested in participating GSoC as well, sorry if I messed up something :-(

**Comment by lem9** [comment]
Thanks, I'm convinced about your approach. I did a few tests in IE 11 and it's fine. A few issues:
* "Toggle text" should be translatable, see https://wiki.phpmyadmin.net/pma/Gettext_for_developers
* "Show/Hide left menu" should be "Show/Hide tables list"
* With "Create relation" the various messages like "select referenced key" should be following the mouse but they are stuck at the upper left position and unreadable

I'll comment on the code later. If this patch gets merged, I'll just replace this idea in the GSoC ideas list.

**Comment by gzzhanghao** [comment]
Moved to #1485

**Pull request closed without merging**
