### PR TITLE
This fixes #14636 - Move operation causes SELECT * FROM `undefined`

### LINKED ISSUE #14636: Move operation causes SELECT * FROM `undefined`
### Describe the bug

When using the move action in the operations tab the next view incorrectly selects from the table name `undefined`

### To Reproduce

```
CREATE TABLE `1_test` (
 `foo` tinyint(3) unsigned NOT NULL,
 PRIMARY KEY (`foo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
Operations Tab > Move table to (database.table) > Enter any new name > Go
Table is moved correctly
Following page shows Table: undefined
```
SELECT * FROM `undefined` WHERE 1
```

### Expected behavior

Following view after move should select from correct table name

### Screenshots

image

image

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.3

### PR DESCRIPTION
**Pull request by wincdev**
-fixed params name in operation js file
-set value in global field table to new table name

Signed-off-by: Vincent Horváth <win9400@gmail.com>

### Description

Please describe your pull request.

Fixes #14636

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@wincdev Can you fix the Selenium test please ?
See: `test/selenium/TableOperationsTest.php`
See https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/438799385#L894

**Comment by wincdev** [comment]
> @wincdev Can you fix the Selenium test please ?
> See: `test/selenium/TableOperationsTest.php`
> See https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/438799385#L894

I will look at it.

**Comment by wincdev** [comment]
Can not someone help me?
Test failed: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/438975941 

> build finished with problems.
make: *** [linkcheck] Error 1
make: Leaving directory `/home/travis/build/phpmyadmin/phpmyadmin/doc'
The command "./test/ci-$CI_MODE" exited with 2.

Review failed: https://app.codacy.com/app/phpMyAdmin/phpmyadmin/pullRequest?prid=2323086
I do not renamed variable...

**Review by williamdes — APPROVED** [review]
Looks good to me, tested OK.

**Comment by williamdes** [comment]
Duplicate of: #14656

**Pull request closed without merging**
