### PR TITLE
Fix broken Relation View

### LINKED ISSUE #14009: Problem with saving the relation view
### Steps to reproduce
1. Open the Relation View of a table
2. Save your settings

### Expected behaviour
The Foreign key constraints should be saved without error.

### Actual behaviour
I get a error message in phpmyadmin 
`Error in processing request
Error code: 500
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.`

and an error in the nginx log
`2018/02/14 11:26:34 [error] 1050#1050: *3617 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /opt/phpmyadmin/libraries/classes/Table.php:2307
Stack trace:
#0 /opt/phpmyadmin/libraries/classes/Controllers/Table/TableRelationController.php(252): PhpMyAdmin\Table->updateForeignKeys(Array, Array, Array, Array, Array, 'duplicity', Array)
#1 /opt/phpmyadmin/libraries/classes/Controllers/Table/TableRelationController.php(126): PhpMyAdmin\Controllers\Table\TableRelationController->updateForForeignKeysAction()
#2 /opt/phpmyadmin/tbl_relation.php(70): PhpMyAdmin\Controllers\Table\TableRelationController->indexAction()
#3 {main}
  thrown in /opt/phpmyadmin/libraries/classes/Table.php on line 2307" while reading response header from upstream, client: 10.8.0.42, server: db1.server.com, request: "POST /tbl_relation.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "db1.server.com"`

On another server with the same setup and the phpmyadmin version 4.2.12deb2+deb8u2 it works fine without errors.

### Server configuration
**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** NGINX (1.10.3 (Ubuntu))

**Database:** MariaDB-10.2.12

**PHP version:** 7.1.14-1

**phpMyAdmin version:** 4.8.0-dev (Git revision: 095c3a8)

### Client configuration
**Browser:** Google Chrome (62.0.3202.62)

**Operating system:** Ubuntu 17.10

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:
Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/14009
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Review by nijel — CHANGES_REQUESTED** [review]
I don't think this fix is sufficient. Actually whole loop makes little sense in case `$foregign_field` is string:

https://github.com/phpmyadmin/phpmyadmin/blob/474b82041248533f2014cc86ecfc54ada350983c/libraries/classes/Table.php#L2297-L2309

So either the string value is not expected here, or the logic is completely wrong.

**Comment by shucon** [comment]
@nijel I've made the relevant changes and the loop now makes sense.

**Comment by shucon** [comment]
@mauriciofauth I think this is unrelated to the other PR.

**Comment by mauriciofauth** [comment]
@shucon No. Issues #13941, #14009 and #14030 were about the same bug, which was created by commit 01bd6d1455722a8647d97c7ae9078356b24478b6.

**Pull request closed without merging**
