### PR TITLE
Fix #13959: table_results horizontal scrolling

### LINKED ISSUE #13959: Too many fields(>13 in my case) in a table leading to page overflow
### Steps to reproduce
1.Make a table with many fields(about 15 or greater)
2.Click table link on left navigation menu

### Expected behaviour
When there are too many columns, the table should have its own scrollbar.

### Actual behaviour
Table overflows out of the page leading to horizontal scrolling(refer screenshot).

horizontal_scroll

### Server configuration
Ubuntu 17.04 zesty

**Web server:**
apache on xampp 7.0.27-0

**phpMyAdmin version:**
4.7.7

### Client configuration
Chromium 60.0.3112.78

### PR DESCRIPTION
**Pull request by rabeehrz**
Signed-off-by: Mohammed Rabeeh <mohammadrabeeh@gmail.com>

### Description

Fixes #13959 

### Fixes

Similar to #15870

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM, I need to test it

**Comment by rabeehrz** [comment]
@williamdes Do I need to make changes?

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Just adding a horizontal scroll bar was reject before as you can see in https://github.com/phpmyadmin/phpmyadmin/pull/14403#pullrequestreview-146706273.

**Comment by williamdes** [comment]
> @williamdes Do I need to make changes?

@mauriciofauth said that it was refused, maybe another fix will be accepted

Thank you for contributing

**Pull request closed without merging**
