### PR TITLE
RFE #1570, part 2. User can choose to use Enter instead of Ctrl+Enter to execute queries.

### PR DESCRIPTION
**Pull request by udan11**
Implements RFE [#1570](https://sourceforge.net/p/phpmyadmin/feature-requests/1570/), part 2.
https://sourceforge.net/p/phpmyadmin/feature-requests/1570/

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Thanks. This is an interesting improvement. Can you improve it further by making it configurable (long-term)?

**Comment by udan11** [comment]
Configurable as in being loaded from the configuration file? If yes, should Ctrl+Enter or Enter be the default option?

**Comment by lem9** [comment]
See the details in https://sourceforge.net/p/phpmyadmin/feature-requests/1570

**Comment by udan11** [comment]
Oh, I'm sorry. I didn't see that. I'll get on it soon!

**Pull request merged**
