### PR TITLE
Add title for group in navigation bar

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

### Description- Added title for group in database in nav bar

Please describe your pull request.
grp

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@mauriciofauth Do you agree to merge ?, you can do so :)

**Comment by williamdes** [comment]
@ibennetch Master or QA ?

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Since this is an enhancement, it should target the `master` branch.

**Comment by bahl24** [comment]
Ok

>

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request closed without merging**
