### PR TITLE
Added tests for sql.lib.php and parse_analyze.inc.php.

### PR DESCRIPTION
**Pull request by udan11**
Added tests for sql.lib.php and parse_analyze.inc.php.
Removed dead code.
Fixed miscellaneous issues.
Fixed a bug in PMA_isJustBrowsing().
Updated sql-parser library to udan11/sql-parser@e713c9f.

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Please fix the failing test.

**Comment by lem9** [comment]
Dan,
there is still a problem in PMA_SqlTest::testIsJustBrowsing.

**Comment by udan11** [comment]
Everything should be fine now. Also rebased to fix merge conflict.

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
