### PR TITLE
Fix #19363 - Wrong query when using backtick in table name

### LINKED ISSUE #19363: Wrong query when using backtick in table name
### Describe the bug

If table name is a backtick, it isn't escaped correctly, when clicking on `SELECT *, SELECT, INSERT, UPDATE, DELETE` buttons from SQL tab.

### To Reproduce

1. Create a table named `
2. Go to SQL tab
3. Click on any  `SELECT *, SELECT, INSERT, UPDATE, DELETE` buttons.
4. See a missing backtick.

### Expected behavior

Backtick should be escaped correctly.

### Screenshots

https://github.com/user-attachments/assets/f58bb32b-2562-4b83-b6a5-febdc590c48c

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by faissaloux**
Fixes #19363

### Issue
SQL Generator does not escape backticks on table name, which generates a non valid query.

### Current
Screenshot from 2024-11-14 17-33-48

### After
Screenshot from 2024-11-14 17-32-38

### Server configuration
- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Okay, this will have to be backported to 5.2

**Comment by williamdes** [comment]
you can push one more commit and re open it

**Comment by faissaloux** [comment]
I can't reopen it! I think I broke it. I'll open a new one.

**Comment by faissaloux** [comment]
This is weird, I'm not able to reopen it. After I comment I'm allowed to! (This to activate `Reopen button`)

**Comment by faissaloux** [comment]
I can't reopen it, I think I broke it! Should I open a new one or I'm missing something?

**Pull request closed without merging**
