### PR TITLE
Use JavaScript module to import jQuery

### PR DESCRIPTION
**Pull request by MauricioFauth**

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
That would be cool that for such changes the genrated output diff is sent on the PR

**Comment by MauricioFauth** [comment]
> That would be cool that for such changes the genrated output diff is sent on the PR

Do you mean, to avoid duplication? In this case, since the jQuery is set in [externals](https://webpack.js.org/configuration/externals/), it hasn't been really imported.

https://github.com/phpmyadmin/phpmyadmin/blob/0056236a4c52caa4f9a9013aa4786381c3b8077c/webpack.config.js#L101-L102

**Comment by williamdes** [comment]
I meant that what I feel frustrating is that we can not see the actual generated JS code for such PRs

**Comment by MauricioFauth** [comment]
> I meant that what I feel frustrating is that we can not see the actual generated JS code for such PRs

I know what you mean. I'm always checking the generated code. How do you think it should be compared?

**Comment by williamdes** [comment]
> > I meant that what I feel frustrating is that we can not see the actual generated JS code for such PRs
> 
> I know what you mean. I'm always checking the generated code. How do you think it should be compared?

maybe a line by line diff just to be sure it is pretty much the same as before

**Comment by MauricioFauth** [comment]
> maybe a line by line diff just to be sure it is pretty much the same as before

Comparing it to the previous generated code, or comparing it to the source?

**Comment by williamdes** [comment]
> > maybe a line by line diff just to be sure it is pretty much the same as before
> 
> Comparing it to the previous generated code, or comparing it to the source?

I was thinking about comparing with previously generated code

**Pull request merged**
