### PR TITLE
Unwanted button hide by see more Button in Pick Central Column removed

### LINKED ISSUE #14310: Column selector "See more" removes "Preview SQL" and "Save" area
### Steps to reproduce
1. Add more than 25 central columns so the "See more" link appears
2. In the structure edit screen, click "Pick from Central Columns"
3. Click "See more" in the "Column selector"
4. The blue "Preview SQL" and "Save" section is now gone and saving the structure is not possible

### Expected behaviour
The blue "Preview SQL" and "Save" section should not disappear

### Actual behavior
The blue "Preview SQL" and "Save" section disappears

### Server configuration
**Operating system**:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-04-18T14:53:04

**Database:** 
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

**phpMyAdmin version:**
phpMyAdmin 4.5.4.1

### Client configuration
**Browser:**
Google Chrome 66.0.3359.181 (Official Build) (64-bit)

**Operating system:**
Edition Windows Pro 10
Version 1803
OS Build 17134.48

phpmyadmin-1
phpmyadmin-2
phpmyadmin-3

### PR DESCRIPTION
**Pull request by thesmallstar**
Signed-off-by: Manthan Surkar <manthan.surkar@gmail.com>

### Description
Fixes  #14310 

*Before:**
image

**After**

image

**What is done?**
When the number of (list items) == max we need to hide the see more button only, but they Go and preview button had a common class that created the problem. In the solution, I have instead used the see more button ID to hide it, which solves the problem.

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
@thesmallstar do you have an issue to link ?

**Comment by thesmallstar** [comment]
@williamdes , sorry I forgot to mention it in PR. I have updated the description.
https://github.com/phpmyadmin/phpmyadmin/issues/14310

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
294e36bdb68dd06ef28ab66931d947e70ffce5da

**Comment by williamdes** [comment]
Merged, thank you @thesmallstar for your contribution !

**Pull request merged**
