### PR TITLE
fixing of bug #11231

### PR DESCRIPTION
**Pull request by sunnygkp10**
By making a ajax call to server after a certain time (10 min) . we can fix the problem of session timeout.

Kindly give reviews about the change i have made.
Thanks.

### CODE REVIEW

**Comment by lem9** [comment]
Thanks for the suggestion. Why do you assume that an interval of 10 minutes is correct in all situations? The timeout can vary based on the LoginCookieValidity directive and php.ini's garbage collection setting. Also, please have a look in js/functions.js, there is a function called UpdateIdleTime() and I thought that its purpose was what you're trying to do.

**Comment by sunnygkp10** [comment]
thank you sir . 
can we take an interval less than the LoginCookieValidity for solution ??

**Comment by lem9** [comment]
I updated my comment, have a look at UpdateIdleTime().

**Comment by sunnygkp10** [comment]
Sir , in my solution timeout never occur, even if user is inactive from a long time and browser window is open .

**Comment by lem9** [comment]
Did you have a look at the function I talked about? It comes from this commit: https://github.com/phpmyadmin/phpmyadmin/commit/42223e1bf658e721359ccfb8b19fbad292b7c4e8

**Comment by lem9** [comment]
Also, removing the feature provided by the LoginCookieValidity directive needs to have good reasons, as I can see good reasons to keep this feature. Therefore it should be discussed on the mailing list.

**Pull request closed without merging**
