### PR TITLE
Fix #17482 - default to "Full texts" when running explain statements 

### LINKED ISSUE #17482: Default to "Full texts" when running ANALYZE
Hey

When the query begins with `ANALYZE` (MariaDB) or `EXPLAIN ANALYZE` (MySQL),
could you please default to "Full texts", so we don't have to run the query again?

`ANALYZE` is used to understand why a query is slow, so having to run it twice is a "waste of time", if you know what I mean :)

image

Example query:

`ANALYZE FORMAT=JSON SELECT * FROM test_table`

Thank you!

### PR DESCRIPTION
**Pull request by iifawzi**
### Description

Hi, this should fix #17482.
Fixes #17482

### CODE REVIEW

**Comment by iifawzi** [comment]
I'm not very sure that this's the correct way of testing this.

**Comment by williamdes** [comment]
> I think it's not testing against the SQL-Parser#dev-master. I've hard-coded the SQL-Parser changes on my machine and it passed.

yeah, you should update in this PR the hash I put in the `composer.json` file ;)

**Comment by iifawzi** [comment]
what do you mean by updating the hash @williamdes?

**Comment by williamdes** [comment]
> what do you mean by updating the hash @williamdes?

https://github.com/phpmyadmin/phpmyadmin/blob/9a8452735c653ac0c35059ab8c93d5b90561fd8c/composer.json#L64

**Review by williamdes — APPROVED** [review]
Looks good, will test it
Thank you for your work on this subject :)

**Comment by nunoperalta** [comment]
Thank you very much for this, guys. You're amazing! 🤩🥳🎉

**Comment by williamdes** [comment]
The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) is updated with this PR 🚀

**Pull request merged**
