### PR TITLE
Fixes #15036 Input fields missing checks

### LINKED ISSUE #15036: Input fields are missing checks.
### Describe the bug
Some input fields are allowing negative numbers. So there should be a check and those fields should not allow negative numbers.

### To Reproduce

1. Click on 'settings'
2. Click on 'features'
3. Click on 'text fields'
4. Change the Minimum size for input field to a negative number
5. Change the Maximum size for input field to a negative number     
6. The input fields wouldn't print any warning or error.

### Expected behavior
I was expecting a warning after giving a negative input.

### Screenshots

image

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

### PR DESCRIPTION
**Pull request by apoorvkhare07**
Signed-off-by: apoorv <apoorvkhare007@gmail.com>

### Description
The Checks were not specified in the config file for the fields `MaxSizeForInputField` and `MinSizeForInputField` . Adding which fixes the issue.

Please describe your pull request.

Fixes #15036 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
@apoorvkhare07 I am about to merge this one, can you signoff with you complete name ?

**Review by williamdes — COMMENTED** [review]
tested: ok
ready to merge !

**Comment by apoorvkhare07** [comment]
@williamdes Added full name to signoff.

**Review by williamdes — APPROVED** [review]
Merged, thanks for the fix !

**Pull request merged**
