### PR TITLE
CloudFlare Flexible SSL support

### PR DESCRIPTION
**Pull request by laukstein**
Resource https://www.cloudflare.com/ssl/
Signed-off-by: Binyamin Laukstein 7raivis@inbox.lv

### CODE REVIEW

**Comment by laukstein** [comment]
Added Signed-off-by.

**Comment by lem9** [comment]
It would be slightly more efficient, in the same method, to keep in an intermediary variable the result of PMA_getenv('something') and reuse that. Plus I believe that the resulting code would be cleaner to read.

**Comment by laukstein** [comment]
@lem9, check if it is what you wanted.

**Comment by lem9** [comment]
Thanks; I squashed your commits and merged: https://github.com/phpmyadmin/phpmyadmin/commit/72cbfd920edb714269d440946638edb99282e1e9

**Comment by laukstein** [comment]
Thanks!

**Comment by benck** [comment]
I'm using version 4.6.4 and still having issues for cloudflare flexible SSL.

The login page looks good https://example.com/phpmyadmin/. But after entering username/password, the login redirects to https://example.com:80/phpmyadmin/.... which is wrong.

I used the solution on [serverfault](https://serverfault.com/questions/715247/phpmyadmin-uses-port-80-on-cloudflare-flexible-ssl) and it works. Thanks!

**Comment by laukstein** [comment]
@benck, https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Config.php doesn't use my proposed fix. I have noticed tons of phpMyAdmin bugs and lack of security over the years, and I recommend you to switch to [HeidiSQL](http://www.heidisql.com).

**Pull request closed without merging**
