### PR TITLE
Remove jQuery and jQuery UI sources from repository

### PR DESCRIPTION
**Pull request by MauricioFauth**
The jquery and jquery-ui packages includes their source codes, which makes it unnecessary to include the source codes in the repository.

### CODE REVIEW

**Comment by mauriciofauth** [comment]
@nijel We can do this, right?

**Comment by nijel** [comment]
The source code is there for licensing reasons (in the end we release under GPLv2, so we have to distribute source code). I'm not really sure how using package manager fits into this...

**Comment by mauriciofauth** [comment]
Currently only the jquery.min.js file is being included in the release archive. Source files are not included. We could add the node_modules directory in the phpmyadmin-sources archive to anyone who wants all the files.

**Comment by mauriciofauth** [comment]
The changes I made now were just to make that PR more specific.

**Comment by nijel** [comment]
In the end I've decide to merge this even though I'm not 100% sure this is okay from legal view. On the other side I have not heard opposite as well...

**Pull request merged**
