### PR TITLE
Fixes #12079

### LINKED ISSUE #12079: Consistent header manipulation and testing
Currently we need runkit to do testing of some `header()` calls and intentionally skip some of them when running in testsuite.

These should be replaced by `Response::header()` and tests should be adjusted to mock this method.

For example this has been already done for cookie auth in 2148e7cad879a9edbc6a82ab03115cd0957f9bee

### PR DESCRIPTION
**Pull request by osaid-r**
Before submitting pull request, please check that every commit:

- [X] Has proper Signed-Off-By
- [X] Has commit message which describes it
- [X] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [X] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ragnerok** [comment]
I know a few other files have similar problems as well but I wanted to make a PR to see if it was the correct way .
P.S It works with phpunit

**Comment by ragnerok** [comment]
@nijel Could you review these before I go on working on the other files

**Comment by nijel** [comment]
There is still [test failure](https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/181984797#L482):

```
     [exec] 1) PMA_User_Preferences_Test::testUserprefsRedirect

     [exec] PMA_sendHeaderLocation called when headers are already sent!

     [exec] 

     [exec] /home/travis/build/phpmyadmin/phpmyadmin/libraries/core.lib.php:506

     [exec] /home/travis/build/phpmyadmin/phpmyadmin/libraries/user_preferences.lib.php:260

     [exec] /home/travis/build/phpmyadmin/phpmyadmin/test/libraries/PMA_user_preferences_test.php:400
```

**Comment by ragnerok** [comment]
I tried something out but it didn't work . What should I do to remove this ?

**Comment by nijel** [comment]
I've applied following fixes to make it work:

* c20474b5c5 Properly set Response mock for testing
* d393505ce1 Avoid using define() for PMA_IS_IIS in tests

The second one is rather cleanup, but the code was not needed at all.

**Pull request merged**
