### PR TITLE
Add Session class

### PR DESCRIPTION
**Pull request by MauricioFauth**
`$_SESSION` handling methods (`get`, `set`, `has`, `delete`) does not handle multidimensional arrays very well.

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by mauriciofauth** [comment]
I decided to remove the methods for handling the `$_SESSION` variable. I think we can put that aside for now.

**Review by nijel — COMMENTED** [review]
I'm not sure about crating new session object several times, this certainly brings some overhead. Maybe using singleton as we do with Response would be better?

**Comment by mauriciofauth** [comment]
I don't think singleton is a good fit for this class. Switching to static methods will solve this problem, I think.

**Comment by nijel** [comment]
That's option as well. I just found it strange to construct class for every use.

**Pull request merged**
