### PR TITLE
fix slowness

### PR DESCRIPTION
**Pull request by m-brangeon**
It fix important problems of slowness when navigating the interface on servers with very high number of tables (more than 30k).
(Avoiding collate clause)

### CODE REVIEW

**Comment by ibennetch** [comment]
Hi, Unfortunately I don't see your commits as part of this pull request. Perhaps something went wrong when creating the pull request or committing your work. Can we help you with that?

**Comment by m-brangeon** [comment]
yes please, i'm not familiar with git branching and merging
can we talk in private ?

**Comment by ibennetch** [comment]
Sure, you can reach the developers mailing list at https://lists.phpmyadmin.net/mailman/listinfo/developers or me directly at bennetch@gmail.com

**Comment by m-brangeon** [comment]
I'm trying to push this :

git diff libraries/Util.php
diff --git a/libraries/Util.php b/libraries/Util.php
index 5dc34e9..190125b 100644
--- a/libraries/Util.php
+++ b/libraries/Util.php
@@ -4489,7 +4489,7 @@ class Util
          if ($lowerCaseTableNames === '0' // issue #10961
              || $lowerCaseTableNames === '2' // issue #11461
          ) {
-            return "COLLATE utf8_bin";
+            return "";
          }
          return "";
      }

**Comment by ibennetch** [comment]
Could you tell us about your system, what is the value of `lower_case_table_names` on your installation and what operating system does your MySQL run on?

**Comment by ibennetch** [comment]
No need to submit a further pull request, we can review that and perform the commit in your name if we decide to use it.

**Comment by ibennetch** [comment]
@m-brangeon This is better to tracked as an issue, so I'm going to close this and move discussion to #12332 if you'd like to monitor the conversation there. If you could mention the circumstances of the slowdown there (the number of tables you use, for instance), that would be helpful, too. Thanks!

**Pull request closed without merging**
