### PR TITLE
reported bug removal for text field

### PR DESCRIPTION
**Pull request by whitepiegon**
I missed a condition and hence maxlength validation condition got added to text field. Added the required condition, which solved the issue.
Signed-off-by: Aayush Anand aayushism12@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Thanks.

**Comment by whitepiegon** [comment]
Marc I was thinking, this validation system can be expanded for other field type also, like decimal, double etc. Your views??

**Comment by lem9** [comment]
Well, everywhere a silent truncation can occur, yes. But please work on your other priority ;)

**Comment by whitepiegon** [comment]
:) I got your point.. I am trying to conc. on that..
May be after my exams end and before other affairs begin, I will expand and finish this feature completely.

**Pull request merged**
