### PR TITLE
Add a console tool

### PR DESCRIPTION
**Pull request by MauricioFauth**
Adds a console tool for phpMyAdmin using the [symfony/console](https://symfony.com/doc/4.3/components/console.html) component and moves the `advisor2po` script to the the console tool.

We can add more commands in the future.

Usage:
```
./scripts/console

./scripts/console po:advisory-rules
```

We already have `symfony/console` installed:
```
$ composer why symfony/console
codacy/coverage  1.4.2    requires  symfony/console (~2.5|~3.0|~4.0)  
phpstan/phpstan  0.11.16  requires  symfony/console (~3.2 || ~4.0)  
```

### CODE REVIEW

**Comment by mauriciofauth** [comment]
@ibennetch Is it better to use _advisory rules_ or _advisor rules_? I saw both being used and I got confused.

**Review by williamdes — APPROVED** [review]
:100:

**Comment by ibennetch** [comment]
I'm a bit late on this one, but for completeness' sake feel "Advisor rules" is better than "Advisory"

**Comment by mauriciofauth** [comment]
Thank you

**Pull request merged**
