### PR TITLE
Create StructureController

### PR DESCRIPTION
**Pull request by gzzhanghao**
Here's the `StructureController`!
Currently it's in initial phase, so I will clean the code continuously.

Further, I need some suggestions on refactoring the display_structure.inc.php. Could we make it a template or create a function in the `StructureController` for it?

Signed-off-by: Jason jason.daurus@gmail.com

### CODE REVIEW

**Comment by zixtor** [comment]
Hi @gzzhanghao, two tests are failing, please fix them.

**Comment by gzzhanghao** [comment]
@zixtor Hi, the test problem should now be fixed.

**Comment by zixtor** [comment]
Jason, when testing, I noticed:-
- On table=>structure page, after clicking on "change" link for any table field, several PHP warnings are displayed.
- When creating a new table, filling some values and clicking on save, it sends a reserved_word_check=1 request to tbl_structure.php, after which an long alert message comes, which is not the case in master.

Except above two scenarios, all else seems fine to me.

**Comment by gzzhanghao** [comment]
@zixtor The first issue you mentioned was fixed. I am analysing the second one and the solution will available soon.

**Comment by gzzhanghao** [comment]
@zixtor Hi, all issues are now fixed, please check and review again :-)

**Comment by zixtor** [comment]
The alert message on creating table got fixed, but "change" links were now pointing to 404 and there were still issues with table=>structure bulk actions, should be fixed after https://github.com/phpmyadmin/phpmyadmin/commit/356d2cd1477f4b5e84784aa878052d6ff139972f https://github.com/phpmyadmin/phpmyadmin/commit/42eb5a1b76fd062236960c4aa50c4f92102d2910 https://github.com/phpmyadmin/phpmyadmin/commit/899337cc1a42fe1b7119973c4a0cf85b60320f61

**Comment by zixtor** [comment]
Jason,
I think now you can move towards completing the commented out tests, to restore the coverage.
Good work overall! Thanks.

**Pull request merged**
