### PR TITLE
Fix #18593 - drop db line included in server export if exporting only…

### LINKED ISSUE #18593: switching between exporting data and structure, has strange effects if something in "Object creation options" is touched
In the latest versions, switching between exporting data and structure, has strange effects if something in "Object creation options" is touched for example:

If I put all the object creation options WITH, and then decide that I don't want to create the tables, I just want to export the data, this is the result:

```
DROP DATABASE IF EXISTS `DBClients`;
CREATE DATABASE IF NOT EXISTS `DBClients` DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci;
USE `DBClients`;
```

As you can see, despite having changed to the option of only exporting data at the last moment, it continues adding statements about the structure of the tables.

If instead of this, I don't touch anything about the creation of objects and go directly to export only data, the header is a bit different:

```
CREATE DATABASE IF NOT EXISTS DBClients DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci;
USE DBClients;
```

It doesn't seem right to me that versions 1 and 2, in which the change was made to export only data, have different headers, it's as if even though the object creation boxes are hidden, they still have effects in the final ".sql" script.

steps to reproduce it, scenario 1:

- at startup /phpmyadmin!!!
- go to export.
- exported custom.
- sql format.
- select the databases.
- go to Object Creation Options | Add Statements: Select All.
- go back to the top option and choose "data"
- download file #-1

steps to reproduce it, scenario 2:

- at startup /phpmyadmin!!!
- go to export.
- exported custom.
- sql format.
- select the databases.
- ~~go to Object Creation Options | Add Statements: Select All.~~ **don't do this**
- go to option and choose "data"
- download file #-2

compare file #-1 and #-2

**_I find it strange that no one had noticed this situation..._**

### PR DESCRIPTION
**Pull request by LHofman**
Signed-off-by: Lennert Hofman <hofmanlennert@gmail.com>

### Description

When doing an SQL server export, if only exporting data, don't include the "drop database" line.

Fixes #18593

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
I did re open for the CI to run
Thank you for this PR

**Comment by LHofman** [comment]
I have a question related to the Data Export.

When exporting SQL from the server (not via DB/Table), the `CREATE DATABASE IF NOT EXISTS` is always included even if only exporting data. What is the purpose of this? If the DB does not exist yet, it'd be created here and then the data will attempt to be inserted, but no tables are created.

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
Merged, thanks for your contribution!

**Comment by MauricioFauth** [comment]
> I have a question related to the Data Export.
> 
> When exporting SQL from the server (not via DB/Table), the `CREATE DATABASE IF NOT EXISTS` is always included even if only exporting data. What is the purpose of this? If the DB does not exist yet, it'd be created here and then the data will attempt to be inserted, but no tables are created.

This looks like an issue. Could you please open a new issue about this?

**Comment by LHofman** [comment]
> This looks like an issue. Could you please open a new issue about this?

I created an issue for this: https://github.com/phpmyadmin/phpmyadmin/issues/19084

**Pull request merged**
