### PR TITLE
Shapefile.lib extension

### PR DESCRIPTION
**Pull request by j0kan**
Fixed a bug regarding the part index. It's now in line with the specification from http://dl.maptools.org/dl/shapelib/shapefile.pdf

Added M and Z coordinates, that means the library now covers the most shape types (except 31 MultiPatch) for loading and saving.

Signed-off-by: Johannes Vockeroth vockeroth@nextbike.net

### CODE REVIEW

**Comment by nijel** [comment]
This is copy of library from http://bfshapefiles.sourceforge.net/, so I'm not sure if improving it in phpMyAdmin is good idea. I've also wondered whether there is not some better maintained library for this purpose we could use, but haven't found time to do the investigation...

**Comment by j0kan** [comment]
Hi,

I'm a "normal user" of the shapefile library. As a user, you will
automatically stumble upon the library as part of phpMyAdmin. So I think
it's a good idea to add the improvements there, too.

Unfortunately the bfshapefiles project is not very active, though I will
try to add my improvements there, too.

I did some research and found nothing better than bfshapefiles for reading
& writing of shape files. Neither there is any library that supports
Measures and Z coordinates for writing. Because it's quite good code, I
just fixed one minor bug and added the support for the M and Z. So from my
knowledge it's now the best implementation of Shapefiles in PHP with almost
full coverage of the original ESRI specification.

Future ToDos could be:
- add MultiPatch for full specification coverage
- replace use of PHP dbase functions and write/read the simple dbase files
directly (dbase implementation does not close resource on dbase_close -
only after finishing the PHP script. That means mass- import/export can
easily hit the "ulimit -u".

Non-PHP alternative implementations:
https://pecl.php.net/package/shape
http://nona.net/software/ext_shapelib/install/ (alpha)
http://shapelib.maptools.org/ (C shapelib)

Johannes

2016-06-09 10:38 GMT+02:00 Michal Čihař <notifications@github.com>:

> This is copy of library from http://bfshapefiles.sourceforge.net/, so I'm
> not sure if improving it in phpMyAdmin is good idea. I've also wondered
> whether there is not some better maintained library for this purpose we
> could use, but haven't found time to do the investigation...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/12309#issuecomment-224833687>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AArHihCPYuYE78MXGzOVDiuKNnCghplCks5qJ9EWgaJpZM4IxrOV>
> .
>



-- 

Johannes Vockeroth
Leiter Entwicklung/IT

http://www.youtube.com/nextbikede
http://www.facebook.com/nextbike

www.nextbike.de
Das Fahrradverleihsystem

Telefon: +49 341 308988915
Mobil: +49 163 1729531
Fax: +49 341 308988913
Email: vockeroth@nextbike.net

nextbike GmbH
Thomasiusstr. 16
04109 Leipzig - Germany

Geschäftsführer: Ralf Kalupner
Amtsgericht Leipzig HRB 21178

Diese E-Mail einschließlich ihrer Anhänge ist vertraulich und kann
rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige
Adressat sind, informieren Sie bitte sofort den Absender und löschen Sie
diese E-Mail sowie gegebenenfalls existierende Kopien. Dritten ist das
Lesen, Verteilen oder Weiterleiten dieser E-Mail sowie jedwedes Vertrauen
auf deren Inhalt untersagt. Vielen Dank.

This email and any attachments may contain confidential and/or privileged
information. If you are not the intended recipient, please notify the
sender immediately and delete this e-mail and any copies of it. Any review,
reliance or distribution by others or forwarding without express permission
is strictly prohibited. Thank you.

**Comment by nijel** [comment]
If it makes sense to use the library outside phpMyAdmin and the upstream is dead, we might as well make sense to maintain it separately (same as we do with https://github.com/phpmyadmin/motranslator/).

I've also found some not so dead libraries on packagist:

* https://packagist.org/packages/shawm11/php-shapefile
* https://packagist.org/packages/muka/shape-reader

Do you have any experience with those?

**Comment by j0kan** [comment]
The problem with the other libraries is, that they are "read only".


2016-06-09 14:46 GMT+02:00 Michal Čihař <notifications@github.com>:

**Comment by nijel** [comment]
Okay, I really didn't look deeper in them. I will probably setup separate repository for this library then and apply your patch there.

**Comment by ibennetch** [comment]
I agree that creating our own fork of this seems to be best. Nijel, let me know if I can assist with this.

**Comment by nijel** [comment]
@ibennetch What I meant was to create separate library out of this code and use it in phpMyAdmin. This way it can be reused by others and they don't have to copy it from our code...

**Comment by ibennetch** [comment]
I'm not sure if I'm not understanding or if my comment was misunderstood. I think you mean to make a new repository with the bfshapefile code, like we did with motranslator, and basically maintain our own repository which will be separate from the original bfshapefile code. Sorry if something didn't come across correctly in my comment but I'm pretty confident we're talking about the same thing.

**Comment by nijel** [comment]
Yes we are, sorry for confusion, I misread your comment..

**Comment by nijel** [comment]
I've just started the repo: https://github.com/phpmyadmin/shapefile

**Comment by nijel** [comment]
I've merged changes to https://github.com/phpmyadmin/shapefile. The switch of phpMyAdmin to use this library is not yet done (I need to figure out how to make correct dependencies there).

**Comment by j0kan** [comment]
"Curretntly the 2D variants of the ShapeFile format as defined in "

should read like

"Currently all 2D and 3D variants except MultiPatch of the ShapeFile format
as defined in "

2016-06-14 10:52 GMT+02:00 Michal Čihař <notifications@github.com>:

**Comment by nijel** [comment]
Thanks, I've updated it now.

**Comment by nijel** [comment]
Also it would be great if you could contribute some tests for the new functionality to the testsuite :-).

**Comment by nijel** [comment]
phpMyAdmin in master branch is now using the new library, it's also available as composer package: https://packagist.org/packages/phpmyadmin/shapefile

**Pull request closed without merging**
