### PR TITLE
Fix #13614 - escaping the database names when granting privileges on tables

### LINKED ISSUE #13614: Backslash escape visible before underscore for user accounts area
I have a database and table with an underscore in the name, such as 'a_z'.

When editing user privileges or creating a new user, I can go to the "Database" tab to edit the database-level permissions for that user. After selecting the database from the list of available database, I'm taken to the screen to edit permissions.

In the header across the top:
`Edit privileges: User account 'a'@'%' - Database a\_z`

The hint at the very bottom:
`[ Database a\_z: Structure ]`
By the way, that link is broken (clicking it gives an error "No databases selected" which I'm guessing is related.

I don't want to see the backslash. It's not really part of my database name, so it shouldn't be shown like this.

If I go further to the table-level privileges, I do not see the backslash escape character.

This is tested with current master

### PR DESCRIPTION
**Pull request by iifawzi**
Signed-off-by: Fawzi E. Abdulfattah <iifawzie@gmail.com>

### Description
Fixes #13614

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Awesome !
Maybe you would want to push one more commit to fix the DB link (expected `_test_u_s__e__r_` to be escaped ?

```html
<em>
          <a href="index.php?route=/server/privileges&amp;username=_test_u_s__e__r_&amp;hostname=%25&amp;dbname=_test_u_s__e__r_&amp;tablename=">
            \_test\_u\_s\_\_e\_\_r\_
          </a>
        </em>
```

by the way escaping is missing also on edit of a current table grant for the DB name

**Comment by iifawzi** [comment]
> Awesome !
> Maybe you would want to push one more commit to fix the DB link (expected `_test_u_s__e__r_` to be escaped ?
> 
> ```
> <em>
>           <a href="index.php?route=/server/privileges&amp;username=_test_u_s__e__r_&amp;hostname=%25&amp;dbname=_test_u_s__e__r_&amp;tablename=">
>             \_test\_u\_s\_\_e\_\_r\_
>           </a>
>         </em>
> ```
> 
> by the way escaping is missing also on edit of a current table grant for the DB name

I didn't get it, which's link? 
I will fix the edit/revoke links right now

**Comment by williamdes** [comment]
This is the link I am talking about :)
image

**Comment by iifawzi** [comment]
All links should be escaped now @williamdes

**Comment by williamdes** [comment]
Thank you, all worked great !

**Pull request merged**
