### PR TITLE
Introduce alias type mapping

### LINKED ISSUE #18613: Editing procedure with BOOL param changes type to INT
### Describe the bug

BOOL type is converted to INT when editing a procedure.
It works with BOOLEAN type.

### To Reproduce

1. Create procedure 
```sql
CREATE PROCEDURE `p` (IN b BOOL) BEGIN END;
``` 
2. Edit procedure
3. See type of `b` changed to INT

### Expected behavior

The BOOL data type should be preserved

### Screenshots

image

### Server configuration

phpMyAdmin version: 5.2 & 6.0

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Fixes #18613

This will be backported to QA, but first we need to fix SQL parser.

### CODE REVIEW

**Comment by M393** [comment]
Thanks for fixing this, @kamil-tekiela

I would prefer if the BOOLEAN type were kept, as it reveals something about the expected use case.
The other aliases make sense. :+1:

**Comment by kamil-tekiela** [comment]
> Thanks for fixing this, @kamil-tekiela
> 
> I would prefer if the BOOLEAN type were kept, as it reveals something about the expected use case. The other aliases make sense. 👍

Right, but it's only visible at the creation time. As soon as you hit save in table creation, it will be converted to TINYINT. So it won't keep this information any longer than it is in your head.

**Comment by M393** [comment]
Sure, but it helps knowing the alias when executing or editing a procedure.

**Comment by williamdes** [comment]
Can this one be rebased ?
Does it need a sql-parser release ?

**Comment by kamil-tekiela** [comment]
This needs to be fixed in SQL parser first. Currently using aliases crashes PMA.

**Comment by williamdes** [comment]
> This needs to be fixed in SQL parser first. Currently using aliases crashes PMA.

Okay, can you manage this on the parser codebase ?
If needed you can backport fixes to QA sql-parser

**Comment by kamil-tekiela** [comment]
Rebased. The `/database/routines` page no longer crashes and the routine using aliases is now editable. I don't know how to write a test for this though. The method `getParameterRow` isn't covered by unit tests as of now.

**Comment by kamil-tekiela** [comment]
Also, I cannot test it on 5.2 yet because the page is still crashing due to non-updated SqlParser.

**Comment by williamdes** [comment]
on 6.0 you mean?

**Comment by kamil-tekiela** [comment]
It works fine on both now. Thanks.

**Comment by MauricioFauth** [comment]
Could you rebase this PR so we can include the `match` in `Types::mapAliasToMysqlType()`.

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
