### PR TITLE
Fix #11561

### LINKED ISSUE #11561: Cannot use third party auth plugins
While creating in a new user, since we have hard-coded the options for choosing the authentication plugin (namely `mysql_native_password`, `mysql_old_password` and for 5.6+ `sha256_password`), the users will not be able to create users with any other authentication plugin that they might have installed (For example, Percona authentication plugin for MySQL).

We should support this dynamically checking for all available and enabled authentication plugins listed in `information_schema`.`plugins`.

### PR DESCRIPTION
**Pull request by devenbansod**
Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Thanks Deven; did you test it on MySQL 5.5.0 to 5.5.6? See http://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-7.html#mysqld-5-5-7-authentication. We are supposed to support MySQL 5.5.x, including those earlier versions without auth plugins.

Also, can you find a way to make the description translatable (at least for the known ones) ?

**Comment by devenbansod** [comment]
No, not until now. I could only test it on MySQL 5.7.6 and MariaDB 10.0.21 for now.

Anyways, I think the link you provided suggests that we can use this approach only for 5.5.7+ and would have to use hard-coding `MySQL Native` and `MySQL 4.0 compatible` for the earlier versions as they don't have plug-able authentication. 

Also, sorry but I could not understand completely what you meant by 'think of a way to make descriptions translatable' ? Currently, I have included the descriptions in the gettext alias. Am I doing something wrong here?

**Comment by lem9** [comment]
This phpMyAdmin family only supports 5.5+ so don't bother with < 5.5, but handle 5.5.0 to 5.5.6. About the translation, this:
````
__($plugin['PLUGIN_DESCRIPTION'])
````
does not work with our translation system. You need a constant there. I have a solution that might work and will implement it afterwards if you don't find it :)

**Comment by lem9** [comment]
Deven,
apart from the translation issue, do you believe that this PR is ready?

**Comment by devenbansod** [comment]
No, I have to look into the issue for MySQL 5.5.0 to 5.5.6 versions.
Once that is done, I let you know.

**Comment by devenbansod** [comment]
Hi Marc, I believe it is ready now.
I have added the required hard-codings for MySQL 5.5.0 - 5.5.6 versions.

**Comment by devenbansod** [comment]
Made the changes to this PR as discussed here : https://github.com/devenbansod/phpmyadmin/commit/22c0cf752566725f1b38bf875e9d9b99126efb3c#commitcomment-13720467

I believe now this PR is good to go. 
I will send a new PR with the refactoring in place, soon.

**Comment by lem9** [comment]
My phpunit says "Not supported query: SELECT `PLUGIN_NAME`, `PLUGIN_DESCRIPTION` FROM `inf
ormation_schema`.`PLUGINS` WHERE `PLUGIN_TYPE` = 'AUTHENTICATION'"

**Comment by devenbansod** [comment]
Should be fixed now. Travis' log shows no error now.
But please let me know if it still exists.

**Comment by lem9** [comment]
Looks fine, thanks.

**Comment by lem9** [comment]
I hope I correctly fixed the merge conflicts in master (not your fault).

**Pull request merged**
