### PR TITLE
Fixed deprecated jquery selectors (Obvious changes)

### LINKED ISSUE #15792: jQuery positional selectors are deprecated
jQuery 3.4.0 [deprecated](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/) the positional selectors `:first`, `:last`, `:eq`, `:even`, `:odd`, `:lt`, `:gt`, and `:nth`.

It's possible to know where we use jQuery positional selectors running the following command:
```
yarn run js-lint
```
That command will return something similar to this:
```
phpmyadmin/js/config.js
  613:9  warning  Positional selector extensions are not allowed  no-jquery/no-sizzle
  621:9  warning  Positional selector extensions are not allowed  no-jquery/no-sizzle
```

### PR DESCRIPTION
**Pull request by yashrajbothra**
### Description

(Commit: b93ae50)
1. `:first` has been replaced to `.first()`
Ref: https://api.jquery.com/first-selector/

2. `:last` has been replaced to `.last()`
Ref: https://api.jquery.com/last-selector/

(Commit : 9888c50)
1. `:eq` has been replaced with `.eq()`
Ref: https://api.jquery.com/eq-selector/

Fixes: #15792

### CODE REVIEW

**Comment by yashrajbothra** [comment]
@williamdes Should i mark it as Draft PR because I am working on some more commits related to this PR ?

**Comment by williamdes** [comment]
@yashrajbothra Draft is better if work is in progress but no problem

**Comment by mauriciofauth** [comment]
If it is a work in progress PR and is not ready to merge, you can mark it as draft.

**Review by williamdes — APPROVED** [review]

**Comment by yashrajbothra** [comment]
@williamdes @mauriciofauth just after few seconds i realised there is no way to go from open to draft

**Comment by ibennetch** [comment]
That's okay, we'll know from the comments here that it's not yet ready for
merge :)

**Review by MauricioFauth — APPROVED** [review]

**Comment by yashrajbothra** [comment]
should i change vendor files because they also contain some deprecated code?

**Comment by williamdes** [comment]
> should i change vendor files because they also contain some deprecated code?

Never change vendor files ;)
But in another PR if you want want to upgrade them we can discuss it

**Comment by williamdes** [comment]
let us know when the PR is ready to merge

**Comment by yashrajbothra** [comment]
And how do i test all these fixes which i am doing ?

**Comment by williamdes** [comment]
> And how do i test all these fixes which i am doing ?

To be honest, it will be difficult
You need to read the code, find the feature and do after and before tests and it takes time

**Comment by yashrajbothra** [comment]
Should i use click event handler to filter the elements as in this implementation we can't use any methods on selectors and `:eq` is deprecated instead `.eq()` is recommended

`$(document).on('click', 'li.trigger div:eq(1) a.ajax img,' +
    ' li.event div:eq(1) a.ajax img', function (event) {`

**Comment by williamdes** [comment]
@yashrajbothra for this can can you replace by adding a css class so you can use it in the selector?
Maybe you can do that in another PR

**Comment by yashrajbothra** [comment]
But `:eq` is now deprecated and i have to fix all deprecated selectors in this PR. So i think this PR is relatable to the change.

**Comment by williamdes** [comment]
> But :eq is now deprecated and i have to fix all deprecated selectors in this PR. So i think this PR is relatable to the change.

I agree, but it will make review more difficult in case of big changes

**Comment by yashrajbothra** [comment]
I thought making more number of commits will help in reviewing.
Should i make more PRs or more commits in this PR only?

**Comment by williamdes** [comment]
> Should i make more PRs or more commits in this PR only?

If can find a balance to only have some obvious changes in one PR and some that require more work in another PR it will help reviewing and merging.
Let us know when we can review :)

**Comment by yashrajbothra** [comment]
Sounds great then this PR will be only for obvious changes. For rest of the stuff i will make another one.
I try to push a commit tommrow after that it will be ready to review 👍 .

**Comment by yashrajbothra** [comment]
Sorry, I need to do force push because previously the commit was containing some vendor files so i have made amendment to unstage those changes. But i dont think Re-review of that commit is required.

**Comment by yashrajbothra** [comment]
Can anyone suggest me which of the possible solution would be better to use in case of `nth-child` as it is deprecated 

[My Solution](https://jsfiddle.net/yashrajbothra/xn5ef3v1/35/)

And please suggest if there is better solution than these?

**Comment by mauriciofauth** [comment]
> Can anyone suggest me which of the possible solution would be better to use in case of `nth-child` as it is deprecated
> 
> [My Solution](https://jsfiddle.net/yashrajbothra/xn5ef3v1/35/)
> 
> And please suggest if there is better solution than these?

Your solution looks good.

**Review by williamdes — APPROVED** [review]
Recent changes are okay and your solution is good

**Comment by williamdes** [comment]
Thank you @yashrajbothra for your hard work on those 2 pull-requests !

**Pull request merged**
