### PR TITLE
Fix #12277 ENUM editor adds blank values

### LINKED ISSUE #12277: VIsual enum editor adds extra (blank) values
When using the visual enum editor to add less than four enum values, it will add blank values. For instance, `` `e_test` enum('a','b','','') NOT NULL``

### PR DESCRIPTION
**Pull request by ibennetch**
Before submitting pull request, please check that every commit:
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them

Signed-off-by: Isaac Bennetch bennetch@gmail.com

### CODE REVIEW

**Comment by nijel** [comment]
Hmm, not sure this is good approach - what if user wants to have empty value as one of choices?

**Comment by ibennetch** [comment]
I did consider that, but didn't come up with a good solution and don't think that scenario comes up often. In the case a user does want a blank value, they can always enter it in the text field on the main page once the visual editor is hidden. I don't really have an idea how we can tell the difference between a default `''` or an intentional one, unless we change the editor to only open one one ENUM value by default, forcing the user to add the rest.

**Comment by nijel** [comment]
I still think empty value is something what can be used. More importantly if you edit value where blank value is already there, it would be removed causing data corruption (not sure how MySQL would behave in such case)...

**Comment by OlafvdSpek** [comment]
Doesn't MySQL always allow empty values in enum columns?

**Pull request closed without merging**
