### PR TITLE
Fixes #11796

### LINKED ISSUE #11796: Use modals for displaying forms in db structure page.
In db structure page, users are redirected to various forms depending on action selected from dropdown. These are actions that will be applied on all the selected tables. It is better if these forms are shown as modals like in table Structure > Indexes > Edit.

### PR DESCRIPTION
**Pull request by Achilles-96**
Signed-off-by: Raghuram Vadapalli raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by lem9** [comment]
Thanks. There is a problem: if I tick no checkbox and choose, for example, "replace table prefix", I get a weird panel.  Also, please fix the failing unit tests and take care of Scrutinizer's warnings.

**Comment by Achilles-96** [comment]
Can someone tell me what is wrong with tests? I'm not familiar with them. I didn't change $_url_params and still it says it is not camel case. I'm not clear on other tests also.

**Comment by lem9** [comment]
Thanks. You'll have to become familiar with unit testing. See cc0b6497c0d96be4c272a07c4bb03e612cb73758 and 348f4dea372249c93b7a6984c35d5a5539d5eb38.

**Comment by Achilles-96** [comment]
@lem9 , Thanks. Can you point me to some documentation for testing. This [documentation](https://wiki.phpmyadmin.net/pma/Development#Developer_documentation) doesn't have that.

**Comment by Achilles-96** [comment]
Oops! I missed that. The documentation does include unit testing.

**Pull request merged**
