### PR TITLE
[WIP] SQL debugging in console

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Known issues and remaining tasks
- [x] Have to think something about self-handled requests
- [x] Have some problem with newly refreshed page
- [x] Update `original` theme
- [x] Cleanup code for old mechanism

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Some of the requests are self-handled, as in it does not use AJAX library in `ajax.js`  (For example running a query in SQL box). What should we do with these request? Right now, it does not show any debug info.

One way is to try to get debug info for every AJAX request made. But it'll also include other unintentional request, for example autocomplete.

**Comment by nisargjhaveri** [comment]
To test, run a query in Console. It works here for sure. :P 
If it does not work somewhere(for some actions), please let me know.

**Comment by lem9** [comment]
Nisarg,
It makes sense to show in the console only what is accumulated by _dbgQuery() from the PMA_DatabaseInterface class.

**Comment by nisargjhaveri** [comment]
But the debugging info is accumulated by `_dbgQuery()` even in case of submitting SQL query box and autocomplete, but right now it is never shown, as they are not managed by `AJAX.responseHandler`.

**Comment by lem9** [comment]
About submitting SQL query box, this is a user action for which debugging info is useful (unless I don't understand what you mean).

For autocomplete, well this generates indirect queries that I don't believe we are interested in, so please have a look to see how we could avoid debuggin info for this.

**Comment by lem9** [comment]
I have started to test and so far I like the interface. I will continue my tests, then review the code. 

One minor thing: after deactivating "Debug SQL" via Settings, the "Debug SQL" console tab is still there.

**Comment by lem9** [comment]
The previous behavior was to regroup all instances of the same query, showing the number of instances. What's your opinion on this?

**Comment by nisargjhaveri** [comment]
I am not sure of usefulness as well as uselessness of grouping queries,so as Madhura suggested on RFE, I was going to implement an option for this. Still thinking about how the interface should be, though.

**Comment by nisargjhaveri** [comment]
Updated, with fix to problem with newly refreshed page and problem after disabling debugging.

**Comment by nisargjhaveri** [comment]
See new commit. I'm not sure of how many more places are there where we should pass `no_debug`. Right now, I added it for navigation reload, and autocomplete.

**Comment by lem9** [comment]
While I continue my tests, please have a look at the failing test and at Scrutinizer's issues.

**Comment by nisargjhaveri** [comment]
Already on it.

**Comment by lem9** [comment]
Can you reproduce this? With your latest commit, I click on Settings and get a js error.

**Comment by lem9** [comment]
About "no_debug", this is a good solution and I am not aware of other places.

**Comment by nisargjhaveri** [comment]
No. Can you please check and tell what the error is?

**Comment by lem9** [comment]
The error is gone none, I'll pay more attention if I see it. 

Another point: the debug panel is updated when I click on various actions (for example browse, search) which is fine; but it's not update when I type in the SQL box and submit.

**Comment by nisargjhaveri** [comment]
Some more info? It was the whole point of the last commit. :/

**Comment by nisargjhaveri** [comment]
I've updated the `original` theme, too. Please check.

**Comment by nisargjhaveri** [comment]
And, did that work after the SQL query box?

**Comment by lem9** [comment]
Sorry, I don't understand your question.

**Comment by nisargjhaveri** [comment]
Sorry.
Does it now show debug information when typing in SQL query box and submitting it?

**Comment by lem9** [comment]
Yes it's fixed now.

**Comment by lem9** [comment]
About the original theme, all seems to work correctly. Please squash the commits so I can better review the code.

**Comment by nisargjhaveri** [comment]
Squashed.

**Comment by lem9** [comment]
There are non-English developers too.

**Comment by lem9** [comment]
Nice work!

**Comment by nisargjhaveri** [comment]
Okay. I'll make it translatable.

And, Thanks :)

**Comment by lem9** [comment]
When the messages are translatable, please squash and I can merge. Then you can work on the grouping query option.

**Comment by lem9** [comment]
How about showing the percentage of total time that each query (or group of queries) took?

**Comment by nisargjhaveri** [comment]
That is a nice idea. I'll do it.

**Comment by lem9** [comment]
Nisarg,
I would prefer merging a branch containing translatable messages but not containing your work on query grouping or percentage.

**Comment by nisargjhaveri** [comment]
Hope I haven't missed any messages.

**Comment by lem9** [comment]
Looks fine.

**Pull request merged**
