### PR TITLE
Remove CSS classses odd and even

### PR DESCRIPTION
**Pull request by vosgus**
Before submitting pull request, please check that every commit:
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them

The odd and even classes for tables are no longer needed. The same
functionality can be achieved using nth-child(). This commit is for the
pmahomme and original theme.

Signed-off-by: Patric Gustafsson patricjgustafsson@outlook.com

### CODE REVIEW

**Comment by ibennetch** [comment]
It appears as if your editor has used tabs instead of spaces for indentation; the phpMyAdmin standard is to use all spaces. Would you mind changing the files and pushing again? (You'll probably have to use the `-force` option with git push).

**Comment by ibennetch** [comment]
Thanks for your contribution.

To track the larger issue, we have:
[x] remove `.odd` and `.even` classes from .css files (implemented in this pull request)
[ ] remove `.odd` and `.even` classes and logic in .php files

**Comment by vosgus** [comment]
Ouch, sorry for that. I'll fix it today or tomorrow.

**Comment by nijel** [comment]
Your change breaks at least displaying tables with th inside:
localhost_localhost_bar_phpmyadmin_4 7 0-dev_-_2016-06-16_10 53 28

**Comment by nijel** [comment]
An progress on missing bits?

* introducing this breaks current rendering in some cases
* it does not remove matching PHP code

**Comment by vosgus** [comment]
Hi, I've submitted a patch for the rendering issues with the table headers, it should be fine now. If the patch is OK I'll start working on removing the PHP code.

**Comment by nijel** [comment]
Thanks, the CSS now seems to work fine.

**Comment by vosgus** [comment]
Since there will be many small commits in this patch I was wondering what would be the best way to do it. Should I make all the changes and then squash them together or is there some other preferred way?

**Comment by nijel** [comment]
I don't mind with small commits either, just try to group similar things into the commit.

**Comment by nijel** [comment]
I see there is quite good progress here. Any estimates when it will be ready for merge?

**Comment by vosgus** [comment]
There are about ten files left that still needs to be worked on. About a week from now I think is a good estimate.

**Comment by nijel** [comment]
Great, thanks for update!

**Comment by vosgus** [comment]
I'm working on the last couple of files right now. One bug that I have found is on the tbl_search.php page and tbl_zoom_select.php page. There are some hidden rows in the tables there so the CSS will not look right. The hidden rows will get the background color instead. 

image

One solution would perhaps be to keep the old CSS code just for these pages. Also I'm a bit unsure what the hidden fields are doing. Are they just there to provide some spaces between the rows?

**Comment by nijel** [comment]
I think these rows with hidden can be folded into previous ones in both cases:

* https://github.com/phpmyadmin/phpmyadmin/blob/master/templates/table/search/rows_normal.phtml
* https://github.com/phpmyadmin/phpmyadmin/blob/master/templates/table/search/rows_zoom.phtml

**Comment by rpv-tomsk** [comment]
Hi!

JFYI:  I think newly reported #12611 may be related to your work in progress.

**Comment by nijel** [comment]
@vosgus I've just fixed the two offending files in master. Are you still interested in completing this?

**Comment by vosgus** [comment]
@nijel Yes I still am. I'll get back to working on it in a few days. If I recall correctly there should not be many files left to fix.

**Comment by nijel** [comment]
That's true, it's almost complete.

**Comment by vosgus** [comment]
@nijel Ok, I think this is done now, I've fixed all the files I could find at least. Please tell me if anything else still needs to be done that I might have missed.

**Comment by nijel** [comment]
Well there are still some places left (see https://github.com/phpmyadmin/phpmyadmin/issues/12070#issuecomment-261484535), but I've decided to merge the code for now as what is done works okay. Thanks for your contribution!

**Pull request merged**
