### PR TITLE
Remove non working analyze explain button

### PR DESCRIPTION
**Pull request by kesselb**
### Description

The service mariadb.org/explain_analyzer is unavailable.

I asked MariaDB via Slack and it's broken for a while. 

Fixes: #17030

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Can you ask them if they can open source it?

**Comment by kesselb** [comment]
> Can you ask them if they can open source it?

Sure

**Comment by williamdes** [comment]
This would close: #17030

If they agree to open source it we can maybe make it internal.

@MauricioFauth since it's broken it is okay to drop this link ?
Or should we disable it with a tooltip for users ?

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
> @MauricioFauth since it's broken it is okay to drop this link ? Or should we disable it with a tooltip for users ?

I think the button should be removed.

**Comment by LinuxJedi** [comment]
Hi all,

I am the Chief Contributions Officer for MariaDB Foundation.

Sorry for the delay in responding to this. I have been on a long vacation over Christmas and New Year and have had to do a bit of research into the history of this tool.

Unfortunately we cannot open source it in its current form. Due to a complicated history (that pre-dates the Foundation itself) we do not have the rights to do so and have been unsuccessful in obtaining them. That being said we at the Foundation do have access to the source code (currently written in Python 2) and do want to reverse engineer it into a new open source tool.

We have not decided on a language or what form this will take yet. We are thinking some kind of library / cli with a JSON output. But are willing to work with the phpMyAdmin community on this if it is something useful.

I'm more than happy to discuss this further as needed.

**Review by williamdes — COMMENTED** [review]
✅

**Pull request merged**
