### PR TITLE
Fix #12143 Cannot login with certain password

### LINKED ISSUE #12143: Cannot login with certain password
phpMyAdmin is treating password 0 (one zero) as empty password so when AllowNoPassword is set (the default), you cannot login.

### PR DESCRIPTION
**Pull request by madhuracj**
This fixes the bug. However, I wonder whether this commit has any security implications. Further discussion is appreciated before merging.

### CODE REVIEW

**Comment by nijel** [comment]
I think it's correct, just the testsuite needs to be adjusted.

The only thing I wonder about is \xff(blank) value, maybe it's needed to avoid empty cookie string? It's there since 11b0c087...

**Comment by ibennetch** [comment]
That was my thought as well, that `\xff(blank)` was to avoid an empty string, but I'm not very clear about it either.

I'm not 100% confident of my assessment of part of the old code, but I also think this looks okay.

**Comment by nijel** [comment]
It was probably only problem with previous ciphers. With current block one, it always produces some content as it's padded...

**Comment by nijel** [comment]
Merged and adjusted tests to not fail.

**Pull request merged**
