### PR TITLE
Fixed icon by removing width

### LINKED ISSUE #15726: Enum Editor Delete Icon
https://demo.phpmyadmin.net/master-config/index.php?route=/server/databases&server=2

pma

### PR DESCRIPTION
**Pull request by yashrajbothra**
### Description

Removed width in img causing stretching of icon

Fixes #15726 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by ibennetch — APPROVED** [review]
Looks good to me!

**Comment by williamdes** [comment]
image
image


@yashrajbothra Can you fix the other themes ?
original theme is not affected

**Comment by williamdes** [comment]
Affects 5.0

**Comment by williamdes** [comment]
Merged, thank you @yashrajbothra 
I added the bootstrap change in cc48051a1edd8d3caac25800b597f4d9a9eaa06f

**Comment by yashrajbothra** [comment]
@williamdes actually i had also changed that bootstrap file. Maybe forgot to stage and commited.i will always review changes before making PR. Thanks

**Comment by williamdes** [comment]
@yashrajbothra You did commit the change but I had to remove it and add it back when merging into master branch

**Pull request merged**
