### PR TITLE
Fixes #15125 flexible alignment of modals

### LINKED ISSUE #15125: Alignment of any modal is not flexible
### Describe the bug
The alignment of any modal appended to some function is not flexible which often leads to misplaced modal when one changes the size of the browser screen.
### To Reproduce
To reproduce you can use the modal for index creation while adding a column
1. Go to Structure of any table
2. Click on 'add columns'
3. Now select any Index say 'Index type'
4. When the modal related to index opens resize the browser screen to see misplaced modal.

### Expected behaviour
As entire Front-end of phpMyadmin is quite flexible, so these appended modals should also be made flexible
### Screenshots
Screenshot 2019-03-29 at 10 23 43 PM
**Small Screen View**
Screenshot 2019-03-29 at 10 24 04 PM 
**Large Screen View**
### Server configuration

- Operating system: macOS Server(5.7.1 )
- Web server: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.0 mod_perl/2.0.8-dev Perl/v5.16.3
- Database version: Localhost via UNIX socket
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Safari (12.0.3)
- Operating system: macOS Mojave (version 10.14.2)

### PR DESCRIPTION
**Pull request by apoorvkhare07**
Signed-off-by: apoorv <apoorvkhare007@gmail.com>

### Description 
Adding window resize handler to centre align the modals with respect to screen size.

Fixes #15125 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by kartik1000** [comment]
hey, @williamdes can we use sudo-bot and verify for the same?

**Comment by williamdes** [comment]
@apoorvkhare07 can you please rebase and signoff this PR ?
I would like to merge it

**Comment by williamdes** [comment]
@apoorvkhare07 would you agree to signoff your work ?

**Pull request closed without merging**
