### PR TITLE
Feature Request: - Export Progress Bar

### PR DESCRIPTION
**Pull request by djprawns**
Also optimized progress process by ensuring messages are broken down into 10 part process if rows exceed 20.
Progress bar is now smoother through animation.

Note: - Currently only supports SQL format to see if the solution is acceptable for merging. If it is, it can be introduced for more formats by introducing same messages in files in libaries/plugins/export folder.
Hoping for the best.

Signed-off-by: Pranav Sharma vanarpsharma@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Very good. Could you fix these messages that show up at each progression step, in my web server's error log (PHP 5.6.3):
````
[Fri Apr 17 10:22:06 2015] [error] [client 192.168.0.74] PHP Notice:  A session had already been started - ignoring session_start() in /progress_sess.php on line 4

[Fri Apr 17 10:22:06 2015] [error] [client 192.168.0.74] PHP Notice:  Use of undefined constant progress_result - assumed 'progress_result' in /progress_sess.php on line 11

[Fri Apr 17 10:22:06 2015] [error] [client 192.168.0.74] PHP Notice:  Use of undefined constant percentage - assumed 'percentage' in progress_sess.php on line 11

````
Also, there are failures in unit tests.

**Comment by vanarpsharma** [comment]
Hey Marc,
I think I have resolved the php issues.
However I dont know about the unit tests? How can I fix them? I have no idea about them.

**Comment by lem9** [comment]
Hi Pranav,
please add commits to fix the PHP warnings, and remove the tab characters. For the unit tests, errors are listed by Travis. Do you know what is a unit test? We have some doc at https://wiki.phpmyadmin.net/pma/Unit_Testing. After you have fixed the other issues, maybe someone from the team can fix the unit tests, we'll see.

**Comment by vanarpsharma** [comment]
Hi Marc,
Could you change this line 
$arr = array(progress_result=>$result, percentage=>$percentage);
in progress_sess.php in your system to 
$arr = array('progress_result'=>$result, 'percentage'=>$percentage);
 to see if the error disappears. What error if any, do you get then?
For some reason I am getting no errors in my log.

**Comment by lem9** [comment]
I am testing b5f7380f8e435fb8a3fb6dace7d14a95aae6089b and the suggested change is already done in this version.

**Pull request closed without merging**
