### PR TITLE
Move to html5 history api

### PR DESCRIPTION
**Pull request by atul516**
Changes:
- clearer URL with easier manipulation of URL script name or query params to navigate.
- as we use no-cache, so browser now makes new requests on pressing back/forth buttons, under HTML5 API. Earlier with hash microhistory, we were manually caching the no-cache content of pages.

### CODE REVIEW

**Comment by zixtor** [comment]
For error reports, I have removed sending microhistory cache data with reports, it sounded useful, but personally to me it came of little use practically. Removal is necessitated because we are now loading microhistory code conditionally only when html5 is not supported. But if any objections to removal, we can consider keeping a cache just to send with reports.
Also, it might require some changes on error reporting server, I could not test if report submission still works after this removal, due to very very slow error reporting server.

**Comment by ibennetch** [comment]
I'm okay with removing microhistory from the error reports. Like you said, it seemed useful at the time but probably isn't very practical at this point.

**Comment by zixtor** [comment]
Thanks, with that, things seem fine to me for merging.

**Comment by zixtor** [comment]
So, with the fast error reporting server I am able to verify that the report submission worked, and I see "Microhistory: null" as on Incidents page [0], so I think the 'Microhistory' field should be removed from the Incidents UI and database of the server. @smita786, please queue this request.

[0] https://reports.phpmyadmin.net/incidents/view/284716

**Comment by smita786** [comment]
@zixtor thanks. I have opened an issue here https://github.com/phpmyadmin/error-reporting-server/issues/83 . 'll fix it soon.

**Comment by zixtor** [comment]
Thank you! :)

**Pull request merged**
