### PR TITLE
Fix JSDoc-comments

### PR DESCRIPTION
**Pull request by Thomas1664**
### Description

I fixed all the JSDoc comments

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by Thomas1664** [comment]
Sign-of-by: Thomas Heinrichs

**Review by williamdes — APPROVED** [review]
This is very impressive !
What tool did/do you use ?

**Comment by Thomas1664** [comment]
> This is very impressive !
> What tool did/do you use ?

I use vscode where I did a find and replace for bad comments like `* @param bool`. I fixed comments that could not be fixed this way during a manual review at the end of find and replace.

**Comment by williamdes** [comment]
I added the rule https://eslint.org/docs/rules/valid-jsdoc to eslint, that will ensure the blocks stay valid

**Pull request merged**
