### PR TITLE
FRE #1578: warn about reserved kyword

### PR DESCRIPTION
**Pull request by smita786**
Signed-off-by: Smita Kumari kumarismita62@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Thanks Smita. Now I see the new confirm dialog for reserved words, but the old warnings are still shown everytime I go to this table's Structure page.

**Comment by smita786** [comment]
Hi Marc

I think, I misunderstood. I thought no matter user enable or disable directive we show the wrning anyway. That why i was asking about removing of cfg_ReservedWordDisableWarning. 
Thanks. I'll just fix it.

**Comment by smita786** [comment]
fixed. it should work now. if it looks good, I'll squash the commits.

**Comment by smita786** [comment]
squashed!

**Comment by lem9** [comment]
Nice work!

**Comment by lem9** [comment]
Smita,
for the plural form of messages, see the usage of _ngettext() here:
https://github.com/phpmyadmin/phpmyadmin/commit/be585531a306d0accccb30f67e27f0b850b62ff8

**Comment by smita786** [comment]
Thanks Marc!

**Pull request merged**
