### PR TITLE
Fixes #15059 Server charset hardcoded in index.php

### LINKED ISSUE #15059: "Server charset" in "Database server" tab showing wrong information.
I'm new here. I got a little confuse so please be kind.

In `/etc/mysql/mariadb.cnf` I changed:

```
[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_unicode_ci 
```

into:

```
[mysqld]
character_set_server = latin1
collation_server = latin1_swedish_ci
```

and restarted `sudo systemctl restart mariadb`. I also did a Ctrl+F5 refresh on the page but it is still showing the old/wrong information:

Server charset: UTF-8 Unicode (utf8)

Is this information being cache somewhere? When I go to the "Databases" tab, it is showing the correct updated default collation which is latin1_swedish_ci. Isn't the informatoin should now be showing "**Server charset: something something (latin1)**" instead of "**Server charset: UTF-8 Unicode (utf8)**"

### PR DESCRIPTION
**Pull request by apoorvkhare07**
### Description

Please describe your pull request.
Initially server charset was hardcoded to `utf-8` in index.php, so even after changing the server charset for mysql it always showed `utf-8` in phpMyAdmin. 
Adding a function `getCharset()` which takes current server-charset through mysql client fixes this issue.

Fixes #15059 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM :100:

**Comment by mauriciofauth** [comment]
Hello @apoorvkhare07. Thanks for your contribution!

We require a full name for legal compliance reasons. Could you use your full name in the signature tag?
For example: `Signed-off-by: Jane Developer <jane@example.org>`

See [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO#L39)

**Review by MauricioFauth — APPROVED** [review]

**Comment by apoorvkhare07** [comment]
@mauriciofauth Made the changes,
Thank you

**Comment by williamdes** [comment]
@ibennetch Can I have your approval on this PR ?

**Review by williamdes — APPROVED** [review]
Merged, thanks @apoorvkhare07 !

**Pull request merged**
