### PR TITLE
Fixes #11538

### LINKED ISSUE #11538: Copy multiple tables to database
As of PhpMyAdmin 4.5.0(.2), the option to copy multiple tables to another database seems to have disappeared:

copy table gone

### PR DESCRIPTION
**Pull request by Achilles-96**
If this looks fine, I'll add other options in 'Copy tables' form.

Signed-off-by: Raghuram Vadapalli raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by lem9** [comment]
Nice work. Suggested improvements:
* do not show the current db name in the db choice
* to show the db choice, a modal dialog similar to table Structure > Indexes > Edit

**Comment by lem9** [comment]
See also c079df0ff3a3023be493f8d16ba71454ad9272f9.

**Comment by Achilles-96** [comment]
@lem9 
I'll be on suggested improvements.
I'm also thinking of adding other options like table Operations > Copy table to.

**Comment by Achilles-96** [comment]
I think current db name should not be shown in table Operations > Copy table to also.

**Pull request merged**
