### PR TITLE
#16604 - Fix table width in Databases page

### PR DESCRIPTION
**Pull request by liviuconcioiu**
Signed-off-by: Liviu Concioiu liviu.concioiu@gmail.com

Ref: #16604

### Description

Fixes table width for Databases page, for large screens.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you, seems like this was missed when fixing #16604 on master branch

**Comment by williamdes** [comment]
Hi @liviuconcioiu 
Could you enable the allow maintainer changes on this PR by checking the checkbox ?
So I can force push the commit with your signoff line

**Comment by liviuconcioiu** [comment]
Is checked.
Untitled

**Comment by williamdes** [comment]
> Is checked.
> Untitled

Sorry, It seems like I was using the wrong command line
Merging your work now :)

**Review by williamdes — APPROVED** [review]

**Pull request merged**
