### PR TITLE
Add backward compatibility for DefaultTabServer, DefaultTabDatabase, DefaultTabTable, NavigationTreeDefaultTabTable and NavigationTreeDefaultTabTable2

### LINKED ISSUE #16698: Wrong Absolute Links In Navigation ("/" instead of "./")
### Describe the bug
With or without defined PmaAbsoluteUri ($cfg['PmaAbsoluteUri'] = 'https://' . $_SERVER['SERVER_NAME'] . '/mysql_latest/';) I got the wrong navigation links on the left menu (see screenshot of the source code in browser). Only the link to a new database is correct (index.php?...), all other links to existing databases are wrong (/?...) I guess instead of (./?...). Where can I change this strange behavior, i.e. changing [slash] with [dot][slash] in href of the pma_navigation_tree_content?

### To Reproduce
As soon as I log in (/mysql_latest/), any link in the navigation translates to href="/?..." instead of href="./?..." or href="[absolute or relative URL defined by PmaAbsoluteUri]?..." which makes phpMyAdmin 5.1.0 unusable for me 😢

### Expected behavior
Correct links to the expected functions.

### Screenshots
SourceCodeScreenshot

### Server configuration
- Operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-66-generic x86_64)
- Web server: Apache 2.4.46
- Database version: MySQL 5.7.33
- PHP version: PHP 7.4.15
- phpMyAdmin version: 5.1.0

### Client configuration
- Browser: Safari 13.1.2 & Firefox 86.0 & Chrome 88.0.4324.192
- Operating system: MacOS 10.13.6

### LINKED ISSUE #16713: PhpMyAdmin\Url::getFromRoute() must be of the type string, null given
### Describe the bug

I received this error:
```
PhpMyAdmin\Url::getFromRoute() must be of the type string, null given
```

### To Reproduce

1. Install 5.1.0 zip file on the server
2. setup config file with cookie login
3. Login
4. Get the error immediately.

### Expected behavior

Getting the normal screen

### Server configuration

- Operating system: Debian GNU/Linux 10 (buster)
- Web server: Apache/2.4.38
- Database version: 5.7.33
- PHP version: PHP 7.3.27-1~deb10u1
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Firefox
- Operating system: Win10

### Additional context

Temporary fix:
Remove "string" from the `PhpMyAdmin\Url::getFromRoute()` method:
```
public static function getFromRoute($route, array $additionalParameters = []): string
```

Stacktrace:
```
Mar  4 09:10:39 calculation-server php: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\Url::getFromRoute() must be of the type string, null given, called in [...]/tmp/twig/58/58c5c0c1b5dbd6c9ffbe3eb3ff4d045c3ea6ed770ea4c6d8adb0e964e263f7c8.php on line 47 and defined in [...]/libraries/classes/Url.php:289
Mar  4 09:10:39 calculation-server php: Stack trace:
Mar  4 09:10:39 calculation-server php: #0 [...]/tmp/twig/58/58c5c0c1b5dbd6c9ffbe3eb3ff4d045c3ea6ed770ea4c6d8adb0e964e263f7c8.php(47): PhpMyAdmin\Url::getFromRoute(NULL)
Mar  4 09:10:39 calculation-server php: #1 [...]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_bca7df91540ab1052aa77dd2ecc2c43f39b06b4429ce97a0060d6039695a4d49->doDisplay(Array, Array)
Mar  4 09:10:39 calculation-server php: #2 [...]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
Mar  4 09:10:39 calculation-server php: #3 [...]/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
Mar  4 09:10:39 calculation-server php: #4 [...]/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
Mar  4 09:10:39 calculation-server php: #5 [...]/libraries/classes/Template.php(129): Twig\TemplateWrapper->render(Array)
Mar  4 09:10:39 calculation-server php: #6 [...]/libraries/classes/Menu.php(247): PhpMyAdmin\Template->render('menu/breadcrumb...', Array)
Mar  4 09:10:39 calculation-server php: #7 [...]/libraries/classes/Menu.php(72): PhpMyAdmin\Menu->getBreadcrumbs()
Mar  4 09:10:39 calculation-server php: #8 [...]/libraries/classes/Header.php(444): PhpMyAdmin\Menu->getDisplay()
Mar  4 09:10:39 calculation-server php: #9 [...]/libraries/classes/Response.php(331): PhpMyAdmin\Header->getDisplay()
Mar  4 09:10:39 calculation-server php: #10 [...]/libraries/classes/Response.php(345): PhpMyAdmin\Response->getDisplay()
Mar  4 09:10:39 calculation-server php: #11 [...]/libraries/classes/Response.php(507): PhpMyAdmin\Response->htmlResponse()
Mar  4 09:10:39 calculation-server php: #12 [internal function]: PhpMyAdmin\Response->response()
Mar  4 09:10:39 calculation-server php: #13 {main}
Mar  4 09:10:39 calculation-server php:   thrown in [...]/libraries/classes/Url.php on line 289
```

### PR DESCRIPTION
**Pull request by csware**
### Description

if a user has a legacy setting for DefaultTabServer, DefaultTabDatabase, DefaultTabTable, NavigationTreeDefaultTabTable and NavigationTreeDefaultTabTable2 don't provide a broken fallback, but mimic the old behavior.

Fixes #16698
Fixes #16713

This affects 5.1.0 and maybe other versions.

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by csware** [comment]
I'm not sure if this PR fixes all cases, such as `LeftDefaultTabTable`

**Comment by williamdes** [comment]
> This affects 5.1.0 and maybe other versions.

Only 5.1.0 for now, and 5.2.0-dev

I will rebase+squash your fix if @mauriciofauth also thinks this is a good fix
I kind of agree with the fix, because it makes sense but is more like a legacy support

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
It's better to add a `default` case to the `switch` instead of supporting these old values.

**Comment by csware** [comment]
> It's better to add a `default` case to the `switch` instead of supporting these old values.

What do you mean with a default value? Wouldn't that mean that the old values won't work any more?

**Review by ibennetch — APPROVED** [review]
We have always considered backwards compatibility important for our configuration settings, I'm glad you caught this.

LGTM

**Comment by williamdes** [comment]
> We have always considered backwards compatibility important for our configuration settings, I'm glad you caught this.

I agree it is important. Will add more tests before merging this

**Comment by williamdes** [comment]
> LeftDefaultTabTable

I could not find anything named like that in the code and in the [docs](https://docs.phpmyadmin.net/en/latest/config.html).

**Review by williamdes — APPROVED** [review]
Good work, It works fine !
I added tests, this PR fixes 3 bugs in total

**Comment by csware** [comment]
Any plans when a new version is released?

**Comment by ibennetch** [comment]
The next release is slightly behind schedule already because of wanting to
incorporate a fix for one remaining issue. William has prepared some
solution for that, so if all goes well with it I expect a release in the
coming days.

Thanks for asking.

**Comment by williamdes** [comment]
> The next release is slightly behind schedule already because of wanting to incorporate a fix for one remaining issue. William has prepared some solution for that, so if all goes well with it I expect a release in the coming days. Thanks for asking.

Yes, it is https://github.com/phpmyadmin/phpmyadmin/issues/16734#issuecomment-839888083
Any feedback and testing is very welcome

**Pull request merged**
