### PR TITLE
Enhancing the 'Save Page As' of the designer section

### LINKED ISSUE #12286: Designer should remember expanded/collapsed state
When using the Designer, I can save the layout, but when I open Designer again the expanded/collapsed state of each table reverts to the default. It would be great if it would save the state as part of the layout status.

### LINKED ISSUE #13371: Designer - automatically toggle the radio button to "Create a page and save it" when the use clicks the bottom text box.
A Designer enhancement would be in the Save As page: we can automatically toggle the radio button to "Create a page and save it" when the use clicks the bottom text box.

### PR DESCRIPTION
**Pull request by Bournvita1998**
### Description

Automatically toggle the radio button to "Create a page and save it" when the user clicks the bottom text box

Here are the screenshots after making the changes to the code:

[Before clicking "Create a page and save it"]
Selection_064

[After clicking "Create a page and save it"]
Selection_066

Fixes #13371 

Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
@sudo-bot Deploy PR

**Review by shucon — APPROVED** [review]

**Comment by shucon** [comment]
LGTM

**Comment by shucon** [comment]
@ibennetch @williamdes I think this PR is ready to be merged.

**Comment by zeenayouhan** [comment]
Automatically toggle the radio button to "Create a page and save it" when the user clicks the bottom text box

**Review by williamdes — APPROVED** [review]
Works fine :100:

**Pull request merged**
