### PR TITLE
Foreign key check checkbox for empty/drop table in db_structure

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by lem9** [comment]
Ok but this is only for the "With selected" drop-down, correct? It would be useful to implement this also for the Empty/Drop action links.

Also, please fix the merge conflicts.

**Comment by nisargjhaveri** [comment]
No, the one for "With selected" drop-down is already there. This is for the action links. This shows a checkbox in confirm dialog.

**Comment by lem9** [comment]
Ok my browser cache had not been cleared. I see the new checkboxes now. 

Please fix the merge conflicts.

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by lem9** [comment]
Nice work.

**Comment by nisargjhaveri** [comment]
Thanks. :)

Can you think of any other places where adding this might be useful?

**Comment by lem9** [comment]
Yes: in table Operations, there are Empty and Delete links.

**Pull request merged**
