### PR TITLE
Add SVG Icons and Logos

### PR DESCRIPTION
**Pull request by mkkeck**
- New folder resources for source files
  - SVG-Icons
  - SVG-Logos

Signed-off-by: Michael Keck <github@michaelkeck.de>

### CODE REVIEW

**Comment by ibennetch** [comment]
These are wonderful, thank you.

I do wonder if they would be better placed in https://github.com/phpmyadmin/data instead, but on the other hand, it doesn't really bother me to have them here.

**Comment by mkkeck** [comment]
@ibennetch
I think resources would be better than data. Data would be perhaps reserved for user data or app  data. Resources means, extra content and files, in raw format. But it doesn't bother me too.

**Comment by williamdes** [comment]
No update on this great PR ?
/rebase /squash ?

**Comment by mkkeck** [comment]
Hi all,
Sorry I am too busy at this moment. I am back in September or October. 

Kind regards 
Michael

**Comment by mkkeck** [comment]
Sorry for late response. I am ttoo busy at the moment, and one more big problem: My workstation is damaged (hardware failure) last week, so I've to buy some new soon as possible.

>  One more thing, your commit does not have the Signed-off-by line, which indicates that you agree with phpMyAdmin Developer's Certificate of Origin. This ensures that the work you're submitting is your own creation.

I've done as descriped, but how can I fix?

> We already have some logos on https://github.com/phpmyadmin/data, what do you think of them? And what do you think of transferring those files to that repository?

Yes I know. I've made these to ;). The newer ones are made mainly but not only for the app.

**Comment by mauriciofauth** [comment]
> I've done as descriped, but how can I fix?

You can add the signature line with `git commit -s`, but for this time you can add a comment with the signature line in this PR. For example:

```
Signed-off-by: Random Developer <random@developer.example.org>
```

**Comment by mkkeck** [comment]
Signed-off-by: Michael Keck <github@michaelkeck.de>

**Comment by mkkeck** [comment]
Signed-off-by: Michael Keck <github@michaelkeck.de>

**Comment by williamdes** [comment]
@mauriciofauth ? :)

**Comment by mauriciofauth** [comment]
Merged, thank you for your contribution!

**Pull request merged**
