### PR TITLE
Fixes #11325 and #11327.

### LINKED ISSUE #11325: Exporting database schema to PDF is broken
Broken in master branch. Generates a corrupted PDF file.

### PR DESCRIPTION
**Pull request by udan11**
Updated sql-parser library to udan11/sql-parser@0966688f69ff52f197378cce4e75014a9a5674f2.

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
For #11327 the DEFAULT part has been fixed, but there is still a space after BIT.

**Comment by lem9** [comment]
For #11325 it looks fine.

**Comment by udan11** [comment]
The extra space didn't cause any issues, but I removed it anyway.

**Comment by lem9** [comment]
True the extra space did not cause any issues but it did not fit with what we see in MySQL manual.

**Comment by lem9** [comment]
Please have a look at the failing test: PMA_ExportSql_Test::testReplaceWithAlias

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
