### PR TITLE
Move classes to PhpMyAdmin namespace

### PR DESCRIPTION
**Pull request by MauricioFauth**
I moved some classes to the `libraries/classes` directory and changed the namespace to `PhpMyAdmin` as discussed in the mailing list.

- Move Advisor to PhpMyAdmin namespace
- Move Bookmark to PhpMyAdmin namespace
- Move Charsets to PhpMyAdmin namespace
- Move Config class to PhpMyAdmin namespace
- Move Console class to PhpMyAdmin namespace
- Move Core to PhpMyAdmin namespace
- Move DatabaseInterface to PhpMyAdmin namespace
- Move DbList to PhpMyAdmin namespace
- Move DbQbe to PhpMyAdmin namespace
- Move DbSearch to PhpMyAdmin namespace
- Move DisplayResults to PhpMyAdmin namespace
- Move Encoding to PhpMyAdmin namespace
- Move Error to PhpMyAdmin namespace
- Move ErrorHandler to PhpMyAdmin namespace
- Move File to PhpMyAdmin namespace
- Move Font to PhpMyAdmin namespace
- Move Footer to PhpMyAdmin namespace
- Move Header to PhpMyAdmin namespace
- Move Index to PhpMyAdmin namespace
- Move IndexColumn to PhpMyAdmin namespace
- Move LanguageManager to PhpMyAdmin namespace
- Move Language to PhpMyAdmin namespace
- Move Linter to PhpMyAdmin namespace
- Move ListAbstract to PhpMyAdmin namespace
- Move ListDatabase to PhpMyAdmin namespace

Signed-off-by: Maurício Meneghini Fauth <mauriciofauth@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
As mentioned on the list, I'd prefer to have separate namespace for the classes shipped with phpMyAdmin and external ones. Having ``PhpMyAdmin\SqlParser`` as external library and ``PhpMyAdmin\Advisor`` as internal sounds confusing. See also https://github.com/phpmyadmin/sql-parser/issues/126

**Comment by mauriciofauth** [comment]
When you commented on the list, I didn't understand that this was your concern.

I understand the second level of the namespace as a kind of module. So I agree that external libraries have two levels. And for that reason too, I think it's okay not to have a sub namespace in the main library.

I think adding sub namespace like `PhpMyAdmin\Core` would end up losing the meaning a bit if used for all internal classes such as `PhpMyAdmin\Core\Plugins` and using `PhpMyAdmin\PhpMyAdmin` would get a bit repetitive. But I still prefer `PhpMyAdmin\Core` instead of `PhpMyAdmin\PhpMyAdmin`.

**Comment by nijel** [comment]
I'm not really sure what's best approach, but I think it would be confusing when looking into the code that some of PhpMyAdmin\* load from libraries/classes, while other from vendor libs...

**Comment by mauriciofauth** [comment]
@nijel, In fact this is very common in projects that modularize their components and it is common to use the same namespace.
When someone looks for `PhpMyAdmin\Advisor`, he will find it in `libraries/classes/Advisor` and when someone looks for `PhpMyAdmin\SqlParser`, as he will not find it in `libraries/classes/SqlParser`, he will find it in `vendor/phpmyadmin/sql-parser`.
This will become clearer when all classes are in a single location.

**Comment by nijel** [comment]
As I've said before - I don't really have strong opinion on this, so having input from other @phpmyadmin/developers is certainly welcome...

**Comment by ibennetch** [comment]
I admit I got a bit lost with the last round of comments.

> When someone looks for `PhpMyAdmin\Advisor`, he will find it in `libraries/classes/Advisor` and when someone looks for `PhpMyAdmin\SqlParser`, as he will not find it in `libraries/classes/SqlParser`, he will find it in `vendor/phpmyadmin/sql-parser`.

I have a slight preference to avoid this, but I'm not clear on what your position is. I also think `PhpMyAdmin\PhpMyAdmin` is repetitive and unnecessarily verbose, and sort of agree that using `PhpMyAdmin\Core` for every internal class is a bit much. So I don't have a good solution right now.

I suppose any good IDE would be able to tell a developer whether the library is in `./libraries/classes/` or `./vendor/phpmyadmin/` so perhaps this is really a non-issue.

**Comment by mauriciofauth** [comment]
Sometimes I get a little bit lost in English, but basically what I meant was what you said, @ibennetch.

My preference is to use `PhpMyAdmin`, but I accept using `PhpMyAdmin\Core`.

**Comment by nijel** [comment]
Okay, let's use just `PhpMyAdmin`...

**Comment by nijel** [comment]
Thanks, merged. And sorry for requesting changes there and back...

**Pull request merged**
