### PR TITLE
Logout position changed

### PR DESCRIPTION
**Pull request by keshakaneria**
Logout button placed on top right corner and removed from Navigation header.

### CODE REVIEW

**Comment by keshakaneria** [comment]
Sir are there changes to be made of solution acceptable?

**Comment by keshakaneria** [comment]
Sir, are there any changes to be made or solution acceptable?!

**Comment by williamdes** [comment]
@sudo-bot Deploy pr

**Comment by williamdes** [comment]
Hey @keshakaneria 
I am sorry but I do not accept the solution you proposed, thank you for contributing

**Pull request closed without merging**
