### PR TITLE
Fix #11383 Query formatting adds space between ! and =

### LINKED ISSUE #11383: Query format
Sample query that formatted wrong
`SELECT * FROM table WHERE row != 1`
`!=` this changes to `! =` (with a space)

Version information: 4.5.0-dev, latest stable version: 4.4.13.1

### PR DESCRIPTION
**Pull request by madhuracj**

### CODE REVIEW

**Comment by lem9** [comment]
@udan11 Please have a look at this.

**Comment by udan11** [comment]
I consider this [one](https://github.com/udan11/sql-parser/commit/aef354a430d329edcbf12843f8047ef27cb9470c) a better fix.

**Comment by lem9** [comment]
@udan11 Could you send a pull request to facilitate testing?

**Comment by udan11** [comment]
@lem9 #11388

**Comment by lem9** [comment]
Thanks but @udan11 fix looks cleaner.

**Comment by madhuracj** [comment]
Agreed.

**Pull request closed without merging**
