### PR TITLE
Improved Filtering in server variables page

### LINKED ISSUE #15174: Improve Filter Method in server variables page
### Is your feature request related to a problem? Please describe.
Right now, the variables can filtered based on the single word present in the variable name or not. Some words are present in a lot string for example 'aria'. 

Screenshot 2019-04-11 at 2 54 08 AM

### Describe the solution you'd like
Instead of searching variable with only a word. Support for full variable name can be provided.

### PR DESCRIPTION
**Pull request by Bournvita1998**
Signed-off-by: Bournvita1998 <mohit.kuri@research.iiit.ac.in>

### Description

The issue here was that the values were stored with no spaces, all spaces have been converted to underscore. But while searching, we were directly using the values with spaces(which won't give us the correct results). Thus I removed all the spaces and converted them into underscore so that we could search the complete string.

Fixes #15174 

Before submitting the pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by Bournvita1998** [comment]
Earlier:

Selection_033

Now:

Selection_032

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by AghaSaad04** [comment]
@williamdes, the above solution proposed by @Bournvita1998 works only for two words, not for multiple. As it replaces only 1 space with an underscore.
I have fixed this and opened up a new PR.

**Comment by Bournvita1998** [comment]
Thanks @AghaSaad04, I have resolved the requested change.

**Comment by Bournvita1998** [comment]
Hi @AghaSaad04!
Just a suggestion, if you find any issue with someone's PR, you must comment and wait for the author so that they could resolve that. Creating a different PR for the same issue when there already exists a PR (under review) is not a good practice.
Thanks!

**Comment by AghaSaad04** [comment]
Thanks, @Bournvita1998. I have just closed mine :)

**Comment by williamdes** [comment]
@sudo-bot Deploy pull-request

**Review by williamdes — APPROVED** [review]
@Bournvita1998 Thanks for your contribution !

**Pull request merged**
