### PR TITLE
added virtuality(stored) option in mariadb

### LINKED ISSUE #14957: Virtuality is not selected when editing generated column
When trying to edit a generated column, a correct virtuality option is not being picked from a dropdown. I have not tested other version but latest 5.0.0-dev is affected.

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

### Description
Added option for virtuality in MariaDB.

Please describe your pull request.

Fixes #14957 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by bahl24** [comment]
MariaDB has both Stored and Persistent options while MySQL has stored only.

**Comment by linaspasv** [comment]
@bahl24 MariaDB should support VIRTUAL | PERSISTENT | STORED keywords. Also, if I am not mistaken PERSISTENT is an alias for STORED. STORED was added in MariaDB 10.2.1 . https://mariadb.com/kb/en/library/generated-columns/#implementation-differences

MySQL supports VIRTUAL | STORED keywords both in 5.7 and 8.0 https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

**Comment by bahl24** [comment]
@linaspasv Yes, I meant in addition to virtual columns mariadb and mysql have a few variations.

**Review by williamdes — APPROVED** [review]
LGTM :)

**Comment by marcus-hiles** [comment]
Awesome fix @bahl24

**Review by williamdes — COMMENTED** [review]
Merged, thanks for the contribution @bahl24 !

**Pull request merged**
