### PR TITLE
Page-related settings, rfe#1559

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by lem9** [comment]
Nisarg,
please have a look at https://scrutinizer-ci.com/g/phpmyadmin/phpmyadmin/inspections/b52e18d6-e64a-4e77-832e-e2563f2e9baf/issues/

**Comment by nisargjhaveri** [comment]
I'll have a loot at those. Also, I realized that I've also missed a couple of issues, like the original theme is not updated yet. I'll fix them today.

**Comment by lem9** [comment]
Nisarg,
just found another problem. This commit breaks the display under /setup. For example, visit phpmyadmin/setup and click on Feature. All sections are displayed at once on the page.

**Comment by nisargjhaveri** [comment]
Also, validation is broken, even in `QA_4_4`. It shows error in console "PMA_messages is not defined.". Looking into it.

**Comment by nisargjhaveri** [comment]
See #1693.

**Comment by lem9** [comment]
Fixed in https://github.com/phpmyadmin/phpmyadmin/commit/a723e049eb51a5f9344e295c5271be0979a4ce80

**Pull request merged**
