### PR TITLE
Fix - French mistake in the genre of the word "space" Signed-off-by: Stanislas Brodin <stanislas.brodin@gmail.com>

### PR DESCRIPTION
**Pull request by sbrodin**
Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by williamdes** [comment]
Pour le signoff il faut `git commit --amend --signoff` et force push.
You need to use Weblate for translations, they will not merge this PR.

**Comment by williamdes** [comment]
@sbrodin By the way I disagree with the use of `une espace`. For me this has no sense.
@lem9 What do you think about the modifications proposed ?

**Comment by sbrodin** [comment]
@williamdes When used in the meaning of the typo character space, "espace" is feminine. When used in the meaning of a surface or volume, it is masculine.

**Comment by williamdes** [comment]
@sbrodin After researching on Internet, you are right. I am shocked by this discovery, I will sleep less stupid thanks to you :)

**Comment by williamdes** [comment]
Go to https://hosted.weblate.org/projects/phpmyadmin/4-8/fr/

**Comment by lem9** [comment]
@williamdes Sorry I don't receive github notifications but indeed it should be « une espace » in this case.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/13dfc93da6988762772d360d1f3cae88f0a7a087

**Comment by lem9** [comment]
So this can be closed.

**Comment by williamdes** [comment]
@sbrodin Not very one browsed internet and changes of point of view, 2a7294a9329889656bc226b00ca5f71f3918f558 reverts you commit

**Pull request closed without merging**
