### PR TITLE
Port some templates to Twig

### PR DESCRIPTION
**Pull request by MauricioFauth**
Signed-off-by: Maurício Meneghini Fauth <mauriciofauth@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by mauriciofauth** [comment]
@nijel, Why 4.7.1 milestone? Both #13100 and #13207 have 4.8.0 milestone.

**Comment by nijel** [comment]
Sorry, it was merged to master, I've set wrong milestone here...

**Comment by mauriciofauth** [comment]
Related to #13297

**Pull request merged**
