### PR TITLE
Fix #14673 - innodb & MySQL 8: DYNAMIC & COMPRESSED ROW_FORMAT missing

### LINKED ISSUE #14673: innodb & MySQL 8: DYNAMIC & COMPRESSED ROW_FORMAT missing
### To Reproduce

1. upgrade to MySQL 8, Go to any table,
2. press Operations
3. try to change ROW_FORMAT of that table 
4. Dropdown shows only Compact and redundant formats.

### Expected behavior
Dynamic and Compressed format should be available

### Fix:
code of this method in Operations class
```
    private function getPossibleRowFormat(){
        $possible_row_formats = array(
            'ARCHIVE' => array(
                'COMPRESSED' => 'COMPRESSED',
            ),
            'ARIA'  => array(
                'FIXED'     => 'FIXED',
                'DYNAMIC'   => 'DYNAMIC',
                'PAGE'      => 'PAGE'
            ),
            'MARIA'  => array(
                'FIXED'     => 'FIXED',
                'DYNAMIC'   => 'DYNAMIC',
                'PAGE'      => 'PAGE'
            ),
            'MYISAM' => array(
                 'FIXED'    => 'FIXED',
                 'DYNAMIC'  => 'DYNAMIC'
            ),
            'PBXT'   => array(
                 'FIXED'    => 'FIXED',
                 'DYNAMIC'  => 'DYNAMIC'
            ),
            'INNODB' => array(
                 'COMPACT'  => 'COMPACT',
                 'REDUNDANT' => 'REDUNDANT',
		  'DYNAMIC' => 'DYNAMIC',
		  'COMPRESSED' => 'COMPRESSED'
            )
        );
        return $possible_row_formats;
    }
```

### PR DESCRIPTION
**Pull request by latifolia**
Signed-off-by: Nugroho Latifolia <nugroho.latifolia@gmail.com>

**Description**

Newer MySQL/MariaDB deprecated all InnoDB File Format parameters, so on PHPMyAdmin Table Operations only show ROW FORMAT to COMPACT & REDUNDANT excluding DYNAMIC & COMPRESSED. This proposed patch will support future generations of MySQL/MariaDB while preserving backward compatibilities with older generations.

Fixes #14673

```php
       /*
        Newer MySQL/MariaDB always return empty a.k.a '' on $innodb_file_format otherwise
        old versions of MySQL/MariaDB must be returning something or not empty.
        This patch is to support newer MySQL/MariaDB while also for backward compatibilities.
        */

        if ( (('Barracuda' == $innodb_file_format) || ('' == $innodb_file_format))
            && $innodbEnginePlugin->supportsFilePerTable()
        ) {
            $possible_row_formats['INNODB']['DYNAMIC'] = 'DYNAMIC';
            $possible_row_formats['INNODB']['COMPRESSED'] = 'COMPRESSED';
        }
```
Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by ibennetch** [comment]
Hi, thanks for your submission. It appears you've accidentally targetted the QA_4_8 branch when this was created against master. No big problem, at the very top of this page is an Edit button where you can edit the title and, just under that, select the branch. You can change there from QA_4_8 to master and that will update the whole pull request.

**Review by williamdes — APPROVED** [review]

**Review by williamdes — COMMENTED** [review]
Merged, thanks for your contribution @latifolia !
I rebased onto `QA_4_8` and added some spaces

**Comment by makuser** [comment]
@latifolia your fix was highly appreciated!
I can confirm it finally fixes some ugly errors when changing something like the auto incremental counter, because now the right ROW_FORMAT is automatically selected, because the actual current setting is available for selection now. ROW_FORMAT was a setting that I did not change before, but it led to errors after hitting `OK`, due to the fact DYNAMIC was not available prior to applying the fix, which I did not see and it led to quite some confused moments until I noticed it.

So thanks again for fixing that! I'm looking forward to when it will finally make its way into a release.

**Comment by williamdes** [comment]
> I'm looking forward to when it will finally make its way into a release.

@makuser You can download `phpMyAdmin 4.9.0.1` on our [website](https://www.phpmyadmin.net/downloads/), it includes this fix

**Comment by makuser** [comment]
> > I'm looking forward to when it will finally make its way into a release.
> 
> @makuser You can download `phpMyAdmin 4.9.0.1` on our [website](https://www.phpmyadmin.net/downloads/), it includes this fix

Thanks for the info, seems like it was released yesterday. That's great to see! I installed it and it works as expected.

Thanks :)

**Pull request merged**
