### PR TITLE
Allow Custom number of rows to be inserted

### PR DESCRIPTION
**Pull request by shucon**
Enhances : https://github.com/phpmyadmin/phpmyadmin/issues/13578

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by mauriciofauth** [comment]
One of the unit tests failed. See [Travis-CI](https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/318246875#L698).

**Comment by shucon** [comment]
@mauriciofauth I fixed the previous tests that failed , but now the selenium test has failed.
Kindly help me with same.

**Comment by devenbansod** [comment]
Hi @shucon the Selenium testsuite sometimes fails due to unexpected network delays. I've re-ran the selenium tests and they seem to be passing now. So the CI is green.

**Comment by shucon** [comment]
Thanks @devenbansod

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
