### PR TITLE
removed disabled attribute

### LINKED ISSUE #15695: Input field for the time in datetime picker is disabled
### Describe the bug

When we click on the calendar button to insert timestamp for a column in the insert tab the input field for time is disabled, whereas while editing a timestamp value from browse tab the input field is not disabled.

### To Reproduce

1. Create a column in a table with type TIMESTAMP.
2. Go in insert tab and click on the calendar button near the input field of that column.
3. You will see that the input filed for time is disabled.

### Expected behavior

The input field for time must not be disabled.

#### In insert tab 
insert_timestamp_issue

#### In browse tab

issue_timestamp

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

Please describe your pull request.

Fixes #15695 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
@yashrajbothra I am sorry but we can not merge your contribution since it modifies a vendor file.
Can you find another way to fix the issue ?

**Comment by yashrajbothra** [comment]
Okay,So should i close the pull request and revert changes or can i do another commit??

**Comment by williamdes** [comment]
@yashrajbothra I prefer to avoid closing pull-requests 
The better solution would be to hard reset to the commit before yours (`git log --graph`) and make a new commit to fix the issue
then use `git push --force`

**Comment by yashrajbothra** [comment]
is this okay ??

**Comment by williamdes** [comment]
@yashrajbothra the branch history is strange beacuse you did not rewrite the history
please apply
```
git checkout issue-15695
git reset --hard origin/QA_4_9
git cherry-pick d20b6ce6f8b20b3c55a486d8dc1591426b006664
git push --force
```

**Review by williamdes — APPROVED** [review]

**Comment by yashrajbothra** [comment]
thanks @williamdes for helping me out

**Comment by williamdes** [comment]
Merged, thank you for your contribution @yashrajbothra !

**Pull request merged**
