### PR TITLE
Add word wrap in export option heading-2 (H2)

### PR DESCRIPTION
**Pull request by anantjain6**
Patch #13745
Signed-off-by: Anant Jain <anantjain60@gmail.com>

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
The same code probably should be added to the original theme.

**Comment by anantjain6** [comment]
@nijel Thanks for notifying it to me
I added a commit 1acd230

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by anantjain6** [comment]
My pleasure

**Pull request merged**
