### PR TITLE
Remove inline js

### PR DESCRIPTION
**Pull request by nikkolai14**
#13270

### CODE REVIEW

**Comment by nikkolai14** [comment]
Oops, sorry guys. I forgot to squash it on my end....

**Comment by williamdes** [comment]
> Oops, sorry guys. I forgot to squash it on my end....

No worries you can still do it and force push **without closing this pull-request** :)

**Comment by nikkolai14** [comment]
> > Oops, sorry guys. I forgot to squash it on my end....
> 
> No worries you can still do it and force push **without closing this pull-request** :)

Can you please guide me with the process using GitKraken? I tried to research but i'm kinda lost what to do, thanks for your help! :)

**Comment by williamdes** [comment]
> > > Oops, sorry guys. I forgot to squash it on my end....
> > 
> > 
> > No worries you can still do it and force push **without closing this pull-request** :)
> 
> Can you please guide me with the process using GitKraken? I tried to research but i'm kinda lost what to do, thanks for your help! :)

So you will need to do:
- Add a remote to `https://github.com/phpmyadmin/phpmyadmin.git` or execute `git remote add phpmyadmin https://github.com/phpmyadmin/phpmyadmin.git`
- Fetch the data or execute `git fetch --all -p`
- Right click on the last commit before yours and do `Reset > Reset soft` or execute `git reset --soft ReplaceCommitHashHere`
- Commit all your changes
- Push your changes and force or execute `git push --force`

I hope you will find how to do :)

Alternative method (could not work properly):
- Add remote
- Fetch
- Right click on the last commit before yours and choose `interactive rebase` or execute `git rebase --interactive`
- Put all to squash
- Commit
- Push

**Comment by nikkolai14** [comment]
@williamdes I think I made it, thanks! :) but now, we have conflicting files... how can I fix this on my end? thanks

**Comment by williamdes** [comment]
> @williamdes I think I made it, thanks! :) but now, we have conflicting files... how can I fix this on my end? thanks

 :) 
You can click on the latest commit of `master` branch and choose rebase or `git rebase phpmyadmin/master`
If you have conflicts you will be able to fix them using GitKraken or any editor 
Then force push

**Comment by nikkolai14** [comment]
> > @williamdes I think I made it, thanks! :) but now, we have conflicting files... how can I fix this on my end? thanks
> 
> :)
> You can click on the latest commit of `master` branch and choose rebase or `git rebase phpmyadmin/master`
> If you have conflicts you will be able to fix them using GitKraken or any editor
> Then force push
> 
> PS: I think you squashed some commits that where not yours, so you will have some "non conflicts" to fix. Anyway using the interface this will be easy. (learning git is hard at the start but after you will rock  )
> 
> This will maybe be complicated to fix, if so let me know and I will fix this for you like I would have done before merging a PR

I'm not sure if I had squashed commits which are not mine because I used your method #1 from above. I can't proceed to do a rebase because there is a merged conflict, maybe I'll let you handle this if you would mine? thank you! :)

**Comment by williamdes** [comment]
> I'm not sure if I had squashed commits which are not mine because I used your method 1 from above. I can't proceed to do a rebase because there is a merged conflict, maybe I'll let you handle this if you would mine? thank you! :)

Sure, I fixed the situation :)
This one was tough, tips: before any new work and pull-request: reset hard on the last commit of `phpmyadmin/master` and create your branch (a hard reset destroys any change done locally, do not use it if you want to keep changes)

Once your workspace is clean, you can work on your next pull-request.

PS: to have your changes from my/your last commit, select the remote commit and `Reset > Reset hard`

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
