### PR TITLE
Fix broken sort

### LINKED ISSUE #13931: Sort is broken
The sort feature [clicking on a field] is broken on a table. It opens the insert page instead - see the video: https://streamable.com/olyx9

Server version: 5.7.20-log - MySQL Community Server (GPL)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Web server
    Apache
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.0.7

phpMyAdmin
    Version information: 4.7.7 (up to date)

Microsoft Windows Server 2012 R2

### PR DESCRIPTION
**Pull request by MauricioFauth**
Fix #13931 

Related to #13887

### CODE REVIEW

**Review by nijel — CHANGES_REQUESTED** [review]
Seems like some fixes from master are still missing. Here is list of related fixes in master and at least first few ones are missing, I haven't checked rest:

* 1fc566fd90 Share code for parsing data-post attribute
* 2bc87216f0 Adjust RTE oprations to use POST
* 613a146e97 Adjust field drop to use POST
* 7508205191 Adjust optimize table to use POST
* 599a981b50 Adjust partition manipulations to use POST
* e7eaea8c86 Adjust browsing distinct values to use POST
* 6ee2f12841 Adjust adding table key operations to use POST
* 8332861d62 Adjust table drop operation to use POST
* ff20564ef0 Adjust table truncate operation to use POST
* 99e9854473 Always use POST for links containing SQL query
* 816c42665a Add tests for Util::linkOrButton
* 3b9fb2b664 Simplify handling of long URLs in Util::linkOrButton

**Comment by mauriciofauth** [comment]
@nijel How about now?

**Comment by nijel** [comment]
I think it's good to merge now, thanks! Still this needs heavy testing now to discover possible breakages...

**Comment by devenbansod** [comment]
This should ideally fix the issue at #13887 too, right?

**Pull request merged**
