### PR TITLE
Add support for Ctrl + C

### PR DESCRIPTION
**Pull request by Achilles-96**
Go to database structure of any database, select some tables and press `ctrl + c`. If you like this functionality, we can implement this wherever possible to enhance usability. Shortcuts do increase speed of work.

Signed-off-by: Raghuram Vadapalli raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by lem9** [comment]
Please read this thread: https://lists.phpmyadmin.net/pipermail/developers/2015-October/thread.html

**Comment by Achilles-96** [comment]
@lem9 Is there any scheme that PMA follows for not clashing with browser's shortcuts(I mean, is any scheme followed for coming up with `ctrl+enter`). If there isn't anything, then I'll try to come up with reasonable shortcuts myself.

**Comment by lem9** [comment]
@Achilles-96 I could not find any doc related to this on wiki.phpmyadmin.net, but you are right, it's needed. It's a tricky problem, because of the difference between browsers for shortcut implementation, and also what they will do in the future. That's why we never used many shortcuts. You may restart the discussion on the developers mailing list, or ask there for more participation here.

**Comment by guillesalazar** [comment]
Hi all! I saw @Achilles-96 invitation on the developers mailing list. I think we could start with a basic list/chart/table of well known browser shortcuts to start with a list of them that we *can't use* and then take it from there. I think implementing them is an amazing idea.

**Comment by ibennetch** [comment]
I think it's a good idea to make a list in the wiki. Please see https://wiki.phpmyadmin.net/pma/Shortcut_keys for the beginnings of that page.

I'm slightly in favor of having some shortcut keys, but these should be discussed and care should be used to avoid overriding browser functionality.

**Comment by lem9** [comment]
Stealing CTRL+C is IMO one of the worst things you can do. It's a common convention to copy text that has been selected.

**Comment by Achilles-96** [comment]
I didn't consider clashing with browser while making this PR. I'll update once new shortcuts are decided.

**Comment by Achilles-96** [comment]
Please refer #11865.

**Pull request closed without merging**
