### PR TITLE
Fix  #12979: Fixed column alignment on foreign keys table.

### LINKED ISSUE #12979: Foreign keys table layout
The vertical alignment here looks weird..
Especially in row 2 but also in row 1 fields column.

pma

### PR DESCRIPTION
**Pull request by souravbadami**
Signed-off-by: Sourav Badami souravbadami@gmail.com

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by souravbadami** [comment]
@ibennetch -- Could you PTAL ?

**Comment by ibennetch** [comment]
This fixes the reported problem for me, however I haven't had a chance to see if there are other unintended side-effects.

**Comment by nijel** [comment]
As this changes quite generic CSS, there are side effects, for example table structure is now also top alligned:

localhost_localhost_bar2_phpmyadmin_4 7 0-beta1_-_2017-02-20_11 40 02

What IMHO looks worse than original middle aligned:

localhost_localhost_bar2_phpmyadmin_4 7 0-beta1_-_2017-02-20_11 40 54

**Comment by nijel** [comment]
You probably need to add the class in the code which adds fields?

**Comment by souravbadami** [comment]
I did. But the problem is -- Initially I set up the alignment and it fixes the issue. But there's another option below to add new rows. When a new row is added, It gets a bit out of sync. Still, I'll try to figure out a solution.

**Pull request closed without merging**
