### PR TITLE
feature 844 structure in PDF export

### PR DESCRIPTION
**Pull request by whitepiegon**
Signed-off-by: Aayush Anand aayushism12@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Nice work. See my comment about translatability.

**Comment by whitepiegon** [comment]
Thanks Marc..
Also I got your point regarding translatibility. I will take care of that from next time. Should I correct that and commit again in this pull request?

**Comment by lem9** [comment]
Yes.

**Comment by whitepiegon** [comment]
Please see if everything is fine now.

**Comment by lem9** [comment]
It looks fine; please squash.

**Comment by lem9** [comment]
Nice work.

**Comment by whitepiegon** [comment]
thanks Marc for guiding me.. :)

**Comment by lem9** [comment]
See 1353a7972056ae1ed3b90b5805a22bda74227fdb

**Pull request merged**
