### PR TITLE
Allow for redirects without showing a error

### LINKED ISSUE #19425: UrlRedirector doesn't work when an extension is missing
### Describe the bug

UrlRedirector doesn't work when an extension is missing.

#19422

### To Reproduce

1. Disable a required extension
2. Click on links
3. See error

### Expected behavior

It should redirect to the extension link.

### Screenshots

https://github.com/user-attachments/assets/f7be8bd8-0b18-4981-9bf3-50e4585cc987

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by marcandreher**
### Description

This allows the user to click the URL provided in the error message to be redirected. Previously, it would just display the same error again.

Fixes #19425

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by marcandreher** [comment]
I failed the signing for this

**Comment by kamil-tekiela** [comment]
`git commit --amend -s`

**Comment by marcandreher** [comment]
should I redo the pr?

**Comment by kamil-tekiela** [comment]
No need. Just push the changes here. After you add the signature, you can do `git push -f`

**Pull request closed without merging**
