### PR TITLE
country_code is defined as NOT NULL, yet INSERT lacks a value!

### PR DESCRIPTION
**Pull request by johnkershaw**
Without a country_code for 'Marc' the second step will fail (cannot relate country_code in REL_persons to country_code in REL_countries if the REL_persons record has no value for country_code).

Since this is the whole point of this example it's going to trip people up who're trying to set up relations in phpMyAdmin (like me!)

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
@johnkershaw I will merge this immediately if you add your signoff line (you can send it as a comment here)

And BTW you can rename all `TYPE=` to `ENGINE=` :)

**Comment by ibennetch** [comment]
This change can go in to QA_4_9. William, I'd suggest merging it to your own repository, then cherry-picking that commit in to your QA_4_9 branch. You can then merge QA_4_9 into master.

Probably like this:

```
git checkout -b johnkershaw-patch-1 master
git pull git://github.com/johnkershaw/phpmyadmin.git patch-1
git checkout QA_4_9
git cherry-pick 1e72dd6c4c27a15d98bdc1d884f639ab5fc0772d
```

Note that the commit ID will change after John fixes the signoff line, so you'll need to substitute the correct ID there instead.

**Comment by johnkershaw** [comment]
Signed-off-by: John Kershaw <john@kershaw.org>

**Comment by johnkershaw** [comment]
Ah, yes, I had to delete all the references to TYPE= to get it to work (I was testing on db4free.com as a prelude to a unit I'm teaching on databases this semester).

**Comment by williamdes** [comment]
Thanks @johnkershaw !

> I'm teaching on databases this semester

Have a good semester with your students :)


Merged as 26373240cdf112bec3862f4a1c5b9dba705c6e1e
I rebased your commit and added some changed (ecad5995abf64b5f2a3e7e240bb16cd8ed3be587)

**Pull request merged**
