### PR TITLE
typo

### PR DESCRIPTION
**Pull request by lucatrev**

### CODE REVIEW

**Comment by Tithugues** [comment]
Hi,
If you agree with our DCO, can you please sign your commit with "-s" option?
`commit -sm "typo"`
Thanks.

**Comment by luke83** [comment]
I'm agree with DCO, but I'm using github Web interface from smartphone.. Is there any way to sign the commit from here?

**Comment by lem9** [comment]
Translations do not really require accepting our DCO. Next time please use our on-line translation server at https://hosted.weblate.org/engage/phpmyadmin/.

**Comment by luke83** [comment]
Thanks @lem9

**Pull request merged**
