### PR TITLE
Enabled lint for console.

### PR DESCRIPTION
**Pull request by udan11**
Enabled lint for console.
Updated sql-parser library to udan11/sql-parser@5e554b3.

Signed-off-by: Dan Ungureanu udan1107@gmail.com

### CODE REVIEW

**Comment by Tithugues** [comment]
Hi,
Would it be possible to get your sql-parser from comporser, instead of including it in pMA sources ?
Thanks.

**Comment by udan11** [comment]
@Tithugues I proposed using Composer in the past. There's been a discussion on the mailing list. I can't link to you now because Sourceforge is in maintenance mode, but as soon as it's up you can look for "Outdated libraries", that was the subject of the discussion.

**Comment by lem9** [comment]
@udan11 Apart from the "Outdated libraries" discussion, I believe that you and I had a discussion specifically about this library. I can't seem to find it right now, but I remember that the outcome was to not use Composer for this library. Any insight you could give about this other discussion?

**Comment by lem9** [comment]
Nice work.

**Comment by udan11** [comment]
From "[Phpmyadmin-devel] Parser and uppercase characters". The quoted text is my question.

```
> The other question I have is about autoloading classes. For this library
> I used the autoloader that is generated by Composer. However, phpMyAdmin
> does not use Composer for managing dependencies and showed no interest
> in starting using it (I proposed it in the past), so now I have to find
> a way to include the required files. Possible solutions: a) manually
> include each class in each file; b) include all files in the beginning;
> c) use the generated Composer autoloader; d) write another smaller
> autoloader. I think that c) is the best solution, but I would love to
> hear your opinions as well.

Looks like c) is the best, but I'm not familiar enough with Composer to
be sure, so I'll welcome other opinions.
```

**Comment by lem9** [comment]
Given that the library's error messages will be localized using phpMyAdmin's gettext mechanism, is it still relevant to include it via Composer instead of being directly in the repo?

**Comment by udan11** [comment]
I did my best to make the library independent of any other component, but making it independent of phpMyAdmin's gettext mechanism would require implementing a new system for handling translations and it's not worth it and would also complicate the translation process a lot.

I still think that the best method to manage the libraries is via Composer, even though they are localized by phpMyAdmin.

**Comment by lem9** [comment]
But I suspect that the way you implemented it in the other pull request, won't work.

**Pull request merged**
