### PR TITLE
MySQL 5.7 Syntax for password change

### PR DESCRIPTION
**Pull request by hkandala**
http://sourceforge.net/p/phpmyadmin/feature-requests/1620/
Will use the preferred syntax for changing password i.e ALTER USER if MySQL version is >= 5.7.6

Signed-off-by: harish095 kandalaharish95@gmail.com

### CODE REVIEW

**Comment by nijel** [comment]
Have you tested this with MariaDB as well? I think it does not support ALTER USER, while it reports higher version than you're testing.

**Comment by harish095** [comment]
No, I haven't tested with MariaDB. It would be a great help if you do that for me. I don't think it would be a problem as I am checking it with PMA_MYSQL_INT_VERSION constant

**Comment by lem9** [comment]
This constant applies to both MySQL and MariaDB.

**Comment by harish095** [comment]
So, is there any way to check if the database is MySQL?

**Comment by lem9** [comment]
See libraries/Util.class.php in the getServerType() function. This is used in index.php.

**Comment by harish095** [comment]
Used the getServerType() to check that server is using MySQL. Hope it resolves the issue. Thanks a lot Marc!

**Comment by lem9** [comment]
Ok, it works when tested on MySQL 5.7.6, however there is a unit test failure, can you fix it? See the travis report.

**Comment by harish095** [comment]
Unit test is saying that PMA_MYSQL_VERSION_COMMENT constant is undefined. I checked the DatabaseInterface.class.php where that constant is defined to see if there is a possibility such that constant is undefined. I can't find anything there. Please suggest me. I will try to fix it.

**Comment by lem9** [comment]
I fixed the unit test : d9fdf6b9aa6a0dcd494ffebfa2e26e1f1eb0050f. To explain the context: when running unit tests, the code is not really connected to a MySQL server so we have to compensate. I also squashed your commits and put a proper signature: dbba36e0b84a62573be7422d3d863cfb0a1d6af0

**Comment by harish095** [comment]
Thanks Marc!

**Pull request closed without merging**
