### PR TITLE
Fix charset error when creating/editing routines; bug #13889

### PR DESCRIPTION
**Pull request by williamdes**
Added an if in order to not add charset for ```VARBINARY``` and ```BINARY```
Fixes the issue #13889

### CODE REVIEW

**Comment by williamdes** [comment]
Travis CI not passing because the website of hypersecu is "DOWN"
[* `HyperFIDO <https:// www.hypersecu.com/products/hyperfido>
](https://raw.githubusercontent.com/phpmyadmin/phpmyadmin/af69e3b7ac32da451725bd491f2d940ab391759e/doc/two_factor.rst)

**Comment by williamdes** [comment]
@lem9 @nijel @ibennetch 
Someone can merge this PR ?

**Review by nijel — CHANGES_REQUESTED** [review]
I think this is wrong approach - it should be rather fixed server side to not generate CHARSET part of the query in this case.

Your approach will lead to problems as well in case user changes the type several times - the charset field will be emptied leading to losing this information while editing.

**Comment by williamdes** [comment]
@nijel I fixed the server side, I had to close/reopen this issue to re trigger the Travis-ci build, because the apple task was not starting..., I hope it didn't spam you with notifications.

**Comment by williamdes** [comment]
@nijel I fixed the server side, are my modifications OK ?

**Comment by williamdes** [comment]
@nijel ?

**Comment by williamdes** [comment]
@ibennetch @nijel Can someone review my changes?

**Comment by nijel** [comment]
It looks better now, can you please adjust indentation of the nested block?

**Comment by williamdes** [comment]
@nijel I corrected the indentation of the nested block.
Merge ?

**Comment by williamdes** [comment]
@nijel I corrected the indentation of the nested block.
Merge ?

**Comment by williamdes** [comment]
@nijel can you merge this PR ?

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
