### PR TITLE
Added LOCK=NONE to ALGORITHM=INPLACE

### LINKED ISSUE #15312: Option to Perform ALTER ONLINE (or ALGORITHM=INPLACE)
When editing the structure of a table, it would be nice to have an option next to the "Preview SQL" button to try an Online Transaction.

image

This would perform the ALTER TABLE with either:

ALTER ONLINE or ALGORITHM=INPLACE

Many times, I want to try to see if I can make a change in the database without locking the table. I could simply select this option and try. If it gives an error saying it's not possible to perform online, then I can try again when the traffic is low.

At the moment, the way I do it is by doing "Preview SQL", copy the generated SQL, and add the word "ONLINE" to it, and try the SQL manually.
Having this checkbox would be a nice feature to avoid these extra steps :)

Thank you.

### PR DESCRIPTION
**Pull request by kartik1000**
Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description

The PR is in addition to Enhancement#15420 to add LOCK=NONE. while doing an online transaction.

Fixes #15312 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by nunoperalta** [comment]
Yup - looks perfect to me!

**Comment by kartik1000** [comment]
@williamdes Please Review.

**Review by williamdes — CHANGES_REQUESTED** [review]
"To avoid accidentally making the table unavailable for reads, writes, or both, specify a clause on the ALTER TABLE statement such as LOCK=NONE (permit reads and writes) or LOCK=SHARED (permit reads). The operation halts immediately if the requested level of concurrency is not available."
https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl.html

https://stackoverflow.com/a/57137660/5155484

I am not sure that forcing the options together is the best idea
Maybe adding another option could be an idea?

**Comment by williamdes** [comment]
@nunoperalta what are your thoughts on this?

**Comment by nunoperalta** [comment]
I think no change needed here.
What you quoted seems to be the expected.

We're asking phpMyAdmin to do an ONLINE transaction, so "LOCK=NONE" is the way to go.

If MySQL/MariaDB will be able to make the transaction without locking (allowing Reads and Writes), then it will proceed.
Otherwise, an error will be returned, saying that this ALTER TABLE cannot be done online.


The StackOverflow question you mentioned doesn't seem to be the expected behavior. Could be a bug in MySQL 5.6, or the person could be doing something else wrong.

LOCK=NONE should definitely never lock the table, and an error will be returned if the database doesn't allow the online transaction.

To me, this PR can be approved.

**Comment by nunoperalta** [comment]
> I am not sure that forcing the options together is the best idea
> Maybe adding another option could be an idea?

I don't see why wouldn't it be a good idea.

MariaDB's "ALTER ONLINE" is equivalent to "LOCK=NONE".

MySQL's way of doing ALTER ONLINE is also with "ALGORITHM=INPLACE, LOCK=NONE"


This page is saying that exactly: https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl.html

> ALTER TABLE tbl_name ADD PRIMARY KEY (column), ALGORITHM=INPLACE, LOCK=NONE;

> To avoid accidentally making the table unavailable for reads, writes, or both, specify a clause on the ALTER TABLE statement such as LOCK=NONE (permit reads and writes)

> To avoid tying up the server with an ALTER TABLE operation that copies the table, include ALGORITHM=INPLACE. The statement halts immediately if it cannot use the in-place mechanism.


Therefore, the safest thing to do is:

> ALGORITHM=INPLACE, LOCK=NONE;




https://stackoverflow.com/questions/35424543/alter-table-without-locking-the-entire-table

> "It should happen automatically, but to be sure set ALGORITHM=inplace and LOCK=none to your ALTER TABLE statement."

https://dev.mysql.com/doc/refman/5.6/en/innodb-online-ddl.html

**Review by williamdes — APPROVED** [review]
Okay, that you for explaining this to me

This solution is the right one

**Comment by nunoperalta** [comment]
Awesome! Thank you both! :)

**Comment by williamdes** [comment]
Thank you for your patience and help :tada: 
I always prefer to understand what I merge ;)

**Pull request merged**
