### PR TITLE
Fixes Table Highlighting

### LINKED ISSUE #13015: Table header highlighting with pmahomme theme
On certain pages, with the pmahomme theme, hovering over a table `<th>` element (usually a header) causes it to highlight. You can compare this to the original theme which does not seem to do so. I propose that pmahomme shouldn't either.

For Relation view, it occurs for all the tables on the page; here's a screenshot of one of them:
screen shot 2017-02-19 at 8 36 46 am

I also notice this behavior on the Charsets tab (where the table headers of "Collation" and "Description" don't have any style; compare to the Engines tab which looks great). The rest of the Charsets page probably could use some improvement as well, but that probably deserves a new issue.

### PR DESCRIPTION
**Pull request by shucon**
Fixes https://github.com/phpmyadmin/phpmyadmin/issues/13015

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by shucon** [comment]
@ibennetch please review the changes

**Comment by shucon** [comment]
@nijel can you please review the changes.

**Comment by mauriciofauth** [comment]
@shucon The table header highlighting has been fixed, but the style is not consistent with the other tables.

**Comment by shucon** [comment]
@mauriciofauth the table looks exactly the same as it was before, except the hover part.
I am thinking that we should open a new issue for the same, else can you suggest me what the table should look like.

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
