### PR TITLE
Fix inverted logic hide serverlist

### PR DESCRIPTION
**Pull request by mapreri**
### Description

I may be misunderstanding something, but I have this setup with multiple servers where I want to hide the server list from any page.

I set `NavigationDisplayServers` to `false` and that hid the list from the side panel, but amusingly it appeared in the home.

-------------
Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
  - I mean… I have tried to reflow the code in a separate commit, if you don't like it I can just drop that part
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Thank you for this PR @mapreri 
It's on my TODO list and will be checked

**Comment by williamdes** [comment]
Hi @mapreri 
Can you hard reset your PR branch onto `QA_5_2` and then cherry-pick the commits and force push ?
So this PR target can be edited and sent to 5.2.

Please do not close it or open a new one :)

I think that after that it's ready for a merge into 5.2. And `QA_5_2` will be merged into master.

Or, this bug is not present on 5.2 versions ?

**Comment by williamdes** [comment]
I did some research, and the code has been like this since 10 years or near to ever.
See 30e0e3648d90f349a119d9f53c94230fb7675210 that changed it a bit.

Or did I mis understand the logic ?

Here is the 2008 initial implementation: https://github.com/phpmyadmin/phpmyadmin/commit/c28818ecee0743e799b60df755b91f3f3b3b6972#diff-9260a516a07596bd0bc2e1e7a636b3af2e6fd9b7edfa1a3b7d46415ad5121359R64
it was renamed since then in https://github.com/phpmyadmin/phpmyadmin/commit/41ddd1cc6a048261b98fa8636ef0c07cf00eb747

**Comment by mapreri** [comment]
sorry, it seems that github has been having some troubles recently in notifying me…

Indeed this bug has been there since forever also according to me.  I guess it's an unusual situation to have?  Not sure.. The organization where this is deployed (that I have recently taken over…) has been carrying forever some patches that simply did not render the section.... :man_shrugging:

**Comment by mapreri** [comment]
I've rebased and changed the target of the PR as requested.  Note that by changing the target, the code changed quite a bit from master, so merging this back _will_ have conflicts that will need to be handled manually.

Also note that I do not claim that this is fully correct: I have no knowledge of the phpmyadmin codebase and I may very well be missing some obvious, so if you have doubts due to how long this bug has been silent, please do your due diligence in making sure I'm not doing something terribly wrong here! :grin:

**Comment by williamdes** [comment]
> sorry, it seems that github has been having some troubles recently in notifying me…
> 
> Indeed this bug has been there since forever also according to me. I guess it's an unusual situation to have?

That's possible, but rare I hope ! That said maybe once a year of two years some ooold bugs surface on edge corner cases or hidden features
Hi https://github.com/phpmyadmin/phpmyadmin/issues/16851#issuecomment-1437447487

> Not sure.. The organization where this is deployed (that I have recently taken over…) has been carrying forever some patches that simply did not render the section.... 

Wow, quite interesting. Is there other patches ?

Would you mind building an unit test for a before and after comparaison ?
If you do not have time, that's okay we can merge like this but I will have do do more testing

**Review by williamdes — APPROVED** [review]
The diff looks okay, thank you

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
Hi @mapreri
>Are you aware of any way to accomplish this with the current available pma configuration items?

Could you post some example lines?
we have a global variable that could be used for you to know what server id you are on.

**Pull request merged**
