### PR TITLE
Fixes #11798

### LINKED ISSUE #11798: Table engine detection fails with dot in database name
When there's a dot in de name of the database, the explode in util.lib.php#27 provides an incorrect array, causing the table cache lookup to fail.
I noticed it because, when using InnoDB tables, it made the engine detection fail (returning "" instead of "InnoDB") which causes the Relation View to not display the foreign keys form.

### PR DESCRIPTION
**Pull request by Achilles-96**
Signed-off-by: Raghuram Vadapalli raghuram.vadapalli@research.iiit.ac.in

### CODE REVIEW

**Comment by lem9** [comment]
Sorry but the problem described in #11798 is still present.

**Comment by Achilles-96** [comment]
Can you please tell me how to reproduce it.

**Comment by lem9** [comment]
It's described in the issue (second sentence).

**Comment by Achilles-96** [comment]
I created a table named `some()+.=table`(in back ticks) and the relation view of that table is displaying 'Foreign key constraints'. Is there anything else which I'm missing?

**Comment by lem9** [comment]
The issue does not mention a table name containing a dot.

**Comment by Achilles-96** [comment]
Oh, it doesn't work for tables containing dot also which is why I got misled and fixed that. I'll try and fix the issue with databases as well and update the PR. Thank you.

**Comment by Achilles-96** [comment]
This fix seems to be working fine for databases as well. I created a database with name `` `some.database` `` and a table in it. And the relation view showed Foreign key constraints detecting InnoDB engine.

**Comment by lem9** [comment]
As I said above, 2d12475131c1d1a248b128f71bb531b15cedca29 does not fix the problem for me. Tried on MySQL 5.7.8 with a database named "some.database" and table t1 with one column c1. No "Foreign key constraints section" is shown.

**Comment by Achilles-96** [comment]
Alright, the main problem here is joining database name and table name with dot like this https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Table.php#L329 but dot is accepted character in database name and table names. Small modification may fix this particular bug but definitely there will be a problem in future. 
In order to avoid future bugs due, we have to change all those instances where db name and table name are joined with dot and also corresponding explode statements. The solution is that we should change separator to some invalid character for naming MySQL tables, but MySQL allows any character in names. 
Any suggestions are welcome.

**Comment by lem9** [comment]
@Achilles-96 Please copy your last comment in the issue itself.

**Pull request closed without merging**
