### PR TITLE
bugs#3935 Table Header issue in Safari 5.0.5

### PR DESCRIPTION
**Pull request by whitepiegon**
Signed-off-by: Aayush Anand aayushism12@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
@whitepiegon To test your patch I need to be able to reproduce the problem. I am trying with Safari 5.0.5 on Windows 7 and am not able to reproduce, with either phpMyAdmin 4.2.9 or the current QA_4_3. Please describe your testing environment. In particular I am mostly interested to reproduce under QA_4_3, as 4.2.x is no longer supported.

**Comment by whitepiegon** [comment]
Hi..
I can easily reproduce this bug in Windows 8 Safari 5.0.5 both in pma 4.2.9 and QA_4_3 in my localhost. Browse any table to see it.

qa43

.

**Comment by lem9** [comment]
Thanks.

**Comment by lem9** [comment]
Aayush,
your patch is now part of QA_4_3; unfortunately, $.browser is no longer available in newer jQuery so I am looking for another solution for the master branch.

**Comment by whitepiegon** [comment]
Ok.. i ll make required change and will commit it asap.

**Comment by nisargjhaveri** [comment]
Also, doing browser specific fixes like this doesn't seem like a good idea to me. Can't we try for some generic solution that works in all browser. Maybe check why it goes wrong in Safari?

**Comment by lem9** [comment]
@whitepiegon No need, already done.

@nisargjhaveri You are welcome to propose a better solution.

**Pull request merged**
