### PR TITLE
[doc] Installation with Composer - add --no-dev option

### PR DESCRIPTION
**Pull request by bamarni**
Otherwise it installs multiple dependencies not needed for running PhpMyAdmin (phpunit, code sniffer, etc.).

Signed-off-by: Bilal Amarni bilal.amarni@gmail.com

### CODE REVIEW

**Comment by ibennetch** [comment]
Great, thanks for the contribution!

**Comment by nijel** [comment]
Merged and backported to QA_4_6. Thanks!

**Comment by ibennetch** [comment]
@nijel Even though it's a minor documentation change do you think this should go to QA_4_5 as well?

**Comment by nijel** [comment]
The documentation in QA_4_5 doesn't cover composer at all :-).

**Comment by ibennetch** [comment]
Thanks.

**Comment by ibennetch** [comment]
Thanks, apparently I'm easily confused :)

**Pull request merged**
