### PR TITLE
RFE #1485

### PR DESCRIPTION
**Pull request by devenbansod**
Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by devenbansod** [comment]
Hi, 
Scrutinizer failed because **Code Coverage was not sent to Scrutinizer**.

About Travis, sorry but I am unable to understand how my changes caused the test in **PMA_FormDisplay_Tpl_Test::testDisplayInput** to fail. 

Any help would be appreciated.

**Comment by ibennetch** [comment]
> Scrutinizer failed because Code Coverage was not sent to Scrutinizer.

I'm not sure about this one

> About Travis, sorry but I am unable to understand how my changes caused the test in PMA_FormDisplay_Tpl_Test::testDisplayInput to fail.

Right, this is a problem from several commits prior. You can see by clicking on the `Details` for Travis, then go to the `Build history` tab, looking down it looks like test #13345 is the first failure.

**Comment by ibennetch** [comment]
Just an update, I'm having trouble testing this due to a fatal PHP error, but I don't believe the error is related to your commit. I'll try to look again in a few hours.

**Comment by lem9** [comment]
Maybe related, see my comment:
https://github.com/phpmyadmin/phpmyadmin/commit/34c28378

**Comment by lem9** [comment]
I suggest rebasing your branch because of a recent fix in master.

**Comment by devenbansod** [comment]
Thanks @lem9. I did the rebasing. It passes the tests now.

**Comment by ibennetch** [comment]
Testing this, I get the error message `#1512 - DROP PARTITION can only be used on RANGE/LIST partitions ` but I don't know much about the use of partitions in this context so it may be that I haven't set something up properly. I'll do further research and see what I can find.

**Comment by devenbansod** [comment]
Yes. You are right. Thanks for pointing that out.

This two links say :
> Dropping a partition from a table that is partitioned by either RANGE or by LIST can be accomplished using the ALTER TABLE statement with a DROP PARTITION clause
https://dev.mysql.com/doc/refman/5.1/en/partitioning-management-range-list.html

> You cannot drop partitions from tables that are partitioned by HASH or KEY in the same way that you can from tables that are partitioned by RANGE or LIST. However, you can merge HASH or KEY partitions using the ALTER TABLE ... COALESCE PARTITION statement. 
https://dev.mysql.com/doc/refman/5.1/en/partitioning-management-hash-key.html

Will look into it more.

**Comment by devenbansod** [comment]
Now, a DROP or COALESCE radio button is added according to the type of partition method used.
Workflow when DROP is used is clear that the Partition(s) selected will be dropped while in case of COALESCE, the number of Partitions selected will be coalesced.

**Comment by devenbansod** [comment]
PMA_Operations_Test::testGetHtmlForPartitionMaintenance

This test printed output: Not supported query: SELECT PARTITION_METHOD FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = "db" AND TABLE_NAME = "table"

I am unable to figure out what is its meaning exactly. Any heads-up regarding this ?

**Comment by zixtor** [comment]
It appears that you are using a new query via PMA_getHtmlForPartitionMaintenance, so to pass testGetHtmlForPartitionMaintenance, you should add the query to libraries/dbi/DBIDummy.class.php with a valid dummy output for the testsuite to use.

**Comment by devenbansod** [comment]
Thanks alot @zixtor :)

Have added it as you suggested. Now passing the previously failing test.

**Comment by ibennetch** [comment]
Since DROP PARTITION is destructive to data stored in that partition, I think we should also prompt the user (similar to when calling DROP DATABASE or TRUNCATE table) for confirmation. What do you think?

**Comment by ibennetch** [comment]
Since DROP doesn't make sense when used with hash or key partitions, do you think it's possible to hide "Drop" from the radio button list in that case? I believe you already do that with "Coalesce" so hopefully it's rather easy to do.

**Comment by ibennetch** [comment]
Otherwise this looks good and is close to being ready to merge. The functionality works great in my testing.

**Comment by devenbansod** [comment]
Yes. Such a check should be done. Because user might not be knowing and he might delete it accidentally. 

Also, would a simple check on 'submit' like this would be okay ? Or do you suggest using the PMA_confirm as used when clicked on the 'Drop Table' Link ?
I was thinking of this.
 
```javascript
        if ( $operation_selected == 'DROP'){
            if (confirm("Are you sure to drop the selected Partition(s)?
                   \nThis will delete the data related to the selected partition(s)")) {
            }
            else {
                event.preventDefault();
            }
        }
```

**Comment by ibennetch** [comment]
I would prefer to use PMA_confirm as in the case of trying to Drop a database, but don't feel particularly strongly about the point; you could probably convince me to change my mind if you have a good reason.

**Comment by devenbansod** [comment]
Added the Confirmation when DROP partition is selected.

**Comment by ibennetch** [comment]
This looks great to me. Nice work. I'll do a bit more testing and merge later tonight, but it looks fine.

**Comment by ibennetch** [comment]
Good job.

**Comment by devenbansod** [comment]
Thanks. :)

**Comment by devenbansod** [comment]
Please see #1681 .

**Pull request merged**
