### PR TITLE
Ui imporve 1.0.0

### PR DESCRIPTION
**Pull request by getmebasilpaul**
To replace the default Loading...(or please wait...) ajax message with an animated circular loader.

image

### CODE REVIEW

**Comment by lem9** [comment]
Thanks. We have seen what you can do in this pull request, but I'm not sure that we should include this library, just to produce this animation.

**Comment by getmebasilpaul** [comment]
We can use this library for future improvements of User Interface. Using this library we can achieve material design in our Interface.

**Comment by lem9** [comment]
I know, but a decision has not been made to go this way.

**Comment by getmebasilpaul** [comment]
Thank you for the update.

**Pull request closed without merging**
