### PR TITLE
Refactor code for generation available auth plugins HTML

### PR DESCRIPTION
**Pull request by devenbansod**
Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
In Server > User accounts > Edit privileges for one account:
````
Notice in ./libraries/display_change_password.lib.php#100
 Undefined variable: default_auth_plugin
````

**Comment by devenbansod** [comment]
Yes. The earlier travis log had pointed out that error.

I was slightly busy, so it took time. 
But it should be fixed now, with this newer commit (already squashed into the earlier). 
Please let me know, if still does not work appropriately anywhere(Create user, Edit User, Change p/w).

**Comment by lem9** [comment]
With MySQL 5.7.8, during Edit privileges, changing the password hashing value and clicking on Go does not really change it.

**Comment by lem9** [comment]
The notice has been fixed but I still have the above problem.

**Comment by devenbansod** [comment]
@lem9 : Can you please check it once now ? 
I tested on 5.7.7 and it worked.

**Comment by lem9** [comment]
Looks fine, thanks.

**Comment by devenbansod** [comment]
Sorry. Just found an unhandled error.
There seems to be an error in the same scenario for MySQL 5.5.7 - 5.7.5. 
I will try to fix it asap.
Sorry again for the trouble.

**Comment by lem9** [comment]
@devenbansod See the following trick: https://github.com/phpmyadmin/phpmyadmin/commit/b884ccd7537032782359e0bb5fceae969b16c307

**Comment by lem9** [comment]
Ok, please open a new PR when you're ready.

**Pull request merged**
