### PR TITLE
More consistent description for Sushosin warning

### PR DESCRIPTION
**Pull request by Vaporizer8**
Modified the description for the Suhosin warning so it is more accurate and consistent with similar warning descriptions.

Signed-off-by: Evert Beurskens evertbeurskens@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Thanks. I redid the commit in your name, including your signature in it.

**Comment by ibennetch** [comment]
That's helpful, thank you @Vaporizer8

**Comment by Vaporizer8** [comment]
Thanks, I guess something went wrong with the tag.

**Comment by lem9** [comment]
The Signed-off-by line has to be inside the comments of the commit itself, not the comments on Github.

**Pull request closed without merging**
