### PR TITLE
OpenDocument export generates invalid file

### PR DESCRIPTION
**Pull request by ibennetch**
Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ibennetch** [comment]
Note that the trailing space is significant; I was torn on whether it more appropriately belongs as part of the OpenDocument::NS declaration or before the next line in every place where NS is used. Since it's needed everywhere I though it more appropriately belongs here.

**Comment by jublo** [comment]
Will this fix OpenDocument text and sheets?

**Comment by ibennetch** [comment]
Changed and rebased because I decided to move the trailing space from the constant to the next code in each place where it's used. I felt having the trailing space exposed as part of the constant was too vulnerable to accidental breakage.

**Comment by ibennetch** [comment]
Yes, this fixes both ODT and ODS files.

**Comment by ibennetch** [comment]
I didn't dig too much in to this, but it's just standard xml so it should pretty much not care about whitespace, which is why this bug is a bit strange for me.

**Comment by nijel** [comment]
I've fixed this independently in 59e9856200726359298a68895dc558c03f127254. I just didn't touch the NS definition...

Sorry, next time I will look at pull requests first time before I start to work on the code.

**Comment by ibennetch** [comment]
Thanks @nijel. What's important is that it got fixed.

**Pull request closed without merging**
