### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Review by williamdes — CHANGES_REQUESTED** [review]
First I would like to thank you for contributing
Then here is my review regarding this change: I hate dependabot and it creates too much work and stress. I want no such problems and PRs to manage. Already tried this bot and it's a pain

**Comment by naveensrinivasan** [comment]
> First I would like to thank you for contributing
> Then here is my review regarding this change: I hate dependabot and it creates too much work and stress. I want no such problems and PRs to manage. Already tried this bot and it's a pain

I understand. FYI this is just for GitHub actions.

**Comment by williamdes** [comment]
> > First I would like to thank you for contributing
> > Then here is my review regarding this change: I hate dependabot and it creates too much work and stress. I want no such problems and PRs to manage. Already tried this bot and it's a pain
> 
> I understand. FYI this is just for GitHub actions.

Yup indeed, this is why it left me hesitant
Let's see what other reviewers say

I would prefer and interface that lists outdated actions
Or a cron action that throws errors

**Comment by MauricioFauth** [comment]
@williamdes Do you think this will work for our workflow? I don't want to backport changes.

**Comment by williamdes** [comment]
> @williamdes Do you think this will work for our workflow? I like tools like this, but I don't want to backport changes.

Honesty, no
It would need to know what branch is the base one to make PRs for

**Comment by MauricioFauth** [comment]
> > @williamdes Do you think this will work for our workflow? I like tools like this, but I don't want to backport changes.
> 
> Honesty, no It would need to know what branch is the base one to make PRs for

So, let's close this.

**Pull request closed without merging**
