### PR TITLE
Add support for xz compression

### PR DESCRIPTION
**Pull request by madhuracj**
Finally, I managed to get the php xz extension installed on a linux machine and test the implementation.

See also https://github.com/phpmyadmin/phpmyadmin/pull/1628

### CODE REVIEW

**Comment by udan11** [comment]
Did you have any problems or found any limitations of the extension while using it? I would like to know in order to implement it and to help you ship this feature as soon as possible.

**Comment by madhuracj** [comment]
Not anything particular.
Btw, support for xz was implemented only for importing. For exporting I couldn't find a xzencode or a similar function.

**Comment by udan11** [comment]
Ok. I hope that I will implement this as soon as possible.

I believe that it would be better if you used `xzread` instead of that output buffering trick and `xzpassthru`.

For writing, you could use `xzwrite`, which writes directly to a file not to a buffer.

**Comment by madhuracj** [comment]
Indeed, xzread would be better. Wonder how we could incorporate xzwrite to out export mechanism.

**Comment by madhuracj** [comment]
Pull request update with xzread

**Comment by udan11** [comment]
Incorporating `xzwrite` into the export mechanism would require quite a lot of work. I believe that it would be so much easier for you and a much better solution if I wrote a `xzencode`, a function that behaves like `gzencode`. It would be basically a drop-in replacement.

I am busy with some exams for now, but I hope that I'll find some time to implement it as soon as possible.

**Comment by udan11** [comment]
I implemented `xzencode` and `xzdecode` in `php-xz` v0.1.1.

**Pull request closed without merging**
