### PR TITLE
Fix Mutation test for all files

### PR DESCRIPTION
**Pull request by MauricioFauth**
This is an attempt to understand why the mutation tests for all files are failing.

### CODE REVIEW

**Comment by MauricioFauth** [comment]
Looks like it's hitting some runner limit, like a CPU limit or memory limit. Most probably the memory limit.

**Comment by williamdes** [comment]
> Looks like it's hitting some runner limit, like a CPU limit or memory limit. Most probably the memory limit.

Looks like it https://github.com/actions/runner-images/issues/6680#issuecomment-1334848113

Exit Code 143: Graceful Termination (SIGTERM)

**Comment by MauricioFauth** [comment]
Yeah, I saw that issue.
I'll look more into it if there's something we could do about it without using a hosted runner or giving up running Infection for all files.

**Comment by MauricioFauth** [comment]
@williamdes it was not canceled this time.

I added an annotation to ignore most of the line that caused timeouts or errors. Most of them are infinite loops.
Looks like one of those or the sum of them are causing the CPU or memory limit.

Next step is to add tests to kill these mutants.

**Comment by williamdes** [comment]
Coool, let's kill them

**Pull request merged**
