### PR TITLE
Using localStorage to save the state of the Designer

### LINKED ISSUE #12286: Designer should remember expanded/collapsed state
When using the Designer, I can save the layout, but when I open Designer again the expanded/collapsed state of each table reverts to the default. It would be great if it would save the state as part of the layout status.

### PR DESCRIPTION
**Pull request by Bournvita1998**
Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

Fixes #12286

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
@sudo-bot Deploy PR

**Comment by shucon** [comment]
Your code is not saving variables properly in localStorage and thus not able to restore the state of the Designer.

**Comment by Bournvita1998** [comment]
@shucon Yes you were right, its not storing values and the data assocated with the tables is also not poping shoehow. Thus while debugging, rather than considering all the tables at once, I have looked at the changes for one of the tables first. Here are the changes made:
Selection_061

Selection_060

Corresponding output associated to this is:

Selection_062

i.e. the values which are being SET and GET are both the same.

**Comment by Bournvita1998** [comment]
Code associated with the above screen shots is:

    var key = $('.designer_tab')[0].id;
    if((localStorage.getItem('id_tbody_' + key) !== null) && (localStorage.getItem('id_hide_tbody_' + key) !== null)) {
        document.getElementById('id_tbody_' + key).innerHTML = localStorage.getItem('id_tbody_' + key);
        document.getElementById('id_hide_tbody_' + key).innerHTML = localStorage.getItem('id_hide_tbody_' + key);
        console.log('GET1 key = ' + 'id_tbody_' + key + '------ with value = ' + document.getElementById('id_tbody_' + key).innerHTML);
        console.log('GET1 key = ' + 'id_hide_tbody_' + key + '------ with value = ' + document.getElementById('id_hide_tbody_' + key).innerHTML);
    }
    console.log('GET2 key = ' + 'id_tbody_' + key + '------ with value = ' + localStorage.getItem('id_tbody_' + key));
    console.log('GET2 key = ' + 'id_hide_tbody_' + key + '------ with value = ' + localStorage.getItem('id_hide_tbody_' + key));

AND

    $('.designer_tab').on('click', '.small_tab,.small_tab2', function () {
        DesignerMove.smallTab($(this).attr('table_name'), 1);
        var t = $(this).attr('table_name');
        var id      = document.getElementById('id_tbody_' + t);
        var idThis = document.getElementById('id_hide_tbody_' + t);
        localStorage.setItem('id_tbody_' + t, id.innerHTML);
        localStorage.setItem('id_hide_tbody_' + t, idThis.innerHTML);
        console.log('SET key = ' + 'id_tbody_' + t + '...... with value = ' + id.innerHTML);
        console.log('SET key = ' + 'id_hide_tbody_' + t + '...... with value = ' + idThis.innerHTML);
    });

**Comment by Bournvita1998** [comment]
Committed the changes as per the comment message but the committed code is for all the tables(not just for one table as shown here in the comment)

**Comment by williamdes** [comment]
@Bournvita1998 can you rebase onto `QA_4_9` and shash your commits ?
you will maybe need to re-do the PR

**Pull request closed without merging**
