### PR TITLE
#844 structure in PDF export

### PR DESCRIPTION
**Pull request by whitepiegon**
Signed-off-by: Aayush Anand aayushism12@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Please fix the test unit failures.

**Comment by whitepiegon** [comment]
Hi Marc... I need your little help in it.. Please bear with me.
I can see 1 error and two fail checks 
1. Scrutinizer — Timed out
2. default
3. continuous-integration/travis-ci/pr
I can see the codacy report and understand the errors which I will correct now. But I can't understand the reason behind travis and Scrutinizer (it says "code coverage data was not received within the specified time") failure. Show me the correct path.
Thank youHi Marc... I need your little help in it.. Please bear with me.
I can see 1 error and two fail checks 
1. Scrutinizer — Timed out
2. default
3. continuous-integration/travis-ci/pr
I can see the codacy report and understand the errors which I will correct now. But I can't understand the reason behind travis and Scrutinizer (it says "code coverage data was not received within the specified time") failure. Show me the correct path.
Thank you

**Comment by whitepiegon** [comment]
Hi Marc... I need your little help in it.. Please bear with me.
I can see 1 error and two fail checks 
1. Scrutinizer — Timed out
2. default
3. continuous-integration/travis-ci/pr
I can see the codacy report and understand the errors which I will correct now. But I can't understand the reason behind travis and Scrutinizer (it says "code coverage data was not received within the specified time") failure. Show me the correct path.
Thank you

**Comment by lem9** [comment]
Please install what is needed for unit testing on your machine. This is described on wiki.phpmyadmin.net. Meanwhile, here are the errors I get:
````
1) PMA_ExportPdf_Test::testSetProperties
Failed asserting that TextPropertyItem Object (...) is an instance of class "Mes
sageOnlyPropertyItem".

test/classes/plugin/export/PMA_ExportPdf_test.php:130

2) PMA_ExportPdf_Test::testExportData
Expectation failed for method name is equal to <string:setAttributes> when invok
ed 1 time(s)
Parameter 0 for invocation PMA_ExportPdf::setAttributes(Array (...)) does not ma
tch expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'aliases' => Array ()
+    'purpose' => 'Dumping Data'
 )

libraries/plugins/export/ExportPdf.class.php:225
/test/classes/plugin/export/PMA_ExportPdf_test.php:277
````

**Comment by whitepiegon** [comment]
Thanks Marc.. 
Basically I was not able to understand why errors like "Failed asserting that TextPropertyItem Object (...) is an instance of class "MessageOnlyPropertyItem"" is giving, when I was not even using "MessageOnlyPropertyItem". At last I found that it required test files to be updated. I did that. Finally, Travis CI build passed. :)
See https://github.com/phpmyadmin/phpmyadmin/pull/1627/files
But now coverage/coveralls is saying — Coverage decreased. If I will need to need to add more tests, so that this patch can be merged or reviewed?

**Comment by lem9** [comment]
Having a "coverage decreased" is not enough to block the merging of a patch, but of course it would be interesting if you could add tests to increase code coverage.

**Pull request closed without merging**
