### PR TITLE
Issue #13032 - fix designer

### LINKED ISSUE #13032: Errors in designer when database contains special chars
When the database name contains some special chars, the designer fails to operate on that. In my particual case the database name is `"'"><iframe onload=ale2`.

This report is related to user submitted report [#31501](https://reports.phpmyadmin.net/reports/view/31501) on the phpmyadmin error reporting server.

### PR DESCRIPTION
**Pull request by williamdes**
This issue fixes multiple issues.

I did not create an issue for :
- https://github.com/phpmyadmin/phpmyadmin/commit/24a8518b2a18a979d662da8cfbedc52c02d1d498 Shows 2 tables in designer when no tables in database

- https://github.com/phpmyadmin/phpmyadmin/commit/057c6faca2a2f41446f4655a3f2ec8b2ffb43091 PHP errors when database has no tables

- https://github.com/phpmyadmin/phpmyadmin/pull/14376/commits/5fe3549b59ff0529a1275cf991a842a9f1b86f88 Designer > new page shows iframe when db name is: `"'"><iframe onload=alert(1)>`

I removed html parsing of values see: https://github.com/phpmyadmin/phpmyadmin/commit/096d170e0488e86c5a3ceb11924b9da444d7daa8

~~I will rebase on master when #14372 is merged.~~

Closes: #13032

### CODE REVIEW

**Comment by nijel** [comment]
Hmm, 5fe3549 probably counts as security issue, CC @madhuracj @ibennetch

**Review by nijel — APPROVED** [review]
Looks good to me, thanks!

**Comment by mauriciofauth** [comment]
@williamdes #14372 was merged.

**Comment by williamdes** [comment]
@mauriciofauth Thank you !
I was searching where I posted "I will rebase on master when ??? is merged."
Rebase done :)
I fixed lint error : `Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines`

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
