### PR TITLE
phpstan level 1

### LINKED ISSUE #14444: phpstan level 1 - found errors
See below, upvote if you agree.

### PR DESCRIPTION
**Pull request by williamdes**
Closes: #14444 

:notebook: If you want me to rebase, squash commits or edit them, feel free to ask. **Do not squash and merge using all the garbage of my commits comments !** (it's ugly !) Ask and I will do a clean commit squash.

- Updated phpstan to master (using fixed version see commit message https://github.com/phpmyadmin/phpmyadmin/pull/14472/commits/f2f3b5283ecb51c35fea263e2a90b9a4aace98f1 )
- Fixed phpdoc and type hints
- Updated phpstan config
- Fixed all errors of `level=1`
- Ignored some
- Fixed phpstan dependency issue by installing globally in CI

### CODE REVIEW

**Comment by williamdes** [comment]
```
 ------ ------------------------------------------------------------------ 
  Line   db_operations.php                                                 
 ------ ------------------------------------------------------------------ 
  247    Variable $sub_part in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------ 
  Line   db_qbe.php                                                        
 ------ ------------------------------------------------------------------ 
  130    Variable $sub_part in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------ 
  Line   db_tracking.php                                                   
 ------ ------------------------------------------------------------------ 
  51     Variable $sub_part in isset() always exists and is not nullable.  
 ------ ------------------------------------------------------------------
```

**Comment by williamdes** [comment]
@mauriciofauth I cleaned all errors reported in `level=1`
I left those 3 errors because I think they must be fixed but not in this PR.
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/406611808#L862
```
 ------ ----------------------------------------------------------------------- 
  Line   libraries/classes/Controllers/Table/TableRelationController.php        
 ------ ----------------------------------------------------------------------- 
  192    Array has 2 duplicate keys with value 'cfg_relation' ('cfg_relation', 'cfg_relation').                                                       
  192    Array has 2 duplicate keys with value 'url_params' ('url_params', 'url_params').                                                         
 ------ ----------------------------------------------------------------------- 
 ------ ---------------------------------------- 
  Line   tbl_operations.php                      
 ------ ---------------------------------------- 
  192    Variable $result might not be defined.  
 ------ ---------------------------------------- 
                                                                                
 [ERROR] Found 3 errors                                                         
                                                                                
```

**Comment by williamdes** [comment]
@mauriciofauth Can you please review all the commits, I have finished working on `level=1` 
Ask if you want me to squash all commits ;)

**Comment by mauriciofauth** [comment]
Selenium test failed. See:
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/408903628#L873

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
