### PR TITLE
Fix #15010 Sql preview show empty modal on

### LINKED ISSUE #15010: Sql preview empty modal on tbl_relation
Use following links 
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/tbl_relation.php?db=information_schema&table=INNODB_BUFFER_PAGE)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/tbl_relation.php?db=information_schema&table=INNODB_BUFFER_PAGE)

`tbl_relation.php?db=information_schema&table=INNODB_BUFFER_PAGE`

### Bug
- Click on `SQL PREVIEW` button
- Shows empty modal (this is the issue, why is it empty..)

### PR DESCRIPTION
**Pull request by apoorvkhare07**
Signed-off-by: Apoorv Khare <apoorvkhare007@gmail.com>

### Description

It was giving empty modal because the `previewSQL` function is being called from here:
`if (isset($_POST['destination_foreign_db'])) { $this->updateForForeignKeysAction(); }`
and in some cases `destination_foreign_db` param is not set in the request, so the modal is coming empty.
Removing the check from here and applying at other relevant places fixes the issue.
Fixes #15010 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by apoorvkhare07** [comment]
@williamdes Is there any issue with this PR ? Let me know what else needs to be done in order to get this merged.

**Comment by williamdes** [comment]
@apoorvkhare07 nothing is wrong, I need to test it :)

**Review by williamdes — APPROVED** [review]
Works fine, rebased the branch
Will merge soon

**Review by williamdes — APPROVED** [review]
Merged, thanks for the contribution @apoorvkhare07 :)

**Pull request merged**
