### PR TITLE
Fix: #17773 On demo server footer links aren't clickable

### LINKED ISSUE #17773: On demo server footer links aren't clickable
### Describe the bug

On demo server, footer links aren't clickable. Probably related to #17749.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/)
2. Try to click on links from footer
3. See error

### Expected behavior

Links should be clickable.

### Screenshots

https://user-images.githubusercontent.com/25424343/195250309-3d94d66e-7f92-4493-b4b9-f61d0630241f.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.2.1-dev

### Client configuration

- Browser: Firefox/Chrome
- Operating system: Windows

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by Arpit-Gulgulia**
Signed-off-by: Arpit Jain <arpitgulgulia@gmail.com>

### Description

Please describe your pull request. Fix for On demo server footer links aren't clickable

Fixes #17773

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by sureemo — COMMENTED** [review]
Sorry the issue is bugs from my PR to make the column visibility toggle dropdown not behind the demo info box.

Please be proposed the better fix on `_common.scss` for each theme:
1. remove the following lines
```
#pma_demo {
  z-index: -1;
}
```

2. and add:
```
.table-responsive-md .data {
  z-index: 9;
}
```

For your consideration. Thank you @Arpit-Gulgulia ^_^

**Comment by Arpit-Gulgulia** [comment]
> Sorry the issue is bugs from my PR to make the column visibility toggle dropdown not behind the demo info box.
> 
> Please be proposed the better fix on `_common.scss` for each theme:
> 
>     1. remove the following lines
> 
> 
> ```
> #pma_demo {
>   z-index: -1;
> }
> ```
> 
>     2. and add:
> 
> 
> ```
> .table-responsive-md .data {
>   z-index: 9;
> }
> ```
> 
> For your consideration. Thank you @Arpit-Gulgulia ^_^

Sure @sureemo , I prefered to not remove anything from existing code but as per suggestion, i will add your proposed fixes. Thanks!

**Comment by Arpit-Gulgulia** [comment]
@MauricioFauth , Could you please review and approved the changes? Thanks!

**Comment by sureemo** [comment]
@Arpit-Gulgulia Thank you for help fixing. Please you also fix for other themes.
The lines suggested to be deleted are added by me some days ago in this PR https://github.com/phpmyadmin/phpmyadmin/pull/17749 so it's not harm to drop them.
Thanks again.

**Comment by Arpit-Gulgulia** [comment]
@sureemo, the Lint CSS file step was failing because of an extra empty line. I have fixed that with the new commit. Please review and approved the changes. Thanks!

**Comment by williamdes** [comment]
Hi @Arpit-Gulgulia
First I would like to thank you for contributing!
Next I would advise you to close this pull-request and create a branch from QA_5_2 and then open a pull-request to QA_5_2 from the created branch

If I am not mistaken this issue affects 5.2 so QA_5_2 should be used as a base branch and target.

You seem to have done some operation that cherry picked commits from the main repository. It's better not to use branches like main and QA_5_2 directly for work, always create a branch from them

**Comment by Arpit-Gulgulia** [comment]
@williamdes, sure. Thanks for your suggestion. I am closing this PR and creating a new one as per your suggestion.

**Pull request closed without merging**
