### PR TITLE
Recaptcha2, request #1382

### PR DESCRIPTION
**Pull request by pbojan**
Contains config variable description, option to make the config from `./setup` script and while enabled the user can't login without entering valid captcha on the login screen for cookie auth type. 

Removed "Test Commit", fixed CSP bug on the login screen and tested on Chrome and Firefox.

### CODE REVIEW

**Comment by crysman** [comment]
Please, what is the minimum PMA version containing this patch? It's to say, if I am running PMA 4.2.6 - if it's already there? :) Thanks

**Comment by lem9** [comment]
@crysman Version is 4.4-dev which is the future 4.4 version.

**Comment by crysman** [comment]
Hups, I see... so it will be available in the next release, ok, perfect. Will be the option to use CAPTCHA available also in PMA GUI? Or just some hidden config line? I would prefer the first one ;)

**Comment by lem9** [comment]
@crysman You were talking about "this patch", which is about a newer version of captcha. Version 4.2 contains captcha support via two configuration lines, as explained in the documentation.

**Pull request merged**
