### PR TITLE
Return HTML instead of echo-ing directly in FormDisplay

### PR DESCRIPTION
**Pull request by nisargjhaveri**
The config/FormDisplay was directly echo-ing content.

I changed it to return HTML, so that the same functions can also be used with PMA_Response.

Someone please confirm what I am trying to do. After that, I'll fix the tests and the merge conflicts.

### CODE REVIEW

**Comment by lem9** [comment]
Yes, this is the correct way.

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by lem9** [comment]
The buttons in the "Configuration file" section (like Display, Download) do not work for me.

**Comment by nisargjhaveri** [comment]
Check now?

**Comment by lem9** [comment]
Yes, the Download button works now

**Comment by nisargjhaveri** [comment]
Fixed remaining test too.

**Comment by lem9** [comment]
Ha, we like these green "All is well" reports !

**Comment by lem9** [comment]
Nisarg,
just found a problem with this commit. Try Settings > Import: some incorrect text is displayed between the lines of menu tabs.

**Comment by nisargjhaveri** [comment]
o.O Looking into it.

**Comment by nisargjhaveri** [comment]
See #1676.

Missed one `echo`. Sorry for that. -.-

**Pull request merged**
