### PR TITLE
Fix #15570 - Page contents go underneath of floating menubar in some cases

### LINKED ISSUE #15570: Page contents go underneath of floating menubar in some cases
### Describe the bug
Similar to #15127 of version 4.9.x  A shift of panels is happening in version 5.0.12-dev

### To Reproduce
1. Go to any database
2. Go to designer tab
2. Refresh the page or press 'f5'
3. Then redirect to homepage by either clicking on 'phpMyadmin' logo
    or 'home' button on the top left

### Current behaviour
Screenshot from 2019-11-13 13-59-48

### Expected behavior
Screenshot from 2019-11-13 13-59-59

### Server configuration

- Operating system: Linux Ubuntu 16.04
- Web server: Apache
- PHP version: 7.1.29
- phpMyAdmin version: 5.0.12-dev

### PR DESCRIPTION
**Pull request by ShailuJain**
### Description

After reloading the designer page, https://github.com/phpmyadmin/phpmyadmin/blob/bfe1afb542c1c9b5c4f7773a2ffe245140db1a14/js/navigation.js#L1168-L1176

height of `$('#floating_menubar')` was 0. So i appended `$('#serverinfo')` and `$('#topmenucontainer')` to `$('#floating_menubar')`.

Fixes #15570 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
@ShailuJain you can re-open it and rebase the PR onto QA 4 9 using hard reset and cherry-pick method ?

**Comment by ShailuJain** [comment]
Can i know the steps please? I haven't done it before @williamdes

**Comment by williamdes** [comment]
@ShailuJain 
```bash
# Checkout your branch
git checkout 15570
# Discard all changes
git reset --hard QA_4_9
# Add your change
git cherry-pick d64d87721172478765efb9f6d189600eb552b88c
# Push to GitHub
git push --force
```
:)

**Comment by ShailuJain** [comment]
Thanks @williamdes. I used the master branch as base and then solved the issue. Now i have rebased the branch to QA 4 9.

**Comment by williamdes** [comment]
Merged, thank you @ShailuJain for your contribution !

**Pull request merged**
