### PR TITLE
clear any validation messages

### PR DESCRIPTION
**Pull request by whitepiegon**
Hi Marc. This commit tries to produce feature you asked for.
Clear any validation message when the "Ignore" checkbox is ticked and reappear when checkbox is unchecked again.
Signed-off-by: Aayush Anand aayushism12@gmail.com

### CODE REVIEW

**Comment by lem9** [comment]
Hi Aayush,
a good improvement but incomplete for two reasons. First, as tested in Iceweasel (Firefox), the field's outline remains red. Second, you refer to "insert_ignore_1" but there may be more than two insert sections.

**Comment by whitepiegon** [comment]
I personally felt that red outline is good as it keeps reflecting that input is invalid however act of removal of error message reflect that it doesn't affect the form validation. This was my view.
Also Marc all these functions, I am using, are default functions. They behave like this. But I can surely write customed functions if u want. So tell me if u want that red outline to be removed? I will modify/develop functions for that.
And yes i will correct this patch as per your 2nd point also. Thank you for telling about this.

**Comment by whitepiegon** [comment]
hi Marc, I was looking for fixing 2nd issue you mentioned. I feel it can be easily taken care of, if "#insert_ignore_1" is replaced by "input[name^='insert_ignore_']". Please confirm if 1st issue also need change. So, I will make final changes and complete this feature.

**Comment by lem9** [comment]
I accept your red outline explanation. Please implement your solution for the 2nd issue.

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
