### PR TITLE
Use button formaction attribute for table structure bulk links

### PR DESCRIPTION
**Pull request by MauricioFauth**
Uses [button formaction attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formaction) for table structure bulk links.

It is a IE10+ feature.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
We should document our compatibility minimums, I think some standardized files exist for that

**Comment by mauriciofauth** [comment]
> We should document our compatibility minimums, I think some standardized files exist for that

@williamdes Bootstrap uses [Browserslist](https://github.com/browserslist/browserslist).

**Comment by williamdes** [comment]
> > We should document our compatibility minimums, I think some standardized files exist for that
> 
> @williamdes Bootstrap uses [Browserslist](https://github.com/browserslist/browserslist).

I was looking for it, thank you
Can you add it?

**Comment by mauriciofauth** [comment]
> Can you add it?

Sure!

**Pull request merged**
