### PR TITLE
Zeroconf fix - work in progress

### PR DESCRIPTION
**Pull request by madhuracj**
For comments

### CODE REVIEW

**Comment by lem9** [comment]
Madhura,
you want to fix this only in master?

**Comment by madhuracj** [comment]
Pull request is for QA_4_3 branch. I'll close this one and open a new PR

**Comment by lem9** [comment]
Ok this setting of globals should be fine; just tell me when the work in progress is ready to test.

**Comment by madhuracj** [comment]
You should be able to test. Not ready for merge since unit tests have not  yet been fixed

**Pull request closed without merging**
