### PR TITLE
more css cleanup

### PR DESCRIPTION
**Pull request by ghost**
even more css code cleanup.

some code standards and automated formating would be nice to see and have. not sure if this is easy to realize.

please review my changes and have a good day :)

### CODE REVIEW

**Comment by BO41** [comment]
why is it not working?
and why are there commits done by @ibennetch ?

**Comment by williamdes** [comment]
@BO41 you need to rebase on master :)

**Comment by BO41** [comment]
...still failing :cry: 

if someone can help me, again

**Comment by williamdes** [comment]
@BO41 Do not worry `codecov/patch` often fails for no good reason, I still do not understand what that is.

@ibennetch What is the purpose of `codecov/patch` ?

**Comment by BO41** [comment]
@williamdes should I be worried about DCOs failing?

**Comment by williamdes** [comment]
@BO41 Yes !
I use the following command to fix all my commits before pushing them to remote
`git rebase --exec 'git commit --amend --no-edit -n --gpg-sign --signoff' origin/master`
If you dont have a gpg key ommit `--gpg-sign`

@ibennetch @nijel Just a question : why do you not use your GPG key to sign commits ?

**Comment by BO41** [comment]
replaced with #14532

**Pull request closed without merging**
