### PR TITLE
Added functionality for redirecting to database structure page on creating new database

### PR DESCRIPTION
**Pull request by djprawns**
as requested on http://sourceforge.net/p/phpmyadmin/feature-requests/1605/

### CODE REVIEW

**Comment by lem9** [comment]
Looks fine, thanks. Could you redo a commit, this time avoiding trailing whitespace and signing your commit as explained above?  Also, it's suggested to create a branch per feature, it helps when you work on more than one feature at the time.  Closing for now.

**Comment by vanarpsharma** [comment]
hey @lem9 , what branch should i switch to? QA_3_4?

**Comment by lem9** [comment]
You can create a branch called, for example, fr1605, starting with the current master branch.  QA_4_3 is for bug fixes only.

**Comment by lem9** [comment]
As I found this patch valuable, I have redone it in your name, with just a slight change (removed unneeded empty strings in addJson). I added your signature as you showed in the other pull request that you accepted our DCO. See c0bad9103e3296f7c191f21b0aee18625ba46399.

**Comment by vanarpsharma** [comment]
ok, so have you merged it yourself through your commits(as in through your system)? or do i initiate another pull request? I am new to this, and am a GSOC aspirant. Trying hard and tried my first confident hand at a feature request/patch.  Please pardon my mistakes. Thankyou.

**Comment by lem9** [comment]
You do not have to do anything.

**Pull request closed without merging**
