### PR TITLE
Fixes looping on Login form

### LINKED ISSUE #16544: [5.1.0-rc1] looping on login form
php 7.2.34 on CentOS 8 (using FPM)

* phpMyAdmin 5.0.4 works
* phpMyAdmin 5.1.0-rc1 loops on login form

Tried with RPM package and official tarball

Load:
```
212.195.5.25 - - [22/Dec/2020:08:25:33 +0100] "GET /phpMyAdmin/ HTTP/2.0" 200 4703
212.195.5.25 - - [22/Dec/2020:08:25:33 +0100] "GET /phpMyAdmin/favicon.ico HTTP/2.0" 200 22486
```

Post credentials
```
212.195.5.25 - - [22/Dec/2020:08:26:00 +0100] "POST /phpMyAdmin/index.php?route=/ HTTP/2.0" 302 20
212.195.5.25 - - [22/Dec/2020:08:26:00 +0100] "GET /phpMyAdmin/index.php?route=/&route=%2F HTTP/2.0" 200 4705
```

Any idea on how to debug ?

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/16544

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
This looks like the right fix!
Thanks a lot, I will investigate

**Comment by ibennetch** [comment]
Works for me. Excellent work @shucon.

I'd like to get a few more tests on this to make sure it works across platforms and versions, but this works great for me in my tests.

**Comment by williamdes** [comment]
I searched and #16386 did add this bug, looks like @rajat315315 did want to avoid something with the trailing slash.
That would be nice to find out what it was

**Comment by shucon** [comment]
> I searched and #16386 did add this bug, looks like @rajat315315 did want to avoid something with the trailing slash.
> That would be nice to find out what it was

I think it was a bug due to some confusion caused by the explanation in StackOverFlow.

**Pull request merged**
