### PR TITLE
Introduce alias type mapping

### LINKED ISSUE #18613: Editing procedure with BOOL param changes type to INT
### Describe the bug

BOOL type is converted to INT when editing a procedure.
It works with BOOLEAN type.

### To Reproduce

1. Create procedure 
```sql
CREATE PROCEDURE `p` (IN b BOOL) BEGIN END;
``` 
2. Edit procedure
3. See type of `b` changed to INT

### Expected behavior

The BOOL data type should be preserved

### Screenshots

image

### Server configuration

phpMyAdmin version: 5.2 & 6.0

### PR DESCRIPTION
**Pull request by kamil-tekiela**
- Ref. #18633

- Fixes #18613

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by MauricioFauth** [comment]
sql-parser 5.9.0 was released. Could you update composer.json to require phpmyadmin/sql-parser ^5.9?

**Comment by williamdes** [comment]
The new bin file is okay for us because of this line that will remove it 
 https://github.com/phpmyadmin/phpmyadmin/blob/984cc32df56b85b8d42595ea086d86515547b522/scripts/create-release.sh#L137

For me LGTM to bump

**Comment by kamil-tekiela** [comment]
Yeah, this works fine on 5.2 
image

**Review by williamdes — APPROVED** [review]
Thank you!

**Review by MauricioFauth — APPROVED** [review]

**Pull request merged**
