### PR TITLE
Editor made both side scrollable

### LINKED ISSUE #16053: Metro theme routine editor diminishing width
### Describe the bug
In the metro theme, when you drag the bottom edge of the code window up or down, the right edge also moves, but always to reduce the width of the code space. In the following screenshots, 

The first is the editor freshly opened
image

Next is after I dragged the bottom  edge up
image

Next is after I dragged the bottom  edge down

image

Finally, up again and the code has gone completely
image

Local host server on Win10 - 64 and Chrome

image

### PR DESCRIPTION
**Pull request by rajat315315**
Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Editor made both sides scrollable.

Fixes #16053 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by rajat315315** [comment]
Just a request..
Can we add `hacktoberfest-accepted` label to PR if it gets merged?

**Comment by ibennetch** [comment]
I don't believe this fixes the reported issue, but I still think it's a good improvement.

My understanding of Hacktoberfest is that if a pull request is merged, it is automatically eligible without needing the hacktoberfest-accepted label, but if something is not going to be merged but still worthy then that's what the hacktoberfest-accepted label is for. I think your research and effort on this and the other pull request will pay off and they'll be merged before the deadline. You've done a good job of researching and finding ways to make legitimate and helpful changes which is great.

**Comment by rajat315315** [comment]
Review please?

**Comment by williamdes** [comment]
> Review please?

I intend to merge if this fixes the issue. scheduled :hourglass_flowing_sand: :)

**Pull request merged**
