### PR TITLE
UI improve 1.0.0

### PR DESCRIPTION
**Pull request by getmebasilpaul**
To replace the default Loading...(or please wait...) ajax message with an animated circular loader. Like given below
image

### CODE REVIEW

**Comment by lem9** [comment]
Have a look at https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO for the Signed-Off-By correct format.

Also, please squash your commits.

**Comment by lem9** [comment]
I had a quick look. This patch is not acceptable, you are replacing some .on() calls with the deprecated .live() call.

**Comment by getmebasilpaul** [comment]
Thank you Marc Delisle, can  you please give little more explanation about this?

**Comment by lem9** [comment]
http://lmgtfy.com/?q=jquery+.live+deprecated&l=1

**Comment by getmebasilpaul** [comment]
Thank you.

**Pull request closed without merging**
