### PR TITLE
Fix #14245 "mysql 8.0.3 and above fails on advisor" for 4.9

### LINKED ISSUE #14245: Status / Advisor problem with MySQL 8.0.11
### Steps to reproduce
1. On PhpMyAdmin, select tab Status and the select link Advisor

### Expected behaviour
Advisor output without errors

### Actual behaviour
```
Errors occurred while executing rule expressions:
- Failed calculating value for rule 'Query cache disabled'. Error when evaluating: Variable "query_cache_size" is not valid around position 1 for expression `query_cache_size`.
- Failed evaluating precondition for rule 'Query cache efficiency (%)'. Error when evaluating: Variable "Qcache_hits" is not valid around position 14 for expression `Com_select + Qcache_hits > 0 && !fired('Query cache disabled')`.
- Failed calculating value for rule 'Query Cache usage'. Error when evaluating: Variable "Qcache_free_memory" is not valid around position 7 for expression `100 - Qcache_free_memory / query_cache_size * 100`.
- Failed calculating value for rule 'Query cache fragmentation'. Error when evaluating: Variable "Qcache_free_blocks" is not valid around position 1 for expression `Qcache_free_blocks / (Qcache_total_blocks / 2) * 100`.
- Failed evaluating precondition for rule 'Query cache low memory prunes'. Error when evaluating: Variable "Qcache_inserts" is not valid around position 1 for expression `Qcache_inserts > 0 && !fired('Query cache disabled')`.
- Failed calculating value for rule 'Query cache max size'. Error when evaluating: Variable "query_cache_size" is not valid around position 1 for expression `query_cache_size`.
- Failed calculating value for rule 'Query cache min result size'. Error when evaluating: Variable "query_cache_limit" is not valid around position 1 for expression `query_cache_limit`.
```
### Server configuration
**Operating system**:
Windows 10 Pro x64

**Web server:**
Apache 2.4.33 (Win64)

**Database:**
MySQL 8.0.11

**PHP version:**
7.2.5 x64 (ApacheLounge)

**phpMyAdmin version:**
4.8.0.1

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10 Home x64

### PR DESCRIPTION
**Pull request by Tithugues**
Fix #14245

### CODE REVIEW

**Comment by Tithugues** [comment]
PR for 5.0 is https://github.com/phpmyadmin/phpmyadmin/pull/15457

**Review by williamdes — APPROVED** [review]
LGTM, thanks for the work !

**Comment by williamdes** [comment]
@Tithugues please fix https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/578951389#L964

**Comment by williamdes** [comment]
Thank you for backporting your changes on #15457 :)

**Pull request merged**
