### PR TITLE
Fix improperly escaped HTML code in database structure page; issue #14071 

### LINKED ISSUE #14071: Database structure page improperly escaped HTML code
I have a table named `table 1`. On the database structure page, the table is shown as `table&nbsp;1`

With git 'master'

### PR DESCRIPTION
**Pull request by meteorlxy**
My first PR to phpMyAdmin.

Sorry I missed signoff in last PR.

This bug #14071 is related to the file `libraries/classes/Controllers/Database/DatabaseStructureController.php`

```php
$truename = htmlspecialchars(
    (!empty($tooltip_truename)
        && isset($tooltip_truename[$current_table['TABLE_NAME']]))
    ? $tooltip_truename[$current_table['TABLE_NAME']]
    : $current_table['TABLE_NAME']
);
$truename = str_replace(' ', '&nbsp;', $truename);
```

I remove `htmlspecialchars()` and `str_replace()`, and the table name displays well.

### CODE REVIEW

**Comment by meteorlxy** [comment]
Why the Selenium tests failed? I think it's not related to my PR.

**Review by shucon — CHANGES_REQUESTED** [review]
I don't think removing htmlspecialchars is a good idea due to security reasons, try correcting the line containing str_replace.

**Comment by ibennetch** [comment]
Thanks for your contribution.

The .gitignore changes shouldn't really be part of this pull request since they're independent of the bug.

Could you please use your real name for the commit signoff message?

**Comment by meteorlxy** [comment]
@shucon But `<` and `>` will be escaped improperly too.

As for security issues, xss in table name? Maybe the attacker should get the database auth first and it will be another securiy problem.

**Comment by meteorlxy** [comment]
@ibennetch  Oh sorry, I'm not familiar with signoff. What should I do? Creat another commit or rebase current commits?

`.gitignore` is not related to this issue, but I think it need to be updated. Should I revert it?

**Comment by meteorlxy** [comment]
@ibennetch 

I've opened another PR #14098 and close this one.

**Pull request closed without merging**
