### PR TITLE
[WIP] Added lint.

### PR DESCRIPTION
**Pull request by udan11**
Added lint. 

Signed-off-by: Dan Ungureanu udan1107@gmail.com

Work in progress. 
- [X] Basic support.
- [X] Add configuration entries.
- [ ] Write more strict rules for parsing depending on context (see udan11/sql-parser#2).
- [x] Reorganize `lint.php`.

### CODE REVIEW

**Comment by lem9** [comment]
Interesting feature. I tested typing errors in the data types and fixing them. I fear about the performance (calling a script almost once per character typed).

Also, something curious: if I type CREATE TBLE then continue with my definition, I have an error below on my VARCHAR not being a correct statement. I guess that this will be fixed with more parsing rules.

**Comment by udan11** [comment]
The accuracy will improve when more rules will be written. I already wrote a couple of new ones and I'll commit the new library to phpMyAdmin soon.

Regarding performance, CodeMirror will make a new request only when you pause typing. For example, if you were to type continuously and only stop when the query is finished, only one request would be made. Also, long queries aren't analyzed.

I guess that I could set a timer to send a request only a couple of seconds (maybe 10) and only if the contents changed. Would that be better?

**Comment by lem9** [comment]
I was not typing fast enough in my test! So I withdraw my comment about performance.

**Comment by lem9** [comment]
Please use the normal token protection inside lint.php; we don't want XSS via this script.

**Comment by lem9** [comment]
Not sure if it's because you're using strlen() instead of mb_strlen(), but I can generate a js error by typing
````
select from école
````

**Comment by udan11** [comment]
I believe there is absolutely no vulnerability in this script. All it does is to accept one user input, parse it and send back a JSON response. Before displaying the result to the user, the response is escaped and any tag that may cause issues is escaped.

Also, I fixed the issue with UTF-8 strings.

**Comment by lem9** [comment]
About strlen(), see https://github.com/phpmyadmin/phpmyadmin/commit/66b4be9b and look at my comments. Can you use mb_strlen() with the '8bit' parameter?

**Comment by lem9** [comment]
If you believe there is no vulnerability, please indicate your reasoning as comments at the beginning of lint.php to document why there is no token protection.

**Comment by lem9** [comment]
Changes are fine; awaiting completion of the WIP.

**Comment by udan11** [comment]
I believe this is ready to be merged. The rules have been improved significantly and further updates will come in the future versions of the library.

**Comment by lem9** [comment]
Nice work. I'm merging but I hope you are aware that some mistakes like "WHRE" are not detected. Also, looks like the linter does not have effect when typing in the console?

**Comment by udan11** [comment]
"WHRE" might not be a mistake. The following query: "SELECT * FROM actor WHRE" is valid.

**Comment by lem9** [comment]
True about the alias case. Now, what about typing in the console?

**Comment by udan11** [comment]
I'll take care of that. :)

**Pull request merged**
