### PR TITLE
Designer settings saved in a new table in configuration storage

### PR DESCRIPTION
**Pull request by devenbansod**
Added a new table in PMA configuration storage.

Stores/ updates the values of designer settings in this new table.

Signed-off-by: Deven Bansod devenbansod.bits@gmail.com

### CODE REVIEW

**Comment by ibennetch** [comment]
Looks good!

**Comment by ibennetch** [comment]
For future reference, see also the other (session-based) implementation we decided against at https://github.com/phpmyadmin/phpmyadmin/pull/1732

**Comment by madhuracj** [comment]
@devenbansod 
Please note that I have changed the column name from 'user' to 'username' to be consistent with other phpMyAdmin tables in https://github.com/phpmyadmin/phpmyadmin/commit/3ff7a264269187298ddc93194c1dfcdd5b5da6a9.

I also think it would be better to avoid using MySQL keywords as column names (`index` and `value`), especially when we show a warning when users are trying to create tables with keywords as column names.

**Comment by devenbansod** [comment]
Thanks @madhuracj . I will take care of it from now on.

About the column names, thanks, I had not realized it before. I will keep a check on keywords while introducing such things in future. 

Also, do you think, `setting` and `preference` for 'index' and 'value' respectively, would make suitable substitutes ?

**Comment by ibennetch** [comment]
Madhura this is a good point, thanks.

Do you see any use to making this table name more generic to potentially store other various phpMyAdmin settings in the future?

**Pull request merged**
