### PR TITLE
Fixed the errors coming up

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
### Description

The issue was coming up on the branch QA_5_1 because a trait method was not properly overridden:
```
getTransFunction((bool $hasPlural, bool $hasContext, bool $hasDomain)
```
The function signature was improper and I have fixed it up.

Fixes https://github.com/phpmyadmin/phpmyadmin/issues/17489

Before submitting the pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Hi,

Thank you for the fix, I am not sure why you are the only one affected by this 🤔 
Maybe it is related to me changing the signature: https://github.com/phpmyadmin/twig-i18n-extension/commit/8febcbe62beeac2f244678bcf6d182efa452a285#diff-01d6e4c018ec19fcbca1035fac1468f7dc96b3c98e1d7af39c62616250e8a750R240

We use v3 and not v4: https://github.com/phpmyadmin/phpmyadmin/blob/ea6a70037c8443c4405bba2242a1fd56a0948da4/composer.json#L53

You can see the upgrade to v4 here: #16675

Do you have some idea about why this happens for you ?

cc @mauriciofauth if you have a idea too

**Comment by SachinBahukhandi** [comment]
I actually tried updating the dependency:
```
 "phpmyadmin/twig-i18n-extension": "^3.0", 
```
To:
 "phpmyadmin/twig-i18n-extension": "^4.0",

Ran `composer update`

It still works fine, without me reverting the changed method signature.
Thoughts, @williamdes ?

**Comment by SachinBahukhandi** [comment]
Also, I see some strange errors out here:
image
Are you also seeing them?

**Comment by williamdes** [comment]
> 

I am a bit puzzled that none of our testing methods did show the error you are reporting 🤔 
So you are using PHP 8.1 and did run `composer update` on your workstation ?
What command do you use to run the local server ?

**Comment by williamdes** [comment]
> Also, I see some strange errors out here: image Are you also seeing them?

Maybe you did reproduce #17465 but I am not sure

**Comment by williamdes** [comment]
By the way you need to run `yarn run build` to solve the CSS and JS 404 issues

**Comment by SachinBahukhandi** [comment]
> > 
> 
> I am a bit puzzled that none of our testing methods did show the error you are reporting thinking So you are using PHP 8.1 and did run `composer update` on your workstation ? What command do you use to run the local server ?

Yes exactly this is what I did.
To run local  server I ran : `php -S localhost:8000`.
I also tried it using apache vhosts.

**Comment by SachinBahukhandi** [comment]
> > Also, I see some strange errors out here: image Are you also seeing them?
> 
> Maybe you did reproduce #17465 but I am not sure

Yes I did it.

**Comment by williamdes** [comment]
I have no errors on my end, here is screenshots
Sélection_2022042219:46:17001
Sélection_2022042219:46:00001

**Comment by mauriciofauth** [comment]
The only way I'm able to reproduce this is to checking out `QA_5_2`, installing the dependencies, then checking out `QA_5_1` and trying to load phpMyAdmin without installing the dependencies.

@SachinBahukhandi, Could you please check out `QA_5_1` again, without your changes, then run `yarn install && composer update` in your terminal, and try again to see if the issue persists? Also, try adding `$cfg['environment'] = 'development';` to your `config.inc.php` file to see if you're having cache issues.

**Comment by SachinBahukhandi** [comment]
> The only way I'm able to reproduce this is to checking out `QA_5_2`, installing the dependencies, then checking out `QA_5_1` and trying to load phpMyAdmin without installing the dependencies.
> 
> @SachinBahukhandi, Could you please check out `QA_5_1` again, without your changes, then run `yarn install && composer update` in your terminal, and try again to see if the issue persists? Also, try adding `$cfg['environment'] = 'development';` to your `config.inc.php` file to see if you're having cache issues.

Tried the same. Checked out to the last commit and tried the above commands before logging in again.
But the error still persists.
image

**Comment by mauriciofauth** [comment]
> Tried the same. Checked out to the last commit and tried the above commands before logging in again. But the error still persists.

Have you added `$cfg['environment'] = 'development';` to your `config.inc.php` file? The page shouldn't be blank in development mode.
Try removing the `tmp` directory and removing the `libraries/cache/routes.cache.php` file.

**Comment by SachinBahukhandi** [comment]
> > Tried the same. Checked out to the last commit and tried the above commands before logging in again. But the error still persists.
> 
> Have you added `$cfg['environment'] = 'development';` to your `config.inc.php` file? The page shouldn't be blank in development mode. Try removing the `tmp` directory and removing the `libraries/cache/routes.cache.php` file.

Ok deleting the `tmp` dir and `libraries/cache/routes.cache.php` makes it work.
But, I see two errors coming up:
image

**Comment by SachinBahukhandi** [comment]
> > > Tried the same. Checked out to the last commit and tried the above commands before logging in again. But the error still persists.
> > 
> > 
> > Have you added `$cfg['environment'] = 'development';` to your `config.inc.php` file? The page shouldn't be blank in development mode. Try removing the `tmp` directory and removing the `libraries/cache/routes.cache.php` file.
> 
> Ok deleting the `tmp` dir and `libraries/cache/routes.cache.php` makes it work. But, I see two errors coming up: image

@MauricioFauth I think this might need to be taken up as to be fixed properly or maybe the underlying cache might be a problem.

**Comment by williamdes** [comment]
> But, I see two errors coming up:

Do not worry about them, it's not a bug. Just some configuration to adjust and probably permissions of `tmp` folder too

**Review by williamdes — CHANGES_REQUESTED** [review]
I am closing this one because 5.1 is ended and now 5.2 is the official supported version
And this file does not exist anymore in 5.2: https://github.com/phpmyadmin/phpmyadmin/tree/QA_5_2/libraries/classes/Twig

But this was a non issue only related to a missing `composer update` command call

**Pull request closed without merging**
