### PR TITLE
Add Support for CHECK Constraints

### PR DESCRIPTION
**Pull request by aroralakshya**
Before submitting pull request, please check that every commit:
#13592 
I'll be making a separate pr for the sql-parser.
Working on tests.

https://github.com/phpmyadmin/sql-parser/pull/200

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nulll-pointer** [comment]
I don't understand about this merge conflict. IndexExtension has been removed from Template.php??

**Comment by ibennetch** [comment]
Yes, @laps15 removed it with aee045f960131cf9a5d97c50c48814ecd6b03d48.

On quick look, I think the reason the merge failed wasn't because of any direct conflicts, just that the adjacent lines to your changes were also changed, so Git is having trouble figuring out out to reconcile the changes. It looks to me like a manual merge will work, so I'll try that and report back here my results.

**Comment by ibennetch** [comment]
Something seems to be off with this when letting phpMyAdmin automatically create the table for me.

Before clicking "Create missing phpMyAdmin configuration storage tables.":

image

After clicking that link:

image

And the table still isn't created.

Even if I manually create the table, this dialog shows that it's missing until I run the "Create missing..." link, so it's odd that it seems to require both manual action and then also running the automatic script.

Finally, when I click the "Go" button to "Add a new Check Constraint", nothing happens.

**Comment by nulll-pointer** [comment]
Im looking into this.

**Comment by williamdes** [comment]
@nulll-pointer no update on this PR?

**Comment by Rockstarrecords11** [comment]
I'm our fix my null I'm. Not null anymorw

**Pull request closed without merging**
