### PR TITLE
index.php readability - HTML instead of php echo

### PR DESCRIPTION
**Pull request by ryanfmurphy**
Hey PhpMyAdmin devs!

I make some changes to the index.php file that (I feel) makes the code much more readable.  Mostly just taking the HTML out of the echo statements so you can have syntax highlighting and easier-to-see indentation.

No worries if this is too big a change to merge, just learning the process and would love to help!

Best,
Ryan

### CODE REVIEW

**Comment by ryanfmurphy** [comment]
By the way, the diff looks a little crazy since I re-indented.  It's easier to see with a git diff -w:

    diff --git a/index.php b/index.php
    index d4ec7f2..a6f1195 100644
    --- a/index.php
    +++ b/index.php
    @@ -91,7 +91,9 @@ if ($GLOBALS['PMA_Config']->isGitRevision()) {
                 PMA_printGitRevision();
                 exit;
             }
    -    echo '<div id="is_git_revision"></div>';
    +?>
    +    <div id="is_git_revision"></div>
    +<?php
         }
     
         // Handles some variables that may have been sent by the calling script
    @@ -101,7 +103,9 @@ $show_query = '1';
     
         // Any message to display?
         if (! empty($message)) {
    -    echo PMA\libraries\Util::getMessage($message);
    +?>
    +    <?= PMA\libraries\Util::getMessage($message) ?>
    +<?php
             unset($message);
         }
     
    @@ -135,17 +139,19 @@ if ($server > 0) {
                         ? $GLOBALS['cfg']['Server']['verbose']
                         : $GLOBALS['cfg']['Server']['host']);
         }
    -
    -echo '<div id="maincontainer">' . "\n";
    -// Anchor for favorite tables synchronization.
    -echo RecentFavoriteTable::getInstance('favorite')->getHtmlSyncFavoriteTables();
    -echo '<div id="main_pane_left">';
    -if ($server > 0 || count($cfg['Servers']) > 1
    -) {
    +?>
    +    <div id="maincontainer">
    +<?php // Anchor for favorite tables synchronization.?>
    +    <?= RecentFavoriteTable::getInstance('favorite')->getHtmlSyncFavoriteTables() ?>
    +        <div id="main_pane_left">
    +<?php
    +    if ($server > 0 || count($cfg['Servers']) > 1) {
             if ($cfg['DBG']['demo']) {
    -        echo '<div class="group">';
    -        echo '<h2>' . __('phpMyAdmin Demo Server') . '</h2>';
    -        echo '<p style="margin: 0.5em 1em 0.5em 1em">';
    +?>
    +            <div class="group">
    +                <h2><?= __('phpMyAdmin Demo Server') ?></h2>
    +                <p style="margin: 0.5em 1em 0.5em 1em">
    +                <?php
                         printf(
                             __(
                                 'You are using the demo server. You can do anything here, but '
    @@ -154,13 +160,16 @@ if ($server > 0 || count($cfg['Servers']) > 1
                             ),
                             '<a href="http://demo.phpmyadmin.net/">demo.phpmyadmin.net</a>'
                         );
    -        echo '</p>';
    -        echo '</div>';
    +                ?>
    +                </p>
    +            </div>
    +<?php
             }
    -    echo '<div class="group">';
    -    echo '<h2>' . __('General settings') . '</h2>';
    -    echo '<ul>';
    -
    +?>
    +            <div class="group">
    +                <h2><?= __('General settings') ?></h2>
    +                <ul>
    +<?php
             /**
              * Displays the MySQL servers choice form
              */
    @@ -169,10 +178,12 @@ if ($server > 0 || count($cfg['Servers']) > 1
                 && (count($cfg['Servers']) > 1
                 || ($server == 0 && count($cfg['Servers']) == 1)))
             ) {
    -        echo '<li id="li_select_server" class="no_bullets" >';
                 include_once 'libraries/select_server.lib.php';
    -        echo PMA\libraries\Util::getImage('s_host.png') . " " . PMA_selectServer(true, true);
    -        echo '</li>';
    +?>
    +                    <li id="li_select_server" class="no_bullets">
    +                        <?= PMA\libraries\Util::getImage('s_host.png') . " " . PMA_selectServer(true, true) ?>
    +                    </li>
    +<?php
             }
     
             /**
    @@ -197,62 +208,73 @@ if ($server > 0 || count($cfg['Servers']) > 1
                         );
                     }
                 } // end if
    -        echo '    <li id="li_select_mysql_collation" class="no_bullets" >';
    -        echo '        <form method="post" action="index.php">' . "\n"
    -           . PMA_URL_getHiddenInputs(null, null, 4, 'collation_connection')
    -           . '            <label for="select_collation_connection">' . "\n"
    -           . '                ' . PMA\libraries\Util::getImage('s_asci.png') . "&nbsp;"
    -                               . __('Server connection collation') . "\n"
    -           // put the doc link in the form so that it appears on the same line
    -           . PMA\libraries\Util::showMySQLDocu('Charset-connection')
    -           . ': ' .  "\n"
    -           . '            </label>' . "\n"
    -
    -           . PMA_generateCharsetDropdownBox(
    +?>
    +                    <li id="li_select_mysql_collation" class="no_bullets" >
    +                        <form method="post" action="index.php">
    +                            <?= PMA_URL_getHiddenInputs(null, null, 4, 'collation_connection') ?>
    +                            <label for="select_collation_connection">
    +                                <?= PMA\libraries\Util::getImage('s_asci.png') ?>&nbsp;
    +                                <?= __('Server connection collation') ?>
    +                                <?php // put the doc link in the form so that it appears on the same line ?>
    +                                <?= PMA\libraries\Util::showMySQLDocu('Charset-connection') ?>
    +                                :
    +                            </label>
    +                            <?= PMA_generateCharsetDropdownBox(
                                     PMA_CSDROPDOWN_COLLATION,
                                     'collation_connection',
                                     'select_collation_connection',
                                     $collation_connection,
                                     true,
                                     true
    -           )
    -           . '        </form>' . "\n"
    -           . '    </li>' . "\n";
    +                            ) ?>
    +                        </form>
    +                    </li>
    +<?php
             } // end of if ($server > 0)
    -    echo '</ul>';
    -    echo '</div>';
    +?>
    +                </ul>
    +            </div>
    +<?php
         }
    -
    -echo '<div class="group">';
    -echo '<h2>' . __('Appearance settings') . '</h2>';
    -echo '  <ul>';
    -
    +?>
    +            <div class="group">
    +                <h2><?= __('Appearance settings') ?></h2>
    +                <ul>
    +<?php
         // Displays language selection combo
         if (empty($cfg['Lang']) && count($GLOBALS['available_languages']) > 1) {
    -    echo '<li id="li_select_lang" class="no_bullets">';
             include_once 'libraries/display_select_lang.lib.php';
    -    echo PMA\libraries\Util::getImage('s_lang.png') . " " . PMA_getLanguageSelectorHtml();
    -    echo '</li>';
    +?>
    +                    <li id="li_select_lang" class="no_bullets">
    +                        <?= PMA\libraries\Util::getImage('s_lang.png') . " " . PMA_getLanguageSelectorHtml() ?>
    +                    </li>
    +<?php
         }
     
         // ThemeManager if available
     
         if ($GLOBALS['cfg']['ThemeManager']) {
    -    echo '<li id="li_select_theme" class="no_bullets">';
    -    echo PMA\libraries\Util::getImage('s_theme.png') . " "
    -            .  $_SESSION['PMA_Theme_Manager']->getHtmlSelectBox();
    -    echo '</li>';
    +?>
    +                    <li id="li_select_theme" class="no_bullets">
    +                        <?= PMA\libraries\Util::getImage('s_theme.png') ?>
    +                        <?= $_SESSION['PMA_Theme_Manager']->getHtmlSelectBox() ?>
    +                    </li>
    +<?php
         }
    -echo '<li id="li_select_fontsize">';
    -echo PMA\libraries\Config::getFontsizeForm();
    -echo '</li>';
    +?>
    +                    <li id="li_select_fontsize">
    +                        <?= PMA\libraries\Config::getFontsizeForm() ?>
    +                    </li>
     
    -echo '</ul>';
    +                </ul>
     
    +<?php
         // User preferences
     
         if ($server > 0) {
    -    echo '<ul>';
    +?>
    +                <ul>
    +                    <?php
                             PMA_printListItem(
                                 PMA\libraries\Util::getImage('b_tblops.png') . "&nbsp;" . __('More settings'),
                                 'li_user_preferences',
    @@ -262,21 +284,22 @@ if ($server > 0) {
                                 null,
                                 "no_bullets"
                             );
    -    echo '</ul>';
    +                    ?>
    +                </ul>
    +<?php
         }
    +?>
    +            </div>
    +        </div>
     
    -echo '</div>';
    -
    -
    -echo '</div>';
    -echo '<div id="main_pane_right">';
    -
    -
    +        <div id="main_pane_right">
    +<?php
         if ($server > 0 && $GLOBALS['cfg']['ShowServerInfo']) {
    -
    -    echo '<div class="group">';
    -    echo '<h2>' . __('Database server') . '</h2>';
    -    echo '<ul>' . "\n";
    +?>
    +            <div class="group">
    +                <h2><?= __('Database server') ?></h2>
    +                <ul>
    +                    <?php
                             PMA_printListItem(
                                 __('Server:') . ' ' . $server_info,
                                 'li_server_info'
    @@ -299,22 +322,25 @@ if ($server > 0 && $GLOBALS['cfg']['ShowServerInfo']) {
                                 __('User:') . ' ' . htmlspecialchars($mysql_cur_user_and_host),
                                 'li_user_info'
                             );
    -
    -    echo '    <li id="li_select_mysql_charset">';
    -    echo '        ' . __('Server charset:') . ' '
    -       . '        <span lang="en" dir="ltr">';
    -    echo '           ' . $mysql_charsets_descriptions[$mysql_charset_map['utf-8']];
    -    echo '           (' . $mysql_charset_map['utf-8'] . ')'
    -       . '        </span>'
    -       . '    </li>'
    -       . '  </ul>'
    -       . ' </div>';
    +                    ?>
    +                    <li id="li_select_mysql_charset">
    +                        <?= __('Server charset:') ?>
    +                        <span lang="en" dir="ltr">
    +                            <?= $mysql_charsets_descriptions[$mysql_charset_map['utf-8']] ?>
    +                            (<?= $mysql_charset_map['utf-8'] ?>)
    +                        </span>
    +                    </li>
    +                </ul>
    +            </div>
    +<?php
         }
     
         if ($GLOBALS['cfg']['ShowServerInfo'] || $GLOBALS['cfg']['ShowPhpInfo']) {
    -    echo '<div class="group">';
    -    echo '<h2>' . __('Web server') . '</h2>';
    -    echo '<ul>';
    +?>
    +            <div class="group">
    +                <h2><?= __('Web server') ?></h2>
    +                <ul>
    +<?php
             if ($GLOBALS['cfg']['ShowServerInfo']) {
                 PMA_printListItem($_SERVER['SERVER_SOFTWARE'], 'li_web_server_software');
     
    @@ -360,13 +386,16 @@ if ($GLOBALS['cfg']['ShowServerInfo'] || $GLOBALS['cfg']['ShowPhpInfo']) {
                     '_blank'
                 );
             }
    -    echo '  </ul>';
    -    echo ' </div>';
    +?>
    +                </ul>
    +            </div>
    +<?php
         }
    -
    -echo '<div class="group pmagroup">';
    -echo '<h2>phpMyAdmin</h2>';
    -echo '<ul>';
    +?>
    +            <div class="group pmagroup">
    +                <h2>phpMyAdmin</h2>
    +                <ul>
    +<?php
         $class = null;
         // We rely on CSP to allow access to http://www.phpmyadmin.net, but IE lacks
         // support here and does not allow request to http once using https.
    @@ -428,13 +457,12 @@ PMA_printListItem(
             null,
             '_blank'
         );
    -echo '    </ul>';
    -echo ' </div>';
    -
    -echo '</div>';
    -
    -echo '</div>';
    -
    +?>
    +                </ul>
    +            </div>
    +        </div>
    +    </div>
    +<?php
         /**
          * Warning if using the default MySQL privileged account
          */

**Comment by lem9** [comment]
Thanks. This is not really the direction we are taking. This summer we started moving to templates, for example https://github.com/Tithugues/phpmyadmin/commit/f31d0ba0b9c1f01a44d8d5db566182614e1a6428

**Comment by ryanfmurphy** [comment]
I saw that I missed the Signed-Off-By: tag.  I tried to do a git commit --amend --signoff to do it, and that seemed to work, but I wasn't sure whether I should actually close this pull request and open a new one?  Or is it ok to use this one?

**Comment by ryanfmurphy** [comment]
Oh cool, what template engine are you using?

**Comment by lem9** [comment]
We use our own.

**Comment by ryanfmurphy** [comment]
Cool!  Do you find my version of the file more readable though?

**Comment by lem9** [comment]
Even if I did, it's better we follow our new approach.

**Comment by ryanfmurphy** [comment]
Are they mutually exclusive?

**Comment by lem9** [comment]
I believe so but I'll let other team members comment on this.

**Comment by ryanfmurphy** [comment]
Ok great, thanks for your consideration of my patch, and for maintaining such an important project!

**Comment by ryanfmurphy** [comment]
So the Travis Build failed, but it looks like it was for a totally unrelated reason - a translation file po/fi.po that's already committed into the repo:

    locales:

     [exec] po/fi.po:5277: a format specification for argument 5 doesn't exist in 'msgstr'

     [exec] msgfmt: found 1 fatal error

     [exec] Error when compiling po/fi.po

     [exec] 

    BUILD FAILED

    /home/travis/build/phpmyadmin/phpmyadmin/build.xml:148: exec returned: 1

**Comment by zixtor** [comment]
@ryanfmurphy looking at the diff in comment, it seems not to be what is desirable for us at this point of time. Templating would essentially involve clear separation of HTML out of the HTML-PHP mix (be it in 'echo' form or '<?php ?>' form, we are avoiding both in favor of templates). Please have a look at the example commit provided by Marc, we welcome your contribution on those lines.

**Comment by ryanfmurphy** [comment]
@zixtor - I totally agree that templates is the way to go -- but isn't this exactly how you migrate towards templates?  Your index file is fill of echoing HTML tags - if you take them out of the echo statements and into PHP's built-in templating system (which is what my patch does), then it becomes much easier to isolate all the data / non-templating functionality away from the presentational HTML stuff.

This is how I've always made that migration anyways, would be interested to hear how you guys are doing the migration if not in this way.

**Comment by ryanfmurphy** [comment]
@zixtor @lem9 - Ok, I looked at the example and I get what you guys are going for template-wise.  Maybe I'll take another stab at it.  Thanks!

**Comment by ryanfmurphy** [comment]
Question @zixtor - in your phtml templates, how would you handle a conditional branch like an "if" (is there a way to do that?).  More generally, is there documentation I could look at on how your phtml templates work?

**Comment by zixtor** [comment]
@ryanfmurphy Yes, your diff may make part of first step towards templating if it is additionally supported with some refactoring of the script to fetch out a template most appropriately. For example: the function PMA_printListItem in this index.php file makes use of a template and does some preliminary work.

So your diff, until it is made part of a full solution towards templating, would not not be much different from status quo. I hope I am not being vague here :)

**Comment by zixtor** [comment]
@ryanfmurphy About the way we are handling 'if" in phtml currently, please see https://github.com/phpmyadmin/phpmyadmin/blob/master/templates/columns_definitions/column_attribute.phtml.
Sorry, we currently don't have detailed documentation on practices to maintain in our phtml files and we are new into it with our old codebase. That's why, on how to properly approach templating may turn out unique to a particular script you are handling. At the moment for us, broadly, templating means fetching a bunch of related HTML out of a file into a 'templates/some_folder/some_name.phtml' file, and then invoking it by calling:-

 namespace current_namespace;
 use PMA\Template;
 include_once './libraries/Template.class.php';
 $response->addHTML(Template::get('the_template_name_without_phml')->render(array('data_variables_to_be_used_by_the_template'));

**Comment by ryanfmurphy** [comment]
Ok thanks!  So it seems to support the usual PHP template get style.
That's convenient.  Thank you for your help Atul!

**Pull request closed without merging**
