### PR TITLE
Move public files to the public directory

### LINKED ISSUE #16229: Create a public directory for public files
By moving public files to a public directory, we improve the security of phpMyAdmin because users will not have access to files that are outside the public directory.

Related to #14814.

### PR DESCRIPTION
**Pull request by MauricioFauth**
- Fixes https://github.com/phpmyadmin/phpmyadmin/issues/16229

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by kamil-tekiela** [comment]
Any tips for contributors how to easily migrate? PMA doesn't see my config file now. I am not sure if I have to change anything on my setup.

**Comment by MauricioFauth** [comment]
> Any tips for contributors how to easily migrate?

Documentation about this is missing. See https://github.com/phpmyadmin/phpmyadmin/issues/18147.
The idea is serve the files from the public directory, but serving the files should work as usual.

> PMA doesn't see my config file now. I am not sure if I have to change anything on my setup.

That's weird. What HTTP server you are using?

**Comment by kamil-tekiela** [comment]
I am using Wampserver, which is running Apache 2.4

**Comment by MauricioFauth** [comment]
> I am not sure if I have to change anything on my setup.

For example, nothing has changed for the demo server setup and it's working. But it is using Nginx.

Note the `public` appearing in the URL:
https://demo.phpmyadmin.net/master-config/public/index.php?route=/

**Comment by kamil-tekiela** [comment]
Ok, the current working directory has changed. Let me check what else I need to adjust.

**Comment by kamil-tekiela** [comment]
I had to adjust the path in the config file and it seems to work fine now. However, I am getting "Cannot modify header information - headers already sent" when logging it with incorrect credentials. I don't know if this is related or not.

**Comment by williamdes** [comment]
> Note the public appearing in the URL:
https://demo.phpmyadmin.net/master-config/public/index.php?route=/

We need to edit the server config so there is no more /public/ needed. And emails we sent since years continue to work (link to the /changelog route)
cc @ibennetch

**Comment by MauricioFauth** [comment]
> I had to adjust the path in the config file and it seems to work fine now. 

@kamil-tekiela What you had to adjust? Is it phpMyAdmin's config file?

**Comment by kamil-tekiela** [comment]
No, I am not using PMA's config file. I am using the one from wampserver and it used hardcoded path. It has this line `$wampConf = @parse_ini_file('../../wampmanager.conf');`

**Pull request merged**
