### PR TITLE
Remove inline js

### PR DESCRIPTION
**Pull request by nikkolai14**
#13270

### CODE REVIEW

**Comment by nikkolai14** [comment]
PMA Team, here is my first commit, just making sure i'm doing the right thing before continuing. :)

**Comment by nikkolai14** [comment]
PMA Team, can you please help me with this travis-ci error? I don't think I touched those files. thanks

**Review by williamdes — APPROVED** [review]
LGTM, the build failure seems unrelated
Maybe a rebase+squash could be a nice way to clean up this error

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!

**Pull request merged**
