### PR TITLE
Fix #12437: CSP Improvements

### LINKED ISSUE #12437: CSP improvements
Usage of not needed CSP values (result in weaker CSP policy)
 
from ReCaptcha Documentation: https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website-how-can-i-configure-it-to-work-with-recaptcha
The needed directives are:
        
        script-src https://www.google.com/recaptcha/, https://www.gstatic.com/recaptcha/
        frame-src https://www.google.com/recaptcha/
        style-src 'unsafe-inline'
    
so the below are probably not needed ($captcha_url in style-src & img-src)
    
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L553
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L560
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L572
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L585
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L590
    
and it's better to use frame-src (deprecated) or child-src

*        https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#child-src
*        https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#frame-src
        
instead of default-src for $captcha_url in:
    
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L565
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L577
*    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L590
 
12) CSP Improvements
 
12.1)
add reflected-xss CSP directive to Content-Security-Policy header only (as it's available only from CSP Level 2)
    reflected-xss block
    
12.2)
add object-src CSP directive such as:
    object-src 'none'
in order to disallow plugin usage (embed/object/applet) tags which isn't used by PMA.
 
more information:

*    https://groups.google.com/a/chromium.org/forum/#!msg/security-dev/UqCSmNUHhNg/XBlvV_E5eowJ
    
12.3)
 
add form-action CSP directive such as:
    form-action 'self'
* https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#form-action
This directive can be used to mitigate:
    XSS by URI Injection [ javascript:alert(1) ] in action attribute
    Leak of data to attacker domain via form submission.

### PR DESCRIPTION
**Pull request by rabeehrz**
Signed-off-by: Mohammed Rabeeh <mohammadrabeeh@gmail.com>

### Description

Improve CSP as mentioned in #12437

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
code looks good but I have to research to understand it ;)

**Review by MauricioFauth — COMMENTED** [review]
Can you explain the reasoning behind your changes?

**Comment by rabeehrz** [comment]
> Can you explain the reasoning behind your changes?

@mauriciofauth I made changes according to the issue opened by @nijel . He gave some direction in the issue and I followed it. :)

**Comment by williamdes** [comment]
I really need someone to explain to me that the change is the right one and why :)

**Comment by williamdes** [comment]
@emanuelb Could I request your approval on this PR please ?

**Comment by emanuelb** [comment]
3 changes, 2 ok, 1 bad:
1. The change of `default-src` to `child-src` is incorrect/bad.
`default-src` must stay unless all other directive affected by it are added, which are (some have fallbacks for other directives in this list):
```
    child-src
    connect-src
    font-src
    frame-src
    img-src
    manifest-src
    media-src
    object-src
    prefetch-src
    script-src
    script-src-elem
    script-src-attr
    style-src
    style-src-elem
    style-src-attr
    worker-src
```
`child-src` can be added in addition if more strict policy possible for nested resources (probably the case, need to check usages of frames in code)
2. Removing '$captcha_url' from img & style is ok (if it's works, in case captcha doesn't use this) 
3. `form-action 'self';` is ok (it ensure that url in form submission `<form action="url">` must be local)

**Comment by williamdes** [comment]
@rabeehrz could you rebase ?

**Comment by rabeehrz** [comment]
@williamdes Hey, I've been busy with a lot of college work and internships at the moment. I will get to it when I get a little bit of free time.

**Comment by williamdes** [comment]
> @williamdes Hey, I've been busy with a lot of college work and internships at the moment. I will get to it when I get a little bit of free time.

Hey

Okay, thank you :)

**Pull request closed without merging**
