### PR TITLE
Fix #17773 - demo footer links should be clickable

### LINKED ISSUE #17773: On demo server footer links aren't clickable
### Describe the bug

On demo server, footer links aren't clickable. Probably related to #17749.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/)
2. Try to click on links from footer
3. See error

### Expected behavior

Links should be clickable.

### Screenshots

https://user-images.githubusercontent.com/25424343/195250309-3d94d66e-7f92-4493-b4b9-f61d0630241f.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.2.1-dev

### Client configuration

- Browser: Firefox/Chrome
- Operating system: Windows

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by Arpit-Gulgulia**
Signed-off-by: Arpit Jain<arpitgulgulia@gmail.com>

### Description

Please describe your pull request: Fix for-17773

Fixes #17773

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Awesome!

**Comment by Arpit-Gulgulia** [comment]
@williamdes , could you please help with this codecov issue?. I'm not familiar with this tool. Would appreciate for any help. Thanks

**Comment by sureemo** [comment]
@Arpit-Gulgulia thank you for the fix. please also help update other themes also - `bootstrap`, `metro`, `original`. thanks again ^_^

**Comment by Arpit-Gulgulia** [comment]
> @Arpit-Gulgulia thank you for the fix. please also help update other themes also - `bootstrap`, `metro`, `original`. thanks again ^_^

Sure @sureemo , Working on others issue. But could you please help me with the above codecov, I haveno clues why it is failing. Would really appreciate for any help. Thanks

**Comment by williamdes** [comment]
> > @Arpit-Gulgulia thank you for the fix. please also help update other themes also - `bootstrap`, `metro`, `original`. thanks again ^_^
> 
> Sure @sureemo , Working on other issues. But could you please help me with the above codecov failing, I have no clues why it is failing. Would really appreciate for any help. Thanks

Nevermind about it, I did hide the message

**Comment by Arpit-Gulgulia** [comment]
> > > @Arpit-Gulgulia thank you for the fix. please also help update other themes also - `bootstrap`, `metro`, `original`. thanks again ^_^
> > 
> > 
> > Sure @sureemo, Working on other issues. But could you please help me with the above codecov failing, I have no clues why it is failing. Would really appreciate any help. Thanks
> 
> Nevermind about it, I did hide the message

Thanks, @williamdes for all your support! this was my first-ever contribution to open-source and hope to contribute many more. Just have one doubt about how the changes will be going merged into the base branch as they are already approved.

**Comment by williamdes** [comment]
> > > > @Arpit-Gulgulia thank you for the fix. please also help update other themes also - `bootstrap`, `metro`, `original`. thanks again ^_^
> > > 
> > > 
> > > Sure @sureemo, Working on other issues. But could you please help me with the above codecov failing, I have no clues why it is failing. Would really appreciate any help. Thanks
> > 
> > 
> > Nevermind about it, I did hide the message
> 
> Thanks, @williamdes for all your support! this was my first-ever contribution to open-source and hope to contribute many more. Just have one doubt about how the changes will be going merged into the base branch as they are already approved.

Approval is just an information, for merging it will show up on this page when it will be done in git

Could you push the change for other themes please?
Just pushing on the same branch will show up here, no need for a new pull-request.

When merging occurs this page will show as merged and we will merge QA_5_2 into master, so your change will be propagated up

**Comment by Arpit-Gulgulia** [comment]
@williamdes, Added the changes for other themes as well.

**Review by williamdes — APPROVED** [review]
Awesome, merge ready

**Comment by williamdes** [comment]
@MauricioFauth I merged this one, but let us know if you think there is a better solution

**Pull request merged**
