### PR TITLE
Remove unneeded closing tags

### PR DESCRIPTION
**Pull request by znck**
Closing tags at the end of file are not mandatory. It is often suggested to omit to closing tags at the end of file to prevent unwanted effects as PHP will start output buffering if there is any character after closing tag.

Also all the changed files are pure PHP.

Reference: http://php.net/manual/en/language.basic-syntax.phptags.php

### CODE REVIEW

**Comment by drainx** [comment]
I don't see what actual use this commit has. Rather than just remove all the closing tags (standard code convention is to have closing tags,) why not just check for whitespace on existing files and remove if present?

If committed, future php files will have to follow this new convention of not using the closing php tag.

**Comment by znck** [comment]
PSR-2 suggests not to close tags in PHP only files.

**Comment by lem9** [comment]
Added to the team meeting agenda (meeting in two days):
https://wiki.phpmyadmin.net/pma/2015-03_Meeting

**Comment by udan11** [comment]
I consider this a great idea. An even better idea would be to fully support the PSR-1 and PSR-2 standards.

**Comment by abdotayb** [comment]
Great notice that will help more with php execiting

**Comment by nijel** [comment]
I think it makes sense to follow general recommendations for code, so I think we can merge this.

**Pull request merged**
