### PR TITLE
fix: fixed the dots besides the navigation bar

### PR DESCRIPTION
**Pull request by ThanasisMpalatsoukas**
configFormDisplayTab seems to be a good selector to add the list-style: none. i checked all themes and the problem seems to dissapear.

fixes part of #18505 

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
@ThanasisMpalatsoukas while this fixes the issue, I think it can be fixed on another part of the code and avoid adding additional CSS styles.

The code that creates the modals should be changed, because the modals are created at the same time in two places on the page. The right place is at the bottom:

two modals

Let's wait for @williamdes review.

**Comment by ThanasisMpalatsoukas** [comment]
@liviuconcioiu weird. There seems to be only one instance of a pageSettingsModal modal in html in what im am seeing while having the modal opened.

image

**Review by williamdes — CHANGES_REQUESTED** [review]
> @ThanasisMpalatsoukas while this fixes the issue, I think it can be fixed on another part of the code and avoid adding additional CSS styles.

Thanks for the first review, indeed we are trying to remove all custom non bootstrap styles. Adding one more will not help
Let's see if there is another solution around that
Maybe bootstrap has some class to do the same job ?

**Comment by williamdes** [comment]
Most probably the code should use tabs instead: https://getbootstrap.com/docs/5.2/components/navs-tabs/

**Comment by liviuconcioiu** [comment]
Inside `maintcontainer` there is `pageSettingsModal`, but at the same time there is `pageSettingsModal` right under it. The same for `functionConfirmModal` and `addIndexModal` (don't know about those two where should be as I never encountered issues).

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/253daa96-1f74-4a8c-8cdd-ffc048cd1274

**Comment by ThanasisMpalatsoukas** [comment]
@liviuconcioiu it does seem that you are right that the second modal creates the problem with the css. You can see that when the modal is at the bottom the right css applies. I will try to see why the modals are generated twice.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
I think removing this entire block from common.scss will be better:

```css
#maincontainer {
  ul {
    list-style-type: disc;
    vertical-align: middle;
  }

  li {
    margin-bottom: 0.3em;
  }
}
```

**Comment by williamdes** [comment]
I am closing this one as no updates where pushed, feel free to ask for re-open and push updates

**Pull request closed without merging**
