### PR TITLE
Fix #16504 - Create view dialog is too big and won't scroll

### LINKED ISSUE #16504: Create view dialog is too big and won't scroll
### Describe the bug

I wanted to create a view, but the dialog box is too big to fit on my screen. I'm unable to scroll up and down.

### To Reproduce

1. Browse a table
2. In the results page "Query results operations" area, click "Create view"
3. The resulting page doesn't quite fit on my display (which is 2800x1800, less of course the browser menu bar)

### Expected behavior

Either the dialog should fit on the page, or I should be able to scroll.

### Screenshots

image

You can barely see what I imagine are "go" and "cancel" buttons at the bottom.

### Server configuration

- Operating system: MacOS
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 5.1.0-dev from master brance

### Client configuration

- Browser: Firefox
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by nsh58**
Signed-off-by: Shinya Nishimura <georgia6954@gmail.com>

### Description

I add createViewDialog's style to current window height.

Fixes #16504

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Looks nice!

**Comment by williamdes** [comment]
@sudo-robot deploy

**Review by williamdes — APPROVED** [review]
Awesome, tested and it works as expected !

**Comment by nsh58** [comment]
I had a valuable experience.
Thank you so much!!

**Pull request merged**
