### PR TITLE
#4788 Inline edit of DATE fields with NULL

### PR DESCRIPTION
**Pull request by daniyals**
Signed-off-by: Daniyal Shahid daniyal36@gmail.com

Added a top margin to the datepicker after a certain window height so that null checkbox is visible

### CODE REVIEW

**Comment by lem9** [comment]
Merged, thanks.

**Comment by zixtor** [comment]
This fix unconditionally adds a margin-top to the datepicker div, which is not quite desirable and produces following problems:-
1. For those columns that do not have DEFAULT NULL, we get blank spacing between input field and datepicker, due to margin-top.
2. Based on the state of page scroll, if the datepicker div is displayed on top of the input field instead of bottom, adding margin-top covers the input field.

**Comment by zixtor** [comment]
I missed it on first look, but above problems seem to be happening after you have once used the datepicker on a column with DEFAULT NULL.

**Comment by daniyalme** [comment]
Updated: https://github.com/phpmyadmin/phpmyadmin/pull/1543

**Comment by lem9** [comment]
@zixtor Can you look at the updated patch?

**Pull request merged**
