### PR TITLE
Work-in-progress: Add support for xz compression

### PR DESCRIPTION
**Pull request by madhuracj**
This is for https://sourceforge.net/p/phpmyadmin/feature-requests/1621/

I was not successful in properly installing php-xz and getting it to work. Wasted couple of hours struggling to get it to work. So this is not tested at all. I am submitting as a PR hoping either that someone will be able to test this or this will be a starting point for someone who's trying to implement.

### CODE REVIEW

**Comment by whitepiegon** [comment]
I was also facing problem in installing php-xz. That's why I didn't take up the work.
During working did you find any good link to learn installing php-xz?? If yes then please give the link. So, that I can try at least.

**Comment by vanarpsharma** [comment]
Had the same problem: installing php-xz from paydens contributions.

**Comment by udan11** [comment]
Hello guys!

I rewrote some parts of the README. You can find my fork [here](https://github.com/udan11/php-xz/blob/master/README.md). I hope everything works fine now!

**Comment by lem9** [comment]
See https://wiki.phpmyadmin.net/pma/2015-04_Meeting#Meeting_4

**Pull request closed without merging**
