### PR TITLE
Fix misspellings (Poland)

### PR DESCRIPTION
**Pull request by kwadrat**
### Description

Some misspellings

Fixes #

Before submitting pull request, please review the following checklist:

- [DONE] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [DONE] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [DONE] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ DONE] Every commit has a descriptive commit message.
- [DONE] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [No new functionality] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Hi !
Thank you for this changes could you post them to https://hosted.weblate.org/languages/pl/phpmyadmin/ so they propagate to more versions than only this PR ?

**Comment by kwadrat** [comment]
Good Morning :)

Yes - I noticed later that you are using Weblate for translation.

I will learn how to use Weblate and I will post my changes there.

Best wishes from Rybnik, Poland, Europe,
Piotr Kasprzyk
https://www.ciri.pl

**Comment by kwadrat** [comment]
I am closing PR as I introduced the changes through Weblate. Thank you!

**Comment by williamdes** [comment]
> I am closing PR as I introduced the changes through Weblate. Thank you!

Thank you for translating !

Commits I found for 5.2 and 6.0:
- 8f6f8c11b6c4138046e7497f3dcc54ee30f89df5
- 74c4f78b526444953e0e9db4ddd8ad71ed3c5c48

**Comment by kwadrat** [comment]
Thank you!

**Pull request closed without merging**
