### PR TITLE
fixed- Move operation causes SELECT * FROM `undefined`

### LINKED ISSUE #14636: Move operation causes SELECT * FROM `undefined`
### Describe the bug

When using the move action in the operations tab the next view incorrectly selects from the table name `undefined`

### To Reproduce

```
CREATE TABLE `1_test` (
 `foo` tinyint(3) unsigned NOT NULL,
 PRIMARY KEY (`foo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
Operations Tab > Move table to (database.table) > Enter any new name > Go
Table is moved correctly
Following page shows Table: undefined
```
SELECT * FROM `undefined` WHERE 1
```

### Expected behavior

Following view after move should select from correct table name

### Screenshots

image

image

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.3

### PR DESCRIPTION
**Pull request by wincdev**
-fixed params name in operation js file
-set value in global field table to new table name

Signed-off-by: Vincent Horváth <vincent.horvath@icloud.com>

### Description

Please describe your pull request.

Fixes #14636 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
@wincdev Can you fix DCO, Details :
```
Commit sha: b28c771, Author: Vincent Horváth,
Committer: Vincent Horváth;
Expected "Vincent Horváth win9400@gmail.com", but got "Vincent Horváth vincent.horvath@icloud.com".
```

**Review by williamdes — APPROVED** [review]
Looks good to me

**Comment by wincdev** [comment]
> @wincdev Can you fix DCO, Details :
> 
> ```
> Commit sha: b28c771, Author: Vincent Horváth,
> Committer: Vincent Horváth;
> Expected "Vincent Horváth win9400@gmail.com", but got "Vincent Horváth vincent.horvath@icloud.com".
> ```

How to remove one field Expected?

**Comment by williamdes** [comment]
@wincdev DCO is now correct, thanks :)

**Comment by wincdev** [comment]
@williamdes  
continuous-integration/travis-ci/pr finished failed CI_MODE=selenium "Selenium2TestCase.php:337". But also check build history  error in  "Selenium2TestCase.php:337" was exist before my pull-request.   
CI_MODE=phpstan the same.

Can you check there test?

**Comment by williamdes** [comment]
@wincdev I restarted the Job :)
PS: I responded to your email

**Review by OlafvdSpek — COMMENTED** [review]
Don't think the whitespace changes should be included.

**Comment by williamdes** [comment]
@wincdev Please squash your commits (dont forget to signoff) and remove the Changelog file from your diffs :)

**Comment by wincdev** [comment]
> @wincdev Please squash your commits (dont forget to signoff) and remove the Changelog file from your diffs :)

It is OK?

**Comment by williamdes** [comment]
@wincdev I think you can try the following command :
```bash
git rebase --interactive origin/master --exec 'git commit --amend --no-edit --signoff'
```

**You will be able to change all commits after first one from `pick` to `squash`.**
Afterwards you will have only one commit left and you can easily remove changelog from the diff. 


You are welcome on our [Slack](https://join.slack.com/t/phpmyadmingh/shared_invite/enQtNDAyODc0MzE2MzczLWY4ZDU0NmViYTdhN2UyZGM0Njc4YjRiYTRiYzI4YTQ0NWJhZjYyMDhlODI4M2JkYThlMzIzZTFiNzNjZWRhZjI) if you want or on Gitter.

**Comment by williamdes** [comment]
New PR: #14651

**Pull request closed without merging**
