### PR TITLE
minor css fix

### PR DESCRIPTION
**Pull request by rahgurung**
With `display: inline`, the width, height, margin-top, margin-bottom, and float properties have no effect.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@mauriciofauth if this CSS change makes sense for you I will merge it

**Comment by williamdes** [comment]
@gurrrung could you please make the change for each theme ?

**Comment by williamdes** [comment]
Thank you :)

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Thanks for your contribution.
These properties have effect because the `position` is `fixed`.

**Comment by williamdes** [comment]
I am closing this PR because the properties seems to be used.
Thank you for your contribution

**Pull request closed without merging**
