### PR TITLE
Fix for #4788

### PR DESCRIPTION
**Pull request by daniyals**
Signed-off-by: daniyal daniyal36@gmail.com

Added a top margin to the datepicker after a certain window height so that null checkbox is visible

### CODE REVIEW

**Comment by lem9** [comment]
Please use your full name in the Signed-off-by line.

**Comment by daniyalme** [comment]
Signed-off-by: Daniyal Shahid daniyal36@gmail.com

**Comment by lem9** [comment]
The patch works fine, thanks. Could you fix the trailing whitespace problem? Also, as the problem is also in 4.3, could you prepare a commit on the QA_4_3 branch?

**Comment by daniyalme** [comment]
Created a new pull request to remove the trailing whitespace.

I'll prepare a commit for QA_4_3 branch

**Pull request closed without merging**
