### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by ibennetch**
Signed-off-by: Isaac Bennetch <bennetch@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by nijel** [comment]
Whitespace should not be significant in XML strings, so adding whitespace to assertXmlStringEqualsXmlString should not be needed....

**Comment by ibennetch** [comment]
That's what I thought as well, but this fixes failing tests for me. I wonder if this is again a problem with my old version of PHPUnit.

**Comment by ibennetch** [comment]
This isn't making much sense to me.

`which phpunit`: `/usr/bin/phpunit`
`phpunit --version` is 4.2.6
`./vendor/phpunit/phpunit/phpunit --version` is 4.8.31

So I have two PHPUnits, one is the package manager version 4.2.6, the other is Composer-installed 4.8.31. Makes sense. But when I run tests from within my phpMyAdmin folder, it calls the Composer version (apparently in spite of my system path):

```
phpunit --exclude-group selenium -c phpunit.xml.nocoverage
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.
```

Which is strange, but even stranger, if I run `phpunit --exclude-group selenium -c phpunit.xml.nocoverage`, the tests in this pull request fail; if I run `./vendor/phpunit/phpunit/phpunit --exclude-group selenium -c phpunit.xml.nocoverage` they pass! Both of those commands show running with the same version, 4.8.31. 

Also, when running with the vendor path, I get two additional notices before the tests run:
```
Warning:        Deprecated configuration setting "strict" used
Warning:        Deprecated configuration setting "selenium" used
```

Since this seems to have *something* to do with my environment, so we can close this pull request, but I'm baffled by this.

Thanks.

**Comment by nijel** [comment]
Maybe it's using phpunit binary from path, but libraries from composer? That could explain some of the confusion...

**Comment by ibennetch** [comment]
Good suggestion, I suppose that makes the most sense. Anyway, I've entirely removed the Debian version and I'll just use Composer to maintain it where needed, since that's the simplest solution.

Thanks for the effort you've put in to these issues.

**Comment by nijel** [comment]
BTW: Something similar has just happened on Travis CI as well: We were using system installed phpunit which picked phpunit libraries from vendor leading to failure:

https://travis-ci.org/phpmyadmin/motranslator/jobs/194429435

**Pull request closed without merging**
