### PR TITLE
remove_msie9 (fix_11987)

### PR DESCRIPTION
**Pull request by poush**
- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them

Signed-off-by: Piyush poush12@gmail.com

### CODE REVIEW

**Comment by ibennetch** [comment]
I believe that by the DCO, we need to require a full name (unless Piyush is your complete legal name).

Aside from that, this looks good to me, although I don't actually have IE anymore to test some aspects of it.

**Comment by poush** [comment]
Can anyone please help me understand 'Failure' on https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/110457341 at line ```1408```

**Comment by poush** [comment]
@ibennetch I will ensure to keep my full name in my commits. I will also update this one once errors are rectified.

**Comment by ibennetch** [comment]
Looks like the tests are passing now, thanks.

**Comment by nijel** [comment]
Thanks, I've merged your changes.

But for next time, please use more descriptive commit messages...

**Pull request merged**
