### PR TITLE
Minimum supported PHP version is now 5.5.

### PR DESCRIPTION
**Pull request by nervo**
Signed-off-by: Florian Rey florian.rey@elao.com

Related to https://github.com/phpmyadmin/phpmyadmin/pull/11427

### CODE REVIEW

**Comment by udan11** [comment]
Please redo your commit after agreeing with [phpMyAdmin Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO).

To do this quickly:
```bash
git commit --amend --signoff
git push origin patch-1 --force
```

**Comment by nervo** [comment]
That *might* be ok :)

**Comment by lem9** [comment]
Thanks. I redid your commit so that the author name matches the Signed-off-by line, with QA_4_5 as the target: https://github.com/phpmyadmin/phpmyadmin/commit/e4d422cb43a973df91e80b5ff85798dd107767b5.patch

**Comment by lem9** [comment]
See also http://wiki.phpmyadmin.net/pma/Git#Before_starting

**Pull request closed without merging**
