### PR TITLE
Fix #13326 - quotes field type int

### LINKED ISSUE #13326: No quotes when field type is int
https://demo.phpmyadmin.net/QA_4_9/tbl_select.php?db=sakila&table=actor

    SELECT * FROM `actor` WHERE `actor_id` = test LIMIT 0, 25 :(

I think it should put quotes around test..

### PR DESCRIPTION
**Pull request by tlshifat**
### Description

no quotes field type int 13326

Fixes #13326

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shifatbuet** [comment]
please proceed .

**Comment by williamdes** [comment]
Please clean your master branch using:
```
git checkout master
git reset --hard 12db01bfc355915eabe1a23b96e068cfc43d37d4
git push --force
```

And then rebase or apply the commands like https://github.com/phpmyadmin/phpmyadmin/pull/15611#issuecomment-561329014 using the commit of this branch

thank you :)

**Comment by shifatbuet** [comment]
> 
> 
> Please clean your master branch using:
> 
> ```
> git checkout master
> git reset --hard 12db01bfc355915eabe1a23b96e068cfc43d37d4
> git push --force
> ```
> 
> And then rebase or apply the commands like [#15611 (comment)](https://github.com/phpmyadmin/phpmyadmin/pull/15611#issuecomment-561329014) using the commit of this branch
> 
> thank you :)

git cherry-pick ?? to  which hash .

**Comment by williamdes** [comment]
@shifatbuet 
image

**Comment by shifatbuet** [comment]
Now its okay I think .  👍  Thanks a lot for your help @williamdes

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
I will have to compare it to https://github.com/phpmyadmin/phpmyadmin/pull/15529/files#diff-02edf360fb1fbc96cdd58c1eb77a255e

#15529 from @beekalam

**Comment by williamdes** [comment]
Thank you for your contribution.
I will accept #15846 because it keeps consistency between Search and Insert pages.

**Pull request closed without merging**
