### PR TITLE
fix - #14401 -- insert_rows keypress Enter behavior -- add event to ENTER key

### LINKED ISSUE #14401: insert_rows keypress Enter behavior
### Steps to reproduce
1. Select table in database overview
2. Choose table record insertion
3. On the bottom, insert different number of record to insert (like 6), press [Enter] instead of clicking outside this input:number (id=insert_rows)

### Expected behaviour
In-page extension of insertable records, like the blur event

### Actual behaviour
Message shows: 'No databases selected'
Click on table name (at top)
Message appears:
Notice in ./libraries/db_table_exists.inc.php#20
 Undefined variable: db

Backtrace

./tbl_change.php#25: require_once(./libraries/db_table_exists.inc.php)
./libraries/classes/InsertEdit.php#2147: include(./tbl_change.php)
./tbl_replace.php#55: PhpMyAdmin\InsertEdit->isInsertRow()

Click on table again and issue disappears

### Server/Client configuration
Ubuntu 18.04
Apache/2.4.29
MariaDB 10.1.29
PHP 7.2.5
phpMyAdmin 4.8.1
Google Chrome 69.0.3452.0 dev x64

### PR DESCRIPTION
**Pull request by saurass**
Signed-off-by: Saurabh Srivastava <saurabhsrivastava312@gmail.com>

## Description
Fixes #14401 

## Problem
* The "Continue insertion with" (with id `insert_rows`) is in a form whose action is set to `tbl_replace.php`
* So when we press `ENTER` , the form gets submitted causing problem.

## Solution
* Add a keypress listener to the field for ENTER key.
* So upon clicking ENTER or focusing anywhere else on the DOM, we execute the same function.
* Thus I made the function `addNewContinueInsertionFiels()` and put the code under this.
* We call this function on `change` OR on `ENTER` press.

This seems to fix the issue.

## Contribution Checklist
- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by saurass** [comment]
@sudo-bot Deploy pr

**Review by williamdes — APPROVED** [review]
Tested: OK
Ready to merge.
Thanks @saurass for the fix !

**Comment by saurass** [comment]
Great. Thanks @williamdes : )

**Review by williamdes — APPROVED** [review]
Merged, thanks @saurass for the fix

**Comment by saurass** [comment]
Thank You @williamdes

**Pull request merged**
