### PR TITLE
Adds non-conflicting default new database name #13099

### PR DESCRIPTION
**Pull request by Achilles-96**
Signed-off-by: Raghuram Vadapalli<raghuram.vadapalli@research.iiit.ac.in>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ibennetch** [comment]
Nice work, but I think a better solution is to remove the default value entirely.

**Comment by ibennetch** [comment]
Note also that we have #13104 which catches the situation where a user does enter the same database name, so we'll try continue having your pull request address the default values.

**Review by nijel — CHANGES_REQUESTED** [review]
I'd also prefer not to have default value. Imagine user has databases named db1...db1000, with this patch going to operations tab would lead to 1000 queries just to have default value which almost nobody will use....

**Comment by Achilles-96** [comment]
Do you also feel default value must be removed for rename form?

**Comment by nijel** [comment]
Yes, I think having the field empty by default is best approach.

**Review by nijel — APPROVED** [review]

**Comment by nijel** [comment]
Merged as 553d1ff343 into QA_4_7 branch, thanks for your contribution!

**Pull request closed without merging**
