### PR TITLE
Replaced `0` to `NULL`  in primary key

### LINKED ISSUE #15187: editing a row and using 'insert as new row' uses primary key 0
### Describe the bug

If editing a row with an autoincrement primary key and using the option 'insert as new row', the new row will get the primary key 0 assigned.

### To Reproduce

Steps to reproduce the behaviour:

0. Have the database server using SQL mode `NO_AUTO_VALUE_ON_ZERO` (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_value_on_zero).
1. Create a table with an autoincrement primary key `id` and a string `name`.
2. Insert some rows to the table.
3. Click on one row and select `edit`.
4. The bottom dialogue by default has `save` selected. Select `insert as new row`.
5. The column `id` now is automatically set to `0`.
6. Press `go` to edit the row.

### Expected behaviour

My intention is to edit a row and insert it as a new row. This works if the automatically added `0` to the column `id` is manually removed. I expect to not have an automatically filled out `0` in the column `id` as soon as I select `insert as new row`.

### Server configuration

- Database version: MySQL 5.6 with `NO_AUTO_VALUE_ON_ZERO` enabled
- phpMyAdmin version: 4.8.5

### Additional context

The SQL mode `NO_AUTO_VALUE_ON_ZERO` needs to be enabled in order to not interpret the given primary key `0` as a literal zero instead of an instruction to create a new primary key.

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

Replaced `0` to `null` for primary id when edited.

Fixes #15187

### CODE REVIEW

**Comment by yashrajbothra** [comment]
I was enhancement so I took `master` as Base 👍

**Review by williamdes — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
@yashrajbothra can you use QA_5_0 as base?
I will consider this one as a bug finally because it blocks the user when inserting new rows

**Comment by williamdes** [comment]
@yashrajbothra I will write a guide to do such operations :)
So you will be able to try it

**Comment by yashrajbothra** [comment]
> @yashrajbothra I will write a guide to do such operations :)
> So you will be able to try it

Ya, that would be better 👍 
For now i think i can do this 😄

**Comment by williamdes** [comment]
> > @yashrajbothra I will write a guide to do such operations :)
> > So you will be able to try it
> 
> Ya, that would be better 
> For now i think i can do this

Sure
Follow #15942

**Comment by yashrajbothra** [comment]
@williamdes  is this good now?

**Review by williamdes — APPROVED** [review]
Yes, thank you!

**Comment by williamdes** [comment]
Thank you for your contribution @yashrajbothra :muscle:

**Pull request merged**
