### PR TITLE
Fixing Issue #13584, adjusting create table input when import config …

### PR DESCRIPTION
**Pull request by ryanml**
…notification is present

Signed-off-by: Ryan Lanese <rlanese@asu.edu>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by ryanml** [comment]
Per issue #13584, when the "Import config" message was present on the create table view, the fixed table input would clip over the config message.

To resolve this, I've added a function that will check for the presence of the config message and the table input, and adjust the 'top' value for the table input from 55px -> 120px

To recreate this, it may be easiest to briefly add..
`#prefs_autoload {
     display: block;
  }`

..to a custom stylesheet so the conflicting situation can be recreated. 

Fix shown:
pr

**Comment by mauriciofauth** [comment]
@ryanml, Can you use your real name in the sign-off line? See [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO).

**Comment by ryanml** [comment]
@mauriciofauth how is this looking? Thanks :)

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!
In your next contribution, create a new branch instead of using the master branch.

**Comment by ryanml** [comment]
@mauriciofauth will do thanks!

**Pull request merged**
