### PR TITLE
Refactor structure.lib.php (Creating Templates)

### PR DESCRIPTION
**Pull request by gzzhanghao**
This PR is opened for refactoring structure.lib.php by applying my previous work about the Template system.

First I will create templates for `PMA_getHtml` series functions, then eliminate them from structure.lib.php by inlining them from where they are called. I may apply similar strategies that were used in `tbl_columns_definition_form.lib.php`.

Signed-off-by: Jason jason.daurus@gmail.com

### CODE REVIEW

**Comment by zixtor** [comment]
Hi @gzzhanghao, please resolve conflicts and I am getting 500 internal server error on Table=>Structure when testing with these changes. Also, there remain many more PMA_getHtml* functions in this file for templating, please notify once that is covered, I will test and we can move towards merging.

**Comment by gzzhanghao** [comment]
@zixtor  Hi, I noticed there are some conflicts just now, so I fixed and you can merge.

**Comment by zixtor** [comment]
Looks fine!

**Comment by gzzhanghao** [comment]
@zixtor Good! Since the work of `StructureController` is a "big" commit, I will push the initial outcomes to GitHub tonight. Then I will do some tests and open a new PR.

**Pull request merged**
