### PR TITLE
fixed the modal heading

### LINKED ISSUE #15810: Unexpected Modal Heading
### Describe the bug

Unexpected code appearing on heading of modal

### To Reproduce

1. Go to 'Navigation Bar'
2. Click on (+) 'Function || Procedure -> New'
3. See error 

### Expected behavior

A heading like **Add Routine** Should appear on Modal

### Screenshots
Unexpected
image

Expected
image

### Configuration

- phpMyAdmin version: 5.1.0-dev (master)

### PR DESCRIPTION
**Pull request by rahgurung**
Closes #15810

### CODE REVIEW

**Comment by williamdes** [comment]
Will this change break other things?
Could you find the commit that added the line so I can agree to remove it back?

**Comment by gurrrung** [comment]
For me it fixed these two things which were effected earlier,
Screenshot from 2020-02-04 22-14-14
Screenshot from 2020-02-04 22-14-24
Further, I tried to have a look at the Create View modal, it was fine too
Screenshot from 2020-02-04 22-15-50

**Comment by williamdes** [comment]
According to the history, reverting the change for https://github.com/phpmyadmin/phpmyadmin/commit/47fa0d8bdb5763f952664c9f282c0e9c56dc0c8d#diff-8cc3bb552cbf4c9c3ac8d03797ac20da could be a fix for you?

**Review by williamdes — CHANGES_REQUESTED** [review]
This will break table renaming, browsing tables and more..

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you for the inital try @gurrrung 
I modified the PR and merged it

**Pull request merged**
