### PR TITLE
Fix tests, use proxy settings from env

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nijel** [comment]
Sorry to break things for you, but I've rewritten response processing in 5a5ceec to avoid manual parsing of HTTP response headers.

**Comment by nisargjhaveri** [comment]
That is much better than this. I'll update this PR. :)

**Comment by nisargjhaveri** [comment]
Updated.

**Comment by lem9** [comment]
Thanks.

**Pull request merged**
